/**
 * Per-subject Convex types for LC Art.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated Art* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { IdField, SystemFields } from "convex/server";

import type {
  ArtSyllabus,
  ArtPaper,
  ArtMarkingScheme,
  ArtTopics,
} from "../../../../../baml_client/typescript/baml_client/lc/art/client";

/**
 * The BAML-generated ArtPayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type ArtPayload =
  | ArtSyllabus
  | ArtPaper
  | ArtMarkingScheme
  | ArtTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface ArtDoc extends IdField<"art">, SystemFields {
  app: "oideachais";
  stage: "lc";
  subject: "art";
  language: "en" | "ga";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: ArtPayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML artType alias for the schema file
export type artType = ArtPayload;
