/**
 * Per-subject Convex types for LC Chemistry.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated Chemistry* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { IdField, SystemFields } from "convex/server";

import type {
  ChemistrySyllabus,
  ChemistryPaper,
  ChemistryMarkingScheme,
  ChemistryTopics,
} from "../../../../../baml_client/typescript/baml_client/lc/chemistry/client";

/**
 * The BAML-generated ChemistryPayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type ChemistryPayload =
  | ChemistrySyllabus
  | ChemistryPaper
  | ChemistryMarkingScheme
  | ChemistryTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface ChemistryDoc extends IdField<"chemistry">, SystemFields {
  app: "oideachais";
  stage: "lc";
  subject: "chemistry";
  language: "en" | "ga";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: ChemistryPayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML chemistryType alias for the schema file
export type chemistryType = ChemistryPayload;
