/**
 * Per-subject Convex table for LC Gaeilge.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Reference:
 *   openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 *   specs/schema-driven-codegen/spec.md

 * Subject metadata:
 *   stage:     lc
 *   subject:   gaeilge
 *   ncca_code: LC-GAEL-LO
 *   languages: ga
 */

import { defineTable } from "convex/server";
import { v } from "convex/values";

export const gaeilge = defineTable({
  app: v.literal("oideachais"),
  stage: v.literal("lc"),
  subject: v.literal("gaeilge"),
  language: v.union(
    v.literal("ga"),
  ),
  // Per-subject BAML-extracted fields:
  syllabus_topic_code: v.string(),
  syllabus_topic_title: v.string(),
  learning_outcome_code: v.string(),
  learning_outcome_text: v.string(),
  blooms_level: v.union(
    v.literal("remember"),
    v.literal("understand"),
    v.literal("apply"),
    v.literal("analyse"),
    v.literal("evaluate"),
    v.literal("create"),
  ),
  // BAML gaeilgePayload fields (the structured extraction output).
  // The BAML payload shape is a discriminated union of 4 extraction outputs
  // and has no generated Convex validator record, so it is stored opaquely.
  // The compile-time shape is `gaeilgeType` in ./gaeilge.types.
  payload: v.any(),
  // Metadata:
  ncca_code: v.string(),
  created_at: v.number(),  // epoch ms
  updated_at: v.number(),
})
  .index("by_app_stage_subject", ["app", "stage", "subject"])
  .index("by_topic", ["syllabus_topic_code"])
  .index("by_ncca_code", ["ncca_code"]);

// Re-export the type for the umbrella schema
export type gaeilgeDoc = typeof gaeilgeDocSchema;
declare const gaeilgeDocSchema: never;
