"""lesson_plan_flow — CocoIndex v1 App for per-lesson plans.

Per openspec/changes/2026-09-23-k12-teacher-student-pipeline-v1/.
Embeds the per-lesson plans generated by the `lesson_planner_agent`.

Embedder: BAAI/bge-m3 (1024-d).

Licence: BUSL-1.1 Cianfhoghlaim edition (per LICENSE.md).
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import cocoindex as coco

LANCEDB_TABLE = "k12_lesson_plans"
LANCEDB_URI = "stedding/lancedb/k12.lance"
EMBEDDING_MODEL = "BAAI/bge-m3"
EMBED_DIM = 1024


@coco.function(name="lesson_plan_flow")
def lesson_plan_flow(flow_builder: coco.FlowBuilder) -> None:
    """Embed lesson plans from the lesson_planner_agent.

    Phase 1 ships as a stub — Phase 2 fills from the per-school
    lesson-plan DB export.
    """
    with flow_builder.read_data("lesson_plan_inputs"):
        rows = flow_builder.add_classes(LessonPlanRecord)
    with rows.row() as row:
        flow_builder.embed(
            row["embedding"],
            coco.structured_data(
                row["title_en"], row["subject"],
                " ".join(row["learning_objectives"] or []),
            ),
        )
        flow_builder.export(
            row["plan_id"], row["teacher_id"], row["class_id"],
            row["subject"], row["date_iso"], row["title_en"],
            row["learning_objectives"], row["activities"],
            row["embedding"],
        )


class LessonPlanRecord(coco.Record):
    plan_id: str
    teacher_id: str
    class_id: str
    subject: str
    date_iso: str
    title_en: str
    learning_objectives: list[str]
    activities: list[str]
    embedding: coco.Vector[1024]


def main() -> None:
    print("lesson_plan_flow: starting")
    flow = lesson_plan_flow.setup()
    flow.update()
    print(f"lesson_plan_flow: complete. Output → {LANCEDB_TABLE} @ {LANCEDB_URI}")


if __name__ == "__main__":
    main()
