"""oideachais.cianfhoghlaim.dlt.official_media.classifier — BAML Stage-2 fallback.

The Stage-2 fallback in the two-stage filter. Invoked by
``AllowlistFilter.classify`` only when:

  1. The username is not in any allowlist YAML, AND
  2. The cheap heuristic in ``allowlist._looks_official`` matches.

Uses the BAML function ``ClassifyOfficialMedia`` declared in
``baml/processing/official_media.baml`` (regenerated to ``baml_client/``).
The fallback returns ``None`` (i.e. the candidate is rejected) when
the BAML call fails for any reason — never raises.
"""
from __future__ import annotations

from typing import Any

import structlog

logger = structlog.get_logger(__name__)

# Module-level import — the baml_client package is generated by
# ``baml-cli generate`` (run via ``mise turbo baml:generate``). In
# dev / CI venvs that have not yet generated the client, the import
# fails and ``_baml_client`` stays ``None``; the wrapper returns
# ``None`` from every call. Once the client is generated, this
# module-level import binds ``_baml_client`` to the real client.
try:
    from baml_client import b as _baml_client  # type: ignore[import-not-found]

    _BAML_AVAILABLE = True
except ImportError:
    _baml_client = None
    _BAML_AVAILABLE = False


def is_baml_available() -> bool:
    """Return True iff the baml_client package is importable."""
    return _BAML_AVAILABLE


def classify_with_baml(
    ig_username: str,
    ig_bio: str = "",
    ig_external_url: str = "",
) -> dict[str, Any] | None:
    """Invoke the BAML ``ClassifyOfficialMedia`` function.

    Returns a normalised dict ``{is_official_media, confidence,
    category, reason}`` or ``None`` on any failure (missing
    BAML client, LiteLLM gateway unreachable, schema parse error,
    etc.). Never raises — the filter is best-effort.
    """
    if _baml_client is None:
        logger.debug(
            "baml_client_missing",
            hint="run `mise turbo baml:generate` to regenerate the client",
        )
        return None

    try:
        decision = _baml_client.ClassifyOfficialMedia(
            ig_username=ig_username,
            ig_bio=ig_bio,
            ig_external_url=ig_external_url or None,
        )
    except Exception as exc:
        logger.warning(
            "ClassifyOfficialMedia_failed",
            ig_username=ig_username,
            error=str(exc),
        )
        return None

    # Map the BAML enum value to a lower-case string the allowlist
    # filter recognises (singular form).
    category_map = {
        "Intelligence": "intelligence",
        "University": "university",
        "Party": "party",
        "Jurisdiction": "jurisdiction",
        "Agency": "agency",
        "EmergencyService": "emergency_service",
        "Military": "military",
        "Government": "government",
        "Other": "other",
    }
    raw_category = str(getattr(decision, "category", "Other"))
    return {
        "is_official_media": bool(getattr(decision, "is_official_media", False)),
        "confidence": float(getattr(decision, "confidence", 0.0)),
        "category": category_map.get(raw_category, "other"),
        "reason": str(getattr(decision, "reason", "")),
    }
