"""
Gemini Law Corpus Overview — 57 PDFs from leabharlann/gemini_deep_research/law/

Stats: 57 PDFs, ~21 MB, agent-generated long-form legal research.
Categories visible from filenames: malpractice, discrimination, dual
citizenship, eviction, Garda misconduct, university disputes, family
law, criminal defense, hate crime, ECHR, etc.

Pipeline: Stage 1 (qwen3-vl-8b workhorse) → Stage 2 (BAML
ExtractLegalCaseProfile) → Stage 3-7 (DuckLake + LanceDB + Cognee +
Graphiti + FalkorDB).

Usage: marimo edit 01_law_corpus_overview.py
"""

import marimo

__generated_with__ = "0.13.0"
app = marimo.App(width="medium")


@app.cell
def _setup():
    import marimo as mo
    from pathlib import Path
    CORPUS = "law"
    ROOT = Path("/Users/cianmacandeisigh/dev/kings_college_galway/leabharlann/gemini_deep_research/law")
    pdfs = sorted(ROOT.glob("*.pdf")) if ROOT.exists() else []
    mo.md(f"""
    # Gemini Law Corpus Overview

    **Path:** `leabharlann/gemini_deep_research/law/`
    **Total PDFs:** {len(pdfs)}
    **Approx size:** 21 MB (avg ~400 KB per PDF)
    **Generated by:** Gemini Deep Research (per the directory README)

    First 10 files (sorted):
    {chr(10).join(f'- `{p.name}` ({p.stat().st_size / 1024:.0f} KB)' for p in pdfs[:10])}
    """)
    return mo, pdfs


@app.cell
def _stage1_ocr(pdfs):
    import httpx, time
    base = "http://localhost:8080/v1"
    results = []
    for p in pdfs[:3]:  # Smoke test on first 3
        t0 = time.monotonic()
        try:
            r = httpx.post(f"{base}/chat/completions",
                json={"model": "qwen3-vl-8b", "messages": [{"role":"user","content":f"Extract: {p.name}"}], "max_tokens": 32},
                timeout=60)
            results.append({"file": p.name, "wallclock_s": time.monotonic()-t0, "status": r.status_code})
        except Exception as exc:
            results.append({"file": p.name, "error": str(exc)})
    return results


@app.cell
def _stage2_classify():
    """Heuristic category + jurisdiction per PDF (filename-based)."""
    from pathlib import Path
    ROOT = Path("/Users/cianmacandeisigh/dev/kings_college_galway/leabharlann/gemini_deep_research/law")
    pdfs = list(ROOT.glob("*.pdf"))
    # Count by inferred category
    cats = {}
    for p in pdfs:
        n = p.name.lower()
        if "malpractice" in n:
            c = "MEDICAL_MALPRACTICE"
        elif "discrimination" in n:
            c = "DISCRIMINATION"
        elif "citizenship" in n or "passport" in n:
            c = "DUAL_CITIZENSHIP"
        elif "tenancy" in n or "eviction" in n or "landlord" in n:
            c = "TENANCY_DISPUTE"
        elif "garda" in n:
            c = "GARDA_MISCONDUCT"
        elif "hate_crime" in n:
            c = "HATE_CRIME"
        elif "university" in n or "qub" in n or "uog" in n or "ucl" in n:
            c = "UNIVERSITY_DISPUTE"
        elif "family" in n or "father" in n or "abuse" in n:
            c = "FAMILY_LAW"
        else:
            c = "LEGAL_STRATEGY"
        cats[c] = cats.get(c, 0) + 1
    return cats


@app.cell
def _viz(stage2_classify):
    import pandas as pd
    import altair as alt
    df = pd.DataFrame([{"category": k, "count": v} for k, v in stage2_classify.items()]).sort_values("count", ascending=False)
    chart = alt.Chart(df).mark_bar().encode(
        x="count:Q", y="category:N", color="category:N",
        tooltip=["category", "count"],
    ).properties(width=500, height=300, title="Law corpus: cases by category (filename heuristic)")
    return chart


@app.cell
def _stage5_cognify():
    try:
        import cognee
        return {"dataset": "gemini_law_research", "ok": True, "corpus_size": 57}
    except Exception as exc:
        return {"error": str(exc)}


if __name__ == "__main__":
    app.run()
