private-resources:
  dotsocr:
    name: "DotsOCR"
    mode: http
    full-domain: "dotsocr.cianfhoghlaim.ie"
    destination: dotsocr:8001
    protocol: http
    sites: [arm1-oci]
    roles: [Member]
