/**
 * A-LEVEL Biology — subject landing page.
 *
 * AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Per openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 * specs/per-subject-coverage/spec.md.
 */

import { createFileRoute, Link } from "@tanstack/react-router";
import { CopilotKit } from "@copilotkit/react-core/v2";
import { useState } from "react";

import { useBiologyActions } from "@/lib/copilotkit/a-level/biology";
import { useBiologyEvents } from "@/lib/ag-ui/a-level/biology";

export const Route = createFileRoute("/a-level/biology/")({
  component: BiologyPage,
});

function BiologyPage() {
  return (
    <CopilotKit runtimeUrl="/api/copilotkit/a-level/biology">
      <div className="max-w-4xl mx-auto flex flex-col gap-8 h-full p-8">
        <div className="flex flex-col gap-2">
          <h1 className="text-4xl font-bold">
            Biology (A-LEVEL)
          </h1>
          <p className="text-slate-600 text-lg">
            Biology — AL-BIO — languages: en
          </p>
        </div>

        <SubjectActionsSection subject="biology" stage="a-level" />

        <Link
          to="/a-level/biology/$topicId"
          params={{ topicId: "AL-BIO-001" }}
          className="btn-tactile"
        >
          Open topic detail →
        </Link>
      </div>
    </CopilotKit>
  );
}

function SubjectActionsSection({
  subject,
  stage,
}: {
  subject: string;
  stage: string;
}) {
  useBiologyActions();

  return (
    <div className="grid grid-cols-2 gap-4">
      <ActionCard
        title="Get syllabus topics"
        description="Fetch the Biology syllabus topics + learning outcomes"
        actionName="get_syllabus_topics"
      />
      <ActionCard
        title="Get exam papers"
        description="List exam papers by year + level"
        actionName="get_exam_papers"
      />
      <ActionCard
        title="Get marking schemes"
        description="Fetch marking schemes + rubrics"
        actionName="get_marking_schemes"
      />
      <ActionCard
        title="Semantic search"
        description="BGE-M3 vector search over the Biology embeddings"
        actionName="semantic_search"
      />
    </div>
  );
}

function ActionCard({
  title,
  description,
  actionName,
}: {
  title: string;
  description: string;
  actionName: string;
}) {
  return (
    <button
      className="rounded-lg border p-4 text-left hover:bg-slate-50"
      data-action={actionName}
    >
      <h3 className="font-semibold">{title}</h3>
      <p className="text-sm text-slate-600">{description}</p>
    </button>
  );
}
