/**
 * CopilotKit action registry for A-LEVEL Business.
 *
 * AUTO-GENERATED by scripts/schema-codegen/copilotkit-actions.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Per openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 * specs/per-subject-coverage/spec.md.
 */

"use client";

import { useCopilotAction } from "@copilotkit/react-core";

export const ACTIONS = [
  {
    "name": "get_syllabus_topics",
    "description": "Get the syllabus topics + learning outcomes for a subject at a level + language.",
    "output_kind": "syllabus"
  },
  {
    "name": "get_exam_papers",
    "description": "List exam papers for a subject + year + level.",
    "output_kind": "papers"
  },
  {
    "name": "get_marking_schemes",
    "description": "Get the marking schemes for a subject + year + level.",
    "output_kind": "marking_schemes"
  },
  {
    "name": "get_topic_detail",
    "description": "Get a single topic's details (NCCA code + learning outcomes + cross-jurisdictional equivalences).",
    "output_kind": "topics"
  },
  {
    "name": "get_cross_jurisdictional_equivalences",
    "description": "Get cross-jurisdictional equivalences for a topic (e.g. LC Maths vs GCSE Maths).",
    "output_kind": "comparison"
  },
  {
    "name": "semantic_search",
    "description": "Semantic vector search over the per-subject embeddings (BGE-M3 1024-d).",
    "output_kind": "topics"
  },
  {
    "name": "extract_syllabus_from_pdf",
    "description": "Extract structured syllabus from a PDF URL (BAML extraction).",
    "output_kind": "syllabus"
  },
  {
    "name": "save_annotation",
    "description": "Save a per-user annotation on a topic (Convex).",
    "output_kind": "annotation"
  },
  {
    "name": "track_progress",
    "description": "Track per-user progress on a topic (Convex).",
    "output_kind": "annotation"
  },
  {
    "name": "get_study_plan",
    "description": "Generate a personalized study plan for a subject.",
    "output_kind": "study_plan"
  },
  {
    "name": "compare_curricula",
    "description": "Compare curricula across stages (e.g. LC Maths vs GCSE Maths).",
    "output_kind": "comparison"
  },
  {
    "name": "get_glossary_term",
    "description": "Get a glossary term definition (Gaeilge + English).",
    "output_kind": "topics"
  },
  {
    "name": "extract_learning_outcome",
    "description": "Extract a learning outcome from text (BAML extraction).",
    "output_kind": "syllabus"
  }
] as const;

export function useBusinessActions() {
  useCopilotAction({
    name: "get_syllabus_topics",
    description: "Get the syllabus topics + learning outcomes for a subject at a level + language.",
    parameters: [
      { name: "stage", type: "string", description: "lc | jc | gcse | a-level", required: true },
      { name: "level", type: "string", description: "hl | ol | fl | a-level" },
      { name: "language", type: "string", description: "en | ga" },
    ],
    handler: async (args) => ({ stub: true, action: "get_syllabus_topics", args }),
  });

  useCopilotAction({
    name: "get_exam_papers",
    description: "List exam papers for a subject + year + level.",
    parameters: [
      { name: "year", type: "number", description: "e.g. 2024", required: true },
      { name: "level", type: "string", description: "hl | ol | fl | a-level" },
      { name: "material_type", type: "string", description: "exam_papers | marking_schemes" },
    ],
    handler: async (args) => ({ stub: true, action: "get_exam_papers", args }),
  });

  useCopilotAction({
    name: "get_marking_schemes",
    description: "Get the marking schemes for a subject + year + level.",
    parameters: [
      { name: "year", type: "number", description: "e.g. 2024", required: true },
      { name: "level", type: "string", description: "hl | ol | fl | a-level" },
    ],
    handler: async (args) => ({ stub: true, action: "get_marking_schemes", args }),
  });

  useCopilotAction({
    name: "get_topic_detail",
    description: "Get a single topic's details (NCCA code + learning outcomes + cross-jurisdictional equivalences).",
    parameters: [
      { name: "topic_code", type: "string", description: "e.g. LC-MATH-LO-023", required: true },
    ],
    handler: async (args) => ({ stub: true, action: "get_topic_detail", args }),
  });

  useCopilotAction({
    name: "get_cross_jurisdictional_equivalences",
    description: "Get cross-jurisdictional equivalences for a topic (e.g. LC Maths vs GCSE Maths).",
    parameters: [
      { name: "topic_code", type: "string", description: "NCCA topic code", required: true },
      { name: "jurisdiction", type: "string", description: "lc | gcse | a-level" },
    ],
    handler: async (args) => ({ stub: true, action: "get_cross_jurisdictional_equivalences", args }),
  });

  useCopilotAction({
    name: "semantic_search",
    description: "Semantic vector search over the per-subject embeddings (BGE-M3 1024-d).",
    parameters: [
      { name: "query", type: "string", description: "natural language query", required: true },
      { name: "top_k", type: "number", description: "default 10" },
    ],
    handler: async (args) => ({ stub: true, action: "semantic_search", args }),
  });

  useCopilotAction({
    name: "extract_syllabus_from_pdf",
    description: "Extract structured syllabus from a PDF URL (BAML extraction).",
    parameters: [
      { name: "pdf_url", type: "string", description: "PDF URL", required: true },
    ],
    handler: async (args) => ({ stub: true, action: "extract_syllabus_from_pdf", args }),
  });

  useCopilotAction({
    name: "save_annotation",
    description: "Save a per-user annotation on a topic (Convex).",
    parameters: [
      { name: "topic_code", type: "string", description: "NCCA topic code", required: true },
      { name: "note", type: "string", description: "user note", required: true },
    ],
    handler: async (args) => ({ stub: true, action: "save_annotation", args }),
  });

  useCopilotAction({
    name: "track_progress",
    description: "Track per-user progress on a topic (Convex).",
    parameters: [
      { name: "topic_code", type: "string", description: "NCCA topic code", required: true },
      { name: "score", type: "number", description: "0-100", required: true },
    ],
    handler: async (args) => ({ stub: true, action: "track_progress", args }),
  });

  useCopilotAction({
    name: "get_study_plan",
    description: "Generate a personalized study plan for a subject.",
    parameters: [
      { name: "subject", type: "string", description: "subject slug", required: true },
      { name: "target_date", type: "string", description: "ISO 8601 target date" },
    ],
    handler: async (args) => ({ stub: true, action: "get_study_plan", args }),
  });

  useCopilotAction({
    name: "compare_curricula",
    description: "Compare curricula across stages (e.g. LC Maths vs GCSE Maths).",
    parameters: [
      { name: "topic_code", type: "string", description: "NCCA topic code", required: true },
      { name: "stages", type: "string[]", description: "e.g. ['lc', 'gcse']", required: true },
    ],
    handler: async (args) => ({ stub: true, action: "compare_curricula", args }),
  });

  useCopilotAction({
    name: "get_glossary_term",
    description: "Get a glossary term definition (Gaeilge + English).",
    parameters: [
      { name: "term", type: "string", description: "Gaeilge or English term", required: true },
      { name: "language", type: "string", description: "en | ga | both" },
    ],
    handler: async (args) => ({ stub: true, action: "get_glossary_term", args }),
  });

  useCopilotAction({
    name: "extract_learning_outcome",
    description: "Extract a learning outcome from text (BAML extraction).",
    parameters: [
      { name: "text", type: "string", description: "input text", required: true },
    ],
    handler: async (args) => ({ stub: true, action: "extract_learning_outcome", args }),
  });
}
