"""Computer Science schema — Cianfhoghlaim Oideachais.

DEPRECATED 2026-08-15 — the 12 hand-written Pydantic classes in this
module have been replaced with thin re-exports from the generated
BAML Python client. The BAML file
(``baml_src/british_isles/ireland/education/subjects/qpack_computer_science.baml``)
is now the single source of truth. The hand-written schema was
explicitly documented as a BAML mirror.

Per the ``centralized-schema-registry`` capability (2026-08-15).
"""
from __future__ import annotations

# Re-export every Comp* class from the generated BAML Python client.
# Enums (str, Enum) and BaseModel subclasses are generated by
# `baml-cli generate` from `baml_src/.../qpack_computer_science.baml`.
from baml_client.baml_client.types import (
    CompBilingualText,
    CompEvidenceLink,
    CompNCCALevel,
    CompTopicArea,
    CompItemType,
    CompFeedbackChannel,
    CompFormativeItem,
    CompFormativeItemAttempt,
    CompScoreBreakdown,
    CompQuestPack,
    CompQuestPackValidation,
    CompNCCALearningOutcome,
)

# Additional types that may exist per subject.
# NOTE: No additional types for this subject — the per-subject extras
# (e.g. ItemType, FeedbackChannel, FormativeItem) live in the main BAML
# client import above. For older BAML clients without these exact enum
# names, fall back to legacy strings below.
from enum import Enum

class FormativeItemType(str, Enum):
    NUMERICAL = "numerical"
    SHORT_ANSWER = "short_answer"
    EXTENDED_RESPONSE = "extended_response"

class FeedbackChannel(str, Enum):
    HINT = "hint"
    ELABORATION = "elaboration"
    MISCONCEPTION = "misconception"
    REINFORCEMENT = "reinforcement"


__all__ = [
    "BilingualText",
    "EvidenceLink",
    "CompNCCALevel",
    "CompTopicArea",
    "CompNCCALearningOutcome",
    "FormativeItem",
    "FormativeItemAttempt",
    "ScoreBreakdown",
    "QuestPack",
    "QuestPackValidation",
    "FormativeItemType",
    "FeedbackChannel",
    "CompBilingualText",
    "CompEvidenceLink",
    "CompFormativeItem",
    "CompFormativeItemAttempt",
    "CompScoreBreakdown",
    "CompQuestPack",
    "CompQuestPackValidation",
]
