/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities/index'
import { Route as EventsSubmitRouteImport } from './routes/events/submit'
import { Route as EventsEventSlugRouteImport } from './routes/events/$eventSlug'
import { Route as CommunitiesCreateRouteImport } from './routes/communities/create'
import { Route as CommunitiesCommunitySlugRouteImport } from './routes/communities/$communitySlug'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as EventsProSubmitRouteImport } from './routes/events/pro.submit'
import { Route as EventsProEventIdRouteImport } from './routes/events/pro.$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSubmitRoute = EventsSubmitRouteImport.update({
  id: '/events/submit',
  path: '/events/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventSlugRoute = EventsEventSlugRouteImport.update({
  id: '/events/$eventSlug',
  path: '/events/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCreateRoute = CommunitiesCreateRouteImport.update({
  id: '/communities/create',
  path: '/communities/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunitySlugRoute =
  CommunitiesCommunitySlugRouteImport.update({
    id: '/communities/$communitySlug',
    path: '/communities/$communitySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsProSubmitRoute = EventsProSubmitRouteImport.update({
  id: '/events/pro/submit',
  path: '/events/pro/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsProEventIdRoute = EventsProEventIdRouteImport.update({
  id: '/events/pro/$eventId',
  path: '/events/pro/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/api/mcp': typeof ApiMcpRoute
  '/communities/$communitySlug': typeof CommunitiesCommunitySlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities': typeof CommunitiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/pro/$eventId': typeof EventsProEventIdRoute
  '/events/pro/submit': typeof EventsProSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/api/mcp': typeof ApiMcpRoute
  '/communities/$communitySlug': typeof CommunitiesCommunitySlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities': typeof CommunitiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/pro/$eventId': typeof EventsProEventIdRoute
  '/events/pro/submit': typeof EventsProSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/api/mcp': typeof ApiMcpRoute
  '/communities/$communitySlug': typeof CommunitiesCommunitySlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/pro/$eventId': typeof EventsProEventIdRoute
  '/events/pro/submit': typeof EventsProSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/my-events'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/.well-known/openid-configuration'
    | '/api/mcp'
    | '/communities/$communitySlug'
    | '/communities/create'
    | '/events/$eventSlug'
    | '/events/submit'
    | '/communities'
    | '/api/auth/$'
    | '/events/pro/$eventId'
    | '/events/pro/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/my-events'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/.well-known/openid-configuration'
    | '/api/mcp'
    | '/communities/$communitySlug'
    | '/communities/create'
    | '/events/$eventSlug'
    | '/events/submit'
    | '/communities'
    | '/api/auth/$'
    | '/events/pro/$eventId'
    | '/events/pro/submit'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/my-events'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/.well-known/openid-configuration'
    | '/api/mcp'
    | '/communities/$communitySlug'
    | '/communities/create'
    | '/events/$eventSlug'
    | '/events/submit'
    | '/communities/'
    | '/api/auth/$'
    | '/events/pro/$eventId'
    | '/events/pro/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  MyEventsRoute: typeof MyEventsRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiMcpRoute: typeof ApiMcpRoute
  CommunitiesCommunitySlugRoute: typeof CommunitiesCommunitySlugRoute
  CommunitiesCreateRoute: typeof CommunitiesCreateRoute
  EventsEventSlugRoute: typeof EventsEventSlugRoute
  EventsSubmitRoute: typeof EventsSubmitRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EventsProEventIdRoute: typeof EventsProEventIdRoute
  EventsProSubmitRoute: typeof EventsProSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/submit': {
      id: '/events/submit'
      path: '/events/submit'
      fullPath: '/events/submit'
      preLoaderRoute: typeof EventsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventSlug': {
      id: '/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof EventsEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/create': {
      id: '/communities/create'
      path: '/communities/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof CommunitiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communitySlug': {
      id: '/communities/$communitySlug'
      path: '/communities/$communitySlug'
      fullPath: '/communities/$communitySlug'
      preLoaderRoute: typeof CommunitiesCommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/pro/submit': {
      id: '/events/pro/submit'
      path: '/events/pro/submit'
      fullPath: '/events/pro/submit'
      preLoaderRoute: typeof EventsProSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/pro/$eventId': {
      id: '/events/pro/$eventId'
      path: '/events/pro/$eventId'
      fullPath: '/events/pro/$eventId'
      preLoaderRoute: typeof EventsProEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  MyEventsRoute: MyEventsRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiMcpRoute: ApiMcpRoute,
  CommunitiesCommunitySlugRoute: CommunitiesCommunitySlugRoute,
  CommunitiesCreateRoute: CommunitiesCreateRoute,
  EventsEventSlugRoute: EventsEventSlugRoute,
  EventsSubmitRoute: EventsSubmitRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EventsProEventIdRoute: EventsProEventIdRoute,
  EventsProSubmitRoute: EventsProSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
