private-resources:
  litellm:
    name: "LiteLLM Gateway"
    mode: http
    full-domain: "litellm.cianfhoghlaim.ie"
    destination: litellm:4000
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
