"""Runtime TypeBuilder helper for the NCCA strand/outcome catalog.

Per ``openspec/changes/2026-07-12-baml-type-builder-ncca-v1``:
The NCCA strand / outcome / curriculum-spec / assessment-component
tree changes yearly.  Rather than regenerating the BAML files on
every NCCA refresh, we expose the catalog via BAML's ``TypeBuilder``
(``@@dynamic`` markers + the baml_client ``TypeBuilder.add_property``
API) and read it from a static config file at startup.

The 4 ``@@dynamic``-marked BAML classes in
``baml/education/_shared/strand_outcome.baml`` are:

    - ``CurriculumStrand`` (~= abstract "Strand")
    - ``LearningOutcome`` (~= abstract "Outcome")
    - ``CurriculumSpecStrand`` (~= abstract "CurriculumSpecification")
    - ``AssessmentComponentStrand`` (~= abstract "AssessmentComponent")

The catalog lives at
``baml/education/_shared/strand_catalog.yaml`` (representative
subset for the 6 LC priority subjects).  The full NCCA tree lives
in the ``leabharlann/`` worktree (not in the baml/ tree).

Usage::

    from baml_client.type_builder import TypeBuilder
    from cianfhoghlaim.baml.education._shared.strand_type_builder import (
        build_ncca_strand_type_builder,
    )

    tb = build_ncca_strand_type_builder()
    # ... pass tb to b.Extract* via baml_options={"tb": tb}
"""
from __future__ import annotations

import pathlib
from typing import Any

import yaml

try:
    # The baml_client is generated by `baml-cli generate` to
    # `baml/shared/baml_client/` -- importable as `baml_client`
    # once the project root is on sys.path.  The TypeBuilder
    # class exposes per-class viewers like ``tb.<ClassName>``
    # which return ``ClassViewer`` objects with
    # ``.props.<prop_name>.type()`` / ``.add_property(name, type)``.
    from baml_client.type_builder import TypeBuilder as _BamlTypeBuilder  # type: ignore[import-not-found]
except Exception:  # pragma: no cover -- tolerate missing baml_client
    _BamlTypeBuilder = None  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Detect whether the baml_client is importable (and matches the installed
# baml-py version).  This lets the helper unit-test cleanly without
# requiring the full baml-cli generate step (the baml-py / baml_client
# version skew triggers a hard ImportError at TypeBuilder import time).
# ---------------------------------------------------------------------------
def _baml_client_is_available() -> bool:
    """Return True iff the baml_client ``TypeBuilder`` is importable.

    Note
    ----
    The baml_client generator version must match the installed
    ``baml-py`` version (currently 0.223.0 in this repo); otherwise
    ``baml_client.type_builder`` raises a ``baml-py out of date``
    ImportError on import.  We catch that gracefully so the catalog
    loader + TypeBuilder factory can be exercised in CI without a
    full ``baml-cli generate`` step.
    """
    return _BamlTypeBuilder is not None


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------
# Resolve the catalog file relative to THIS module so it works regardless
# of the working directory the loader is invoked from.  The catalog ships
# alongside this module at:
#     cianfhoghlaim/baml/education/_shared/strand_catalog.yaml
_THIS_DIR = pathlib.Path(__file__).resolve().parent
_DEFAULT_CATALOG_PATH = _THIS_DIR / "strand_catalog.yaml"


# ---------------------------------------------------------------------------
# Type-name mapping (catalog → baml_py.FieldType)
# ---------------------------------------------------------------------------
# The catalog uses terse string type names ("string", "int", "float",
# "bool") which we map to the corresponding ``tb.<primitive>()``
# factory.  The mapping is intentionally small: the NCCA catalog only
# uses 4 primitive types.  Extending it (e.g. to support enums or
# class refs) only requires adding entries here + providing the
# corresponding ``tb.<type>()`` factory on the TypeBuilder.
_TYPE_FACTORY_NAMES: dict[str, str] = {
    "string": "string",
    "int": "int",
    "float": "float",
    "bool": "bool",
}


# ---------------------------------------------------------------------------
# Catalog loader
# ---------------------------------------------------------------------------
def load_catalog(
    catalog_path: pathlib.Path | str | None = None,
) -> dict[str, Any]:
    """Load the NCCA catalog from the canonical YAML config file.

    Parameters
    ----------
    catalog_path : optional
        Override the catalog path (used by tests + the
        ``strand_type_builder_smoke`` test which passes a YAML
        blob directly).

    Returns
    -------
    dict[str, Any]
        The parsed catalog with keys ``strands``, ``outcomes``,
        ``specifications``, ``assessment_components``.  Missing
        sections default to ``[]``.

    Notes
    -----
    If the YAML file is missing (e.g. in a slimmed-down CI image),
    we return an empty catalog rather than raising -- the caller
    can still build a TypeBuilder with just the static BAML fields.
    """
    path = pathlib.Path(catalog_path) if catalog_path else _DEFAULT_CATALOG_PATH
    if not path.exists():
        return {
            "strands": [],
            "outcomes": [],
            "specifications": [],
            "assessment_components": [],
        }
    with path.open() as fh:
        data = yaml.safe_load(fh) or {}
    # Ensure all 4 sections are present (defensive against missing keys).
    for section in ("strands", "outcomes", "specifications", "assessment_components"):
        data.setdefault(section, [])
    return data


# ---------------------------------------------------------------------------
# Property-injection helpers
# ---------------------------------------------------------------------------
def _inject_properties(
    class_viewer: Any,
    properties: dict[str, str],
    tb: Any,
) -> None:
    """Inject ``{prop_name: primitive_type_name}`` into a class viewer.

    Parameters
    ----------
    class_viewer : baml_client.type_builder.ClassViewer
        The viewer returned by ``tb.<ClassName>`` (e.g. ``tb.Strand``).
    properties : dict[str, str]
        Mapping ``prop_name -> primitive_type_name`` where the type
        name is one of the keys in ``_TYPE_FACTORY_NAMES``.
    tb : baml_client.type_builder.TypeBuilder
        The parent TypeBuilder instance (needed to call
        ``tb.<primitive>()`` factories).

    Notes
    -----
    We use the canonical ``baml_py`` ``FieldType`` API via the
    TypeBuilder's primitive factories (``tb.string()``, ``tb.int()``,
    etc).  For enums / nested class references, extend the mapping
    table above.
    """
    for prop_name, prop_type in properties.items():
        factory_name = _TYPE_FACTORY_NAMES.get(prop_type)
        if factory_name is None:
            # Unknown type -- skip with a deterministic comment-style
            # fallback.  Mark this in the docstring for the
            # operator to see in the CI test report.
            raise ValueError(
                f"Unsupported catalog property type {prop_type!r} for "
                f"property {prop_name!r}; valid types: "
                f"{sorted(_TYPE_FACTORY_NAMES)}"
            )
        field_type = getattr(tb, factory_name)()
        class_viewer.add_property(prop_name, field_type)


# ---------------------------------------------------------------------------
# Public TypeBuilder factory
# ---------------------------------------------------------------------------
def build_ncca_strand_type_builder(
    catalog: dict[str, Any] | None = None,
    catalog_path: pathlib.Path | str | None = None,
) -> Any:
    """Build a TypeBuilder with the NCCA catalog applied.

    Parameters
    ----------
    catalog : optional dict
        Pre-loaded catalog (skips the YAML read).  Used by the
        BAML test block to pass an inline catalog blob.
    catalog_path : optional path
        Override the catalog path (used by tests).

    Returns
    -------
    baml_client.type_builder.TypeBuilder
        The frozen TypeBuilder instance, ready to be passed to
        any ``b.<Function>(..., baml_options={"tb": tb})`` call.

    Side effects
    ------------
    Adds the per-strand / per-outcome / per-spec / per-component
    properties declared in the catalog to the 4 ``@@dynamic``
    BAML classes (``CurriculumStrand``, ``LearningOutcome``,
    ``CurriculumSpecStrand``, ``AssessmentComponentStrand``).

    Falls back to an empty TypeBuilder if the baml_client is not
    yet generated (``mise run baml:generate``) -- this lets the
    module be imported in environments without the generated
    client (e.g. CI lint, marimo notebooks that don't extract).
    """
    if _BamlTypeBuilder is None:
        # baml_client not yet generated -- the operator needs to run
        # `mise run baml:generate`.  We return a sentinel rather
        # than crashing so callers can `try/except` around it.
        return None  # type: ignore[return-value]

    tb = _BamlTypeBuilder()

    # Load the catalog (unless a pre-loaded dict was supplied).
    if catalog is None:
        catalog = load_catalog(catalog_path=catalog_path)

    # Inject strands -> CurriculumStrand
    for strand_def in catalog.get("strands", []):
        properties = strand_def.get("properties", {})
        if not properties:
            continue
        _inject_properties(tb.CurriculumStrand, properties, tb)

    # Inject outcomes -> LearningOutcome
    for outcome_def in catalog.get("outcomes", []):
        properties = outcome_def.get("properties", {})
        if not properties:
            continue
        _inject_properties(tb.LearningOutcome, properties, tb)

    # Inject specifications -> CurriculumSpecStrand
    for spec_def in catalog.get("specifications", []):
        properties = spec_def.get("properties", {})
        if not properties:
            continue
        _inject_properties(tb.CurriculumSpecStrand, properties, tb)

    # Inject assessment components -> AssessmentComponentStrand
    for component_def in catalog.get("assessment_components", []):
        properties = component_def.get("properties", {})
        if not properties:
            continue
        _inject_properties(tb.AssessmentComponentStrand, properties, tb)

    return tb


# ---------------------------------------------------------------------------
# Module exports
# ---------------------------------------------------------------------------
__all__ = [
    "load_catalog",
    "build_ncca_strand_type_builder",
]


# ---------------------------------------------------------------------------
# Convenience CLI for the operator
# ---------------------------------------------------------------------------
if __name__ == "__main__":  # pragma: no cover
    # ``python -m baml.education._shared.strand_type_builder`` smoke test:
    # load the catalog, instantiate the TypeBuilder (or report the
    # baml-py version mismatch), and exit non-zero on hard failures.
    import sys

    cat = load_catalog()
    print(
        f"Loaded catalog: strands={len(cat['strands'])} "
        f"outcomes={len(cat['outcomes'])} "
        f"specifications={len(cat['specifications'])} "
        f"assessment_components={len(cat['assessment_components'])}"
    )

    if not _baml_client_is_available():
        print(
            "WARNING: baml_client.TypeBuilder not importable "
            "(run `mise run baml:generate` to regenerate the "
            "client at baml/shared/baml_client/).",
            file=sys.stderr,
        )
        sys.exit(0)  # catalog-valid YAML is enough for CI smoke

    tb = build_ncca_strand_type_builder(cat)
    print(f"TypeBuilder instantiated: {type(tb).__name__}")
    sys.exit(0)

