.PHONY: install

install:
	# 🏗️ Installing dependencies and pre-commit hooks...
	uv pip install -e .
	# ✅ Dependencies installed.
	pre-commit install
	# ✅ Pre-commit hooks installed.

# Run linters
.PHONY: lint
lint: ensure-ruff
	# 🏗️ Running linters, your files will not be mutated.
	# Use 'make check' to auto-apply fixes."
	ruff check
	# ✅ Linting complete."

# Run formatter (if dev does not do so in their IDE)
.PHONY: format
format: ensure-ruff
	# 🏗️ Running formatter, your files will be changed to comply to formatting configs.
	ruff format
	# display the summaries of diffs in repo, some of these diffs are generated by the formatter
	git diff --stat
	# ✅ Formatting complete. Please review your git diffs, if any.

# Run ruff auto lint and format via pre-commit hook
.PHONY: check
check: ensure-ruff
	# 🏗️ Running pre-commit linter and formatters on files...
	@(pre-commit run --all-files)

# Clean up
.PHONY: clean
clean:
	# 🧼 Cleaning up venv.
	rm -rf $(VENV_DIR)
	# ✅ Cleaned up venv. Run 'make install' to re-generate.

# Help message
.PHONY: help
help:
	# 📖 Showing available commands...
	@echo "Usage: make <target>"
	@echo "Targets:"
	@echo "  install    Install dependencies and pre-commit hooks"
	@echo "  lint       Run linters"
	@echo "  format     Run formatter"
	@echo "  check      Run ruff auto lint and format via pre-commit hook"
	@echo "  clean      Clean up venv"
	@echo "  help       Show this help message"
	# ✅ Help message displayed.