private-resources:
  windmill:
    name: "Windmill"
    mode: http
    full-domain: "windmill.cianfhoghlaim.ie"
    destination: windmill:8080
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member