private-resources:
  mailcow-dockerized:
    name: "Mailcow-dockerized"
    mode: http
    full-domain: "mailcow-dockerized.cianfhoghlaim.ie"
    destination: mailcow-dockerized:8080
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member