services:
  pocket-id:
    labels:
      - "pangolin.private-resources.pocket-id.name=Pocket ID OIDC Provider"
      - "pangolin.private-resources.pocket-id.mode=http"
      - "pangolin.private-resources.pocket-id.destination=pocket-id"
      - "pangolin.private-resources.pocket-id.full-domain=auth.cianfhoghlaim.ie"
      - "pangolin.private-resources.pocket-id.destination-port=8080"
      - "pangolin.private-resources.pocket-id.protocol=https"
      - "pangolin.private-resources.pocket-id.roles[0]=Member"
