/**
 * A-LEVEL Sociology — per-topic detail page.
 *
 * AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 */

import { createFileRoute, useParams } from "@tanstack/react-router";
import { CopilotKit } from "@copilotkit/react-core/v2";

import { useSociologyActions } from "@/lib/copilotkit/a-level/sociology";

export const Route = createFileRoute("/a-level/sociology/$topicId" as const)({
  component: SociologyTopicPage,
});

function SociologyTopicPage() {
  const { topicId } = useParams({ from: Route.id });

  return (
    <CopilotKit runtimeUrl="/api/copilotkit/a-level/sociology">
      <div className="max-w-4xl mx-auto flex flex-col gap-8 h-full p-8">
        <h1 className="text-3xl font-bold">Topic: {topicId}</h1>
        <p className="text-slate-600">
          Sociology (A-LEVEL) — topic detail.
        </p>

        <TopicDetailActions topicId={topicId} />
      </div>
    </CopilotKit>
  );
}

function TopicDetailActions({ topicId }: { topicId: string }) {
  useSociologyActions();

  return (
    <div className="grid grid-cols-2 gap-4">
      <button data-action="get_topic_detail" data-topic-id={topicId}>
        Get topic detail
      </button>
      <button data-action="get_cross_jurisdictional_equivalences" data-topic-id={topicId}>
        Get cross-jurisdictional equivalences
      </button>
      <button data-action="save_annotation" data-topic-id={topicId}>
        Save annotation
      </button>
      <button data-action="track_progress" data-topic-id={topicId}>
        Track progress
      </button>
    </div>
  );
}
