/**
 * BetterAuth Configuration for oideachais-web
 *
 * Auto-generated by Dagger auth module.
 * Uses PocketID OAuth for authentication.
 */

import { betterAuth } from "better-auth";
import { genericOAuth } from "better-auth/plugins";

const POCKETID_ISSUER = process.env.POCKETID_ISSUER || "https://auth.cianfhoghlaim.ie";

export const auth = betterAuth({
  emailAndPassword: {
    enabled: false, // OAuth only
  },
  plugins: [
    genericOAuth({
      config: [
        {
          providerId: "pocketid",
          clientId: process.env.POCKETID_CLIENT_ID!,
          clientSecret: process.env.POCKETID_CLIENT_SECRET!,
          discoveryUrl: POCKETID_ISSUER + "/.well-known/openid-configuration",
          scopes: ["openid", "profile", "email", "groups"],
        },
      ],
    }),
  ],
  trustedOrigins: [
    "http://localhost:3005",
    "https://oideachais.cianfhoghlaim.ie",
  ],
});

export type Session = typeof auth.$Infer.Session;
export type User = typeof auth.$Infer.Session.user;
