/**
 * BetterAuth Client for oideachais-web
 *
 * Auto-generated by Dagger auth module.
 */

import { createAuthClient } from "better-auth/react";
import { genericOAuthClient } from "better-auth/client/plugins";

const baseURL = typeof window !== "undefined"
  ? window.location.origin
  : process.env.AUTH_BASE_URL || "http://localhost:3005";

export const authClient = createAuthClient({
  baseURL,
  plugins: [genericOAuthClient()],
});

export const {
  signIn,
  signUp,
  signOut,
  useSession,
  getSession,
} = authClient;
