import { useState } from "react";
import { createFileRoute, useParams } from "@tanstack/react-router";
import { useQuery } from "convex/react";
import { CopilotChat } from "@copilotkit/react-ui/v2";
import { useCopilotAction } from "@copilotkit/react-core/v2";
import { api } from "../../../convex/_generated/api";
import { SUBJECTS } from "../__root";
import { BadgeCard, type BadgeCardData } from "../../components/BadgeCard";

export const Route = createFileRoute("/realm/$subject")({
  component: RealmPage,
});

// The subject specialist agent each realm's CopilotKit chat routes to
// (agents/tuatha/<subject>_agent.py). Used both for the chat's
// `instructions` and as a display label.
const AGENT_NAME: Record<string, string> = {
  mathematics: "math_agent",
  applied_mathematics: "appm_agent",
  chemistry: "chem_agent",
  geography: "geog_agent",
  gaeilge: "gael_agent",
  english: "engl_agent",
  computer_science: "comp_agent",
  history: "hist_agent",
};

const LEVEL_LABELS: Record<string, string> = {
  LC_HL: "Higher Level / Ardleibhéal",
  LC_OL: "Ordinary Level / Gnáthleibhéal",
  LC_FL: "Foundation Level / Bonnleibhéal",
  JC: "Junior Cycle",
};

// Matches convex/questPacks.ts's row shape (camelCase, `items` is the
// subject's <Prefix>FormativeItem[] as JSON — see
// quest_pack_assets.py's module docstring for why it's typed loosely
// here rather than duplicating each subject's BAML enum shapes).
interface FormativeItem {
  id: string;
  lo_code: string;
  prompt: { text_en: string; text_ga?: string | null };
  difficulty: number;
  est_time_minutes: number;
}

interface QuestPackRow {
  packId: string;
  subject: string;
  framework: string;
  level: string;
  titleEn: string;
  titleGa?: string | null;
  descriptionEn: string;
  descriptionGa?: string | null;
  totalItems: number;
  totalMarks: number;
  estTimeMinutes: number;
  losCovered: string[];
  items: FormativeItem[];
  generatedAt: string;
  generatedBy: string;
}

function RealmPage() {
  const { subject } = useParams({ from: "/realm/$subject" });
  const meta = SUBJECTS.find((s) => s.slug === subject);

  // Real query against the docs-informed pack generated by
  // orchestration/defs/2_materials/lc_extraction/quest_pack_assets.py
  // — replaces the hardcoded item counts this route used to render.
  const pack = useQuery(api.questPacks.getBySubject, { subject }) as
    | QuestPackRow
    | null
    | undefined;

  // Streams a badge card into the chat the moment the agent reports a
  // quest completion — the generative-UI centerpiece of
  // 2026-08-08-agui-generative-credential-ui-v1. The agent (via AG-UI)
  // calls this action with the real SkillTreeBadge fields returned by
  // tuatha/badges/ledger.py::issue_badge(); this never fabricates a
  // badge client-side, it only renders one the backend already issued.
  useCopilotAction({
    name: "renderBadgeCard",
    description:
      "Render an earned badge inline in the chat immediately after a student's formative-item response earns one (marks_awarded / total_marks >= 0.8). Call this once per newly-issued badge, using the exact fields returned by the badge issuance tool — never invent a badge that wasn't actually issued.",
    parameters: [
      { name: "subject", type: "string", required: true },
      { name: "level", type: "string", required: true },
      { name: "competencyCode", type: "string", required: true },
      { name: "competencyTextEn", type: "string", required: true },
      { name: "competencyTextGa", type: "string", required: false },
      { name: "keyCompetencies", type: "string[]", required: false },
      { name: "evidenceType", type: "string", required: true },
      { name: "evidenceScorePct", type: "number", required: true },
      { name: "agentIssuer", type: "string", required: true },
      { name: "dateEarned", type: "number", required: true },
    ],
    render: ({ args }) => <BadgeCard badge={args as unknown as BadgeCardData} />,
  });

  if (!meta) {
    return (
      <div className="text-center py-12">
        <h1 className="text-2xl font-bold">Unknown subject</h1>
        <p className="text-muted-foreground mt-2">
          No realm exists for subject "{subject}".
        </p>
      </div>
    );
  }

  const Icon = meta.icon;
  const agentName = AGENT_NAME[subject] ?? `${subject}_agent`;

  return (
    <div className="space-y-8">
      <header className="flex items-center gap-4">
        <Icon className="h-12 w-12 text-primary" />
        <div>
          <h1 className="text-3xl font-bold">{meta.name_en}</h1>
          <p className="text-lg text-muted-foreground italic">{meta.name_ga}</p>
        </div>
      </header>

      <section>
        <h2 className="text-xl font-semibold mb-4">Quest packs</h2>
        {pack === undefined ? (
          <p className="text-sm text-muted-foreground">Loading quest pack…</p>
        ) : pack === null ? (
          <p className="text-sm text-muted-foreground">
            No quest pack has been generated for {meta.name_en} yet — run the{" "}
            <code>{subject}_quest_pack</code> Dagster asset to generate one from
            the official NCCA syllabus + past papers.
          </p>
        ) : (
          <QuestPackCard pack={pack} />
        )}
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-4">
          Talk to the {meta.name_en} tutor
        </h2>
        <div className="rounded-lg border bg-card overflow-hidden" style={{ height: 480 }}>
          <CopilotChat
            instructions={`You are ${agentName}, the ${meta.name_en} specialist tutor for the Cianfhoghlaim Educational MMO. Ground every answer in the official NCCA Leaving Certificate ${meta.name_en} syllabus, past papers, and marking-scheme guidance — cite the source page when you quote a learning outcome. When a student completes a formative item and earns a badge, call renderBadgeCard with the badge fields returned by the scoring tool.`}
            labels={{
              title: `${meta.name_en} tutor`,
              initial: `Sláinte! Ask me anything about the ${meta.name_en} syllabus, or start a quest above.`,
              placeholder: `Ask ${agentName} a question…`,
            }}
          />
        </div>
      </section>
    </div>
  );
}

function QuestPackCard({ pack }: { pack: QuestPackRow }) {
  const [expanded, setExpanded] = useState(false);
  const levelLabel = LEVEL_LABELS[pack.level] ?? pack.level;
  const firstItem = pack.items[0];

  return (
    <div className="p-4 rounded-lg border bg-card space-y-3">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-semibold">
            {pack.titleEn} — {levelLabel}
          </h3>
          {pack.titleGa && <p className="text-sm text-muted-foreground italic">{pack.titleGa}</p>}
          <p className="text-sm text-muted-foreground mt-1">{pack.descriptionEn}</p>
          <p className="text-xs text-muted-foreground mt-1">
            {pack.totalItems} formative items · {pack.totalMarks} marks · ≈{pack.estTimeMinutes} min
            · {pack.losCovered.length} learning outcomes covered · generated by {pack.generatedBy}
          </p>
        </div>
        <button
          className="px-3 py-1 rounded bg-primary text-primary-foreground text-sm shrink-0"
          onClick={() => setExpanded((v) => !v)}
          disabled={!firstItem}
        >
          {expanded ? "Hide" : "Start"}
        </button>
      </div>

      {expanded && firstItem && (
        <div className="rounded border bg-background p-3 space-y-1">
          <p className="text-xs uppercase tracking-wide text-muted-foreground">
            {firstItem.lo_code} · difficulty {firstItem.difficulty} · ≈{firstItem.est_time_minutes} min
          </p>
          <p className="text-sm">{firstItem.prompt.text_en}</p>
          {firstItem.prompt.text_ga && (
            <p className="text-sm text-muted-foreground italic">{firstItem.prompt.text_ga}</p>
          )}
        </div>
      )}
    </div>
  );
}
