private-resources:
  grafana:
    name: "Grafana Monitoring"
    mode: http
    full-domain: "grafana.cianfhoghlaim.ie"
    destination: grafana:3000
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
  prometheus:
    name: "Prometheus"
    mode: http
    full-domain: "prometheus.cianfhoghlaim.ie"
    destination: prometheus:9090
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
  alertmanager:
    name: "Alertmanager"
    mode: http
    full-domain: "alerts.cianfhoghlaim.ie"
    destination: alertmanager:9093
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
