services:
  main-service:
    labels:
      - "pangolin.private-resources.networking-toolbox.name=Networking-toolbox"
      - "pangolin.private-resources.networking-toolbox.mode=http"
      - "pangolin.private-resources.networking-toolbox.destination-port=8080"
      - "pangolin.private-resources.networking-toolbox.protocol=http"
      - "pangolin.private-resources.networking-toolbox.roles[0]=Member"

      - "pangolin.private-resources.networking-toolbox.full-domain=networking-toolbox.cianfhoghlaim.ie"
