private-resources:
  croilar-web:
    name: "croilar Web"
    mode: http
    full-domain: "web.croilar.cianfhoghlaim.ie"
    destination: croilar-web:3000
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
