# =============================================================================
# MATHESAR - Pangolin Blueprint
# =============================================================================

private-resources:
  mathesar:
    name: "Mathesar"
    full-domain: "mathesar.cianfhoghlaim.ie"
    mode: http
    destination-port: 8000
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
