services:
  main-service:
    labels:
      - "pangolin.private-resources.cognee.name=Cognee"
      - "pangolin.private-resources.cognee.mode=http"
      - "pangolin.private-resources.cognee.destination-port=8080"
      - "pangolin.private-resources.cognee.protocol=http"
      - "pangolin.private-resources.cognee.roles[0]=Member"

      - "pangolin.private-resources.cognee.full-domain=cognee.cianfhoghlaim.ie"
