/**
 * Per-subject Convex types for GCSE Modern Foreign Languages.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated ModernForeignLanguages* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { IdField, SystemFields } from "convex/server";

import type {
  ModernForeignLanguagesSyllabus,
  ModernForeignLanguagesPaper,
  ModernForeignLanguagesMarkingScheme,
  ModernForeignLanguagesTopics,
} from "../../../../../baml_client/typescript/baml_client/gcse/modern_foreign_languages/client";

/**
 * The BAML-generated ModernForeignLanguagesPayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type ModernForeignLanguagesPayload =
  | ModernForeignLanguagesSyllabus
  | ModernForeignLanguagesPaper
  | ModernForeignLanguagesMarkingScheme
  | ModernForeignLanguagesTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface ModernForeignLanguagesDoc extends IdField<"modern_foreign_languages">, SystemFields {
  app: "oideachais";
  stage: "gcse";
  subject: "modern_foreign_languages";
  language: "en";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: ModernForeignLanguagesPayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML modernForeignLanguagesType alias for the schema file
export type modernForeignLanguagesType = ModernForeignLanguagesPayload;
