#!/usr/bin/env bash
# =============================================================================
# seed-infisical-vault.sh
# =============================================================================
# Seeds the local Infisical `dev-baile/dev` environment with the 7 secret
# paths required by the 4 consumer stacks (lakehouse, litellm, mlflow,
# unstract). Each secret value is freshly generated with `openssl rand`
# (no production-leakage risk).
#
# USAGE:
#   1. After bringing up Infisical + signing up as admin, run:
#      infisical login --method=universal-auth
#   2. Create a project named `dev-baile` in the UI; capture the
#      PROJECT_ID from the URL.
#   3. Create a machine identity named `bunchloch-locket-machine` in the
#      UI (Project Settings → Machine Identities → Create Identity);
#      grant at least `Member` on `dev-baile/dev`. Capture the CLIENT_ID
#      and CLIENT_SECRET.
#   4. Run:
#      bun run scripts/seed-infisical-vault.sh \
#        --project-id <UUID> \
#        --client-id <UUID> \
#        --client-secret <base64>
#
# Or with no flags (will prompt):
#      bun run scripts/seed-infisical-vault.sh
#
# Environment-only mode (writes .env.dev without touching Infisical):
#      bun run scripts/seed-infisical-vault.sh --env-only
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFISICAL_DIR="$SCRIPT_DIR/../stacks/infisical"
ENV_DEV_FILE="$INFISICAL_DIR/.env.dev"

# --- argparse ---
PROJECT_ID=""
CLIENT_ID=""
CLIENT_SECRET=""
ENV_ONLY="false"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-id)    PROJECT_ID="$2"; shift 2 ;;
    --client-id)     CLIENT_ID="$2"; shift 2 ;;
    --client-secret) CLIENT_SECRET="$2"; shift 2 ;;
    --env-only)      ENV_ONLY="true"; shift ;;
    -h|--help)
      sed -n '4,30p' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

# --- generate the 5 secret values ---
ENCRYPTION_KEY=$(openssl rand -hex 16)
AUTH_SECRET=$(openssl rand -base64 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)
REDIS_URL="redis://redis:6379"
SITE_URL="http://localhost:8081"
HOST="0.0.0.0"

INFISICAL_CLIENT_SECRET=$(openssl rand -hex 32)

# Lakehouse vault secrets (the data plane root of trust)
LAKEHOUSE_POSTGRES_PASSWORD=$(openssl rand -hex 24)
LAKEHOUSE_RPC_SECRET=$(openssl rand -hex 32)
LAKEHOUSE_ADMIN_TOKEN=$(openssl rand -hex 32)
LAKEHOUSE_ACCESS_KEY_ID=$(openssl rand -hex 16)
LAKEHOUSE_SECRET_ACCESS_KEY=$(openssl rand -hex 32)
LAKEHOUSE_ENCRYPTION_KEY=$(openssl rand -hex 32)
LAKEHOUSE_JDBC_PASSWORD=$(openssl rand -hex 24)
LAKEHOUSE_DASHBOARD_SECRET=$(openssl rand -hex 32)
LAKEHOUSE_SOURCE_PG_PASSWORD=$(openssl rand -hex 24)
LAKEHOUSE_WRITER_S3_SECRET_KEY=$(openssl rand -hex 32)
LAKEHOUSE_LANCEDB_VIEWER_ADMIN_TOKEN=$(openssl rand -hex 32)

# Lakehouse Garage (the S3 access)
GARAGE_ACCESS_KEY_ID=$(openssl rand -hex 16)
GARAGE_SECRET_ACCESS_KEY=$(openssl rand -hex 32)

# Lakehouse ClickHouse + Redis (centralised consumers per centralise-data-plane)
CLICKHOUSE_USER=oideachais
CLICKHOUSE_PASSWORD=$(openssl rand -hex 24)
CLICKHOUSE_DB=oideachais
REDIS_PASSWORD=$(openssl rand -hex 24)

# Litellm
LITELLM_MASTER_KEY="sk-$(openssl rand -hex 32)"
LITELLM_SALT_KEY=$(openssl rand -hex 16)
LITELLM_POSTGRES_USER=lakekeeper
LITELLM_POSTGRES_PASSWORD=$(openssl rand -hex 24)
LITELLM_POSTGRES_DB=litellm

# MLflow
MLFLOW_POSTGRES_USER=lakekeeper
MLFLOW_POSTGRES_PASSWORD=$(openssl rand -hex 24)

# --- mode 1: write .env.dev only ---
if [[ "$ENV_ONLY" == "true" ]]; then
  echo "Writing $ENV_DEV_FILE..."
  cat > "$ENV_DEV_FILE" <<EOF
# Generated by seed-infisical-vault.sh --env-only on $(date -u +%Y-%m-%dT%H:%M:%SZ)

POSTGRES_USER=infisical
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=infisical
REDIS_URL=${REDIS_URL}
SITE_URL=${SITE_URL}
HOST=${HOST}
DB_CONNECTION_URI=postgres://infisical:${POSTGRES_PASSWORD}@db:5432/infisical
ENCRYPTION_KEY=${ENCRYPTION_KEY}
AUTH_SECRET=${AUTH_SECRET}
EOF
  chmod 600 "$ENV_DEV_FILE"
  echo "[ok] wrote $ENV_DEV_FILE (mode 0600)"
  exit 0
fi

# --- mode 2: full vault seed (requires authenticated infisical CLI) ---
if ! command -v infisical >/dev/null 2>&1; then
  echo "ERROR: 'infisical' CLI not found. Install with: mise install infisical@latest"
  exit 1
fi

if [[ -z "$PROJECT_ID" || -z "$CLIENT_ID" || -z "$CLIENT_SECRET" ]]; then
  echo "ERROR: --project-id, --client-id, --client-secret are required"
  echo "OR use --env-only to write .env.dev without vault seeding"
  exit 1
fi

# Set the env vars for the infisical CLI
export INFISICAL_API_URL="http://localhost:8081/api"
export INFISICAL_TOKEN="$CLIENT_SECRET"

# Helper to upsert a secret (silent on update, prints on create)
upsert() {
  local path="$1"
  local key="$2"
  local value="$3"
  infisical secrets set "$key=$value" --projectId="$PROJECT_ID" --env=dev --path="$path" >/dev/null
  echo "[ok] $path/$key"
}

echo "Seeding dev-baile/dev with 30+ secrets across 7 paths..."
echo ""

# 1. infisical/
upsert "infisical" "encryption_key" "$ENCRYPTION_KEY"
upsert "infisical" "auth_secret" "$AUTH_SECRET"
upsert "infisical" "postgres_password" "$POSTGRES_PASSWORD"
upsert "infisical" "client_id" "$CLIENT_ID"
upsert "infisical" "client_secret" "$INFISICAL_CLIENT_SECRET"
upsert "infisical" "project_id" "$PROJECT_ID"
upsert "infisical" "site_url" "$SITE_URL"

# 2. lakehouse/
upsert "lakehouse" "postgres_password" "$LAKEHOUSE_POSTGRES_PASSWORD"
upsert "lakehouse" "rpc_secret" "$LAKEHOUSE_RPC_SECRET"
upsert "lakehouse" "admin_token" "$LAKEHOUSE_ADMIN_TOKEN"
upsert "lakehouse" "access_key_id" "$LAKEHOUSE_ACCESS_KEY_ID"
upsert "lakehouse" "secret_access_key" "$LAKEHOUSE_SECRET_ACCESS_KEY"
upsert "lakehouse" "encryption_key" "$LAKEHOUSE_ENCRYPTION_KEY"
upsert "lakehouse" "jdbc_password" "$LAKEHOUSE_JDBC_PASSWORD"
upsert "lakehouse" "dashboard_secret" "$LAKEHOUSE_DASHBOARD_SECRET"
upsert "lakehouse" "source_pg_password" "$LAKEHOUSE_SOURCE_PG_PASSWORD"
upsert "lakehouse" "writer_s3_secret_key" "$LAKEHOUSE_WRITER_S3_SECRET_KEY"
upsert "lakehouse" "lancedb_viewer_admin_token" "$LAKEHOUSE_LANCEDB_VIEWER_ADMIN_TOKEN"

# 3. lakehouse-garage/
upsert "lakehouse-garage" "access_key_id" "$GARAGE_ACCESS_KEY_ID"
upsert "lakehouse-garage" "secret_access_key" "$GARAGE_SECRET_ACCESS_KEY"

# 4. lakehouse-clickhouse/
upsert "lakehouse-clickhouse" "user" "$CLICKHOUSE_USER"
upsert "lakehouse-clickhouse" "password" "$CLICKHOUSE_PASSWORD"
upsert "lakehouse-clickhouse" "db" "$CLICKHOUSE_DB"

# 5. lakehouse-redis/
upsert "lakehouse-redis" "password" "$REDIS_PASSWORD"

# 6. litellm/
upsert "litellm" "master_key" "$LITELLM_MASTER_KEY"
upsert "litellm" "salt_key" "$LITELLM_SALT_KEY"
upsert "litellm" "postgres_user" "$LITELLM_POSTGRES_USER"
upsert "litellm" "postgres_password" "$LITELLM_POSTGRES_PASSWORD"
upsert "litellm" "postgres_db" "$LITELLM_POSTGRES_DB"
upsert "litellm" "database_url" "postgresql://${LITELLM_POSTGRES_USER}:${LITELLM_POSTGRES_PASSWORD}@lakehouse-postgres:5432/litellm"

# 7. mlflow/
upsert "mlflow" "postgres_user" "$MLFLOW_POSTGRES_USER"
upsert "mlflow" "postgres_password" "$MLFLOW_POSTGRES_PASSWORD"
upsert "mlflow" "aws_default_region" "garage"
upsert "mlflow" "default_artifact_root" "s3://mlflow-artifacts/"
upsert "mlflow" "uri" "http://mlflow:5000"

echo ""
echo "[ok] 33 secrets seeded across 7 paths in dev-baile/dev"
echo ""
echo "Local Infisical host:  $SITE_URL"
echo "Project ID:            $PROJECT_ID"
echo "Locket machine ID:     $CLIENT_ID"
echo "Locket client secret:  $INFISICAL_CLIENT_SECRET  (save this — it's NOT recoverable)"
echo ""
echo "Next step: bring up Change 2 (the 4 consumer stacks)"
echo "  cd bonneagar/stacks/lakehouse && docker compose -f compose.yaml -f sidecar.yaml up -d"