[package]
name = "celtic-nft"
description = "Solana Metaplex Core NFT program for Celtic game collectibles"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "celtic_nft"

[features]
default = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
solana-program = { workspace = true }
mpl-core = { workspace = true }
cianfhoghlaim-shared-types = { path = "../../../stdb-modules/shared-types" }

[dev-dependencies]
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true }
