"""Browser tools for domain-specific scraping.

Tools for Irish educational and cultural content extraction.
"""

from .approval import (
    ApprovalRequest,
    ApprovalResponse,
    approval_tools,
    cancel_approval,
    get_pending_approvals,
    handle_approval,
    request_approval,
    wait_for_approval,
)
from .canuint_scraper import (
    CanuintRecording,
    CanuintScraper,
    DialectCollection,
    IrishDialect,
    RecordingType,
    download_canuint_audio,
    export_tts_dataset,
    scrape_canuint_dialect,
    scrape_canuint_recording,
)
from .duchas_scraper import (
    DuchasCollection,
    DuchasPage,
    DuchasScraper,
    DuchasVolume,
    download_duchas_image,
    get_scraper,
    scrape_duchas_collection,
    scrape_duchas_page,
    scrape_duchas_volume,
)
from .zai_tools import (
    analyze_chart,
    analyze_video,
    analyze_vision,
    compare_ui_images,
    diagnose_error,
    extract_text_ocr,
    get_github_repo_structure,
    read_github_file,
    search_github_docs,
    ui_diff,
    ui_to_code,
    ui_to_prompt,
    ui_to_spec,
    understand_diagram,
    visual_grounding,
    web_reader,
    web_search_prime,
)

__all__ = [
    # Duchas
    "DuchasCollection",
    "DuchasPage",
    "DuchasScraper",
    "DuchasVolume",
    "download_duchas_image",
    "get_scraper",
    "scrape_duchas_collection",
    "scrape_duchas_page",
    "scrape_duchas_volume",
    # Canuint
    "CanuintRecording",
    "CanuintScraper",
    "DialectCollection",
    "IrishDialect",
    "RecordingType",
    "download_canuint_audio",
    "export_tts_dataset",
    "scrape_canuint_dialect",
    "scrape_canuint_recording",
    # Approval
    "ApprovalRequest",
    "ApprovalResponse",
    "approval_tools",
    "cancel_approval",
    "get_pending_approvals",
    "handle_approval",
    "request_approval",
    "wait_for_approval",
    # ZAI Vision Tools
    "analyze_chart",
    "analyze_video",
    "analyze_vision",
    "compare_ui_images",
    "diagnose_error",
    "extract_text_ocr",
    "get_github_repo_structure",
    "read_github_file",
    "search_github_docs",
    "ui_diff",
    "ui_to_code",
    "ui_to_prompt",
    "ui_to_spec",
    "understand_diagram",
    "visual_grounding",
    "web_reader",
    "web_search_prime",
]
