private-resources:
  headplane:
    name: "Headplane (Web UI)"
    mode: http
    full-domain: "hp.cianfhoghlaim.ie"
    destination-port: 3000
    protocol: http
    sites: [arm1-oci]
    roles: [Member]
