services:
  main-service:
    labels:
      - "pangolin.private-resources.blinko.name=Blinko"
      - "pangolin.private-resources.blinko.mode=http"
      - "pangolin.private-resources.blinko.full-domain=blinko.cianfhoghlaim.ie"
      - "pangolin.private-resources.blinko.destination=blinko:8080"
      - "pangolin.private-resources.blinko.protocol=http"
      - "pangolin.private-resources.blinko.roles[0]=Member"