// =============================================================================
// GENERATE ANSIBLE INVENTORY ACTION
// =============================================================================
// Generates Ansible inventory YAML from Komodo servers.
// Run this after adding new servers or updating server configurations.
//
// Usage:
//   km run action generate-ansible-inventory
//   km run action generate-ansible-inventory --output=/etc/ansible/inventory/komodo.yml
// =============================================================================

const dryRun = ARGS.dryRun || false;
const outputPath = ARGS.output || "/etc/komodo/ansible/inventory/komodo-generated.yml";
const outputServer = ARGS.server || "arm1-oci"; // Server where to write inventory

interface ServerInfo {
  name: string;
  ip: string;
  user: string;
  region?: string;
  isCore: boolean;
  hasPeriphery: boolean;
}

// Get all servers from Komodo
console.log("Fetching servers from Komodo...\n");
const servers = await komodo.read("ListServers", {});

const serverInfos: ServerInfo[] = [];

for (const server of servers) {
  const details = await komodo.read("GetServer", { server: server.name });

  // Extract IP from address
  let ip = details?.config?.address || "";
  ip = ip.replace(/:\d+$/, "").replace(/^https?:\/\//, "").replace(/^wss?:\/\//, "");

  // Determine user based on server name/region
  let user = "ubuntu";
  if (server.name.includes("hetzner")) {
    user = "root";
  } else if (server.name === "bunchloch") {
    user = "cliste";
  }

  // Determine if this is core server
  const isCore = server.name === "bunchloch" || server.name.includes("core");

  // Check if periphery is connected
  const hasPeriphery = details?.info?.state === "Ok";

  serverInfos.push({
    name: server.name,
    ip,
    user,
    region: details?.config?.region,
    isCore,
    hasPeriphery,
  });

  const peripheryStatus = hasPeriphery ? "connected" : "not connected";
  console.log(`  ${server.name}: ${ip} (user: ${user}, periphery: ${peripheryStatus})`);
}

// Generate inventory YAML
const coreHosts = serverInfos.filter((s) => s.isCore).map((s) => s.name);
const peripheryHosts = serverInfos.filter((s) => s.hasPeriphery).map((s) => s.name);
const allHosts = serverInfos.map((s) => s.name);

const inventory = `---
# =============================================================================
# KOMODO INVENTORY (Auto-generated)
# =============================================================================
# Generated by: generate-ansible-inventory action
# Generated at: ${new Date().toISOString()}
# =============================================================================

all:
  hosts:
${serverInfos
  .map(
    (s) => `    ${s.name}:
      ansible_host: "${s.ip}"
      ansible_user: ${s.user}${s.name === "bunchloch" ? "\n      ansible_become: false" : ""}`
  )
  .join("\n")}

  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_ed25519

    # Periphery version
    periphery_version: "2.0.0-dev-102"

    # Periphery configuration (outbound mode)
    periphery_core_address: "wss://komodo.cianfhoghlaim.ie"
    periphery_mode: outbound
    periphery_server_enabled: false
    periphery_passkey_op_ref: "op://dev-baile/komodo/passkey"

    # Locket configuration
    locket_enabled: true
    locket_provider: op-connect
    locket_op_connect_host: "http://132.145.27.89:8080"

  children:
    # All hosts with locket
    locket:
      hosts:
${allHosts.map((h) => `        ${h}:`).join("\n")}

    # Hosts with periphery
    periphery:
      vars:
        periphery_agent_secrets:
          - name: "PERIPHERY_PASSKEYS"
            value: "{{ periphery_passkey_op_ref }}"
          - name: "OP_CONNECT_HOST"
            value: "{{ locket_op_connect_host }}"
      hosts:
${peripheryHosts.map((h) => `        ${h}:`).join("\n")}

    # Core hosts (Komodo Core runs here)
    core:
      hosts:
${coreHosts.map((h) => `        ${h}:`).join("\n") || "        # No core hosts defined"}

    # Environment groups
    production:
      hosts:
${peripheryHosts.map((h) => `        ${h}:`).join("\n")}
`;

console.log("\nGenerated inventory:");
console.log("---");
console.log(inventory);
console.log("---");

if (!dryRun) {
  // Write inventory to the specified server
  console.log(`\nWriting inventory to ${outputServer}:${outputPath}...`);

  // Ensure directory exists
  await komodo.execute("RunCommand", {
    server: outputServer,
    command: `mkdir -p $(dirname ${outputPath})`,
  });

  // Write the file
  await komodo.execute("RunCommand", {
    server: outputServer,
    command: `cat > ${outputPath} << 'INVENTORYEOF'
${inventory}
INVENTORYEOF`,
  });

  console.log(`  Inventory written to ${outputPath}`);
} else {
  console.log(`\n[DRY-RUN] Would write inventory to ${outputServer}:${outputPath}`);
}

return {
  success: true,
  dryRun,
  servers: serverInfos.length,
  coreHosts,
  peripheryHosts,
  outputPath,
  outputServer,
};
