import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, Loader2 } from "lucide-react";
import { fetchSnapshot, type MarimoNotebook } from "../../../lib/webstack";

export const Route = createFileRoute("/_layout/notebooks/$slug")({
  component: NotebookDetailPage,
});

function NotebookDetailPage() {
  const { slug } = Route.useParams();
  const [notebook, setNotebook] = useState<MarimoNotebook | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFoundFlag, setNotFoundFlag] = useState(false);

  useEffect(() => {
    let mounted = true;
    fetchSnapshot().then((s) => {
      if (!mounted) return;
      const nb = s.marimoNotebooks.find((n) => n.slug === slug);
      if (!nb) {
        setNotFoundFlag(true);
      } else {
        setNotebook(nb);
      }
      setLoading(false);
    });
    return () => {
      mounted = false;
    };
  }, [slug]);

  if (notFoundFlag) throw notFound();
  if (loading) {
    return (
      <div className="p-6 flex items-center gap-2 text-muted-foreground">
        <Loader2 className="animate-spin" size={16} />
        Loading…
      </div>
    );
  }
  if (!notebook) return null;

  return (
    <div className="p-6 space-y-4">
      <Link
        to="/notebooks"
        className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1"
      >
        <ArrowLeft size={14} />
        Notebooks
      </Link>
      <div>
        <h1 className="text-2xl font-bold">{notebook.title}</h1>
        <div className="text-sm text-muted-foreground font-mono">
          {notebook.project} / {notebook.slug}
        </div>
      </div>
      <div className="bg-card rounded-lg border p-6 text-center text-muted-foreground">
        <div className="text-sm">
          Marimo WASM export is generated by{" "}
          <code className="font-mono">bun run croilar/scripts/export-marimo-wasm.ts</code>
        </div>
        <div className="text-xs mt-2">
          {notebook.file} · {notebook.cellCount} cells
        </div>
      </div>
    </div>
  );
}
