/**
 * Service Clients Module
 *
 * Generates unified service client libraries for all apps,
 * providing standardized access to:
 * - LiteLLM (LLM Gateway)
 * - Langfuse (Observability)
 * - LanceDB / FalkorDB (Vector/Graph)
 * - Cognee (AI Memory)
 */

import { dag, Directory, object, func } from "@dagger.io/dagger";
import { APP_CONFIGS } from "./apps.js";

// =============================================================================
// Service endpoints
// =============================================================================

const SERVICES = {
  litellm: {
    production: "https://llm.cianfhoghlaim.ie",
    local: "http://localhost:4000",
    envVar: "LITELLM_URL",
  },
  langfuse: {
    production: "https://langfuse.cianfhoghlaim.ie",
    local: "http://localhost:3000",
    envVar: "LANGFUSE_HOST",
  },
  lancedb: {
    production: "https://lancedb.cianfhoghlaim.ie",
    local: "http://localhost:8080",
    envVar: "LANCEDB_URI",
  },
  falkordb: {
    production: "falkordb.cianfhoghlaim.ie",
    local: "localhost",
    port: 6379,
    envVar: "FALKORDB_HOST",
  },
  qdrant: {
    production: "qdrant.cianfhoghlaim.ie",
    local: "localhost",
    httpPort: 6333,
    grpcPort: 6334,
    envVar: "QDRANT_HOST",
  },
  cognee: {
    production: "https://cognee.cianfhoghlaim.ie",
    local: "http://localhost:8001",
    envVar: "COGNEE_HOST",
  },
  mlflow: {
    production: "https://mlflow.cianfhoghlaim.ie",
    local: "http://localhost:5000",
    envVar: "MLFLOW_TRACKING_URI",
  },
};

@object()
export class ServiceClients {
  /**
   * Generate TypeScript service client for an app
   */
  @func()
  generateTypescriptClient(appName: string): string {
    return `// ${appName} - Unified Service Client
// Auto-generated by Dagger ServiceClients module
// Provides access to all ML infrastructure services

// =============================================================================
// Service Configuration
// =============================================================================

export const services = {
  llm: {
    endpoint: process.env.LITELLM_URL || "${SERVICES.litellm.production}",
    apiKey: process.env.LITELLM_API_KEY,
  },
  langfuse: {
    publicKey: process.env.LANGFUSE_PUBLIC_KEY,
    secretKey: process.env.LANGFUSE_SECRET_KEY,
    host: process.env.LANGFUSE_HOST || "${SERVICES.langfuse.production}",
  },
  vectordb: {
    lancedb: process.env.LANCEDB_URI || "${SERVICES.lancedb.production}",
    falkordb: {
      host: process.env.FALKORDB_HOST || "${SERVICES.falkordb.production}",
      port: parseInt(process.env.FALKORDB_PORT || "${SERVICES.falkordb.port}"),
      password: process.env.FALKORDB_PASSWORD,
    },
    qdrant: {
      host: process.env.QDRANT_HOST || "${SERVICES.qdrant.production}",
      httpPort: parseInt(process.env.QDRANT_PORT || "${SERVICES.qdrant.httpPort}"),
      apiKey: process.env.QDRANT_API_KEY,
    },
  },
  memory: {
    cognee: process.env.COGNEE_HOST || "${SERVICES.cognee.production}",
  },
  mlflow: {
    trackingUri: process.env.MLFLOW_TRACKING_URI || "${SERVICES.mlflow.production}",
  },
};

// =============================================================================
// LLM Client (via LiteLLM Gateway)
// =============================================================================

export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface ChatOptions {
  model?: string;
  temperature?: number;
  maxTokens?: number;
}

export async function chat(
  messages: ChatMessage[],
  options: ChatOptions = {}
): Promise<{ content: string; model: string }> {
  const { model = "fast", temperature = 0.7, maxTokens } = options;

  const response = await fetch(\`\${services.llm.endpoint}/v1/chat/completions\`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(services.llm.apiKey ? { Authorization: \`Bearer \${services.llm.apiKey}\` } : {}),
    },
    body: JSON.stringify({
      model,
      messages,
      temperature,
      ...(maxTokens ? { max_tokens: maxTokens } : {}),
    }),
  });

  if (!response.ok) {
    throw new Error(\`LiteLLM error: \${response.status} \${response.statusText}\`);
  }

  const data = await response.json();
  return {
    content: data.choices[0].message.content,
    model: data.model,
  };
}

// Model aliases for convenience
export const models = {
  fast: "fast",           // Gemma-3n (lightweight)
  reasoning: "reasoning", // Nemotron-3-Nano (complex tasks)
  vision: "vision",       // Qwen3-VL (multimodal)
  ocr: "ocr",            // olmOCR2 (document processing)
  image: "image",        // Z-Image-Turbo (generation)
  irish: "irish",        // Qomhrá (Irish language)
  extract: "extract",    // Gemini 2.5 Pro (structured extraction)
};

// =============================================================================
// Langfuse Tracing
// =============================================================================

export function createTrace(name: string, metadata?: Record<string, unknown>) {
  // Lazy import to avoid issues when Langfuse SDK not installed
  const { Langfuse } = require("langfuse");

  const client = new Langfuse({
    publicKey: services.langfuse.publicKey,
    secretKey: services.langfuse.secretKey,
    baseUrl: services.langfuse.host,
  });

  return client.trace({
    name,
    metadata: {
      app: "${appName}",
      ...metadata,
    },
  });
}

// =============================================================================
// Vector Search
// =============================================================================

export async function vectorSearch(
  query: string,
  collection: string,
  topK = 10
): Promise<Array<{ id: string; score: number; payload: Record<string, unknown> }>> {
  // Use Qdrant for vector search
  const response = await fetch(
    \`http://\${services.vectordb.qdrant.host}:\${services.vectordb.qdrant.httpPort}/collections/\${collection}/points/search\`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(services.vectordb.qdrant.apiKey
          ? { "api-key": services.vectordb.qdrant.apiKey }
          : {}),
      },
      body: JSON.stringify({
        query,
        limit: topK,
        with_payload: true,
      }),
    }
  );

  if (!response.ok) {
    throw new Error(\`Qdrant error: \${response.status}\`);
  }

  const data = await response.json();
  return data.result || [];
}

// =============================================================================
// Knowledge Graph Query
// =============================================================================

export async function graphQuery(
  cypher: string,
  graphName = "curriculum"
): Promise<unknown> {
  const { createClient } = require("redis");

  const client = createClient({
    socket: {
      host: services.vectordb.falkordb.host,
      port: services.vectordb.falkordb.port,
    },
    password: services.vectordb.falkordb.password,
  });

  await client.connect();

  try {
    const result = await client.sendCommand(["GRAPH.QUERY", graphName, cypher]);
    return result;
  } finally {
    await client.disconnect();
  }
}

// =============================================================================
// AI Memory
// =============================================================================

export async function searchMemory(
  query: string,
  topK = 10
): Promise<unknown> {
  const response = await fetch(\`\${services.memory.cognee}/v1/search\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ query, top_k: topK }),
  });

  if (!response.ok) {
    throw new Error(\`Cognee error: \${response.status}\`);
  }

  return response.json();
}

export async function addToMemory(
  content: string,
  collection = "default"
): Promise<unknown> {
  const response = await fetch(\`\${services.memory.cognee}/v1/add\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ content, collection }),
  });

  if (!response.ok) {
    throw new Error(\`Cognee error: \${response.status}\`);
  }

  return response.json();
}
`;
  }

  /**
   * Generate Python service client for an app
   */
  @func()
  generatePythonClient(appName: string): string {
    return `# ${appName} - Unified Service Client
# Auto-generated by Dagger ServiceClients module
# Provides access to all ML infrastructure services

import os
from typing import Any, Optional

import httpx

# =============================================================================
# Service Configuration
# =============================================================================

class ServiceConfig:
    """Centralized service configuration."""

    llm_endpoint = os.environ.get("LITELLM_URL", "${SERVICES.litellm.production}")
    llm_api_key = os.environ.get("LITELLM_API_KEY")

    langfuse_host = os.environ.get("LANGFUSE_HOST", "${SERVICES.langfuse.production}")
    langfuse_public_key = os.environ.get("LANGFUSE_PUBLIC_KEY")
    langfuse_secret_key = os.environ.get("LANGFUSE_SECRET_KEY")

    lancedb_uri = os.environ.get("LANCEDB_URI", "${SERVICES.lancedb.production}")
    falkordb_host = os.environ.get("FALKORDB_HOST", "${SERVICES.falkordb.production}")
    falkordb_port = int(os.environ.get("FALKORDB_PORT", "${SERVICES.falkordb.port}"))
    falkordb_password = os.environ.get("FALKORDB_PASSWORD")

    qdrant_host = os.environ.get("QDRANT_HOST", "${SERVICES.qdrant.production}")
    qdrant_port = int(os.environ.get("QDRANT_PORT", "${SERVICES.qdrant.httpPort}"))
    qdrant_api_key = os.environ.get("QDRANT_API_KEY")

    cognee_host = os.environ.get("COGNEE_HOST", "${SERVICES.cognee.production}")
    mlflow_uri = os.environ.get("MLFLOW_TRACKING_URI", "${SERVICES.mlflow.production}")


config = ServiceConfig()


# =============================================================================
# LLM Client (via LiteLLM Gateway)
# =============================================================================

async def chat(
    messages: list[dict[str, str]],
    model: str = "fast",
    temperature: float = 0.7,
    max_tokens: Optional[int] = None,
) -> dict[str, Any]:
    """Send a chat completion request to LiteLLM."""
    headers = {"Content-Type": "application/json"}
    if config.llm_api_key:
        headers["Authorization"] = f"Bearer {config.llm_api_key}"

    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
    }
    if max_tokens:
        payload["max_tokens"] = max_tokens

    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"{config.llm_endpoint}/v1/chat/completions",
            json=payload,
            headers=headers,
            timeout=60.0,
        )
        response.raise_for_status()
        data = response.json()
        return {
            "content": data["choices"][0]["message"]["content"],
            "model": data["model"],
        }


# Model aliases
MODELS = {
    "fast": "fast",           # Gemma-3n (lightweight)
    "reasoning": "reasoning", # Nemotron-3-Nano (complex tasks)
    "vision": "vision",       # Qwen3-VL (multimodal)
    "ocr": "ocr",            # olmOCR2 (document processing)
    "image": "image",        # Z-Image-Turbo (generation)
    "irish": "irish",        # Qomhrá (Irish language)
    "extract": "extract",    # Gemini 2.5 Pro (structured extraction)
}


# =============================================================================
# Langfuse Tracing
# =============================================================================

def create_trace(name: str, metadata: Optional[dict[str, Any]] = None):
    """Create a Langfuse trace."""
    from langfuse import Langfuse

    client = Langfuse(
        public_key=config.langfuse_public_key,
        secret_key=config.langfuse_secret_key,
        host=config.langfuse_host,
    )

    return client.trace(
        name=name,
        metadata={
            "app": "${appName}",
            **(metadata or {}),
        },
    )


# =============================================================================
# Vector Search
# =============================================================================

async def vector_search(
    query: str,
    collection: str,
    top_k: int = 10,
) -> list[dict[str, Any]]:
    """Search vectors in Qdrant."""
    headers = {"Content-Type": "application/json"}
    if config.qdrant_api_key:
        headers["api-key"] = config.qdrant_api_key

    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"http://{config.qdrant_host}:{config.qdrant_port}/collections/{collection}/points/search",
            json={"query": query, "limit": top_k, "with_payload": True},
            headers=headers,
        )
        response.raise_for_status()
        data = response.json()
        return data.get("result", [])


# =============================================================================
# Knowledge Graph Query
# =============================================================================

async def graph_query(cypher: str, graph_name: str = "curriculum") -> Any:
    """Execute a Cypher query on FalkorDB."""
    import redis.asyncio as redis

    client = redis.Redis(
        host=config.falkordb_host,
        port=config.falkordb_port,
        password=config.falkordb_password,
        decode_responses=True,
    )

    try:
        result = await client.execute_command("GRAPH.QUERY", graph_name, cypher)
        return result
    finally:
        await client.close()


# =============================================================================
# AI Memory
# =============================================================================

async def search_memory(query: str, top_k: int = 10) -> Any:
    """Search Cognee memory."""
    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"{config.cognee_host}/v1/search",
            json={"query": query, "top_k": top_k},
        )
        response.raise_for_status()
        return response.json()


async def add_to_memory(content: str, collection: str = "default") -> Any:
    """Add content to Cognee memory."""
    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"{config.cognee_host}/v1/add",
            json={"content": content, "collection": collection},
        )
        response.raise_for_status()
        return response.json()
`;
  }

  /**
   * Generate environment template for an app
   */
  @func()
  generateEnvTemplate(appName: string): string {
    return `# ${appName} - ML Infrastructure Environment Variables
# Auto-generated by Dagger ServiceClients module

# =============================================================================
# LiteLLM Gateway
# =============================================================================
LITELLM_URL=${SERVICES.litellm.production}
LITELLM_API_KEY=  # Optional: Set if authentication required

# =============================================================================
# Langfuse Observability
# =============================================================================
LANGFUSE_HOST=${SERVICES.langfuse.production}
LANGFUSE_PUBLIC_KEY=  # Get from Langfuse dashboard
LANGFUSE_SECRET_KEY=  # Get from Langfuse dashboard

# =============================================================================
# Vector Databases
# =============================================================================
# LanceDB
LANCEDB_URI=${SERVICES.lancedb.production}

# FalkorDB (Graph + Vector)
FALKORDB_HOST=${SERVICES.falkordb.production}
FALKORDB_PORT=${SERVICES.falkordb.port}
FALKORDB_PASSWORD=  # Set for production

# Qdrant
QDRANT_HOST=${SERVICES.qdrant.production}
QDRANT_PORT=${SERVICES.qdrant.httpPort}
QDRANT_API_KEY=  # Optional

# =============================================================================
# AI Memory
# =============================================================================
COGNEE_HOST=${SERVICES.cognee.production}

# =============================================================================
# MLflow
# =============================================================================
MLFLOW_TRACKING_URI=${SERVICES.mlflow.production}
`;
  }

  /**
   * Write service clients to all apps in the monorepo
   */
  @func()
  async writeServiceClients(
    source: Directory,
    appNames?: string[]
  ): Promise<string> {
    const apps = appNames || Object.keys(APP_CONFIGS);
    const results: string[] = [];

    for (const appName of apps) {
      const config = APP_CONFIGS[appName];
      if (!config) {
        results.push(`${appName}: App not found in registry`);
        continue;
      }

      const runtime = config.runtime;
      const clientPath = `${config.path}/src/lib/services`;

      if (runtime === "bun" || runtime === "node") {
        // Write TypeScript client
        const content = this.generateTypescriptClient(appName);
        results.push(`${appName}: Would write TypeScript client to ${clientPath}.ts`);
      } else if (runtime === "uv") {
        // Write Python client
        const content = this.generatePythonClient(appName);
        results.push(`${appName}: Would write Python client to ${clientPath}.py`);
      }
    }

    return results.join("\n");
  }

  /**
   * Get all service endpoints
   */
  @func()
  getServiceEndpoints(local: boolean = false): Record<string, string> {
    const endpoints: Record<string, string> = {};

    for (const [name, service] of Object.entries(SERVICES)) {
      endpoints[name] = local
        ? (service as { local: string }).local
        : (service as { production: string }).production;
    }

    return endpoints;
  }
}
