/**
 * Per-subject Convex types for LC Accounting.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated Accounting* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { Doc as BaseDoc } from "convex/server";

import type {
  AccountingSyllabus,
  AccountingPaper,
  AccountingMarkingScheme,
  AccountingTopics,
} from "../../../../baml_client/typescript/baml_client/lc/accounting/client";

/**
 * The BAML-generated AccountingPayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type AccountingPayload =
  | AccountingSyllabus
  | AccountingPaper
  | AccountingMarkingScheme
  | AccountingTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface AccountingDoc extends BaseDoc {
  app: "oideachais";
  stage: "lc";
  subject: "accounting";
  language: "en" | "ga";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: AccountingPayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML accountingType alias for the schema file
export type accountingType = AccountingPayload;
