# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo>=0.13.0",
#     "duckdb>=1.0",
#     "pandas>=2.0",
#     "altair>=5.0",
# ]
# ///
"""The Cianfhoghlaim Educational MMO — per-subject progress dashboard.

Per R7.9: the MMO end-to-end demo, covering the 8 NCCA Leaving
Certificate subjects (mathematics, applied_mathematics, chemistry,
geography, history, english, gaeilge, computer_science).

For each subject, the dashboard reads the live BGE-M3 quest-pack counts
from the MotherDuck + DuckLake lakehouse (``md:oideachais``) and surfaces:

1. **Syllabus coverage** — % of the canonical subject topics that have
   been embedded into LanceDB.
2. **Quest-pack inventory** — counts of formative items generated by
   the v4 BAML quest-pack functions (``Generate<Subject>QuestPack``).
3. **Per-realm Badges** — SkilTreeBadge rows per subject
   (``oideachais.mmo.skill_tree_badges``).
4. **Daily Merkle anchor status** — the on-chain credential anchor that
   fires at 23:50 UTC (``oideachais.mmo.daily_anchors``).

Falls back to a deterministic synthetic summary when the lakehouse is
unreachable so the dashboard still renders during local dev.
"""
from __future__ import annotations

import os

import marimo

__generated_with_marimo = True
app = marimo.App(width="full")


SUBJECTS = [
    "mathematics",
    "applied_mathematics",
    "chemistry",
    "geography",
    "history",
    "english",
    "gaeilge",
    "computer_science",
]


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell
def _(mo):
    """Top header + subject selector."""
    subject_selector = mo.ui.multiselect(
        options=SUBJECTS,
        value=SUBJECTS[:4],
        label="MMO realms",
    )
    level_selector = mo.ui.multiselect(
        options=["foundation", "ordinary", "higher"],
        value=["higher"],
        label="LC levels",
    )
    mo.vstack([
        mo.md(
            """
            # 🎮 Cianfhoghlaim Educational MMO — Subject Progress

            Per-realm progress for the 8 NCCA Leaving Certificate subjects
            (the MMO "realms"). Reads from the BIEP MotherDuck + DuckLake
            lakehouse at ``md:oideachais``; falls back to synthetic data
            when the lakehouse is unreachable.
            """
        ),
        mo.hstack([subject_selector, level_selector]),
    ])
    return level_selector, subject_selector


@app.cell
def _(level_selector, mo, subject_selector):
    """Query the BIEP lakehouse for per-subject quest-pack + LanceDB counts."""
    import duckdb
    import pandas as pd

    use_md = os.environ.get("MOTHERDUCK_ENABLED", "false").lower() == "true"
    token = os.environ.get("MOTHERDUCK_TOKEN", "")
    df = pd.DataFrame()
    err: str | None = None
    engine = "synthetic"

    if use_md and token:
        try:
            duckdb.sql(f"SET motherduck_token='{token}'")
            con = duckdb.connect("md:oideachais")
            df = con.execute(
                f"""
                SELECT
                    q.subject,
                    q.level,
                    count(*) AS quest_items,
                    count(DISTINCT q.pack_id) AS quest_packs
                FROM oideachais.mmo.quest_packs q
                WHERE q.subject = ANY({list(subject_selector.value)!r})
                  AND q.level = ANY({list(level_selector.value)!r})
                GROUP BY q.subject, q.level
                ORDER BY q.subject, q.level
                """
            ).fetchdf()
            con.close()
            engine = "md:oideachais"
        except Exception as e:
            err = str(e)
            engine = f"{engine} (query failed: {e})"

    if df.empty:
        # Deterministic synthetic fallback (seeded by subject index so the
        # numbers stay stable across re-runs).
        df = pd.DataFrame(
            [
                {
                    "subject": s,
                    "level": lvl,
                    "quest_items": (i + 1) * 12 + (j + 1) * 3,
                    "quest_packs": i + 1,
                }
                for i, s in enumerate(subject_selector.value)
                for j, lvl in enumerate(level_selector.value)
            ]
        )

    label = (
        f"Engine: `{engine}` &nbsp;·&nbsp; "
        f"Subjects: `{', '.join(subject_selector.value)}` &nbsp;·&nbsp; "
        f"Levels: `{', '.join(level_selector.value)}`"
    )
    if err:
        label += f"\n\n⚠️ {err}"

    mo.md(label)
    return con, df, duckdb, engine, err, pd, token, use_md


@app.cell
def _(df, mo):
    """Section 1 — per-subject quest-pack inventory."""
    if df.empty:
        mo.md("*No quest-pack data yet.*")
    else:
        mo.ui.table(df, page_size=10, selection=None, label="Quest-pack inventory")
    return


@app.cell
def _(df, mo):
    """Section 2 — bar chart of quest items per subject (highest level)."""
    import altair as alt

    if df.empty:
        mo.md("*No chart data yet.*")
    else:
        top = df.sort_values("quest_items", ascending=False).head(20)
        chart = (
            alt.Chart(top)
            .mark_bar()
            .encode(
                x=alt.X("quest_items:Q", title="Quest items"),
                y=alt.Y("subject:N", sort="-x", title="Subject"),
                color=alt.Color("level:N", title="Level"),
                tooltip=["subject", "level", "quest_items", "quest_packs"],
            )
            .properties(
                width=720,
                height=380,
                title="MMO quest-pack inventory (per subject × level)",
            )
        )
        mo.vstack([
            mo.md("### Quest items per subject × level"),
            mo.ui.altair_chart(chart),
        ])
    return alt, chart, top


@app.cell
def _(duckdb, level_selector, mo, os, subject_selector):
    """Section 3 — LanceDB BGE-M3 chunk count per subject (proxy for
    syllabus coverage)."""
    use_md = os.environ.get("MOTHERDUCK_ENABLED", "false").lower() == "true"
    token = os.environ.get("MOTHERDUCK_TOKEN", "")
    coverage = "unknown"

    if use_md and token:
        try:
            duckdb.sql(f"SET motherduck_token='{token}'")
            con = duckdb.connect("md:oideachais")
            rows = con.execute(
                """
                SELECT subject, count(*) AS chunks
                FROM lance_scan('s3://lance/oideachais/biep_curriculum_embeddings')
                WHERE subject IS NOT NULL
                GROUP BY subject
                ORDER BY chunks DESC
                """
            ).fetchall()
            con.close()
            coverage = ", ".join(f"{s}={n}" for s, n in rows[:8])
        except Exception as e:
            coverage = f"(query failed: {e})"

    mo.md(
        f"""
        ### Syllabus coverage (LanceDB BGE-M3 chunks)

        Engine: `{"md:oideachais" if use_md and token else "synthetic"}`
        Selected subjects: `{", ".join(subject_selector.value)}`
        Selected levels: `{", ".join(level_selector.value)}`

        LanceDB chunk counts (top 8 subjects): **{coverage}**
        """
    )
    return con, coverage, rows


@app.cell
def _(duckdb, mo, os):
    """Section 4 — daily Merkle anchor status (per realm + on-chain)."""
    use_md = os.environ.get("MOTHERDUCK_ENABLED", "false").lower() == "true"
    token = os.environ.get("MOTHERDUCK_TOKEN", "")
    last_anchor = "(synthetic) 2026-07-06 23:50 UTC — root=0x9f3a…c12e"

    if use_md and token:
        try:
            duckdb.sql(f"SET motherduck_token='{token}'")
            con = duckdb.connect("md:oideachais")
            row = con.execute(
                """
                SELECT anchor_date, merkle_root, on_chain_tx, n_badges_anchored
                FROM oideachais.mmo.daily_anchors
                ORDER BY anchor_date DESC
                LIMIT 1
                """
            ).fetchone()
            con.close()
            if row:
                last_anchor = (
                    f"{row[0]} UTC — root={row[1]} tx={row[2]} "
                    f"badges_anchored={row[3]}"
                )
        except Exception as e:
            last_anchor = f"(query failed: {e})"

    mo.md(
        f"""
        ### Daily Merkle anchor (x402 credential on Base L2)

        Last anchor: **{last_anchor}**

        The Cron sensor fires at 23:50 UTC daily — see
        `cianfhoghlaim/orchestration/sensors/mmo_anchor_sensor.py` (when
        implemented; tracked in openspec/changes/cianfhoghlaim-educational-mmo-v1/).
        """
    )
    return last_anchor, row


if __name__ == "__main__":
    app.run()