/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealmSubjectRouteImport } from './routes/realm/$subject'
import { Route as AnchorDateRouteImport } from './routes/anchor/$date'
import { Route as TeacherClassQuestsRouteImport } from './routes/teacher/$class/quests'
import { Route as StudentIdMasteryRouteImport } from './routes/student/$id/mastery'
import { Route as StudentIdBadgesRouteImport } from './routes/student/$id/badges'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmSubjectRoute = RealmSubjectRouteImport.update({
  id: '/realm/$subject',
  path: '/realm/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const AnchorDateRoute = AnchorDateRouteImport.update({
  id: '/anchor/$date',
  path: '/anchor/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassQuestsRoute = TeacherClassQuestsRouteImport.update({
  id: '/teacher/$class/quests',
  path: '/teacher/$class/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIdMasteryRoute = StudentIdMasteryRouteImport.update({
  id: '/student/$id/mastery',
  path: '/student/$id/mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIdBadgesRoute = StudentIdBadgesRouteImport.update({
  id: '/student/$id/badges',
  path: '/student/$id/badges',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anchor/$date': typeof AnchorDateRoute
  '/realm/$subject': typeof RealmSubjectRoute
  '/student/$id/badges': typeof StudentIdBadgesRoute
  '/student/$id/mastery': typeof StudentIdMasteryRoute
  '/teacher/$class/quests': typeof TeacherClassQuestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anchor/$date': typeof AnchorDateRoute
  '/realm/$subject': typeof RealmSubjectRoute
  '/student/$id/badges': typeof StudentIdBadgesRoute
  '/student/$id/mastery': typeof StudentIdMasteryRoute
  '/teacher/$class/quests': typeof TeacherClassQuestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anchor/$date': typeof AnchorDateRoute
  '/realm/$subject': typeof RealmSubjectRoute
  '/student/$id/badges': typeof StudentIdBadgesRoute
  '/student/$id/mastery': typeof StudentIdMasteryRoute
  '/teacher/$class/quests': typeof TeacherClassQuestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anchor/$date'
    | '/realm/$subject'
    | '/student/$id/badges'
    | '/student/$id/mastery'
    | '/teacher/$class/quests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anchor/$date'
    | '/realm/$subject'
    | '/student/$id/badges'
    | '/student/$id/mastery'
    | '/teacher/$class/quests'
  id:
    | '__root__'
    | '/'
    | '/anchor/$date'
    | '/realm/$subject'
    | '/student/$id/badges'
    | '/student/$id/mastery'
    | '/teacher/$class/quests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnchorDateRoute: typeof AnchorDateRoute
  RealmSubjectRoute: typeof RealmSubjectRoute
  StudentIdBadgesRoute: typeof StudentIdBadgesRoute
  StudentIdMasteryRoute: typeof StudentIdMasteryRoute
  TeacherClassQuestsRoute: typeof TeacherClassQuestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm/$subject': {
      id: '/realm/$subject'
      path: '/realm/$subject'
      fullPath: '/realm/$subject'
      preLoaderRoute: typeof RealmSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anchor/$date': {
      id: '/anchor/$date'
      path: '/anchor/$date'
      fullPath: '/anchor/$date'
      preLoaderRoute: typeof AnchorDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$class/quests': {
      id: '/teacher/$class/quests'
      path: '/teacher/$class/quests'
      fullPath: '/teacher/$class/quests'
      preLoaderRoute: typeof TeacherClassQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$id/mastery': {
      id: '/student/$id/mastery'
      path: '/student/$id/mastery'
      fullPath: '/student/$id/mastery'
      preLoaderRoute: typeof StudentIdMasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$id/badges': {
      id: '/student/$id/badges'
      path: '/student/$id/badges'
      fullPath: '/student/$id/badges'
      preLoaderRoute: typeof StudentIdBadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnchorDateRoute: AnchorDateRoute,
  RealmSubjectRoute: RealmSubjectRoute,
  StudentIdBadgesRoute: StudentIdBadgesRoute,
  StudentIdMasteryRoute: StudentIdMasteryRoute,
  TeacherClassQuestsRoute: TeacherClassQuestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
