# =============================================================================
# MEMGRAPH - Pangolin Blueprint
# =============================================================================

private-resources:
  memgraph-lab:
    name: "Memgraph Lab"
    full-domain: "memgraph.cianfhoghlaim.ie"
    mode: http
    destination: memgraph-lab:3000
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
