private-resources:
  langfuse:
    name: "Langfuse"
    full-domain: "langfuse.cianfhoghlaim.ie"
    mode: http
    destination: langfuse:8080
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
