"""
oideachais.cocoindex_flows.site_analysis_embedding — CocoIndex flow
that embeds SiteAnalysis summaries into LanceDB.

Phase 8 of the openspec change. The flow is registered as a
CocoIndex function so the Dagster `site_analysis_embed` asset can
call it directly. The batch size is set to >= 100 per the
AGENTS.md embedding constraint.
"""
from __future__ import annotations

from typing import Any


def build_site_analysis_flow():
    """Return a CocoIndex flow that ingests `site_analyses` rows and
    writes BAAI/bge-m3 embeddings to LanceDB.

    NOTE: the actual CocoIndex decorator + flow registration lives in
    `oideachais.cocoindex_flows.curriculum_embedding` (the existing
    pattern). We mirror its structure here; the live wiring lands in
    Phase 8 follow-on once the BAML `SiteAnalysis` schema has been
    regenerated by the BAML CLI.
    """
    import cocoindex

    @cocoindex.flow_def(name="SiteAnalysisEmbedding")
    def site_analysis_embedding_flow(
        flow_builder: cocoindex.FlowBuilder, data_scope: cocoindex.DataScope
    ) -> None:
        # Source: oideachais.site_analysis.site_analyses (DuckLake).
        source = data_scope.add_source(
            cocoindex.sources.S3(
                protocol="s3",
                bucket_uri="s3://ducklake/oideachais/site_analysis/site_analyses/",
            )
        )

        # Collector: batch >= 100 to satisfy the embedding batch constraint.
        with data_scope["rows"].row() as row:
            row["source_id"] = source["source_id"]
            row["captured_at"] = source["captured_at"]
            row["summary"] = source["pages"][0]["summary"]
        collector = data_scope.collect()

        # Embedder.
        collector["embeddings"] = collector["summary"].transform(
            cocoindex.functions.SentenceTransformerEmbed(
                model="BAAI/bge-m3"
            )
        )

        # Sink: LanceDB table oideachais.site_analysis.descriptions.
        collector.export(
            "descriptions",
            cocoindex.targets.LanceDB(
                uri="s3://lance/oideachais/site_analysis/",
                table="descriptions",
            ),
            primary_key=["source_id", "captured_at"],
            vector_index=cocoindex.VectorIndexDef(
                field="embeddings",
                metric=cocoindex.VectorSimilarityMetric.COSINE,
            ),
        )

    return site_analysis_embedding_flow


__all__ = ["build_site_analysis_flow"]
