// bonneagar/iac/commands/deploy-periphery.ts — Provisions Komodo Periphery on a managed host
//
// v2.9.0+ implementation. Uses the bons IaC's Komodo client (hand-rolled
// REST wrapper, not the buggy npm SDK) to:
//   1. Create an onboarding key in Komodo Core
//   2. Register the Server in Komodo with `address: ""` (outbound mode)
//   3. Render the Periphery `core.config.toml` + the `docker-compose.yaml`
//   4. Write both files to the local `/etc/komodo/` (or configurable)
//   5. Return the compose path + the onboarding key for operator verification
//
// The Komodo docs recommend this pattern (https://komo.do/docs/setup/connect-servers):
// - Periphery runs as systemd OR as a docker container
// - For docker, the bons IaC generates the docker-compose
// - The onboarding key is one-time-use (consumed on first connection)
//
// Usage:
//   bun run iac:deploy-periphery --connect-as=bunchloch
//   bun run iac:deploy-periphery --connect-as=oci.arm1-oci --komodo-url=https://komodo.cianfhoghlaim.ie

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { log, logStep, logOk, logError, logWarn } from "../cli.ts";
import { ensureKomodoAuth } from "../auth.ts";
import { KomodoClient } from "../clients/komodo-client.ts";

interface DeployPeripheryOpts {
  connectAs: string;
  rootDirectory?: string;
  komodoUrl?: string;
}

interface DeployPeripheryResult {
  ts: string;
  connectAs: string;
  onboardingKey: string;
  coreAddress: string;
  peripheryDir: string;
  composePath: string;
  configPath: string;
  serverId?: string;
  auditPath: string;
}

function getArg(name: string, args: string[]): string | undefined {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 ? args[idx + 1] : undefined;
}

export async function deployPeriphery(opts?: DeployPeripheryOpts): Promise<DeployPeripheryResult> {
  logStep("iac:deploy-periphery — provisions Komodo Periphery on a managed host");

  const args = process.argv.slice(2);
  const connectAs = opts?.connectAs ?? getArg("connect-as", args) ?? require("os").hostname();
  const rootDirectory = opts?.rootDirectory ?? getArg("root-dir", args) ?? "/etc/komodo";
  const komodoUrl = opts?.komodoUrl ?? getArg("komodo-url", args) ?? process.env.KOMODO_URL ?? "https://komodo.cianfhoghlaim.ie";

  if (!connectAs) {
    throw new Error("--connect-as is required (e.g. --connect-as=bunchloch)");
  }

  log(`  Komodo URL: ${komodoUrl}`);
  log(`  Connect as: ${connectAs}`);
  log(`  Periphery root: ${rootDirectory}`);

  // 1. Auth to Komodo
  const komodo = await ensureKomodoAuth();
  const kc = new KomodoClient(komodo.url, komodo.jwt);

  // 2. Create an onboarding key
  log("Step 1: Create onboarding key via Komodo API");
  const onboardingKey = (await kc.write("CreateOnboardingKey", {
    name: `bons-iac-${connectAs}-${Date.now()}`,
    enabled: true,
    expires: 0, // never expires (operator can rotate manually)
  })) as string;
  if (!onboardingKey) {
    throw new Error("Failed to create onboarding key (no key returned)");
  }
  logOk(`  Onboarding key created (length: ${(onboardingKey as string).length} chars)`);

  // 3. Register the Server in Komodo (with empty address = outbound mode)
  log("Step 2: Register Server in Komodo (address=\"\" = outbound mode)");
  let serverId: string | undefined;
  try {
    const server = (await kc.write("CreateServer", {
      name: connectAs,
      address: "",
      tags: ["host:" + connectAs, "periphery", "bons-iac-managed"],
    })) as { id?: string };
    serverId = server?.id;
    logOk(`  Server '${connectAs}' registered (id=${serverId})`);
  } catch (e) {
    logWarn(`  CreateServer failed (may already exist): ${(e as Error).message}`);
  }

  // 4. Render the Periphery core.config.toml
  log("Step 3: Render Periphery core.config.toml + docker-compose.yaml");
  mkdirSync(rootDirectory, { recursive: true });

  const configToml = `#
# 🦎 KOMODO PERIPHERY CONFIG 🦎
# Generated by bons IaC iac:deploy-periphery on ${new Date().toISOString()}
# Do NOT edit manually — re-run iac:deploy-periphery to regenerate
#

## The address of Komodo Core to connect to.
core_address = "${komodoUrl}"

## The Server this Periphery agent should connect as.
connect_as = "${connectAs}"

## Optional. Create a Server Onboarding Key in the Komodo UI.
## This allows Periphery to create a new Server in the UI with the above name.
onboarding_key = "${onboardingKey}"

## List of accepted Core public keys.
## Periphery gains knowledge of the Core public key through the noise handshake.
## If neither these nor passkeys provided, inbound connections will not be authenticated.
## Spki base64 DER directly and PEM file are accepted. Use \`file:/path/to/core.pub\` to load from file.
## If not set, the noise handshake will use the first Core public key it sees.
## Accepts Spki base64 DER directly and PEM file.
# core_public_keys = "MCowBQYDK2Vu..."

## Specify the root directory used by Periphery agent.
## All your compose files and repos need to be inside this directory
## for Periphery to interact with them.
root_directory = "${rootDirectory}"

## Optional. Override the directory periphery will use to manage repos.
# repo_dir = "${rootDirectory}/repos"

## Optional. Override the directory periphery will use to manage stacks.
# stack_dir = "${rootDirectory}/stacks"

## Disable the terminal APIs and disallow remote shell access through Periphery.
disable_terminals = false

## Disable the container exec / attach APIs and disallow remote container shell access.
disable_container_terminals = false

## The port the server runs on (for inbound mode).
## If core_address is set, this is outbound mode and the server is not used.
port = 8120

## The IP address the periphery server will bind to.
bind_ip = "[::]"

## Enable HTTPS server using the given key and cert.
ssl_enabled = false

## Stats polling
stats_polling_rate = "5-sec"
container_stats_polling_rate = "30-sec"

## Logging
logging.level = "info"
logging.stdio = "standard"
logging.pretty = false
logging.opentelemetry_service_name = "Periphery"
logging.opentelemetry_scope_name = "Komodo"
`;

  const configPath = join(rootDirectory, "periphery.config.toml");
  writeFileSync(configPath, configToml);
  logOk(`  Periphery config written to ${configPath}`);

  // 5. Render the docker-compose.yaml
  const composeYaml = `#
# Komodo Periphery — generated by bons IaC iac:deploy-periphery on ${new Date().toISOString()}
# Do NOT edit manually — re-run iac:deploy-periphery to regenerate
#
# Run: cd ${rootDirectory} && docker compose up -d
#

version: "3.8"

services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    container_name: ${connectAs}-periphery
    restart: unless-stopped
    init: true
    user: "0:0"  # root so the Periphery can manage Docker + send signals
    environment:
      # Periphery picks up its config from /config/periphery.config.toml
      PERIPHERY_CONFIG_PATH: /config/periphery.config.toml
      PERIPHERY_ROOT_DIRECTORY: /etc/komodo
    volumes:
      - ./periphery.config.toml:/config/periphery.config.toml:ro
      - ${rootDirectory}:/etc/komodo
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc:ro
    healthcheck:
      test: ["CMD", "periphery", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - komodo-net

networks:
  komodo-net:
    driver: bridge
`;

  const composePath = join(rootDirectory, "docker-compose.yml");
  writeFileSync(composePath, composeYaml);
  logOk(`  docker-compose.yaml written to ${composePath}`);

  // 6. Audit record
  const result: DeployPeripheryResult = {
    ts: new Date().toISOString(),
    connectAs,
    onboardingKey: onboardingKey as string,
    coreAddress: komodoUrl,
    peripheryDir: rootDirectory,
    composePath,
    configPath,
    serverId,
    auditPath: "",
  };
  const auditPath = `/tmp/periphery-deploy-${result.ts.replace(/[:.]/g, "-")}.json`;
  writeFileSync(auditPath, JSON.stringify(result, null, 2));
  result.auditPath = auditPath;
  logOk(`  audit record: ${auditPath}`);

  return result;
}
