private-resources:
  croilar-hono-api:
    name: "Croílár Auth API"
    mode: http
    full-domain: "auth.croilar.cianfhoghlaim.ie"
    destination: croilar-hono-api:4000
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
