/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as RegistryRouteImport } from './../routes/registry'
import { Route as PointsCalculatorRouteImport } from './../routes/points-calculator'
import { Route as MatriculationAuditorRouteImport } from './../routes/matriculation-auditor'
import { Route as Ga__layoutRouteImport } from './../routes/ga-__layout'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as OfficialMediaPwaIndexRouteImport } from './../routes/official-media-pwa/index'
import { Route as CChar233imeannaIndexRouteImport } from './../routes/céimeanna/index'
import { Route as ControlPanelIndexRouteImport } from './../routes/control-panel/index'
import { Route as BiepV3IndexRouteImport } from './../routes/biep-v3/index'
import { Route as BiepV2IndexRouteImport } from './../routes/biep-v2/index'
import { Route as AnalyzerIndexRouteImport } from './../routes/analyzer/index'
import { Route as LcMathematicsRouteImport } from './../routes/lc/mathematics'
import { Route as LcIrishRouteImport } from './../routes/lc/irish'
import { Route as LcHistoryRouteImport } from './../routes/lc/history'
import { Route as LcFrenchRouteImport } from './../routes/lc/french'
import { Route as LcConstructionStudiesRouteImport } from './../routes/lc/construction-studies'
import { Route as LcBusinessRouteImport } from './../routes/lc/business'
import { Route as LcBiologyRouteImport } from './../routes/lc/biology'
import { Route as EnAboutRouteImport } from './../routes/en/about'
import { Route as En_layoutRouteImport } from './../routes/en/__layout'
import { Route as CChar233imeannaCeimRouteImport } from './../routes/céimeanna/$ceim'
import { Route as BiepV3SctWlsNiRouteImport } from './../routes/biep-v3/sct-wls-ni'
import { Route as BiepV3IrelandRouteImport } from './../routes/biep-v3/ireland'
import { Route as BiepV3EnglandRouteImport } from './../routes/biep-v3/england'
import { Route as BiepV3CrownRouteImport } from './../routes/biep-v3/crown'
import { Route as BiepV2_init_RouteImport } from './../routes/biep-v2/__init__'
import { Route as EnStagesIndexRouteImport } from './../routes/en/stages/index'
import { Route as EnSubjectsSlugRouteImport } from './../routes/en/subjects/$slug'
import { Route as EnStagesStageRouteImport } from './../routes/en/stages/$stage'
import { Route as EnPracticeSubjectRouteImport } from './../routes/en/practice/$subject'
import { Route as EnPastPapersSubjectRouteImport } from './../routes/en/past-papers/$subject'
import { Route as EnMarkingSchemesSubjectRouteImport } from './../routes/en/marking-schemes/$subject'
import { Route as EnLcMathematicsRouteImport } from './../routes/en/lc/mathematics'
import { Route as EnLcIrishRouteImport } from './../routes/en/lc/irish'
import { Route as EnLcHistoryRouteImport } from './../routes/en/lc/history'
import { Route as EnLcFrenchRouteImport } from './../routes/en/lc/french'
import { Route as EnLcConstructionStudiesRouteImport } from './../routes/en/lc/construction-studies'
import { Route as EnLcBusinessRouteImport } from './../routes/en/lc/business'
import { Route as EnLcBiologyRouteImport } from './../routes/en/lc/biology'
import { Route as EnExaminerReportsSubjectRouteImport } from './../routes/en/examiner-reports/$subject'
import { Route as EnDashboardsStageRouteImport } from './../routes/en/dashboards/$stage'
import { Route as EnAdminComponentsRouteImport } from './../routes/en/admin/components'

const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsCalculatorRoute = PointsCalculatorRouteImport.update({
  id: '/points-calculator',
  path: '/points-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculationAuditorRoute = MatriculationAuditorRouteImport.update({
  id: '/matriculation-auditor',
  path: '/matriculation-auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const Ga__layoutRoute = Ga__layoutRouteImport.update({
  id: '/ga-__layout',
  path: '/ga-__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialMediaPwaIndexRoute = OfficialMediaPwaIndexRouteImport.update({
  id: '/official-media-pwa/',
  path: '/official-media-pwa/',
  getParentRoute: () => rootRouteImport,
} as any)
const CChar233imeannaIndexRoute = CChar233imeannaIndexRouteImport.update({
  id: '/céimeanna/',
  path: '/céimeanna/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelIndexRoute = ControlPanelIndexRouteImport.update({
  id: '/control-panel/',
  path: '/control-panel/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiepV3IndexRoute = BiepV3IndexRouteImport.update({
  id: '/biep-v3/',
  path: '/biep-v3/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiepV2IndexRoute = BiepV2IndexRouteImport.update({
  id: '/biep-v2/',
  path: '/biep-v2/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerIndexRoute = AnalyzerIndexRouteImport.update({
  id: '/analyzer/',
  path: '/analyzer/',
  getParentRoute: () => rootRouteImport,
} as any)
const LcMathematicsRoute = LcMathematicsRouteImport.update({
  id: '/lc/mathematics',
  path: '/lc/mathematics',
  getParentRoute: () => rootRouteImport,
} as any)
const LcIrishRoute = LcIrishRouteImport.update({
  id: '/lc/irish',
  path: '/lc/irish',
  getParentRoute: () => rootRouteImport,
} as any)
const LcHistoryRoute = LcHistoryRouteImport.update({
  id: '/lc/history',
  path: '/lc/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LcFrenchRoute = LcFrenchRouteImport.update({
  id: '/lc/french',
  path: '/lc/french',
  getParentRoute: () => rootRouteImport,
} as any)
const LcConstructionStudiesRoute = LcConstructionStudiesRouteImport.update({
  id: '/lc/construction-studies',
  path: '/lc/construction-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const LcBusinessRoute = LcBusinessRouteImport.update({
  id: '/lc/business',
  path: '/lc/business',
  getParentRoute: () => rootRouteImport,
} as any)
const LcBiologyRoute = LcBiologyRouteImport.update({
  id: '/lc/biology',
  path: '/lc/biology',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const En_layoutRoute = En_layoutRouteImport.update({
  id: '/en/__layout',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CChar233imeannaCeimRoute = CChar233imeannaCeimRouteImport.update({
  id: '/céimeanna/$ceim',
  path: '/céimeanna/$ceim',
  getParentRoute: () => rootRouteImport,
} as any)
const BiepV3SctWlsNiRoute = BiepV3SctWlsNiRouteImport.update({
  id: '/biep-v3/sct-wls-ni',
  path: '/biep-v3/sct-wls-ni',
  getParentRoute: () => rootRouteImport,
} as any)
const BiepV3IrelandRoute = BiepV3IrelandRouteImport.update({
  id: '/biep-v3/ireland',
  path: '/biep-v3/ireland',
  getParentRoute: () => rootRouteImport,
} as any)
const BiepV3EnglandRoute = BiepV3EnglandRouteImport.update({
  id: '/biep-v3/england',
  path: '/biep-v3/england',
  getParentRoute: () => rootRouteImport,
} as any)
const BiepV3CrownRoute = BiepV3CrownRouteImport.update({
  id: '/biep-v3/crown',
  path: '/biep-v3/crown',
  getParentRoute: () => rootRouteImport,
} as any)
const BiepV2_init_Route = BiepV2_init_RouteImport.update({
  id: '/biep-v2/__init__',
  path: '/biep-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStagesIndexRoute = EnStagesIndexRouteImport.update({
  id: '/en/stages/',
  path: '/en/stages/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSubjectsSlugRoute = EnSubjectsSlugRouteImport.update({
  id: '/en/subjects/$slug',
  path: '/en/subjects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStagesStageRoute = EnStagesStageRouteImport.update({
  id: '/en/stages/$stage',
  path: '/en/stages/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPracticeSubjectRoute = EnPracticeSubjectRouteImport.update({
  id: '/en/practice/$subject',
  path: '/en/practice/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPastPapersSubjectRoute = EnPastPapersSubjectRouteImport.update({
  id: '/en/past-papers/$subject',
  path: '/en/past-papers/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMarkingSchemesSubjectRoute = EnMarkingSchemesSubjectRouteImport.update({
  id: '/en/marking-schemes/$subject',
  path: '/en/marking-schemes/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLcMathematicsRoute = EnLcMathematicsRouteImport.update({
  id: '/en/lc/mathematics',
  path: '/en/lc/mathematics',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLcIrishRoute = EnLcIrishRouteImport.update({
  id: '/en/lc/irish',
  path: '/en/lc/irish',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLcHistoryRoute = EnLcHistoryRouteImport.update({
  id: '/en/lc/history',
  path: '/en/lc/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLcFrenchRoute = EnLcFrenchRouteImport.update({
  id: '/en/lc/french',
  path: '/en/lc/french',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLcConstructionStudiesRoute = EnLcConstructionStudiesRouteImport.update({
  id: '/en/lc/construction-studies',
  path: '/en/lc/construction-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLcBusinessRoute = EnLcBusinessRouteImport.update({
  id: '/en/lc/business',
  path: '/en/lc/business',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLcBiologyRoute = EnLcBiologyRouteImport.update({
  id: '/en/lc/biology',
  path: '/en/lc/biology',
  getParentRoute: () => rootRouteImport,
} as any)
const EnExaminerReportsSubjectRoute =
  EnExaminerReportsSubjectRouteImport.update({
    id: '/en/examiner-reports/$subject',
    path: '/en/examiner-reports/$subject',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnDashboardsStageRoute = EnDashboardsStageRouteImport.update({
  id: '/en/dashboards/$stage',
  path: '/en/dashboards/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAdminComponentsRoute = EnAdminComponentsRouteImport.update({
  id: '/en/admin/components',
  path: '/en/admin/components',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ga-__layout': typeof Ga__layoutRoute
  '/matriculation-auditor': typeof MatriculationAuditorRoute
  '/points-calculator': typeof PointsCalculatorRoute
  '/registry': typeof RegistryRoute
  '/biep-v2': typeof BiepV2_init_Route
  '/biep-v3/crown': typeof BiepV3CrownRoute
  '/biep-v3/england': typeof BiepV3EnglandRoute
  '/biep-v3/ireland': typeof BiepV3IrelandRoute
  '/biep-v3/sct-wls-ni': typeof BiepV3SctWlsNiRoute
  '/céimeanna/$ceim': typeof CChar233imeannaCeimRoute
  '/en': typeof En_layoutRoute
  '/en/about': typeof EnAboutRoute
  '/lc/biology': typeof LcBiologyRoute
  '/lc/business': typeof LcBusinessRoute
  '/lc/construction-studies': typeof LcConstructionStudiesRoute
  '/lc/french': typeof LcFrenchRoute
  '/lc/history': typeof LcHistoryRoute
  '/lc/irish': typeof LcIrishRoute
  '/lc/mathematics': typeof LcMathematicsRoute
  '/analyzer/': typeof AnalyzerIndexRoute
  '/biep-v2/': typeof BiepV2IndexRoute
  '/biep-v3/': typeof BiepV3IndexRoute
  '/control-panel/': typeof ControlPanelIndexRoute
  '/céimeanna/': typeof CChar233imeannaIndexRoute
  '/official-media-pwa/': typeof OfficialMediaPwaIndexRoute
  '/en/admin/components': typeof EnAdminComponentsRoute
  '/en/dashboards/$stage': typeof EnDashboardsStageRoute
  '/en/examiner-reports/$subject': typeof EnExaminerReportsSubjectRoute
  '/en/lc/biology': typeof EnLcBiologyRoute
  '/en/lc/business': typeof EnLcBusinessRoute
  '/en/lc/construction-studies': typeof EnLcConstructionStudiesRoute
  '/en/lc/french': typeof EnLcFrenchRoute
  '/en/lc/history': typeof EnLcHistoryRoute
  '/en/lc/irish': typeof EnLcIrishRoute
  '/en/lc/mathematics': typeof EnLcMathematicsRoute
  '/en/marking-schemes/$subject': typeof EnMarkingSchemesSubjectRoute
  '/en/past-papers/$subject': typeof EnPastPapersSubjectRoute
  '/en/practice/$subject': typeof EnPracticeSubjectRoute
  '/en/stages/$stage': typeof EnStagesStageRoute
  '/en/subjects/$slug': typeof EnSubjectsSlugRoute
  '/en/stages/': typeof EnStagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ga-__layout': typeof Ga__layoutRoute
  '/matriculation-auditor': typeof MatriculationAuditorRoute
  '/points-calculator': typeof PointsCalculatorRoute
  '/registry': typeof RegistryRoute
  '/biep-v2': typeof BiepV2IndexRoute
  '/biep-v3/crown': typeof BiepV3CrownRoute
  '/biep-v3/england': typeof BiepV3EnglandRoute
  '/biep-v3/ireland': typeof BiepV3IrelandRoute
  '/biep-v3/sct-wls-ni': typeof BiepV3SctWlsNiRoute
  '/céimeanna/$ceim': typeof CChar233imeannaCeimRoute
  '/en': typeof En_layoutRoute
  '/en/about': typeof EnAboutRoute
  '/lc/biology': typeof LcBiologyRoute
  '/lc/business': typeof LcBusinessRoute
  '/lc/construction-studies': typeof LcConstructionStudiesRoute
  '/lc/french': typeof LcFrenchRoute
  '/lc/history': typeof LcHistoryRoute
  '/lc/irish': typeof LcIrishRoute
  '/lc/mathematics': typeof LcMathematicsRoute
  '/analyzer': typeof AnalyzerIndexRoute
  '/biep-v3': typeof BiepV3IndexRoute
  '/control-panel': typeof ControlPanelIndexRoute
  '/céimeanna': typeof CChar233imeannaIndexRoute
  '/official-media-pwa': typeof OfficialMediaPwaIndexRoute
  '/en/admin/components': typeof EnAdminComponentsRoute
  '/en/dashboards/$stage': typeof EnDashboardsStageRoute
  '/en/examiner-reports/$subject': typeof EnExaminerReportsSubjectRoute
  '/en/lc/biology': typeof EnLcBiologyRoute
  '/en/lc/business': typeof EnLcBusinessRoute
  '/en/lc/construction-studies': typeof EnLcConstructionStudiesRoute
  '/en/lc/french': typeof EnLcFrenchRoute
  '/en/lc/history': typeof EnLcHistoryRoute
  '/en/lc/irish': typeof EnLcIrishRoute
  '/en/lc/mathematics': typeof EnLcMathematicsRoute
  '/en/marking-schemes/$subject': typeof EnMarkingSchemesSubjectRoute
  '/en/past-papers/$subject': typeof EnPastPapersSubjectRoute
  '/en/practice/$subject': typeof EnPracticeSubjectRoute
  '/en/stages/$stage': typeof EnStagesStageRoute
  '/en/subjects/$slug': typeof EnSubjectsSlugRoute
  '/en/stages': typeof EnStagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ga-__layout': typeof Ga__layoutRoute
  '/matriculation-auditor': typeof MatriculationAuditorRoute
  '/points-calculator': typeof PointsCalculatorRoute
  '/registry': typeof RegistryRoute
  '/biep-v2/__init__': typeof BiepV2_init_Route
  '/biep-v3/crown': typeof BiepV3CrownRoute
  '/biep-v3/england': typeof BiepV3EnglandRoute
  '/biep-v3/ireland': typeof BiepV3IrelandRoute
  '/biep-v3/sct-wls-ni': typeof BiepV3SctWlsNiRoute
  '/céimeanna/$ceim': typeof CChar233imeannaCeimRoute
  '/en/__layout': typeof En_layoutRoute
  '/en/about': typeof EnAboutRoute
  '/lc/biology': typeof LcBiologyRoute
  '/lc/business': typeof LcBusinessRoute
  '/lc/construction-studies': typeof LcConstructionStudiesRoute
  '/lc/french': typeof LcFrenchRoute
  '/lc/history': typeof LcHistoryRoute
  '/lc/irish': typeof LcIrishRoute
  '/lc/mathematics': typeof LcMathematicsRoute
  '/analyzer/': typeof AnalyzerIndexRoute
  '/biep-v2/': typeof BiepV2IndexRoute
  '/biep-v3/': typeof BiepV3IndexRoute
  '/control-panel/': typeof ControlPanelIndexRoute
  '/céimeanna/': typeof CChar233imeannaIndexRoute
  '/official-media-pwa/': typeof OfficialMediaPwaIndexRoute
  '/en/admin/components': typeof EnAdminComponentsRoute
  '/en/dashboards/$stage': typeof EnDashboardsStageRoute
  '/en/examiner-reports/$subject': typeof EnExaminerReportsSubjectRoute
  '/en/lc/biology': typeof EnLcBiologyRoute
  '/en/lc/business': typeof EnLcBusinessRoute
  '/en/lc/construction-studies': typeof EnLcConstructionStudiesRoute
  '/en/lc/french': typeof EnLcFrenchRoute
  '/en/lc/history': typeof EnLcHistoryRoute
  '/en/lc/irish': typeof EnLcIrishRoute
  '/en/lc/mathematics': typeof EnLcMathematicsRoute
  '/en/marking-schemes/$subject': typeof EnMarkingSchemesSubjectRoute
  '/en/past-papers/$subject': typeof EnPastPapersSubjectRoute
  '/en/practice/$subject': typeof EnPracticeSubjectRoute
  '/en/stages/$stage': typeof EnStagesStageRoute
  '/en/subjects/$slug': typeof EnSubjectsSlugRoute
  '/en/stages/': typeof EnStagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ga-__layout'
    | '/matriculation-auditor'
    | '/points-calculator'
    | '/registry'
    | '/biep-v2'
    | '/biep-v3/crown'
    | '/biep-v3/england'
    | '/biep-v3/ireland'
    | '/biep-v3/sct-wls-ni'
    | '/céimeanna/$ceim'
    | '/en'
    | '/en/about'
    | '/lc/biology'
    | '/lc/business'
    | '/lc/construction-studies'
    | '/lc/french'
    | '/lc/history'
    | '/lc/irish'
    | '/lc/mathematics'
    | '/analyzer/'
    | '/biep-v2/'
    | '/biep-v3/'
    | '/control-panel/'
    | '/céimeanna/'
    | '/official-media-pwa/'
    | '/en/admin/components'
    | '/en/dashboards/$stage'
    | '/en/examiner-reports/$subject'
    | '/en/lc/biology'
    | '/en/lc/business'
    | '/en/lc/construction-studies'
    | '/en/lc/french'
    | '/en/lc/history'
    | '/en/lc/irish'
    | '/en/lc/mathematics'
    | '/en/marking-schemes/$subject'
    | '/en/past-papers/$subject'
    | '/en/practice/$subject'
    | '/en/stages/$stage'
    | '/en/subjects/$slug'
    | '/en/stages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ga-__layout'
    | '/matriculation-auditor'
    | '/points-calculator'
    | '/registry'
    | '/biep-v2'
    | '/biep-v3/crown'
    | '/biep-v3/england'
    | '/biep-v3/ireland'
    | '/biep-v3/sct-wls-ni'
    | '/céimeanna/$ceim'
    | '/en'
    | '/en/about'
    | '/lc/biology'
    | '/lc/business'
    | '/lc/construction-studies'
    | '/lc/french'
    | '/lc/history'
    | '/lc/irish'
    | '/lc/mathematics'
    | '/analyzer'
    | '/biep-v3'
    | '/control-panel'
    | '/céimeanna'
    | '/official-media-pwa'
    | '/en/admin/components'
    | '/en/dashboards/$stage'
    | '/en/examiner-reports/$subject'
    | '/en/lc/biology'
    | '/en/lc/business'
    | '/en/lc/construction-studies'
    | '/en/lc/french'
    | '/en/lc/history'
    | '/en/lc/irish'
    | '/en/lc/mathematics'
    | '/en/marking-schemes/$subject'
    | '/en/past-papers/$subject'
    | '/en/practice/$subject'
    | '/en/stages/$stage'
    | '/en/subjects/$slug'
    | '/en/stages'
  id:
    | '__root__'
    | '/'
    | '/ga-__layout'
    | '/matriculation-auditor'
    | '/points-calculator'
    | '/registry'
    | '/biep-v2/__init__'
    | '/biep-v3/crown'
    | '/biep-v3/england'
    | '/biep-v3/ireland'
    | '/biep-v3/sct-wls-ni'
    | '/céimeanna/$ceim'
    | '/en/__layout'
    | '/en/about'
    | '/lc/biology'
    | '/lc/business'
    | '/lc/construction-studies'
    | '/lc/french'
    | '/lc/history'
    | '/lc/irish'
    | '/lc/mathematics'
    | '/analyzer/'
    | '/biep-v2/'
    | '/biep-v3/'
    | '/control-panel/'
    | '/céimeanna/'
    | '/official-media-pwa/'
    | '/en/admin/components'
    | '/en/dashboards/$stage'
    | '/en/examiner-reports/$subject'
    | '/en/lc/biology'
    | '/en/lc/business'
    | '/en/lc/construction-studies'
    | '/en/lc/french'
    | '/en/lc/history'
    | '/en/lc/irish'
    | '/en/lc/mathematics'
    | '/en/marking-schemes/$subject'
    | '/en/past-papers/$subject'
    | '/en/practice/$subject'
    | '/en/stages/$stage'
    | '/en/subjects/$slug'
    | '/en/stages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Ga__layoutRoute: typeof Ga__layoutRoute
  MatriculationAuditorRoute: typeof MatriculationAuditorRoute
  PointsCalculatorRoute: typeof PointsCalculatorRoute
  RegistryRoute: typeof RegistryRoute
  BiepV2_init_Route: typeof BiepV2_init_Route
  BiepV3CrownRoute: typeof BiepV3CrownRoute
  BiepV3EnglandRoute: typeof BiepV3EnglandRoute
  BiepV3IrelandRoute: typeof BiepV3IrelandRoute
  BiepV3SctWlsNiRoute: typeof BiepV3SctWlsNiRoute
  CChar233imeannaCeimRoute: typeof CChar233imeannaCeimRoute
  En_layoutRoute: typeof En_layoutRoute
  EnAboutRoute: typeof EnAboutRoute
  LcBiologyRoute: typeof LcBiologyRoute
  LcBusinessRoute: typeof LcBusinessRoute
  LcConstructionStudiesRoute: typeof LcConstructionStudiesRoute
  LcFrenchRoute: typeof LcFrenchRoute
  LcHistoryRoute: typeof LcHistoryRoute
  LcIrishRoute: typeof LcIrishRoute
  LcMathematicsRoute: typeof LcMathematicsRoute
  AnalyzerIndexRoute: typeof AnalyzerIndexRoute
  BiepV2IndexRoute: typeof BiepV2IndexRoute
  BiepV3IndexRoute: typeof BiepV3IndexRoute
  ControlPanelIndexRoute: typeof ControlPanelIndexRoute
  CChar233imeannaIndexRoute: typeof CChar233imeannaIndexRoute
  OfficialMediaPwaIndexRoute: typeof OfficialMediaPwaIndexRoute
  EnAdminComponentsRoute: typeof EnAdminComponentsRoute
  EnDashboardsStageRoute: typeof EnDashboardsStageRoute
  EnExaminerReportsSubjectRoute: typeof EnExaminerReportsSubjectRoute
  EnLcBiologyRoute: typeof EnLcBiologyRoute
  EnLcBusinessRoute: typeof EnLcBusinessRoute
  EnLcConstructionStudiesRoute: typeof EnLcConstructionStudiesRoute
  EnLcFrenchRoute: typeof EnLcFrenchRoute
  EnLcHistoryRoute: typeof EnLcHistoryRoute
  EnLcIrishRoute: typeof EnLcIrishRoute
  EnLcMathematicsRoute: typeof EnLcMathematicsRoute
  EnMarkingSchemesSubjectRoute: typeof EnMarkingSchemesSubjectRoute
  EnPastPapersSubjectRoute: typeof EnPastPapersSubjectRoute
  EnPracticeSubjectRoute: typeof EnPracticeSubjectRoute
  EnStagesStageRoute: typeof EnStagesStageRoute
  EnSubjectsSlugRoute: typeof EnSubjectsSlugRoute
  EnStagesIndexRoute: typeof EnStagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points-calculator': {
      id: '/points-calculator'
      path: '/points-calculator'
      fullPath: '/points-calculator'
      preLoaderRoute: typeof PointsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriculation-auditor': {
      id: '/matriculation-auditor'
      path: '/matriculation-auditor'
      fullPath: '/matriculation-auditor'
      preLoaderRoute: typeof MatriculationAuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga-__layout': {
      id: '/ga-__layout'
      path: '/ga-__layout'
      fullPath: '/ga-__layout'
      preLoaderRoute: typeof Ga__layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official-media-pwa/': {
      id: '/official-media-pwa/'
      path: '/official-media-pwa'
      fullPath: '/official-media-pwa/'
      preLoaderRoute: typeof OfficialMediaPwaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/céimeanna/': {
      id: '/céimeanna/'
      path: '/céimeanna'
      fullPath: '/céimeanna/'
      preLoaderRoute: typeof CChar233imeannaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel/': {
      id: '/control-panel/'
      path: '/control-panel'
      fullPath: '/control-panel/'
      preLoaderRoute: typeof ControlPanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biep-v3/': {
      id: '/biep-v3/'
      path: '/biep-v3'
      fullPath: '/biep-v3/'
      preLoaderRoute: typeof BiepV3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biep-v2/': {
      id: '/biep-v2/'
      path: '/biep-v2'
      fullPath: '/biep-v2/'
      preLoaderRoute: typeof BiepV2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer/': {
      id: '/analyzer/'
      path: '/analyzer'
      fullPath: '/analyzer/'
      preLoaderRoute: typeof AnalyzerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lc/mathematics': {
      id: '/lc/mathematics'
      path: '/lc/mathematics'
      fullPath: '/lc/mathematics'
      preLoaderRoute: typeof LcMathematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lc/irish': {
      id: '/lc/irish'
      path: '/lc/irish'
      fullPath: '/lc/irish'
      preLoaderRoute: typeof LcIrishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lc/history': {
      id: '/lc/history'
      path: '/lc/history'
      fullPath: '/lc/history'
      preLoaderRoute: typeof LcHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lc/french': {
      id: '/lc/french'
      path: '/lc/french'
      fullPath: '/lc/french'
      preLoaderRoute: typeof LcFrenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lc/construction-studies': {
      id: '/lc/construction-studies'
      path: '/lc/construction-studies'
      fullPath: '/lc/construction-studies'
      preLoaderRoute: typeof LcConstructionStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lc/business': {
      id: '/lc/business'
      path: '/lc/business'
      fullPath: '/lc/business'
      preLoaderRoute: typeof LcBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lc/biology': {
      id: '/lc/biology'
      path: '/lc/biology'
      fullPath: '/lc/biology'
      preLoaderRoute: typeof LcBiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/__layout': {
      id: '/en/__layout'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof En_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/céimeanna/$ceim': {
      id: '/céimeanna/$ceim'
      path: '/céimeanna/$ceim'
      fullPath: '/céimeanna/$ceim'
      preLoaderRoute: typeof CChar233imeannaCeimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biep-v3/sct-wls-ni': {
      id: '/biep-v3/sct-wls-ni'
      path: '/biep-v3/sct-wls-ni'
      fullPath: '/biep-v3/sct-wls-ni'
      preLoaderRoute: typeof BiepV3SctWlsNiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biep-v3/ireland': {
      id: '/biep-v3/ireland'
      path: '/biep-v3/ireland'
      fullPath: '/biep-v3/ireland'
      preLoaderRoute: typeof BiepV3IrelandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biep-v3/england': {
      id: '/biep-v3/england'
      path: '/biep-v3/england'
      fullPath: '/biep-v3/england'
      preLoaderRoute: typeof BiepV3EnglandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biep-v3/crown': {
      id: '/biep-v3/crown'
      path: '/biep-v3/crown'
      fullPath: '/biep-v3/crown'
      preLoaderRoute: typeof BiepV3CrownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biep-v2/__init__': {
      id: '/biep-v2/__init__'
      path: '/biep-v2'
      fullPath: '/biep-v2'
      preLoaderRoute: typeof BiepV2_init_RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/stages/': {
      id: '/en/stages/'
      path: '/en/stages'
      fullPath: '/en/stages/'
      preLoaderRoute: typeof EnStagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/subjects/$slug': {
      id: '/en/subjects/$slug'
      path: '/en/subjects/$slug'
      fullPath: '/en/subjects/$slug'
      preLoaderRoute: typeof EnSubjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/stages/$stage': {
      id: '/en/stages/$stage'
      path: '/en/stages/$stage'
      fullPath: '/en/stages/$stage'
      preLoaderRoute: typeof EnStagesStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/practice/$subject': {
      id: '/en/practice/$subject'
      path: '/en/practice/$subject'
      fullPath: '/en/practice/$subject'
      preLoaderRoute: typeof EnPracticeSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/past-papers/$subject': {
      id: '/en/past-papers/$subject'
      path: '/en/past-papers/$subject'
      fullPath: '/en/past-papers/$subject'
      preLoaderRoute: typeof EnPastPapersSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/marking-schemes/$subject': {
      id: '/en/marking-schemes/$subject'
      path: '/en/marking-schemes/$subject'
      fullPath: '/en/marking-schemes/$subject'
      preLoaderRoute: typeof EnMarkingSchemesSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/lc/mathematics': {
      id: '/en/lc/mathematics'
      path: '/en/lc/mathematics'
      fullPath: '/en/lc/mathematics'
      preLoaderRoute: typeof EnLcMathematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/lc/irish': {
      id: '/en/lc/irish'
      path: '/en/lc/irish'
      fullPath: '/en/lc/irish'
      preLoaderRoute: typeof EnLcIrishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/lc/history': {
      id: '/en/lc/history'
      path: '/en/lc/history'
      fullPath: '/en/lc/history'
      preLoaderRoute: typeof EnLcHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/lc/french': {
      id: '/en/lc/french'
      path: '/en/lc/french'
      fullPath: '/en/lc/french'
      preLoaderRoute: typeof EnLcFrenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/lc/construction-studies': {
      id: '/en/lc/construction-studies'
      path: '/en/lc/construction-studies'
      fullPath: '/en/lc/construction-studies'
      preLoaderRoute: typeof EnLcConstructionStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/lc/business': {
      id: '/en/lc/business'
      path: '/en/lc/business'
      fullPath: '/en/lc/business'
      preLoaderRoute: typeof EnLcBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/lc/biology': {
      id: '/en/lc/biology'
      path: '/en/lc/biology'
      fullPath: '/en/lc/biology'
      preLoaderRoute: typeof EnLcBiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/examiner-reports/$subject': {
      id: '/en/examiner-reports/$subject'
      path: '/en/examiner-reports/$subject'
      fullPath: '/en/examiner-reports/$subject'
      preLoaderRoute: typeof EnExaminerReportsSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/dashboards/$stage': {
      id: '/en/dashboards/$stage'
      path: '/en/dashboards/$stage'
      fullPath: '/en/dashboards/$stage'
      preLoaderRoute: typeof EnDashboardsStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/admin/components': {
      id: '/en/admin/components'
      path: '/en/admin/components'
      fullPath: '/en/admin/components'
      preLoaderRoute: typeof EnAdminComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Ga__layoutRoute: Ga__layoutRoute,
  MatriculationAuditorRoute: MatriculationAuditorRoute,
  PointsCalculatorRoute: PointsCalculatorRoute,
  RegistryRoute: RegistryRoute,
  BiepV2_init_Route: BiepV2_init_Route,
  BiepV3CrownRoute: BiepV3CrownRoute,
  BiepV3EnglandRoute: BiepV3EnglandRoute,
  BiepV3IrelandRoute: BiepV3IrelandRoute,
  BiepV3SctWlsNiRoute: BiepV3SctWlsNiRoute,
  CChar233imeannaCeimRoute: CChar233imeannaCeimRoute,
  En_layoutRoute: En_layoutRoute,
  EnAboutRoute: EnAboutRoute,
  LcBiologyRoute: LcBiologyRoute,
  LcBusinessRoute: LcBusinessRoute,
  LcConstructionStudiesRoute: LcConstructionStudiesRoute,
  LcFrenchRoute: LcFrenchRoute,
  LcHistoryRoute: LcHistoryRoute,
  LcIrishRoute: LcIrishRoute,
  LcMathematicsRoute: LcMathematicsRoute,
  AnalyzerIndexRoute: AnalyzerIndexRoute,
  BiepV2IndexRoute: BiepV2IndexRoute,
  BiepV3IndexRoute: BiepV3IndexRoute,
  ControlPanelIndexRoute: ControlPanelIndexRoute,
  CChar233imeannaIndexRoute: CChar233imeannaIndexRoute,
  OfficialMediaPwaIndexRoute: OfficialMediaPwaIndexRoute,
  EnAdminComponentsRoute: EnAdminComponentsRoute,
  EnDashboardsStageRoute: EnDashboardsStageRoute,
  EnExaminerReportsSubjectRoute: EnExaminerReportsSubjectRoute,
  EnLcBiologyRoute: EnLcBiologyRoute,
  EnLcBusinessRoute: EnLcBusinessRoute,
  EnLcConstructionStudiesRoute: EnLcConstructionStudiesRoute,
  EnLcFrenchRoute: EnLcFrenchRoute,
  EnLcHistoryRoute: EnLcHistoryRoute,
  EnLcIrishRoute: EnLcIrishRoute,
  EnLcMathematicsRoute: EnLcMathematicsRoute,
  EnMarkingSchemesSubjectRoute: EnMarkingSchemesSubjectRoute,
  EnPastPapersSubjectRoute: EnPastPapersSubjectRoute,
  EnPracticeSubjectRoute: EnPracticeSubjectRoute,
  EnStagesStageRoute: EnStagesStageRoute,
  EnSubjectsSlugRoute: EnSubjectsSlugRoute,
  EnStagesIndexRoute: EnStagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
