[#usage]
= Usage

Once the dataset is formatted and `pylaia` is installed and in your environment, you may use the following commands:

* {blank}
`pylaia-htr-create-model`:: To create a new PyLaia model. More details in the xref:./initialization/index.adoc[dedicated page].
* {blank}
`pylaia-htr-dataset-validate`:: To compute statistics and run validation checks on a dataset. More details in the xref:./datasets/index.adoc[dedicated page].
* {blank}
`pylaia-htr-train-ctc`:: To train a PyLaia model. More details in the xref:./training/index.adoc[dedicated page].
* {blank}
`pylaia-htr-decode-ctc`:: To predict using a trained PyLaia model. More details in the xref:./prediction/index.adoc[dedicated page].
* {blank}
`pylaia-htr-netout`:: To dump features from a PyLaia model. More details in the xref:./netout/index.adoc[dedicated page].

'''

Related pages:

* Learn how to format a xref:./datasets/format.adoc[dataset in PyLaia format]
* Learn how to use PyLaia with an xref:./language_models/index.adoc[explicit language model]
