/**
 * Per-subject Convex types for JC Gaeilge.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated Gaeilge* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { IdField, SystemFields } from "convex/server";

import type {
  GaeilgeSyllabus,
  GaeilgePaper,
  GaeilgeMarkingScheme,
  GaeilgeTopics,
} from "../../../../../baml_client/typescript/baml_client/jc/gaeilge/client";

/**
 * The BAML-generated GaeilgePayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type GaeilgePayload =
  | GaeilgeSyllabus
  | GaeilgePaper
  | GaeilgeMarkingScheme
  | GaeilgeTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface GaeilgeDoc extends IdField<"gaeilge">, SystemFields {
  app: "oideachais";
  stage: "jc";
  subject: "gaeilge";
  language: "ga";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: GaeilgePayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML gaeilgeType alias for the schema file
export type gaeilgeType = GaeilgePayload;
