/**
 * Per-subject Convex types for JC History.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated History* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { IdField, SystemFields } from "convex/server";

import type {
  HistorySyllabus,
  HistoryPaper,
  HistoryMarkingScheme,
  HistoryTopics,
} from "../../../../../baml_client/typescript/baml_client/jc/history/client";

/**
 * The BAML-generated HistoryPayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type HistoryPayload =
  | HistorySyllabus
  | HistoryPaper
  | HistoryMarkingScheme
  | HistoryTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface HistoryDoc extends IdField<"history">, SystemFields {
  app: "oideachais";
  stage: "jc";
  subject: "history";
  language: "en" | "ga";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: HistoryPayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML historyType alias for the schema file
export type historyType = HistoryPayload;
