/**
 * Per-subject Convex types for JC Science.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated Science* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { IdField, SystemFields } from "convex/server";

import type {
  ScienceSyllabus,
  SciencePaper,
  ScienceMarkingScheme,
  ScienceTopics,
} from "../../../../../baml_client/typescript/baml_client/jc/science/client";

/**
 * The BAML-generated SciencePayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type SciencePayload =
  | ScienceSyllabus
  | SciencePaper
  | ScienceMarkingScheme
  | ScienceTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface ScienceDoc extends IdField<"science">, SystemFields {
  app: "oideachais";
  stage: "jc";
  subject: "science";
  language: "en" | "ga";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: SciencePayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML scienceType alias for the schema file
export type scienceType = SciencePayload;
