services:
  kafka:
    labels:
      - "pangolin.private-resources.kafka.name=Kafka Broker"
      - "pangolin.private-resources.kafka.mode=tcp"
      - "pangolin.private-resources.kafka.tcp-ports=9094"
      - "pangolin.private-resources.kafka.destination=127.0.0.1"
      - "pangolin.private-resources.kafka.protocol=tcp"
      - "pangolin.private-resources.kafka.roles[0]=Member"
  kafka-ui:
    labels:
      - "pangolin.private-resources.kafka-ui.name=Kafka UI"
      - "pangolin.private-resources.kafka-ui.mode=http"
      - "pangolin.private-resources.kafka-ui.full-domain=kafka.cianfhoghlaim.ie"
      - "pangolin.private-resources.kafka-ui.destination-port=8080"
      - "pangolin.private-resources.kafka-ui.protocol=http"
      - "pangolin.private-resources.kafka-ui.roles[0]=Member"
