/**
 * scripts/schema-codegen/ag-ui-types.ts
 *
 * Step 4 of the schema-driven codegen pipeline (per the
 * 2026-08-13-web-monorepo-consolidation-and-agent-integration-v1
 * change, Phase O).
 *
 * Emits AG-UI protocol event type wrappers per subject from the BAML/Zod
 * schemas. The AG-UI protocol has 17 standard event types per
 * https://docs.ag-ui.com — we emit typed wrappers for the 5 most
 * commonly used by the per-subject agent (RUN_STARTED,
 * RUN_FINISHED, TOOL_CALL_*, TEXT_MESSAGE_*, STATE_DELTA).
 *
 * For each (stage, subject) pair, this step writes:
 *   - web/apps/oideachais/src/lib/ag-ui/<stage>/<subject>.ts
 *     — the per-subject AG-UI event types
 *
 * Returns: array of emitted file paths (relative to repo root).
 */

import * as path from "node:path";
import * as fs from "node:fs/promises";

import type { SubjectRow } from "./index";

// =============================================================================
// The 17 AG-UI event types
// (per https://docs.ag-ui.com/concepts/messages — full protocol)
// =============================================================================

const AG_UI_EVENT_TYPES = [
  "RUN_STARTED",
  "RUN_FINISHED",
  "RUN_ERROR",
  "STEP_STARTED",
  "STEP_FINISHED",
  "TEXT_MESSAGE_START",
  "TEXT_MESSAGE_CONTENT",
  "TEXT_MESSAGE_END",
  "TOOL_CALL_START",
  "TOOL_CALL_ARGS",
  "TOOL_CALL_END",
  "TOOL_CALL_RESULT",
  "STATE_SNAPSHOT",
  "STATE_DELTA",
  "MESSAGES_SNAPSHOT",
  "RAW",
  "CUSTOM",
] as const;

type AgUiEventType = (typeof AG_UI_EVENT_TYPES)[number];

// =============================================================================
// Public API
// =============================================================================

export async function runAgUiTypes(
  repoRoot: string,
  subjects: ReadonlyArray<SubjectRow>,
  dryRun: boolean,
): Promise<ReadonlyArray<string>> {
  console.log(
    `\n[4/5] ag-ui-types (${subjects.length} subjects, ${AG_UI_EVENT_TYPES.length} event types/subject)`,
  );

  const emitted: string[] = [];

  for (const row of subjects) {
    const out = renderSubjectAgUiTypes(row);
    const outPath = path.join(
      repoRoot,
      `web/apps/oideachais/src/lib/ag-ui/${row.stage}`,
      `${row.subject}.ts`,
    );

    if (!dryRun) {
      await fs.mkdir(path.dirname(outPath), { recursive: true });
      await fs.writeFile(outPath, out);
    }

    emitted.push(
      `web/apps/oideachais/src/lib/ag-ui/${row.stage}/${row.subject}.ts`,
    );
  }

  // Also emit a barrel file that re-exports all subjects
  const barrelPath = path.join(
    repoRoot,
    "web/apps/oideachais/src/lib/ag-ui/index.ts",
  );
  if (!dryRun) {
    await fs.mkdir(path.dirname(barrelPath), { recursive: true });
    await fs.writeFile(barrelPath, renderBarrelFile(subjects));
  }
  emitted.push("web/apps/oideachais/src/lib/ag-ui/index.ts");

  console.log(`  emitted ${emitted.length} files`);
  return emitted;
}

// =============================================================================
// Renderers
// =============================================================================

/**
 * Render the per-subject AG-UI event types file. Each subject gets a
 * typed wrapper around the 17 AG-UI events with the subject's
 * metadata baked in.
 */
export function renderSubjectAgUiTypes(row: SubjectRow): string {
  const identifier = `${row.stage}_${row.subject}`;
  const PascalId =
    identifier.charAt(0).toUpperCase() + identifier.slice(1).replace(/_(\w)/g, (_, c: string) => c.toUpperCase());

  return `/**
 * AG-UI protocol event types for ${row.stage.toUpperCase()} ${row.display_name}.
 *
 * AUTO-GENERATED by scripts/schema-codegen/ag-ui-types.ts (Phase O).
 * DO NOT EDIT — re-run \`bun run scripts/schema-codegen/index.ts\` to update.
 *
 * The 17 standard AG-UI event types (per https://docs.ag-ui.com/concepts/messages)
 * with the per-subject metadata baked in.
 *
 * Reference:
 *   openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 *   specs/tanstack-ai-agui-integration/spec.md
 */

import type {
  BaseEvent,
  RunAgentInput,
} from "@ag-ui/core";

// ─── The 17 standard AG-UI event types ─────────────────────────────────

export type AgUiEventType =
${AG_UI_EVENT_TYPES.map((e) => `  | "${e}"`).join("\n")};

// ─── Per-subject typed event wrappers ────────────────────────────────────

export interface ${PascalId}RunStarted extends BaseEvent {
  type: "RUN_STARTED";
  threadId: string;
  runId: string;
  subject: "${row.subject}";
  stage: "${row.stage}";
}

export interface ${PascalId}RunFinished extends BaseEvent {
  type: "RUN_FINISHED";
  threadId: string;
  runId: string;
  subject: "${row.subject}";
}

export interface ${PascalId}RunError extends BaseEvent {
  type: "RUN_ERROR";
  threadId: string;
  runId: string;
  subject: "${row.subject}";
  error: string;
}

export interface ${PascalId}TextMessageStart extends BaseEvent {
  type: "TEXT_MESSAGE_START";
  messageId: string;
  subject: "${row.subject}";
}

export interface ${PascalId}TextMessageContent extends BaseEvent {
  type: "TEXT_MESSAGE_CONTENT";
  messageId: string;
  delta: string;
  subject: "${row.subject}";
}

export interface ${PascalId}ToolCallStart extends BaseEvent {
  type: "TOOL_CALL_START";
  toolCallId: string;
  toolCallName: string;
  parentMessageId?: string;
  subject: "${row.subject}";
}

export interface ${PascalId}ToolCallArgs extends BaseEvent {
  type: "TOOL_CALL_ARGS";
  toolCallId: string;
  delta: string;
  subject: "${row.subject}";
}

export interface ${PascalId}ToolCallEnd extends BaseEvent {
  type: "TOOL_CALL_END";
  toolCallId: string;
  subject: "${row.subject}";
}

export interface ${PascalId}ToolCallResult extends BaseEvent {
  type: "TOOL_CALL_RESULT";
  toolCallId: string;
  content: string;
  error?: string;
  subject: "${row.subject}";
}

export interface ${PascalId}StateDelta extends BaseEvent {
  type: "STATE_DELTA";
  delta: Record<string, unknown>;
  subject: "${row.subject}";
}

export interface ${PascalId}MessagesSnapshot extends BaseEvent {
  type: "MESSAGES_SNAPSHOT";
  messages: ReadonlyArray<unknown>;
  subject: "${row.subject}";
}

// The canonical RunAgentInput for the per-subject agent
export interface ${PascalId}RunAgentInput extends RunAgentInput {
  subject: "${row.subject}";
  stage: "${row.stage}";
  ncca_code: "${row.ncca_code}";
  languages: ${JSON.stringify(row.languages)};
}

// The canonical tools exposed by the per-subject agent
export interface ${PascalId}Tools {
  get_syllabus_topics: (params: {
    level?: "hl" | "ol" | "fl" | "a-level";
    language?: "en" | "ga";
  }) => Promise<unknown>;
  get_exam_papers: (params: {
    year: number;
    level?: "hl" | "ol" | "fl" | "a-level";
  }) => Promise<unknown>;
  get_marking_schemes: (params: {
    year: number;
    level?: "hl" | "ol" | "fl" | "a-level";
  }) => Promise<unknown>;
  get_topic_detail: (params: { topic_code: string }) => Promise<unknown>;
  get_cross_jurisdictional_equivalences: (params: {
    topic_code: string;
    jurisdiction?: "lc" | "gcse" | "a-level";
  }) => Promise<unknown>;
  semantic_search: (params: {
    query: string;
    top_k?: number;
  }) => Promise<unknown>;
  extract_syllabus_from_pdf: (params: { pdf_url: string }) => Promise<unknown>;
  save_annotation: (params: {
    topic_code: string;
    note: string;
  }) => Promise<unknown>;
  track_progress: (params: {
    topic_code: string;
    score: number;
  }) => Promise<unknown>;
  get_study_plan: (params: {
    subject: string;
    target_date?: string;
  }) => Promise<unknown>;
  compare_curricula: (params: {
    topic_code: string;
    stages: ReadonlyArray<string>;
  }) => Promise<unknown>;
  get_glossary_term: (params: {
    term: string;
    language?: "en" | "ga" | "both";
  }) => Promise<unknown>;
  extract_learning_outcome: (params: { text: string }) => Promise<unknown>;
}

// The canonical 17-event union type for the per-subject agent
export type ${PascalId}Event =
  | ${PascalId}RunStarted
  | ${PascalId}RunFinished
  | ${PascalId}RunError
  | ${PascalId}TextMessageStart
  | ${PascalId}TextMessageContent
  | ${PascalId}ToolCallStart
  | ${PascalId}ToolCallArgs
  | ${PascalId}ToolCallEnd
  | ${PascalId}ToolCallResult
  | ${PascalId}StateDelta
  | ${PascalId}MessagesSnapshot;
`;
}

/**
 * Render the barrel file that re-exports all subjects.
 */
export function renderBarrelFile(subjects: ReadonlyArray<SubjectRow>): string {
  const exports = subjects
    .map((row) => {
      const identifier = `${row.stage}_${row.subject}`;
      const PascalId =
        identifier.charAt(0).toUpperCase() +
        identifier.slice(1).replace(/_(\w)/g, (_, c: string) => c.toUpperCase());
      return `export * from "./${row.stage}/${row.subject}";`;
    })
    .join("\n");

  return `/**
 * AG-UI event types barrel — re-exports all per-subject AG-UI types.
 *
 * AUTO-GENERATED by scripts/schema-codegen/ag-ui-types.ts (Phase O).
 * DO NOT EDIT — re-run \`bun run scripts/schema-codegen/index.ts\` to update.
 *
 * Per openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 * specs/tanstack-ai-agui-integration/spec.md
 */

${exports}
`;
}
