/**
 * scripts/schema-codegen/per-subject-routes.ts
 *
 * Step 5 of the schema-driven codegen pipeline (per the
 * 2026-08-13-web-monorepo-consolidation-and-agent-integration-v1
 * change, Phase O).
 *
 * Emits per-subject TanStack Start routes from the BAML/Zod schemas.
 *
 * For each (stage, subject) pair, this step writes:
 *   - web/apps/oideachais/routes/<stage>/<subject>/index.tsx
 *     — the per-subject landing page (TanStack Start file-based route)
 *   - web/apps/oideachaim/routes/<stage>/<subject>/$topicId.tsx
 *     — the per-subject topic detail page
 *   - web/apps/oideachais/routes/<stage>/<subject>/AGENTS.md
 *     — the per-subject routing docs
 *
 * Returns: array of emitted file paths (relative to repo root).
 */

import * as path from "node:path";
import * as fs from "node:fs/promises";

import type { SubjectRow } from "./index";

// =============================================================================
// Public API
// =============================================================================

export async function runPerSubjectRoutes(
  repoRoot: string,
  subjects: ReadonlyArray<SubjectRow>,
  dryRun: boolean,
): Promise<ReadonlyArray<string>> {
  console.log(`\n[5/5] per-subject-routes (${subjects.length} subjects)`);

  const emitted: string[] = [];

  for (const row of subjects) {
    const indexSource = renderSubjectIndexRoute(row);
    const topicSource = renderSubjectTopicRoute(row);
    const agentsMd = renderSubjectAgentsMd(row);

    const perStageDir = `${row.stage}/${row.subject}`;
    const indexPath = path.join(
      repoRoot,
      `web/apps/oideachais/routes/${perStageDir}`,
      "index.tsx",
    );
    const topicPath = path.join(
      repoRoot,
      `web/apps/oideachais/routes/${perStageDir}`,
      "$topicId.tsx",
    );
    const agentsMdPath = path.join(
      repoRoot,
      `web/apps/oideachais/routes/${perStageDir}`,
      "AGENTS.md",
    );

    if (!dryRun) {
      await fs.mkdir(path.dirname(indexPath), { recursive: true });
      await fs.writeFile(indexPath, indexSource);
      await fs.writeFile(topicPath, topicSource);
      await fs.writeFile(agentsMdPath, agentsMd);
    }

    emitted.push(
      `web/apps/oideachais/routes/${perStageDir}/index.tsx`,
      `web/apps/oideachais/routes/${perStageDir}/$topicId.tsx`,
      `web/apps/oideachais/routes/${perStageDir}/AGENTS.md`,
    );
  }

  console.log(`  emitted ${emitted.length} files`);
  return emitted;
}

// =============================================================================
// Renderers
// =============================================================================

/**
 * Render the per-subject index route (TanStack Start file-based route).
 * The route loads the BAML-extracted syllabus + papers + marking
 * schemes + topics + renders them in a CopilotKit v2 + AG-UI layout.
 */
export function renderSubjectIndexRoute(row: SubjectRow): string {
  const PascalId =
    row.subject.charAt(0).toUpperCase() +
    row.subject.slice(1).replace(/_(\w)/g, (_, c: string) => c.toUpperCase());

  return `/**
 * ${row.stage.toUpperCase()} ${row.display_name} — subject landing page.
 *
 * AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O).
 * DO NOT EDIT — re-run \`bun run scripts/schema-codegen/index.ts\` to update.
 *
 * Per openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 * specs/per-subject-coverage/spec.md.
 */

import { createFileRoute, Link } from "@tanstack/react-router";
import { CopilotKit } from "@copilotkit/react-core/v2";
import { useState } from "react";

import { use${PascalId}Actions } from "@/lib/copilotkit/${row.stage}/${row.subject}";
import { use${PascalId}Events } from "@/lib/ag-ui/${row.stage}/${row.subject}";

export const Route = createFileRoute("/${row.stage}/${row.subject}/")({
  component: ${PascalId}Page,
});

function ${PascalId}Page() {
  return (
    <CopilotKit runtimeUrl="/api/copilotkit/${row.stage}/${row.subject}">
      <div className="max-w-4xl mx-auto flex flex-col gap-8 h-full p-8">
        <div className="flex flex-col gap-2">
          <h1 className="text-4xl font-bold">
            ${row.display_name} (${row.stage.toUpperCase()})
          </h1>
          <p className="text-slate-600 text-lg">
            ${row.display_name} — ${row.ncca_code} — languages: ${row.languages.join(", ")}
          </p>
        </div>

        <SubjectActionsSection subject="${row.subject}" stage="${row.stage}" />

        <Link
          to="/${row.stage}/${row.subject}/\$topicId"
          params={{ topicId: "${row.ncca_code}-001" }}
          className="btn-tactile"
        >
          Open topic detail →
        </Link>
      </div>
    </CopilotKit>
  );
}

function SubjectActionsSection({
  subject,
  stage,
}: {
  subject: string;
  stage: string;
}) {
  use${PascalId}Actions();

  return (
    <div className="grid grid-cols-2 gap-4">
      <ActionCard
        title="Get syllabus topics"
        description="Fetch the ${row.display_name} syllabus topics + learning outcomes"
        actionName="get_syllabus_topics"
      />
      <ActionCard
        title="Get exam papers"
        description="List exam papers by year + level"
        actionName="get_exam_papers"
      />
      <ActionCard
        title="Get marking schemes"
        description="Fetch marking schemes + rubrics"
        actionName="get_marking_schemes"
      />
      <ActionCard
        title="Semantic search"
        description="BGE-M3 vector search over the ${row.display_name} embeddings"
        actionName="semantic_search"
      />
    </div>
  );
}

function ActionCard({
  title,
  description,
  actionName,
}: {
  title: string;
  description: string;
  actionName: string;
}) {
  return (
    <button
      className="rounded-lg border p-4 text-left hover:bg-slate-50"
      data-action={actionName}
    >
      <h3 className="font-semibold">{title}</h3>
      <p className="text-sm text-slate-600">{description}</p>
    </button>
  );
}
`;
}

/**
 * Render the per-subject topic detail route.
 */
export function renderSubjectTopicRoute(row: SubjectRow): string {
  const PascalId =
    row.subject.charAt(0).toUpperCase() +
    row.subject.slice(1).replace(/_(\w)/g, (_, c: string) => c.toUpperCase());

  return `/**
 * ${row.stage.toUpperCase()} ${row.display_name} — per-topic detail page.
 *
 * AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O).
 * DO NOT EDIT — re-run \`bun run scripts/schema-codegen/index.ts\` to update.
 */

import { createFileRoute, useParams } from "@tanstack/react-router";
import { CopilotKit } from "@copilotkit/react-core/v2";

import { use${PascalId}Actions } from "@/lib/copilotkit/${row.stage}/${row.subject}";

export const Route = createFileRoute("/${row.stage}/${row.subject}/\$topicId" as const)({
  component: ${PascalId}TopicPage,
});

function ${PascalId}TopicPage() {
  const { topicId } = useParams({ from: Route.id });

  return (
    <CopilotKit runtimeUrl="/api/copilotkit/${row.stage}/${row.subject}">
      <div className="max-w-4xl mx-auto flex flex-col gap-8 h-full p-8">
        <h1 className="text-3xl font-bold">Topic: {topicId}</h1>
        <p className="text-slate-600">
          ${row.display_name} (${row.stage.toUpperCase()}) — topic detail.
        </p>

        <TopicDetailActions topicId={topicId} />
      </div>
    </CopilotKit>
  );
}

function TopicDetailActions({ topicId }: { topicId: string }) {
  use${PascalId}Actions();

  return (
    <div className="grid grid-cols-2 gap-4">
      <button data-action="get_topic_detail" data-topic-id={topicId}>
        Get topic detail
      </button>
      <button data-action="get_cross_jurisdictional_equivalences" data-topic-id={topicId}>
        Get cross-jurisdictional equivalences
      </button>
      <button data-action="save_annotation" data-topic-id={topicId}>
        Save annotation
      </button>
      <button data-action="track_progress" data-topic-id={topicId}>
        Track progress
      </button>
    </div>
  );
}
`;
}

/**
 * Render the per-subject AGENTS.md file.
 */
export function renderSubjectAgentsMd(row: SubjectRow): string {
  const route = `/${row.stage}/${row.subject}/`;
  return `# \`${route}\` — ${row.display_name} (${row.stage.toUpperCase()}) Agent Routing

> **The per-subject routing docs for ${row.stage.toUpperCase()} ${row.display_name}.**
> AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O).

## Routing

Load this AGENTS.md when:

- You add / modify a per-subject feature for ${row.display_name}
- You wire the ${row.subject}_${row.stage}_agent to a new surface
- You add / modify the per-subject CopilotKit actions

For platform-wide context, load [\`../../../AGENTS.md\`](../../../AGENTS.md).

## Subject metadata

| Field | Value |
|:--|:--|
| Stage | ${row.stage} |
| Subject slug | \`${row.subject}\` |
| Display name | ${row.display_name} |
| NCCA code | \`${row.ncca_code}\` |
| Languages | ${row.languages.join(", ")} |
| Per-subject agent | \`${row.subject}_${row.stage}_agent\` (60-subject matrix, Phase U) |
| Per-subject BAML extraction | 8 functions (Phase P) |
| Per-subject CocoIndex flow | 1 (per stage × subject) |
| Per-subject marimo notebook | 1 |
| Per-subject CopilotKit actions | 13 (Phase K) |
| Per-subject Hono API route | \`/api/copilotkit/${row.stage}/${row.subject}\` (Phase G) |
| Per-subject web routes | \`${route}\` + \`${route}$topicId\` |

## Adjacent specs

- [\`per-subject-coverage\`](../../../openspec/specs/per-subject-coverage/spec.md) — the 60-subject coverage matrix
- [\`per-subject-agents\`](../../../openspec/specs/per-subject-agents/spec.md) — the 60 per-subject agents
- [\`tanstack-ai-agui-integration\`](../../../openspec/specs/tanstack-ai-agui-integration/spec.md) — TanStack AI + AG-UI compliance

## DO NOT

- **Never** hardcode a model string — route through \`MODEL_REGISTRY\`
- **Never** add per-subject Convex tables outside the umbrella schema
- **Never** deploy without running \`mise run codegen:all\`

## Skill pointers

| Skill | When to load |
|:--|:--|
| [\`schema-codegen\`](../../../.agents/skills/schema-codegen/SKILL.md) | The BAML → Zod → Convex → CopilotKit codegen pipeline |
| [\`tanstack-start\`](../../../.agents/skills/tanstack-start/SKILL.md) | TanStack Start file-based routing |
| [\`centralized-registry\`](../../../.agents/skills/centralized-registry/SKILL.md) | The model + schema registry |

<!-- AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O); DO NOT HAND-EDIT -->
`;
}
