services:
  main-service:
    labels:
      - "pangolin.public-resources.DnsServer.name=Dnsserver"
      - "pangolin.public-resources.DnsServer.full-domain=DnsServer.cianfhoghlaim.ie"
      - "pangolin.public-resources.DnsServer.protocol=http"
      - "pangolin.public-resources.DnsServer.targets[0].method=http"
      - "pangolin.public-resources.DnsServer.targets[0].port=8080"
