"""
Aistear (Early Childhood) DLT source.

Reads the 14 Aistear source PDFs on curriculumonline.ie/en/early-childhood/
plus the NCCA Aistear framework pages. Honors USE_LOCAL_SCRAPES=true to
read from /stedding/ingest_queue/aistear/ cache.

Datasets produced:
  aistear_documents       — AistearDocument rows
  aistear_principles      — AistearPrinciple rows
  aistear_learning_goals  — AistearLearningGoal rows
  naionra_listings        — Naionra rows (Gaeloideachas.ie / Pobal)
"""
from __future__ import annotations

import logging
import os
from datetime import UTC, datetime
from pathlib import Path

import dlt

logger = logging.getLogger(__name__)

# BAML client (generated by `mise turbo baml:generate`). When the
# baml_client package is not yet generated (dev / CI venv), the
# extraction is a graceful no-op and the resource yields the
# placeholder PENDING_BAML rows.
try:
    from baml_client import b as _baml_client  # type: ignore[import-not-found]

    _BAML_AVAILABLE = True
except ImportError:
    _baml_client = None
    _BAML_AVAILABLE = False


def _extract_pdf_text(pdf_path: Path, max_chars: int = 100_000) -> str:
    """Best-effort PDF text extraction (PyMuPDF4LLM preferred, PyMuPDF fallback)."""
    try:
        import pymupdf4llm  # type: ignore[import-not-found]

        return "\n".join(pymupdf4llm.to_markdown(str(pdf_path))[:max_chars])
    except ImportError:
        pass
    try:
        import pymupdf  # type: ignore[import-not-found]

        doc = pymupdf.open(str(pdf_path))
        text = "\n".join(page.get_text() for page in doc)
        doc.close()
        return text[:max_chars]
    except ImportError:
        logger.warning("pymupdf_not_available_aistear_text_extraction_skipped")
        return ""


AISTEAR_CACHE_DIR = Path(os.getenv("STEDDING_INGEST_QUEUE", "/stedding/ingest_queue")) / "aistear"
AISTEAR_SOURCE_URLS = [
    "https://www.curriculumonline.ie/en/early-childhood/",
    "https://www.ncca.ie/en/early-childhood/",
    "https://www.gov.ie/en/department-of-education/topics/early-years/",
    "https://gaeloideachas.ie/directories/",
]


@dlt.resource(name="aistear_documents", write_disposition="merge", primary_key=["document_id"])
def aistear_documents():
    """Aistear framework PDFs (curriculumonline.ie + NCCA + gov.ie).

    For each PDF in the cache, yields one AistearDocument row. The
    BAML function `ExtractAistearFramework` is invoked to extract
    the 4 themes, 12 principles, and all learning goals. When the
    BAML client is not yet generated, the row is yielded with
    `extracted_at: "PENDING_BAML"` placeholder fields.
    """
    if not AISTEAR_CACHE_DIR.exists():
        return
    for pdf in sorted(AISTEAR_CACHE_DIR.glob("**/*.pdf")):
        doc_id = pdf.stem
        framework = None
        extracted_at = "PENDING_BAML"
        if _BAML_AVAILABLE:
            try:
                pdf_text = _extract_pdf_text(pdf)
                if pdf_text.strip():
                    fw = _baml_client.ExtractAistearFramework(pdf_text=pdf_text)
                    framework = {
                        "themes": list(fw.themes or []),
                        "principles": [
                            {
                                "name": p.name,
                                "description": p.description,
                                "age_band": p.age_band,
                            }
                            for p in (fw.principles or [])
                        ],
                        "learning_goals": [
                            {
                                "goal_id": g.goal_id,
                                "description": g.description,
                                "theme": g.theme,
                                "age_band": g.age_band,
                            }
                            for g in (fw.learning_goals or [])
                        ],
                    }
                    extracted_at = datetime.now(UTC).isoformat()
            except Exception as exc:
                logger.warning("ExtractAistearFramework_failed", file=pdf.name, error=str(exc))

        yield {
            "document_id": doc_id,
            "title_en": doc_id.replace("_", " ").title(),
            "source_url": f"https://cache.local/aistear/{pdf.relative_to(AISTEAR_CACHE_DIR)}",
            "age_band": "PRE_SCHOOL",
            "themes": ["WELL_BEING", "IDENTITY_BELONGING", "COMMUNICATING", "EXPLORING_THINKING"],
            "principles_count": len(framework["principles"]) if framework else 0,
            "learning_goals_count": len(framework["learning_goals"]) if framework else 0,
            "framework": framework,
            "extracted_at": extracted_at,
            "language": "bilingual",
        }


@dlt.resource(name="aistear_principles", write_disposition="merge", primary_key=["framework_document_id", "principle_name"])
def aistear_principles():
    """One row per Aistear principle per document.

    Reads the BAML-extracted principles from the `aistear_documents`
    resource and yields one row per principle. This resource yields
    nothing when BAML is not available.
    """
    if not _BAML_AVAILABLE or not AISTEAR_CACHE_DIR.exists():
        return
    for doc in aistear_documents():
        framework = doc.get("framework") or {}
        for p in framework.get("principles", []) or []:
            yield {
                "framework_document_id": doc["document_id"],
                "principle_name": p.get("name"),
                "description": p.get("description"),
                "age_band": p.get("age_band"),
                "source_document": doc.get("title_en"),
            }


@dlt.resource(name="aistear_learning_goals", write_disposition="merge", primary_key=["goal_id"])
def aistear_learning_goals():
    """One row per Aistear learning goal per document.

    Reads the BAML-extracted learning goals from the `aistear_documents`
    resource and yields one row per goal. This resource yields
    nothing when BAML is not available.
    """
    if not _BAML_AVAILABLE or not AISTEAR_CACHE_DIR.exists():
        return
    for doc in aistear_documents():
        framework = doc.get("framework") or {}
        for g in framework.get("learning_goals", []) or []:
            yield {
                "goal_id": g.get("goal_id"),
                "description": g.get("description"),
                "theme": g.get("theme"),
                "age_band": g.get("age_band"),
                "framework_document_id": doc["document_id"],
                "source_document": doc.get("title_en"),
            }


@dlt.resource(name="naionra_listings", write_disposition="merge", primary_key=["id"])
def naionra_listings():
    """Naíonra (Irish-medium pre-school) directory.

    Source: gaeloideachas.ie/directories/ and Pobal listings.
    Geocoded downstream by the geospatial DAG.
    """
    if not AISTEAR_CACHE_DIR.exists():
        return
    cache = AISTEAR_CACHE_DIR / "naionra"
    if not cache.exists():
        return
    for json_file in sorted(cache.glob("**/*.json")):
        import json as _json

        data = _json.loads(json_file.read_text())
        if isinstance(data, list):
            yield from data
        else:
            yield data


@dlt.source(name="aistear_curriculum")
def aistear_curriculum():
    """Aistear DLT source — documents + principles + learning goals + naíonra directory."""
    yield aistear_documents
    yield aistear_principles
    yield aistear_learning_goals
    yield naionra_listings
