/**
 * Per-subject Convex types for A-LEVEL Business.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Re-exports the BAML-generated Business* types from step 1 + adds the
 * Convex-specific doc type.
 */

import type { IdField, SystemFields } from "convex/server";

import type {
  BusinessSyllabus,
  BusinessPaper,
  BusinessMarkingScheme,
  BusinessTopics,
} from "../../../../../baml_client/typescript/baml_client/a-level/business/client";

/**
 * The BAML-generated BusinessPayload type (the union of the 4 extraction
 * functions' outputs).
 */
export type BusinessPayload =
  | BusinessSyllabus
  | BusinessPaper
  | BusinessMarkingScheme
  | BusinessTopics;

/**
 * The per-subject Convex doc type (the BAML payload + Convex metadata).
 */
export interface BusinessDoc extends IdField<"business">, SystemFields {
  app: "oideachais";
  stage: "a-level";
  subject: "business";
  language: "en";
  syllabus_topic_code: string;
  syllabus_topic_title: string;
  learning_outcome_code: string;
  learning_outcome_text: string;
  blooms_level:
    | "remember"
    | "understand"
    | "apply"
    | "analyse"
    | "evaluate"
    | "create";
  payload: BusinessPayload;
  ncca_code: string;
  created_at: number;
  updated_at: number;
}

// Re-export the BAML businessType alias for the schema file
export type businessType = BusinessPayload;
