"""
BAML Integration Adapter for Dagster.

Wraps the BAML-compiled client (from `baml_client/`) and routes all extraction
calls through the canonical LiteLLM gateway. Provides:

  - EnhancedBAMLExtractionPipeline.process_document() — full document extraction
  - Convenience wrappers for each BAML function in baml/

The BAML client in turn points to the LiteLLM gateway (see baml/clients.baml).
The gateway in turn handles fallback to local GGUF / MLX / cloud providers.

Reference: docs/data_engineering/baml.md
            baml/education/_shared/curriculum_relationships.baml
            baml/processing/image_generation.baml
"""
from __future__ import annotations

import logging
import os
from typing import Any

logger = logging.getLogger(__name__)

# BAML client is generated by `baml-cli generate` from baml/**/*.baml
# The generated client lives at baml_client/ and is importable as
# `from baml_client import b` (b is the BAML namespace).
try:
    from baml_client import b
    from baml_client.types import (
        CurriculumSpecification,
        ExaminerReport,
        ExamPaper,
        ExtractedRelationship,
        LearningOutcome,
        MarkingScheme,
    )
    HAS_BAML_CLIENT = True
except ImportError:
    HAS_BAML_CLIENT = False
    logger.warning(
        "baml_client not generated. Run from repo root: "
        "`uv run baml-cli generate` (or `mise run baml:generate` if defined)"
    )


# =============================================================================
# Configuration
# =============================================================================

LITELLM_BASE_URL = os.getenv("LITELLM_BASE_URL", "http://litellm:4000/v1")
LITELLM_MASTER_KEY = os.getenv("LITELLM_MASTER_KEY", "sk-1234")


# =============================================================================
# Pipeline
# =============================================================================

class EnhancedBAMLExtractionPipeline:
    """Wraps BAML functions with retry, observability, and cost tracking.

    BAML functions used (all via the LiteLLM gateway):
      - ExtractCurriculumSpecification (baml/education/_shared/curriculum_relationships.baml)
      - ExtractExamPaperStructure     (same)
      - ExtractMarkingScheme          (same)
      - ExtractExaminerReportInsights  (same)
      - MapOutcomesToExamQuestions    (same)
      - ExtractImagePrompt            (baml/processing/image_generation.baml)
      - BuildFIBOConfig               (same)
    """

    def __init__(
        self,
        subject: str = "",
        cycle: str = "junior_cycle",
        language: str = "en",
        max_retries: int = 2,
    ):
        self.subject = subject
        self.cycle = cycle
        self.language = language
        self.max_retries = max_retries

        if not HAS_BAML_CLIENT:
            raise RuntimeError(
                "baml_client not generated. Run: bun run baml:generate "
                "or `uv run baml-cli generate` from the repo root."
            )

    # ------------------------------------------------------------------
    # Curriculum extraction
    # ------------------------------------------------------------------

    def extract_curriculum_specification(
        self,
        document_text: str,
        subject: str | None = None,
        cycle: str | None = None,
        language: str | None = None,
    ) -> CurriculumSpecification:
        """Extract a full CurriculumSpecification from a syllabus/spec PDF."""
        return b.ExtractCurriculumSpecification(
            document_text=document_text,
            subject=subject or self.subject,
            cycle=cycle or self.cycle,
            language=language or self.language,
        )

    def extract_exam_paper(
        self,
        document_text: str,
        subject: str,
        year: int,
        level: str,
        paper_number: int,
    ) -> ExamPaper:
        return b.ExtractExamPaperStructure(
            document_text=document_text,
            subject=subject,
            year=year,
            level=level,
            paper_number=paper_number,
        )

    def extract_marking_scheme(
        self,
        document_text: str,
        subject: str,
        year: int,
        level: str,
    ) -> MarkingScheme:
        return b.ExtractMarkingScheme(
            document_text=document_text,
            subject=subject,
            year=year,
            level=level,
        )

    def extract_examiner_report(
        self,
        document_text: str,
        subject: str,
        year: int,
        level: str,
    ) -> ExaminerReport:
        return b.ExtractExaminerReportInsights(
            document_text=document_text,
            subject=subject,
            year=year,
            level=level,
        )

    # ------------------------------------------------------------------
    # Image generation (Phase 7)
    # ------------------------------------------------------------------

    def extract_image_prompt(
        self,
        outcome_text: str,
        subject: str,
        cycle: str = "senior_cycle",
        purpose: str = "STUDY_CARD",
    ):
        from baml_client.types import ImagePurpose
        return b.ExtractImagePrompt(
            outcome_text=outcome_text,
            subject=subject,
            cycle=cycle,
            purpose=ImagePurpose(purpose),
        )

    def build_fibo_config(self, spec, outcome_id: str, syllabus_path: str):
        return b.BuildFIBOConfig(
            spec=spec,
            outcome_id=outcome_id,
            syllabus_path=syllabus_path,
        )

    # ------------------------------------------------------------------
    # Legacy entry point (kept for backwards compat)
    # ------------------------------------------------------------------

    def process_document(self, doc_text: str, context: dict) -> dict[str, Any]:
        """Process a document end-to-end. Returns a dict of extracted entities."""
        subject = context.get("subject", self.subject)
        cycle = context.get("cycle", self.cycle)
        language = context.get("language", self.language)

        spec = self.extract_curriculum_specification(
            document_text=doc_text,
            subject=subject,
            cycle=cycle,
            language=language,
        )
        return spec.model_dump() if hasattr(spec, "model_dump") else spec.dict()
