"""Mathematics schema — Cianfhoghlaim Oideachais.

DEPRECATED 2026-08-15 — the 12 hand-written Pydantic classes in this
module have been replaced with thin re-exports from the generated
BAML Python client. The BAML file
(``baml_src/british_isles/ireland/education/subjects/qpack_mathematics.baml``)
is now the single source of truth. The hand-written schema was
explicitly documented as a BAML mirror:

    "These mirror the BAML classes in
    ``cianfhoghlaim/baml/qpack_mathematics.baml`` and are used for
    runtime type validation in the Dagster assets. The BAML file is
    the source of truth (it controls the LLM contract); this module
    mirrors the shapes so the Python pipeline can be type-checked
    without round-tripping through BAML codegen."

The mirror is now unnecessary because the generated BAML Python
client (``baml_client/baml_client/types.py``) is the runtime type
source. This module is retained as a back-compat shim — direct
imports from
``dlt_sources.british_isles.ireland.education.subjects.mathematics.schema``
continue to resolve via re-export.

Per the ``centralized-schema-registry`` capability (2026-08-15).
"""
from __future__ import annotations

# Re-export every Math* class from the generated BAML Python client.
# `MathNCCALevel` and `MathTopicArea` are enums (str, Enum); the others
# are BaseModel subclasses — all generated by `baml-cli generate`
# from `baml_src/.../qpack_mathematics.baml`.
from baml_client.baml_client.types import (
    MathBilingualText,
    MathEvidenceLink,
    MathNCCALevel,
    MathNCCALearningOutcome,
    MathTopicArea,
    MathFormativeItem,
    MathFormativeItemAttempt,
    MathScoreBreakdown,
    MathQuestPack,
    MathQuestPackValidation,
)

# These names existed in the legacy hand-written module but had no
# BAML equivalents (they were internal DLT data carriers — DLT
# resource shapes, not BAML types). Retained as thin aliases to the
# BAML enums to keep import-compatibility for downstream consumers.
try:
    from baml_client.baml_client.types import (
        MathQuestionType as FormativeItemType,
        MathMarkingBand as FeedbackChannel,
    )
except ImportError:
    # Older BAML clients may not have these exact enum names; fall
    # back to the legacy strings.
    from enum import Enum

    class FormativeItemType(str, Enum):
        NUMERICAL = "numerical"
        SHORT_ANSWER = "short_answer"
        EXTENDED_RESPONSE = "extended_response"

    class FeedbackChannel(str, Enum):
        HINT = "hint"
        ELABORATION = "elaboration"
        MISCONCEPTION = "misconception"
        REINFORCEMENT = "reinforcement"


__all__ = [
    "BilingualText",
    "EvidenceLink",
    "MathNCCALevel",
    "MathTopicArea",
    "MathNCCALearningOutcome",
    "FormativeItem",
    "FormativeItemAttempt",
    "ScoreBreakdown",
    "QuestPack",
    "QuestPackValidation",
    "FormativeItemType",
    "FeedbackChannel",
    "MathBilingualText",
    "MathEvidenceLink",
    "MathFormativeItem",
    "MathFormativeItemAttempt",
    "MathScoreBreakdown",
    "MathQuestPack",
    "MathQuestPackValidation",
]
