/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Ga_layoutRouteImport } from './routes/ga/__layout'
import { Route as EnPointsCalculatorRouteImport } from './routes/en/points-calculator'
import { Route as EnMatriculationAuditorRouteImport } from './routes/en/matriculation-auditor'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as En_layoutRouteImport } from './routes/en/__layout'
import { Route as GaCChar233imeannaIndexRouteImport } from './routes/ga/céimeanna/index'
import { Route as EnStagesIndexRouteImport } from './routes/en/stages/index'
import { Route as GaLeavingCertMathematicsRouteImport } from './routes/ga/leaving-cert/mathematics'
import { Route as GaLeavingCertIrishRouteImport } from './routes/ga/leaving-cert/irish'
import { Route as GaLeavingCertHistoryRouteImport } from './routes/ga/leaving-cert/history'
import { Route as GaLeavingCertFrenchRouteImport } from './routes/ga/leaving-cert/french'
import { Route as GaLeavingCertConstructionStudiesRouteImport } from './routes/ga/leaving-cert/construction-studies'
import { Route as GaLeavingCertBusinessRouteImport } from './routes/ga/leaving-cert/business'
import { Route as GaLeavingCertBiologyRouteImport } from './routes/ga/leaving-cert/biology'
import { Route as GaCChar233imeannaCChar233imRouteImport } from './routes/ga/céimeanna/$céim'
import { Route as EnSubjectsSlugRouteImport } from './routes/en/subjects/$slug'
import { Route as EnStagesStageRouteImport } from './routes/en/stages/$stage'
import { Route as EnPracticeSubjectRouteImport } from './routes/en/practice/$subject'
import { Route as EnPastPapersSubjectRouteImport } from './routes/en/past-papers/$subject'
import { Route as EnMarkingSchemesSubjectRouteImport } from './routes/en/marking-schemes/$subject'
import { Route as EnLeavingCertMathematicsRouteImport } from './routes/en/leaving-cert/mathematics'
import { Route as EnLeavingCertIrishRouteImport } from './routes/en/leaving-cert/irish'
import { Route as EnLeavingCertHistoryRouteImport } from './routes/en/leaving-cert/history'
import { Route as EnLeavingCertFrenchRouteImport } from './routes/en/leaving-cert/french'
import { Route as EnLeavingCertConstructionStudiesRouteImport } from './routes/en/leaving-cert/construction-studies'
import { Route as EnLeavingCertBusinessRouteImport } from './routes/en/leaving-cert/business'
import { Route as EnLeavingCertBiologyRouteImport } from './routes/en/leaving-cert/biology'
import { Route as EnExaminerReportsSubjectRouteImport } from './routes/en/examiner-reports/$subject'
import { Route as EnDashboardsStageRouteImport } from './routes/en/dashboards/$stage'
import { Route as EnAdminComponentsRouteImport } from './routes/en/admin/components'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ga_layoutRoute = Ga_layoutRouteImport.update({
  id: '/ga/__layout',
  path: '/ga',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPointsCalculatorRoute = EnPointsCalculatorRouteImport.update({
  id: '/en/points-calculator',
  path: '/en/points-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMatriculationAuditorRoute = EnMatriculationAuditorRouteImport.update({
  id: '/en/matriculation-auditor',
  path: '/en/matriculation-auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const En_layoutRoute = En_layoutRouteImport.update({
  id: '/en/__layout',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const GaCChar233imeannaIndexRoute = GaCChar233imeannaIndexRouteImport.update({
  id: '/ga/céimeanna/',
  path: '/ga/céimeanna/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStagesIndexRoute = EnStagesIndexRouteImport.update({
  id: '/en/stages/',
  path: '/en/stages/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertMathematicsRoute =
  GaLeavingCertMathematicsRouteImport.update({
    id: '/ga/leaving-cert/mathematics',
    path: '/ga/leaving-cert/mathematics',
    getParentRoute: () => rootRouteImport,
  } as any)
const GaLeavingCertIrishRoute = GaLeavingCertIrishRouteImport.update({
  id: '/ga/leaving-cert/irish',
  path: '/ga/leaving-cert/irish',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertHistoryRoute = GaLeavingCertHistoryRouteImport.update({
  id: '/ga/leaving-cert/history',
  path: '/ga/leaving-cert/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertFrenchRoute = GaLeavingCertFrenchRouteImport.update({
  id: '/ga/leaving-cert/french',
  path: '/ga/leaving-cert/french',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertConstructionStudiesRoute =
  GaLeavingCertConstructionStudiesRouteImport.update({
    id: '/ga/leaving-cert/construction-studies',
    path: '/ga/leaving-cert/construction-studies',
    getParentRoute: () => rootRouteImport,
  } as any)
const GaLeavingCertBusinessRoute = GaLeavingCertBusinessRouteImport.update({
  id: '/ga/leaving-cert/business',
  path: '/ga/leaving-cert/business',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertBiologyRoute = GaLeavingCertBiologyRouteImport.update({
  id: '/ga/leaving-cert/biology',
  path: '/ga/leaving-cert/biology',
  getParentRoute: () => rootRouteImport,
} as any)
const GaCChar233imeannaCChar233imRoute =
  GaCChar233imeannaCChar233imRouteImport.update({
    id: '/ga/céimeanna/$céim',
    path: '/ga/céimeanna/$céim',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnSubjectsSlugRoute = EnSubjectsSlugRouteImport.update({
  id: '/en/subjects/$slug',
  path: '/en/subjects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStagesStageRoute = EnStagesStageRouteImport.update({
  id: '/en/stages/$stage',
  path: '/en/stages/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPracticeSubjectRoute = EnPracticeSubjectRouteImport.update({
  id: '/en/practice/$subject',
  path: '/en/practice/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPastPapersSubjectRoute = EnPastPapersSubjectRouteImport.update({
  id: '/en/past-papers/$subject',
  path: '/en/past-papers/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMarkingSchemesSubjectRoute = EnMarkingSchemesSubjectRouteImport.update({
  id: '/en/marking-schemes/$subject',
  path: '/en/marking-schemes/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertMathematicsRoute =
  EnLeavingCertMathematicsRouteImport.update({
    id: '/en/leaving-cert/mathematics',
    path: '/en/leaving-cert/mathematics',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnLeavingCertIrishRoute = EnLeavingCertIrishRouteImport.update({
  id: '/en/leaving-cert/irish',
  path: '/en/leaving-cert/irish',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertHistoryRoute = EnLeavingCertHistoryRouteImport.update({
  id: '/en/leaving-cert/history',
  path: '/en/leaving-cert/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertFrenchRoute = EnLeavingCertFrenchRouteImport.update({
  id: '/en/leaving-cert/french',
  path: '/en/leaving-cert/french',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertConstructionStudiesRoute =
  EnLeavingCertConstructionStudiesRouteImport.update({
    id: '/en/leaving-cert/construction-studies',
    path: '/en/leaving-cert/construction-studies',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnLeavingCertBusinessRoute = EnLeavingCertBusinessRouteImport.update({
  id: '/en/leaving-cert/business',
  path: '/en/leaving-cert/business',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertBiologyRoute = EnLeavingCertBiologyRouteImport.update({
  id: '/en/leaving-cert/biology',
  path: '/en/leaving-cert/biology',
  getParentRoute: () => rootRouteImport,
} as any)
const EnExaminerReportsSubjectRoute =
  EnExaminerReportsSubjectRouteImport.update({
    id: '/en/examiner-reports/$subject',
    path: '/en/examiner-reports/$subject',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnDashboardsStageRoute = EnDashboardsStageRouteImport.update({
  id: '/en/dashboards/$stage',
  path: '/en/dashboards/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAdminComponentsRoute = EnAdminComponentsRouteImport.update({
  id: '/en/admin/components',
  path: '/en/admin/components',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof En_layoutRoute
  '/en/about': typeof EnAboutRoute
  '/en/matriculation-auditor': typeof EnMatriculationAuditorRoute
  '/en/points-calculator': typeof EnPointsCalculatorRoute
  '/ga': typeof Ga_layoutRoute
  '/en/admin/components': typeof EnAdminComponentsRoute
  '/en/dashboards/$stage': typeof EnDashboardsStageRoute
  '/en/examiner-reports/$subject': typeof EnExaminerReportsSubjectRoute
  '/en/leaving-cert/biology': typeof EnLeavingCertBiologyRoute
  '/en/leaving-cert/business': typeof EnLeavingCertBusinessRoute
  '/en/leaving-cert/construction-studies': typeof EnLeavingCertConstructionStudiesRoute
  '/en/leaving-cert/french': typeof EnLeavingCertFrenchRoute
  '/en/leaving-cert/history': typeof EnLeavingCertHistoryRoute
  '/en/leaving-cert/irish': typeof EnLeavingCertIrishRoute
  '/en/leaving-cert/mathematics': typeof EnLeavingCertMathematicsRoute
  '/en/marking-schemes/$subject': typeof EnMarkingSchemesSubjectRoute
  '/en/past-papers/$subject': typeof EnPastPapersSubjectRoute
  '/en/practice/$subject': typeof EnPracticeSubjectRoute
  '/en/stages/$stage': typeof EnStagesStageRoute
  '/en/subjects/$slug': typeof EnSubjectsSlugRoute
  '/ga/céimeanna/$céim': typeof GaCChar233imeannaCChar233imRoute
  '/ga/leaving-cert/biology': typeof GaLeavingCertBiologyRoute
  '/ga/leaving-cert/business': typeof GaLeavingCertBusinessRoute
  '/ga/leaving-cert/construction-studies': typeof GaLeavingCertConstructionStudiesRoute
  '/ga/leaving-cert/french': typeof GaLeavingCertFrenchRoute
  '/ga/leaving-cert/history': typeof GaLeavingCertHistoryRoute
  '/ga/leaving-cert/irish': typeof GaLeavingCertIrishRoute
  '/ga/leaving-cert/mathematics': typeof GaLeavingCertMathematicsRoute
  '/en/stages/': typeof EnStagesIndexRoute
  '/ga/céimeanna/': typeof GaCChar233imeannaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof En_layoutRoute
  '/en/about': typeof EnAboutRoute
  '/en/matriculation-auditor': typeof EnMatriculationAuditorRoute
  '/en/points-calculator': typeof EnPointsCalculatorRoute
  '/ga': typeof Ga_layoutRoute
  '/en/admin/components': typeof EnAdminComponentsRoute
  '/en/dashboards/$stage': typeof EnDashboardsStageRoute
  '/en/examiner-reports/$subject': typeof EnExaminerReportsSubjectRoute
  '/en/leaving-cert/biology': typeof EnLeavingCertBiologyRoute
  '/en/leaving-cert/business': typeof EnLeavingCertBusinessRoute
  '/en/leaving-cert/construction-studies': typeof EnLeavingCertConstructionStudiesRoute
  '/en/leaving-cert/french': typeof EnLeavingCertFrenchRoute
  '/en/leaving-cert/history': typeof EnLeavingCertHistoryRoute
  '/en/leaving-cert/irish': typeof EnLeavingCertIrishRoute
  '/en/leaving-cert/mathematics': typeof EnLeavingCertMathematicsRoute
  '/en/marking-schemes/$subject': typeof EnMarkingSchemesSubjectRoute
  '/en/past-papers/$subject': typeof EnPastPapersSubjectRoute
  '/en/practice/$subject': typeof EnPracticeSubjectRoute
  '/en/stages/$stage': typeof EnStagesStageRoute
  '/en/subjects/$slug': typeof EnSubjectsSlugRoute
  '/ga/céimeanna/$céim': typeof GaCChar233imeannaCChar233imRoute
  '/ga/leaving-cert/biology': typeof GaLeavingCertBiologyRoute
  '/ga/leaving-cert/business': typeof GaLeavingCertBusinessRoute
  '/ga/leaving-cert/construction-studies': typeof GaLeavingCertConstructionStudiesRoute
  '/ga/leaving-cert/french': typeof GaLeavingCertFrenchRoute
  '/ga/leaving-cert/history': typeof GaLeavingCertHistoryRoute
  '/ga/leaving-cert/irish': typeof GaLeavingCertIrishRoute
  '/ga/leaving-cert/mathematics': typeof GaLeavingCertMathematicsRoute
  '/en/stages': typeof EnStagesIndexRoute
  '/ga/céimeanna': typeof GaCChar233imeannaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en/__layout': typeof En_layoutRoute
  '/en/about': typeof EnAboutRoute
  '/en/matriculation-auditor': typeof EnMatriculationAuditorRoute
  '/en/points-calculator': typeof EnPointsCalculatorRoute
  '/ga/__layout': typeof Ga_layoutRoute
  '/en/admin/components': typeof EnAdminComponentsRoute
  '/en/dashboards/$stage': typeof EnDashboardsStageRoute
  '/en/examiner-reports/$subject': typeof EnExaminerReportsSubjectRoute
  '/en/leaving-cert/biology': typeof EnLeavingCertBiologyRoute
  '/en/leaving-cert/business': typeof EnLeavingCertBusinessRoute
  '/en/leaving-cert/construction-studies': typeof EnLeavingCertConstructionStudiesRoute
  '/en/leaving-cert/french': typeof EnLeavingCertFrenchRoute
  '/en/leaving-cert/history': typeof EnLeavingCertHistoryRoute
  '/en/leaving-cert/irish': typeof EnLeavingCertIrishRoute
  '/en/leaving-cert/mathematics': typeof EnLeavingCertMathematicsRoute
  '/en/marking-schemes/$subject': typeof EnMarkingSchemesSubjectRoute
  '/en/past-papers/$subject': typeof EnPastPapersSubjectRoute
  '/en/practice/$subject': typeof EnPracticeSubjectRoute
  '/en/stages/$stage': typeof EnStagesStageRoute
  '/en/subjects/$slug': typeof EnSubjectsSlugRoute
  '/ga/céimeanna/$céim': typeof GaCChar233imeannaCChar233imRoute
  '/ga/leaving-cert/biology': typeof GaLeavingCertBiologyRoute
  '/ga/leaving-cert/business': typeof GaLeavingCertBusinessRoute
  '/ga/leaving-cert/construction-studies': typeof GaLeavingCertConstructionStudiesRoute
  '/ga/leaving-cert/french': typeof GaLeavingCertFrenchRoute
  '/ga/leaving-cert/history': typeof GaLeavingCertHistoryRoute
  '/ga/leaving-cert/irish': typeof GaLeavingCertIrishRoute
  '/ga/leaving-cert/mathematics': typeof GaLeavingCertMathematicsRoute
  '/en/stages/': typeof EnStagesIndexRoute
  '/ga/céimeanna/': typeof GaCChar233imeannaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/en/about'
    | '/en/matriculation-auditor'
    | '/en/points-calculator'
    | '/ga'
    | '/en/admin/components'
    | '/en/dashboards/$stage'
    | '/en/examiner-reports/$subject'
    | '/en/leaving-cert/biology'
    | '/en/leaving-cert/business'
    | '/en/leaving-cert/construction-studies'
    | '/en/leaving-cert/french'
    | '/en/leaving-cert/history'
    | '/en/leaving-cert/irish'
    | '/en/leaving-cert/mathematics'
    | '/en/marking-schemes/$subject'
    | '/en/past-papers/$subject'
    | '/en/practice/$subject'
    | '/en/stages/$stage'
    | '/en/subjects/$slug'
    | '/ga/céimeanna/$céim'
    | '/ga/leaving-cert/biology'
    | '/ga/leaving-cert/business'
    | '/ga/leaving-cert/construction-studies'
    | '/ga/leaving-cert/french'
    | '/ga/leaving-cert/history'
    | '/ga/leaving-cert/irish'
    | '/ga/leaving-cert/mathematics'
    | '/en/stages/'
    | '/ga/céimeanna/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/en/about'
    | '/en/matriculation-auditor'
    | '/en/points-calculator'
    | '/ga'
    | '/en/admin/components'
    | '/en/dashboards/$stage'
    | '/en/examiner-reports/$subject'
    | '/en/leaving-cert/biology'
    | '/en/leaving-cert/business'
    | '/en/leaving-cert/construction-studies'
    | '/en/leaving-cert/french'
    | '/en/leaving-cert/history'
    | '/en/leaving-cert/irish'
    | '/en/leaving-cert/mathematics'
    | '/en/marking-schemes/$subject'
    | '/en/past-papers/$subject'
    | '/en/practice/$subject'
    | '/en/stages/$stage'
    | '/en/subjects/$slug'
    | '/ga/céimeanna/$céim'
    | '/ga/leaving-cert/biology'
    | '/ga/leaving-cert/business'
    | '/ga/leaving-cert/construction-studies'
    | '/ga/leaving-cert/french'
    | '/ga/leaving-cert/history'
    | '/ga/leaving-cert/irish'
    | '/ga/leaving-cert/mathematics'
    | '/en/stages'
    | '/ga/céimeanna'
  id:
    | '__root__'
    | '/'
    | '/en/__layout'
    | '/en/about'
    | '/en/matriculation-auditor'
    | '/en/points-calculator'
    | '/ga/__layout'
    | '/en/admin/components'
    | '/en/dashboards/$stage'
    | '/en/examiner-reports/$subject'
    | '/en/leaving-cert/biology'
    | '/en/leaving-cert/business'
    | '/en/leaving-cert/construction-studies'
    | '/en/leaving-cert/french'
    | '/en/leaving-cert/history'
    | '/en/leaving-cert/irish'
    | '/en/leaving-cert/mathematics'
    | '/en/marking-schemes/$subject'
    | '/en/past-papers/$subject'
    | '/en/practice/$subject'
    | '/en/stages/$stage'
    | '/en/subjects/$slug'
    | '/ga/céimeanna/$céim'
    | '/ga/leaving-cert/biology'
    | '/ga/leaving-cert/business'
    | '/ga/leaving-cert/construction-studies'
    | '/ga/leaving-cert/french'
    | '/ga/leaving-cert/history'
    | '/ga/leaving-cert/irish'
    | '/ga/leaving-cert/mathematics'
    | '/en/stages/'
    | '/ga/céimeanna/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  En_layoutRoute: typeof En_layoutRoute
  EnAboutRoute: typeof EnAboutRoute
  EnMatriculationAuditorRoute: typeof EnMatriculationAuditorRoute
  EnPointsCalculatorRoute: typeof EnPointsCalculatorRoute
  Ga_layoutRoute: typeof Ga_layoutRoute
  EnAdminComponentsRoute: typeof EnAdminComponentsRoute
  EnDashboardsStageRoute: typeof EnDashboardsStageRoute
  EnExaminerReportsSubjectRoute: typeof EnExaminerReportsSubjectRoute
  EnLeavingCertBiologyRoute: typeof EnLeavingCertBiologyRoute
  EnLeavingCertBusinessRoute: typeof EnLeavingCertBusinessRoute
  EnLeavingCertConstructionStudiesRoute: typeof EnLeavingCertConstructionStudiesRoute
  EnLeavingCertFrenchRoute: typeof EnLeavingCertFrenchRoute
  EnLeavingCertHistoryRoute: typeof EnLeavingCertHistoryRoute
  EnLeavingCertIrishRoute: typeof EnLeavingCertIrishRoute
  EnLeavingCertMathematicsRoute: typeof EnLeavingCertMathematicsRoute
  EnMarkingSchemesSubjectRoute: typeof EnMarkingSchemesSubjectRoute
  EnPastPapersSubjectRoute: typeof EnPastPapersSubjectRoute
  EnPracticeSubjectRoute: typeof EnPracticeSubjectRoute
  EnStagesStageRoute: typeof EnStagesStageRoute
  EnSubjectsSlugRoute: typeof EnSubjectsSlugRoute
  GaCChar233imeannaCChar233imRoute: typeof GaCChar233imeannaCChar233imRoute
  GaLeavingCertBiologyRoute: typeof GaLeavingCertBiologyRoute
  GaLeavingCertBusinessRoute: typeof GaLeavingCertBusinessRoute
  GaLeavingCertConstructionStudiesRoute: typeof GaLeavingCertConstructionStudiesRoute
  GaLeavingCertFrenchRoute: typeof GaLeavingCertFrenchRoute
  GaLeavingCertHistoryRoute: typeof GaLeavingCertHistoryRoute
  GaLeavingCertIrishRoute: typeof GaLeavingCertIrishRoute
  GaLeavingCertMathematicsRoute: typeof GaLeavingCertMathematicsRoute
  EnStagesIndexRoute: typeof EnStagesIndexRoute
  GaCChar233imeannaIndexRoute: typeof GaCChar233imeannaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/__layout': {
      id: '/ga/__layout'
      path: '/ga'
      fullPath: '/ga'
      preLoaderRoute: typeof Ga_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/points-calculator': {
      id: '/en/points-calculator'
      path: '/en/points-calculator'
      fullPath: '/en/points-calculator'
      preLoaderRoute: typeof EnPointsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/matriculation-auditor': {
      id: '/en/matriculation-auditor'
      path: '/en/matriculation-auditor'
      fullPath: '/en/matriculation-auditor'
      preLoaderRoute: typeof EnMatriculationAuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/__layout': {
      id: '/en/__layout'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof En_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/céimeanna/': {
      id: '/ga/céimeanna/'
      path: '/ga/céimeanna'
      fullPath: '/ga/céimeanna/'
      preLoaderRoute: typeof GaCChar233imeannaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/stages/': {
      id: '/en/stages/'
      path: '/en/stages'
      fullPath: '/en/stages/'
      preLoaderRoute: typeof EnStagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/mathematics': {
      id: '/ga/leaving-cert/mathematics'
      path: '/ga/leaving-cert/mathematics'
      fullPath: '/ga/leaving-cert/mathematics'
      preLoaderRoute: typeof GaLeavingCertMathematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/irish': {
      id: '/ga/leaving-cert/irish'
      path: '/ga/leaving-cert/irish'
      fullPath: '/ga/leaving-cert/irish'
      preLoaderRoute: typeof GaLeavingCertIrishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/history': {
      id: '/ga/leaving-cert/history'
      path: '/ga/leaving-cert/history'
      fullPath: '/ga/leaving-cert/history'
      preLoaderRoute: typeof GaLeavingCertHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/french': {
      id: '/ga/leaving-cert/french'
      path: '/ga/leaving-cert/french'
      fullPath: '/ga/leaving-cert/french'
      preLoaderRoute: typeof GaLeavingCertFrenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/construction-studies': {
      id: '/ga/leaving-cert/construction-studies'
      path: '/ga/leaving-cert/construction-studies'
      fullPath: '/ga/leaving-cert/construction-studies'
      preLoaderRoute: typeof GaLeavingCertConstructionStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/business': {
      id: '/ga/leaving-cert/business'
      path: '/ga/leaving-cert/business'
      fullPath: '/ga/leaving-cert/business'
      preLoaderRoute: typeof GaLeavingCertBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/biology': {
      id: '/ga/leaving-cert/biology'
      path: '/ga/leaving-cert/biology'
      fullPath: '/ga/leaving-cert/biology'
      preLoaderRoute: typeof GaLeavingCertBiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/céimeanna/$céim': {
      id: '/ga/céimeanna/$céim'
      path: '/ga/céimeanna/$céim'
      fullPath: '/ga/céimeanna/$céim'
      preLoaderRoute: typeof GaCChar233imeannaCChar233imRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/subjects/$slug': {
      id: '/en/subjects/$slug'
      path: '/en/subjects/$slug'
      fullPath: '/en/subjects/$slug'
      preLoaderRoute: typeof EnSubjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/stages/$stage': {
      id: '/en/stages/$stage'
      path: '/en/stages/$stage'
      fullPath: '/en/stages/$stage'
      preLoaderRoute: typeof EnStagesStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/practice/$subject': {
      id: '/en/practice/$subject'
      path: '/en/practice/$subject'
      fullPath: '/en/practice/$subject'
      preLoaderRoute: typeof EnPracticeSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/past-papers/$subject': {
      id: '/en/past-papers/$subject'
      path: '/en/past-papers/$subject'
      fullPath: '/en/past-papers/$subject'
      preLoaderRoute: typeof EnPastPapersSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/marking-schemes/$subject': {
      id: '/en/marking-schemes/$subject'
      path: '/en/marking-schemes/$subject'
      fullPath: '/en/marking-schemes/$subject'
      preLoaderRoute: typeof EnMarkingSchemesSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/mathematics': {
      id: '/en/leaving-cert/mathematics'
      path: '/en/leaving-cert/mathematics'
      fullPath: '/en/leaving-cert/mathematics'
      preLoaderRoute: typeof EnLeavingCertMathematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/irish': {
      id: '/en/leaving-cert/irish'
      path: '/en/leaving-cert/irish'
      fullPath: '/en/leaving-cert/irish'
      preLoaderRoute: typeof EnLeavingCertIrishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/history': {
      id: '/en/leaving-cert/history'
      path: '/en/leaving-cert/history'
      fullPath: '/en/leaving-cert/history'
      preLoaderRoute: typeof EnLeavingCertHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/french': {
      id: '/en/leaving-cert/french'
      path: '/en/leaving-cert/french'
      fullPath: '/en/leaving-cert/french'
      preLoaderRoute: typeof EnLeavingCertFrenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/construction-studies': {
      id: '/en/leaving-cert/construction-studies'
      path: '/en/leaving-cert/construction-studies'
      fullPath: '/en/leaving-cert/construction-studies'
      preLoaderRoute: typeof EnLeavingCertConstructionStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/business': {
      id: '/en/leaving-cert/business'
      path: '/en/leaving-cert/business'
      fullPath: '/en/leaving-cert/business'
      preLoaderRoute: typeof EnLeavingCertBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/biology': {
      id: '/en/leaving-cert/biology'
      path: '/en/leaving-cert/biology'
      fullPath: '/en/leaving-cert/biology'
      preLoaderRoute: typeof EnLeavingCertBiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/examiner-reports/$subject': {
      id: '/en/examiner-reports/$subject'
      path: '/en/examiner-reports/$subject'
      fullPath: '/en/examiner-reports/$subject'
      preLoaderRoute: typeof EnExaminerReportsSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/dashboards/$stage': {
      id: '/en/dashboards/$stage'
      path: '/en/dashboards/$stage'
      fullPath: '/en/dashboards/$stage'
      preLoaderRoute: typeof EnDashboardsStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/admin/components': {
      id: '/en/admin/components'
      path: '/en/admin/components'
      fullPath: '/en/admin/components'
      preLoaderRoute: typeof EnAdminComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  En_layoutRoute: En_layoutRoute,
  EnAboutRoute: EnAboutRoute,
  EnMatriculationAuditorRoute: EnMatriculationAuditorRoute,
  EnPointsCalculatorRoute: EnPointsCalculatorRoute,
  Ga_layoutRoute: Ga_layoutRoute,
  EnAdminComponentsRoute: EnAdminComponentsRoute,
  EnDashboardsStageRoute: EnDashboardsStageRoute,
  EnExaminerReportsSubjectRoute: EnExaminerReportsSubjectRoute,
  EnLeavingCertBiologyRoute: EnLeavingCertBiologyRoute,
  EnLeavingCertBusinessRoute: EnLeavingCertBusinessRoute,
  EnLeavingCertConstructionStudiesRoute: EnLeavingCertConstructionStudiesRoute,
  EnLeavingCertFrenchRoute: EnLeavingCertFrenchRoute,
  EnLeavingCertHistoryRoute: EnLeavingCertHistoryRoute,
  EnLeavingCertIrishRoute: EnLeavingCertIrishRoute,
  EnLeavingCertMathematicsRoute: EnLeavingCertMathematicsRoute,
  EnMarkingSchemesSubjectRoute: EnMarkingSchemesSubjectRoute,
  EnPastPapersSubjectRoute: EnPastPapersSubjectRoute,
  EnPracticeSubjectRoute: EnPracticeSubjectRoute,
  EnStagesStageRoute: EnStagesStageRoute,
  EnSubjectsSlugRoute: EnSubjectsSlugRoute,
  GaCChar233imeannaCChar233imRoute: GaCChar233imeannaCChar233imRoute,
  GaLeavingCertBiologyRoute: GaLeavingCertBiologyRoute,
  GaLeavingCertBusinessRoute: GaLeavingCertBusinessRoute,
  GaLeavingCertConstructionStudiesRoute: GaLeavingCertConstructionStudiesRoute,
  GaLeavingCertFrenchRoute: GaLeavingCertFrenchRoute,
  GaLeavingCertHistoryRoute: GaLeavingCertHistoryRoute,
  GaLeavingCertIrishRoute: GaLeavingCertIrishRoute,
  GaLeavingCertMathematicsRoute: GaLeavingCertMathematicsRoute,
  EnStagesIndexRoute: EnStagesIndexRoute,
  GaCChar233imeannaIndexRoute: GaCChar233imeannaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './app/router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
