#!/bin/bash
# =============================================================================
# SYNC BLUEPRINTS TO NEWT
# =============================================================================
# Combines all stack blueprints and syncs them to the Newt server.
#
# Usage:
#   ./scripts/sync-blueprints.sh                    # Sync all blueprints
#   ./scripts/sync-blueprints.sh --dry-run          # Show what would be synced
#   ./scripts/sync-blueprints.sh --list             # List available blueprints
#   ./scripts/sync-blueprints.sh langfuse cognee    # Sync specific stacks only
#
# Environment Variables:
#   NEWT_HOST       - SSH host for Newt server (default: ubuntu@132.145.27.89)
#   NEWT_DIR        - Blueprints directory on server (default: /opt/newt/blueprints)
#   TAISCE_DIR      - Local taisce directory (default: script parent)
# =============================================================================

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TAISCE_DIR="${TAISCE_DIR:-$(dirname "$SCRIPT_DIR")}"
STACKS_DIR="${TAISCE_DIR}/stacks"

NEWT_HOST="${NEWT_HOST:-ubuntu@132.145.27.89}"
NEWT_DIR="${NEWT_DIR:-/opt/newt/blueprints}"
COMBINED_FILE="/tmp/taisce-blueprints.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
DRY_RUN=0
LIST_ONLY=0
SELECTED_STACKS=()

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        --list)
            LIST_ONLY=1
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--dry-run] [--list] [stack1 stack2 ...]"
            echo ""
            echo "Options:"
            echo "  --dry-run   Show combined blueprint without syncing"
            echo "  --list      List available blueprints"
            echo "  stack...    Specific stacks to include (default: all)"
            exit 0
            ;;
        *)
            SELECTED_STACKS+=("$1")
            shift
            ;;
    esac
done

# List blueprints
if [ "$LIST_ONLY" = "1" ]; then
    echo -e "${BLUE}Available blueprints:${NC}"
    echo ""
    for stack_dir in "$STACKS_DIR"/*/; do
        stack_name=$(basename "$stack_dir")
        blueprint_file="${stack_dir}blueprint.yaml"
        if [ -f "$blueprint_file" ]; then
            # Check if blueprint has resources
            if grep -q "public-resources:" "$blueprint_file" 2>/dev/null; then
                echo -e "  ${GREEN}${stack_name}${NC}"
                # Show domains
                grep "full-domain:" "$blueprint_file" 2>/dev/null | sed 's/.*full-domain: *"\(.*\)"/    → \1/' || true
            else
                echo -e "  ${YELLOW}${stack_name}${NC} (no public resources)"
            fi
        fi
    done
    exit 0
fi

# Build combined blueprint
echo -e "${BLUE}Building combined blueprint...${NC}"
echo ""

cat > "$COMBINED_FILE" << 'EOF'
# =============================================================================
# TAISCE - Combined Pangolin Blueprints
# =============================================================================
# Auto-generated by sync-blueprints.sh
# DO NOT EDIT MANUALLY - changes will be overwritten
#
# Source: croí/taisce/stacks/*/blueprint.yaml
# =============================================================================

public-resources:
EOF

STACK_COUNT=0
for stack_dir in "$STACKS_DIR"/*/; do
    stack_name=$(basename "$stack_dir")
    blueprint_file="${stack_dir}blueprint.yaml"

    # Skip if not in selected stacks (when specified)
    if [ ${#SELECTED_STACKS[@]} -gt 0 ]; then
        if [[ ! " ${SELECTED_STACKS[*]} " =~ " ${stack_name} " ]]; then
            continue
        fi
    fi

    if [ -f "$blueprint_file" ]; then
        # Check if blueprint has public-resources
        if grep -q "public-resources:" "$blueprint_file" 2>/dev/null; then
            echo -e "  Adding: ${GREEN}${stack_name}${NC}"

            # Extract content under public-resources and indent
            echo "" >> "$COMBINED_FILE"
            echo "  # --- ${stack_name} ---" >> "$COMBINED_FILE"

            # Use awk to extract content after public-resources:
            awk '/^public-resources:/{found=1; next} found{print}' "$blueprint_file" >> "$COMBINED_FILE"

            ((STACK_COUNT++))
        else
            echo -e "  Skipping: ${YELLOW}${stack_name}${NC} (no public resources)"
        fi
    fi
done

echo ""
echo -e "${GREEN}Combined ${STACK_COUNT} blueprints${NC}"

# Dry run - just show the file
if [ "$DRY_RUN" = "1" ]; then
    echo ""
    echo -e "${BLUE}Combined blueprint (dry-run):${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    cat "$COMBINED_FILE"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    exit 0
fi

# Sync to server
echo ""
echo -e "${BLUE}Syncing to Newt server...${NC}"
echo "  Host: ${NEWT_HOST}"
echo "  Path: ${NEWT_DIR}/taisce.yaml"
echo ""

# Create directory if needed and copy file
ssh "$NEWT_HOST" "mkdir -p $NEWT_DIR"
scp "$COMBINED_FILE" "${NEWT_HOST}:${NEWT_DIR}/taisce.yaml"

echo -e "${GREEN}Blueprints synced successfully!${NC}"
echo ""

# Optionally restart Newt
read -p "Restart Newt to apply changes? [y/N] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}Restarting Newt...${NC}"
    ssh "$NEWT_HOST" "cd /opt/newt && docker compose restart"
    echo -e "${GREEN}Newt restarted!${NC}"
fi

# Cleanup
rm -f "$COMBINED_FILE"

echo ""
echo -e "${GREEN}Done!${NC}"
