#!/usr/bin/env python3
"""Generate lakehouse .env.dev from Infisical vault."""
import json
import os
import urllib.parse
import urllib.request


TOKEN = os.environ.get("INFISICAL_TOKEN", "")
PROJECT_ID = os.environ.get("INFISICAL_PROJECT_ID", "")
CLIENT_ID = os.environ.get("INFISICAL_LOCKET_CLIENT_ID", "")
CLIENT_SECRET = os.environ.get("INFISICAL_LOCKET_CLIENT_SECRET", "")
API_URL = os.environ.get("INFISICAL_API_URL", "http://localhost:8081/api")
ENV_PATH = "/Users/cianmacandeisigh/dev/kings_college_galway/bonneagar/stacks/lakehouse/.env.dev"


def get_access_token():
    req = urllib.request.Request(
        f"{API_URL}/v1/auth/universal-auth/login",
        data=json.dumps({"clientId": CLIENT_ID, "clientSecret": CLIENT_SECRET}).encode(),
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())["accessToken"]


def get_secret(token, path, key):
    url = f"{API_URL}/v3/secrets/raw/{urllib.parse.quote(key)}?workspaceId={PROJECT_ID}&environment=dev&secretPath=/{path}"
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())["secret"]["secretValue"]


def main():
    if not all([TOKEN, PROJECT_ID, CLIENT_ID, CLIENT_SECRET]):
        print("ERROR: source the infisical bootstrap file first", file=__import__('sys').stderr)
        __import__('sys').exit(1)

    # Prefer UA login (machine identity) over the bootstrap admin token
    token = get_access_token()
    print(f"[ok] UA access token: {token[:60]}...")

    pairs = [
        ("POSTGRES_USER", "lakekeeper", "literal"),
        ("POSTGRES_PASSWORD", ("lakehouse", "postgres_password"), "infisical"),
        ("POSTGRES_DB", "lakekeeper", "literal"),
        ("CLICKHOUSE_USER", ("lakehouse-clickhouse", "user"), "infisical"),
        ("CLICKHOUSE_PASSWORD", ("lakehouse-clickhouse", "password"), "infisical"),
        ("CLICKHOUSE_DB", ("lakehouse-clickhouse", "db"), "infisical"),
        ("REDIS_PASSWORD", ("lakehouse-redis", "password"), "infisical"),
        ("REDIS_MAXMEMORY_POLICY", "allkeys-lru", "literal"),
        ("GARAGE_RPC_SECRET", ("lakehouse", "rpc_secret"), "infisical"),
        ("GARAGE_ADMIN_TOKEN", ("lakehouse", "admin_token"), "infisical"),
        ("GARAGE_ACCESS_KEY_ID", ("lakehouse-garage", "access_key_id"), "infisical"),
        ("GARAGE_SECRET_ACCESS_KEY", ("lakehouse-garage", "secret_access_key"), "infisical"),
        ("LAKEKEEPER_ENCRYPTION_KEY", ("lakehouse", "encryption_key"), "infisical"),
        ("LAKEKEEPER_SSL_MODE", "prefer", "literal"),
        ("NIMTABLE_JDBC_PASSWORD", ("lakehouse", "jdbc_password"), "infisical"),
        ("NIMTABLE_DASHBOARD_SECRET", ("lakehouse", "dashboard_secret"), "infisical"),
        ("OLAKE_JDBC_PASSWORD", ("lakehouse", "jdbc_password"), "infisical"),
        ("OLAKE_SOURCE_PG_PASSWORD", ("lakehouse", "source_pg_password"), "infisical"),
        ("OLAKE_WRITER_S3_SECRET_KEY", ("lakehouse", "writer_s3_secret_key"), "infisical"),
        ("LANCEDB_VIEWER_ADMIN_TOKEN", ("lakehouse", "lancedb_viewer_admin_token"), "infisical"),
    ]

    lines = [
        "# Generated by generate-lakehouse-env.py from dev-baile/dev (Infisical)",
        "# All secrets pulled via Universal Auth (bunchloch-locket-machine identity)",
        "",
    ]

    for env_name, value, kind in pairs:
        if kind == "literal":
            lines.append(f"{env_name}={value}")
        else:
            path, key = value
            secret = get_secret(token, path, key)
            lines.append(f"{env_name}={secret}")
            print(f"[ok] {env_name} = {secret[:8]}... ({len(secret)} chars)")

    with open(ENV_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(ENV_PATH, 0o600)
    print(f"\n[ok] wrote {ENV_PATH}")


if __name__ == "__main__":
    main()