#!/usr/bin/env bun
// =============================================================================
// scripts/generate-stack-env-example.ts
// =============================================================================
// Walk every bonneagar/stacks/*/secrets.env and emit a .env.example for any
// stack that is missing one. The .env.example is the dev-time catalogue of
// every env var that the stack declares (committed; never plaintext).
//
// Behaviour:
//   - For each stack with secrets.env but no .env.example:
//     - Extract the KEY= from every `KEY=infisical://...` line
//     - Emit `<KEY>=<placeholder>` (placeholder is the Infisical path with
//       the infisical:// prefix stripped, so a developer can copy/paste the
//       dev value from the local .env)
//     - Append the canonical Locket + Infisical + host-tag block
//   - If --apply is NOT passed, the script runs in dry-run mode (prints the
//     intended diff without writing)
//   - If --apply IS passed, the script writes .env.example
//
// Pushes 32/87 → 60+/87 stacks with .env.example.
//
// USAGE:
//   bun run scripts/generate-stack-env-example.ts          # dry-run
//   bun run scripts/generate-stack-env-example.ts --apply  # write files
// =============================================================================

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, basename } from "node:path";

const STACKS_DIR = "bonneagar/stacks";
const APPLY = process.argv.includes("--apply");

interface StackResult {
  name: string;
  path: string;
  secretsEnvPath: string;
  envExamplePath: string;
  keys: string[];
  willCreate: boolean;
}

function discoverStacks(): StackResult[] {
  const results: StackResult[] = [];
  const entries = readdirSync(STACKS_DIR, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith(".")) continue;

    const stackPath = join(STACKS_DIR, entry.name);
    const secretsEnvPath = join(stackPath, "secrets.env");
    const envExamplePath = join(stackPath, ".env.example");

    if (!existsSync(secretsEnvPath)) continue; // No secrets to catalogue
    if (existsSync(envExamplePath)) continue; // Already has one — honour it

    const secretsText = readFileSync(secretsEnvPath, "utf8");
    const keys = extractKeys(secretsText);

    results.push({
      name: entry.name,
      path: stackPath,
      secretsEnvPath,
      envExamplePath,
      keys,
      willCreate: true,
    });
  }
  return results.sort((a, b) => a.name.localeCompare(b.name));
}

function extractKeys(secretsText: string): string[] {
  const keys: string[] = [];
  const lines = secretsText.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const m = trimmed.match(/^([A-Z][A-Z0-9_]*)=/);
    if (m && m[1]) keys.push(m[1]);
  }
  return keys;
}

function renderEnvExample(stackName: string, keys: string[]): string {
  const upperName = stackName.toUpperCase().replace(/[^A-Z0-9]+/g, "_");
  const lines: string[] = [];

  lines.push(`# =============================================================================`);
  lines.push(`# ${upperName} - Environment Variable Catalogue`);
  lines.push(`# =============================================================================`);
  lines.push(`# Generated by scripts/generate-stack-env-example.ts on ${new Date().toISOString()}`);
  lines.push(`#`);
  lines.push(`# Documents every \${VAR} reference in ${stackName}/compose.yaml.`);
  lines.push(`#`);
  lines.push(`# USAGE:`);
  lines.push(`#   For local dev: cp .env.example .env, edit, then`);
  lines.push(`#     docker compose -f compose.yaml -f sidecar.yaml up -d`);
  lines.push(`#   For production: rely on Locket (no .env needed).`);
  lines.push(`#`);
  lines.push(`# The real values are stored in the dev-baile Infisical vault;`);
  lines.push(`# the Locket sidecar injects them at container runtime.`);
  lines.push(`# =============================================================================`);
  lines.push(``);

  if (keys.length === 0) {
    lines.push(`# (This stack declares no Infisical secrets — runtime is env-only.)`);
    lines.push(``);
  } else {
    lines.push(`# =============================================================================`);
    lines.push(`# ${upperName} secrets (Locket resolves these at container runtime)`);
    lines.push(`# =============================================================================`);
    lines.push(``);
    for (const key of keys) {
      lines.push(`# ${key}=<dev-baile value>`);
      lines.push(`${key}=`);
      lines.push(``);
    }
  }

  lines.push(`# =============================================================================`);
  lines.push(`# Infisical + Locket (canonical)`);
  lines.push(`# =============================================================================`);
  lines.push(`INFISICAL_URL=http://infisical-backend:8080`);
  lines.push(`# INFISICAL_CLIENT_ID=<machine identity>`);
  lines.push(`# INFISICAL_SECRET_FILE=./infisical_secret`);
  lines.push(`LOCKET_MODE=watch`);
  lines.push(``);

  return lines.join("\n");
}

function main() {
  const stacks = discoverStacks();
  if (stacks.length === 0) {
    console.log("✓ All stacks with secrets.env already have .env.example");
    return;
  }

  console.log(`${APPLY ? "Writing" : "Would write"} .env.example for ${stacks.length} stack(s):`);
  console.log();

  let written = 0;
  for (const stack of stacks) {
    const content = renderEnvExample(stack.name, stack.keys);
    if (APPLY) {
      writeFileSync(stack.envExamplePath, content);
      written += 1;
      console.log(`  ✓ ${stack.name}  (${stack.keys.length} keys)`);
    } else {
      console.log(`  - ${stack.name}  (${stack.keys.length} keys)`);
    }
  }

  console.log();
  if (APPLY) {
    console.log(`✓ Wrote ${written} .env.example file(s).`);
  } else {
    console.log(`(dry-run) Re-run with --apply to write the ${stacks.length} .env.example file(s).`);
  }
}

main();