#!/usr/bin/env bun
// =============================================================================
// scripts/generate-komodo-stacks.ts
// =============================================================================
// Walk every bonneagar/stacks/*/compose.yaml and emit a
// komodo/stacks/<name>-<host>.toml from the 6-file contract. Hosts come from
// the labels on the compose.yaml services (defaults to "bunchloch").
//
// Behaviour:
//   - For each stack with compose.yaml but no matching komodo/stacks/*.toml:
//     - Read compose.yaml to find:
//       - The host tag (from `labels.host:*` if present, else "bunchloch")
//       - The infisical:// secrets (from secrets.env)
//       - The Pangolin routes (from pangolin.yaml)
//     - Emit a toml file matching the canonical komodo stack shape:
//       [[stack]] / name / description / tags / [stack.config] /
//       server_id / run_directory / file_paths / environment / [stack.stats]
//   - Skip if the matching komodo/stacks/<name>-<host>.toml already exists
//   - If --apply is NOT passed, runs in dry-run mode
//
// Generates for the 57 missing stacks (current: 30 hand-curated + 57 generated
// = 87). After pick-5b drops stack count to 86, regenerates for the missing
// entries.
//
// USAGE:
//   bun run scripts/generate-komodo-stacks.ts          # dry-run
//   bun run scripts/generate-komodo-stacks.ts --apply  # write files
// =============================================================================

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const STACKS_DIR = "bonneagar/stacks";
const KOMODO_DIR = "bonneagar/komodo/stacks";
const APPLY = process.argv.includes("--apply");

interface StackResult {
  name: string;
  composePath: string;
  host: string;
  secretsEnvKeys: string[];
  komodoPath: string;
  willCreate: boolean;
}

function discoverStacks(): StackResult[] {
  const results: StackResult[] = [];
  const entries = readdirSync(STACKS_DIR, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith(".")) continue;

    const stackPath = join(STACKS_DIR, entry.name);
    const composePath = join(stackPath, "compose.yaml");
    if (!existsSync(composePath)) continue;

    const composeText = readFileSync(composePath, "utf8");
    const host = extractHost(composeText);

    const komodoPath = join(KOMODO_DIR, `${entry.name}-${host}.toml`);
    if (existsSync(komodoPath)) continue; // already exists

    const secretsEnvPath = join(stackPath, "secrets.env");
    const secretsEnvKeys: string[] = [];
    if (existsSync(secretsEnvPath)) {
      const secretsText = readFileSync(secretsEnvPath, "utf8");
      secretsEnvKeys.push(...extractKeys(secretsText));
    }

    results.push({
      name: entry.name,
      composePath,
      host,
      secretsEnvKeys,
      komodoPath,
      willCreate: true,
    });
  }
  return results.sort((a, b) => a.name.localeCompare(b.name));
}

function extractHost(composeText: string): string {
  // Look for `host:<x>` in the compose text (labels or top-level).
  // The retired Hetzner host is no longer accepted; remaining hosts
  // are arm1-oci (control plane) and bunchloch (workload).
  const m = composeText.match(/host:(bunchloch|arm1-oci)/);
  return m ? m[1] : "bunchloch";
}

function extractKeys(secretsText: string): string[] {
  const keys: string[] = [];
  const lines = secretsText.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const m = trimmed.match(/^([A-Z][A-Z0-9_]*)=infisical:\/\//);
    if (m && m[1]) keys.push(m[1]);
  }
  return keys;
}

function renderToml(stack: StackResult): string {
  const lines: string[] = [];
  lines.push(`# =============================================================================`);
  lines.push(`# ${stack.name.toUpperCase()}-${stack.host.toUpperCase()} — auto-generated komodo stack`);
  lines.push(`# =============================================================================`);
  lines.push(`# Generated by scripts/generate-komodo-stacks.ts on ${new Date().toISOString()}`);
  lines.push(`#`);
  lines.push(`# Mirrors the 6-file GOLD_STANDARD contract from`);
  lines.push(`# bonneagar/stacks/${stack.name}/compose.yaml + sidecar.yaml + secrets.env`);
  lines.push(`# + pangolin.yaml + blueprint.yaml + .env.example.`);
  lines.push(`# Hand-curated komodo stacks live alongside this file at`);
  lines.push(`# bonneagar/komodo/stacks/<name>-<host>.toml (the 30-stack curated subset).`);
  lines.push(`#`);
  lines.push(`# Host: ${stack.host}`);
  lines.push(`# Secrets: ${stack.secretsEnvKeys.length} infisical:// refs resolved at runtime`);
  lines.push(`# =============================================================================`);
  lines.push(``);
  lines.push(`[[stack]]`);
  lines.push(`name = "${stack.name}-${stack.host}"`);
  lines.push(`description = "Bonneagar stack ${stack.name} on ${stack.host} (auto-generated from the 6-file GOLD_STANDARD contract at bonneagar/stacks/${stack.name}/)"`);
  lines.push(`tags = [`);
  lines.push(`  "host:${stack.host}",`);
  lines.push(`  "tier:application",`);
  lines.push(`  "type:auto-generated",`);
  lines.push(`  "stack:${stack.name}",`);
  lines.push(`]`);
  lines.push(``);
  lines.push(`[stack.config]`);
  lines.push(`server_id = "${stack.host}"`);
  lines.push(`run_directory = "/etc/komodo/${stack.name}"`);
  lines.push(`file_paths = [`);
  lines.push(`  "bonneagar/stacks/${stack.name}/compose.yaml",`);
  lines.push(`  "bonneagar/stacks/${stack.name}/sidecar.yaml",`);
  lines.push(`]`);
  if (stack.secretsEnvKeys.length > 0) {
    lines.push(`environment = """`);
    for (const key of stack.secretsEnvKeys) {
      lines.push(`${key}=infisical://dev-baile/${stack.name}/${key.toLowerCase()}`);
    }
    lines.push(`"""`);
  }
  lines.push(``);
  lines.push(`# [stack.stats] omitted (no resource limits declared in compose.yaml)`);
  lines.push(``);
  return lines.join("\n");
}

function main() {
  const stacks = discoverStacks();
  if (stacks.length === 0) {
    console.log("✓ All stacks already have a matching komodo/stacks/*.toml");
    return;
  }

  const byHost = stacks.reduce((acc, s) => {
    acc[s.host] = (acc[s.host] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  console.log(`${APPLY ? "Writing" : "Would write"} komodo/stacks/<name>-<host>.toml for ${stacks.length} stack(s):`);
  for (const [host, count] of Object.entries(byHost)) {
    console.log(`  - ${count} on ${host}`);
  }
  console.log();

  let written = 0;
  for (const stack of stacks) {
    const content = renderToml(stack);
    if (APPLY) {
      writeFileSync(stack.komodoPath, content);
      written += 1;
      console.log(`  ✓ ${stack.name}  (${stack.host}, ${stack.secretsEnvKeys.length} secrets)`);
    } else {
      console.log(`  - ${stack.name}  (${stack.host}, ${stack.secretsEnvKeys.length} secrets)`);
    }
  }

  console.log();
  if (APPLY) {
    console.log(`✓ Wrote ${written} komodo stack file(s).`);
  } else {
    console.log(`(dry-run) Re-run with --apply to write the ${stacks.length} file(s).`);
  }
}

main();