#!/usr/bin/env bash
# =============================================================================
# generate-stack-docs.sh — Emit per-stack markdown docs for the 89 stacks
# =============================================================================
# Per the 2026-07-30-pre-deploy-blockers-resolution-v1 openspec change
# (closes GitHub issue #107).
#
# USAGE:
#   bash scripts/generate-stack-docs.sh                # writes to cianfhoghlaim/docs/stacks/
#   bash scripts/generate-stack-docs.sh --check       # exit 1 if any stack missing a doc
#   bash scripts/generate-stack-docs.sh --out <path>  # custom output dir
#
# APPROACH:
#   1. Calls `bash scripts/stack-doctor.sh --emit-md <INDEX>` to write the
#      single combined INDEX.md (the 1-shot dump of all 89 stacks).
#   2. Then walks `bonneagar/stacks/*/` and emits a per-stack markdown
#      doc to `cianfhoghlaim/docs/stacks/<name>.md`.
#   3. Each per-stack doc follows the canonical 4-section outline:
#         # <Stack Name>
#         ## Purpose
#         ## Files (GOLD_STANDARD status)
#         ## Source of truth
#         ## See also
#
# This is the per-stack surface that the deployment control panel
# (`notebooks/00_control_panel.py`) reads.
# =============================================================================

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STACKS_DIR="${STACKS_DIR:-$REPO_ROOT/bonneagar/stacks}"
DOCS_DIR_DEFAULT="$REPO_ROOT/cianfhoghlaim/docs/stacks"
OUT_DIR=""
CHECK_ONLY=0

# --- Args ---
for arg in "$@"; do
  case "$arg" in
    --check)       CHECK_ONLY=1 ;;
    --out)
      shift_next=1
      ;;
    --out=*)
      OUT_DIR="${arg#--out=}"
      ;;
    -h|--help)
      cat <<USAGE
Usage: $0 [options]
  --check       exit 1 if any stack missing a doc (CI gate)
  --out <path>  custom output dir (default: cianfhoghlaim/docs/stacks/)
USAGE
      exit 0
      ;;
    *)
      if [ "${shift_next:-0}" = "1" ]; then
        OUT_DIR="$arg"
        shift_next=0
      fi
      ;;
  esac
done

OUT_DIR="${OUT_DIR:-$DOCS_DIR_DEFAULT}"

if [ "$CHECK_ONLY" = "0" ]; then
  mkdir -p "$OUT_DIR"
fi

# --- Step 1: Emit the combined INDEX.md ---
INDEX_PATH="$OUT_DIR/INDEX.md"
if [ -f "$REPO_ROOT/scripts/stack-doctor.sh" ]; then
  echo "[generate-stack-docs] running stack-doctor --emit-md $INDEX_PATH"
  DOCS_DIR="$OUT_DIR" bash "$REPO_ROOT/scripts/stack-doctor.sh" --emit-md "$INDEX_PATH" >/dev/null 2>&1 || true
fi

# --- Step 2: Walk every stack directory and emit a per-stack doc ---
total=0
written=0
missing=0
for stack in "$STACKS_DIR"/*/; do
  [ -d "$stack" ] || continue
  stack_name=$(basename "$stack")
  total=$((total + 1))

  # Skip non-stack directories (sentinels like GOLD_STANDARD.md, INDEX.md, README.md)
  case "$stack_name" in
    INDEX.md|README.md|GOLD_STANDARD.md|HEALTH_REPORT.md|wave2|GOLD*) continue ;;
  esac

  # Skip files (not directories)
  [ -d "$stack" ] || continue

  out="$OUT_DIR/${stack_name}.md"
  if [ "$CHECK_ONLY" = "1" ]; then
    if [ -f "$out" ]; then
      written=$((written + 1))
    else
      missing=$((missing + 1))
      echo "MISSING: $stack_name"
    fi
    continue
  fi

  # Emit the canonical 4-section doc for this stack
  compose="❌"; [ -f "$stack/compose.yaml" ] && compose="✓"
  sidecar="❌"; [ -f "$stack/sidecar.yaml" ] && sidecar="✓"
  secrets="❌"; [ -f "$stack/secrets.env" ] && secrets="✓"
  pangolin="❌"; [ -f "$stack/pangolin.yaml" ] && pangolin="✓"
  blueprint="❌"; [ -f "$stack/blueprint.yaml" ] && blueprint="✓"
  env_example="❌"; [ -f "$stack/.env.example" ] && env_example="✓"

  # Pull the image name (best-effort) from compose.yaml
  image=""
  if [ -f "$stack/compose.yaml" ]; then
    image=$(grep -E '^[[:space:]]*image:' "$stack/compose.yaml" 2>/dev/null | head -1 | sed -e 's/^[[:space:]]*image:[[:space:]]*//' || true)
  fi

  # Pull the purpose (best-effort) from README.md or compose.yaml header
  purpose=""
  if [ -f "$stack/README.md" ]; then
    purpose=$(head -1 "$stack/README.md" | sed -e 's/^#[[:space:]]*//' || true)
  fi
  if [ -z "$purpose" ] && [ -f "$stack/compose.yaml" ]; then
    purpose=$(grep -m1 -E '^# ' "$stack/compose.yaml" 2>/dev/null | sed -e 's/^#[[:space:]]*//' || true)
  fi

  cat > "$out" <<STACK_DOC
# ${stack_name}

> Auto-generated by scripts/generate-stack-docs.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
> Per the 2026-07-30-pre-deploy-blockers-resolution-v1 openspec change
> (closes GitHub issue #107).

## Purpose

${purpose:-(no purpose documented — add a README.md or compose.yaml header comment)}

## Files (GOLD_STANDARD status)

| File | Status |
|------|:------:|
| compose.yaml   | $compose |
| sidecar.yaml   | $sidecar |
| secrets.env    | $secrets |
| pangolin.yaml  | $pangolin |
| blueprint.yaml | $blueprint |
| .env.example   | $env_example |

## Image

\`\`\`
${image:-(none — no compose.yaml or no image: line)}
\`\`\`

## Source of truth

- Spec: \`openspec/specs/infrastructure-stacks/spec.md\`
- Directory: \`bonneagar/stacks/${stack_name}/\`

## See also

- Index: \`cianfhoghlaim/docs/stacks/INDEX.md\`
- Deployment control panel: \`notebooks/00_control_panel.py\`
STACK_DOC
  written=$((written + 1))
done

echo "[generate-stack-docs] total=$total written=$written out=$OUT_DIR"
if [ "$CHECK_ONLY" = "1" ]; then
  if [ "$missing" -gt 0 ]; then
    echo "[generate-stack-docs] FAIL: $missing stacks missing docs"
    exit 1
  fi
  echo "[generate-stack-docs] OK: all $total stacks have docs"
  exit 0
fi
