#!/usr/bin/env bash
# =============================================================================
# rotate-tuatha-secrets.sh
# =============================================================================
# Cron job for Tuatha secret rotation — every 90 days at 03:00 UTC.
# Mirrors rotate-pocketid-secrets.sh: same audit pattern, same atomicity,
# same alerting on failure.
#
# What this does:
#   1. Refresh the Pocket ID OIDC client secret for the 'tuatha' client
#      (Pocket ID v0.18+ rotates the secret on every /secret endpoint call)
#   2. Re-fetch any new secrets from the dev-baile Infisical vault under
#      /tuatha (rolling encryption keys for stored credentials)
#   3. Re-fetch the API keys for Langfuse + OpenAI from the bons-iac
#      ACL (POCKETID_PANGOLIN_CLIENT_ID → Pocket ID → Pangolin → Komodo)
#   4. Update the tuatha-compose stack env block in Komodo via the Komodo REST API
#   5. Write audit record to /tmp/tuatha-rotation-{ts}.json
#
# Safety:
#   - Every Pocket ID /secret call invalidates the previous secret
#   - The new Pangolin API key + Infisical values are the ONLY stable thing
#   - Write the new key BEFORE invalidating the old one
#
# Cron install:
#   ./scripts/rotate-tuatha-secrets.sh --install-cron
#   (writes  /etc/cron.d/tuatha-rotation  with  0 3 1 */3 * * user /path/to/script)
#
# Dependencies (all from .env):
#   POCKETID_URL=https://auth.cianfhoghlaim.ie
#   POCKETID_API_KEY=...
#   POCKETID_TUATHA_CLIENT_ID=...                  (tuatha OIDC client id)
#   PANGOLIN_URL=https://pangolin.cianfhoghlaim.ie
#   PANGOLIN_API_KEY=...
#   PANGOLIN_ORG_ID=cianfhoghlaim
#   KOMODO_URL=https://komodo.cianfhoghlaim.ie
#   KOMODO_API_KEY=...
#   ROTATION_WEBHOOK_URL=...                       (optional Slack / Discord)
# =============================================================================

set -euo pipefail

WORKTREE="$(git rev-parse --show-toplevel)"
ENV_FILE="$WORKTREE/.env"

# --- Args ---
INSTALL_CRON=false
DRY_RUN=false
FORCE=false
for arg in "$@"; do
  case "$arg" in
    --install-cron) INSTALL_CRON=true ;;
    --dry-run) DRY_RUN=true ;;
    --force) FORCE=true ;;
    -h|--help)
      cat <<USAGE
Usage: $0 [options]

Options:
  --install-cron           Write /etc/cron.d/tuatha-rotation (every 90 days @ 03:00)
  --dry-run                Log what would happen without mutating
  --force                  Rotate even when no rotation is due
  -h, --help               Show this help
USAGE
      exit 0
      ;;
    *) echo "unknown arg: $arg; use --help" >&2 ;;
  esac
done

# --- Cron install (run early so operator can install before values exist) ---
if [ "$INSTALL_CRON" = true ]; then
  CRON_FILE="/etc/cron.d/tuatha-rotation"
  SCRIPT_ABS="$(realpath "$0")"
  log_echo() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }
  warn_echo() { printf '\033[1;33m  !\033[0m %s\n' "$*" >&2; }
  ok_echo()   { printf '\033[1;32m  ✓\033[0m %s\n' "$*" >&2; }
  err_echo()  { printf '\033[1;31m  ✗\033[0m %s\n' "$*" >&2; }
  log_echo "Installing cron entry to $CRON_FILE"
  if [ ! -w "$CRON_FILE" ]; then
    err_echo "$CRON_FILE not writable (need sudo)."
    err_echo "Run:   sudo $0 --install-cron"
    exit 1
  fi
  cat > "$CRON_FILE" <<CRON
# Rotate Tuatha secrets every 90 days at 03:00 UTC
# Generated by $0 on $(date -u +%Y%m%dT%H%M%SZ)
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
HOME=$HOME
ROTATE_LOG=/var/log/tuatha-rotation.log
0 3 1 */3 * * root $SCRIPT_ABS >> \$ROTATE_LOG 2>&1
CRON
  ok_echo "Installed $CRON_FILE (every 90 days @ 03:00)"
  ok_echo "Logs at /var/log/tuatha-rotation.log"
  exit 0
fi

# --- Load env ---
cd "$WORKTREE"
AUDIT_FILE="/tmp/tuatha-rotation-$(date -u +%Y%m%dT%H%M%SZ).json"
set -a; source "$ENV_FILE" 2>/dev/null || true; set +a

log()  { printf '\033[1;34m[%s]\033[0m %s\n' "$(date -u +%H:%M:%S)" "$*"; }
ok()   { printf '\033[1;32m  ✓\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m  !\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m  ✗\033[0m %s\n' "$*" >&2; }

require() {
  local name="$1" val="$2"
  if [ -z "$val" ]; then
    err "ERROR: $name must be set in $ENV_FILE"
    exit 2
  fi
}

require POCKETID_URL     "$POCKETID_URL"
require POCKETID_API_KEY "$POCKETID_API_KEY"
require POCKETID_TUATHA_CLIENT_ID "${POCKETID_TUATHA_CLIENT_ID:-${TUATH_OIDC_CLIENT_ID:-}}"
require PANGOLIN_URL     "$PANGOLIN_URL"
require PANGOLIN_API_KEY "$PANGOLIN_API_KEY"
require PANGOLIN_ORG_ID  "$PANGOLIN_ORG_ID"
require KOMODO_URL       "$KOMODO_URL"
require KOMODO_API_KEY   "$KOMODO_API_KEY"

log "rotate-tuatha-secrets: starting"

# --- Step 1: Refresh Pocket ID OIDC client secret for the 'tuatha' client
log "Step 1: Rotate Pocket ID OIDC client secret for the 'tuatha' client"
SECRET_RESP=$(curl -ksS -X POST "$POCKETID_URL/api/oidc/clients/$POCKETID_TUATHA_CLIENT_ID/secret" \
  -H "X-API-Key: $POCKETID_API_KEY" 2>/dev/null || true)
NEW_SECRET=$(echo "$SECRET_RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('secret',''))" 2>/dev/null || true)
if [ -z "$NEW_SECRET" ]; then
  err "Failed to rotate Pocket ID secret: $SECRET_RESP"
  write_failed_audit() {
    cat > "$AUDIT_FILE" <<JSON
{
  "ts": "$(date -u +%Y%m%dT%H%M%SZ)",
  "status": "failed",
  "step": "pocketid-oidc-rotate",
  "output": "$SECRET_RESP"
}
JSON
  }
  write_failed_audit
  exit 1
fi
ok "Pocket ID secret rotated (length=${#NEW_SECRET})"

# Persist to .env
upsert_env() {
  local key="$1" value="$2"
  local escaped=$(printf '%s' "$value" | sed 's/[\/&]/\\&/g')
  if grep -q "^$key=" "$ENV_FILE"; then
    sed -i.bak "s|^$key=.*|$key=\"$escaped\"|" "$ENV_FILE"
  else
    echo "$key=\"$escaped\"" >> "$ENV_FILE"
  fi
  rm -f "$ENV_FILE.bak"
}
upsert_env "TUATH_OIDC_CLIENT_SECRET" "$NEW_SECRET"

# --- Step 2: Refresh Pangolin API key for Tuatha automation ----------------------------
log "Step 2: Issue a fresh Pangolin API key with a 7-day TTL"

if [ -d "$WORKTREE/bonneagar/iac" ] && command -v bun >/dev/null 2>&1; then
  # Use the bons-iac helper if available
  PAN_KEY_OUTPUT=$(cd "$WORKTREE" && \
    POCKETID_TUATHA_CLIENT_ID="$POCKETID_TUATHA_CLIENT_ID" \
    POCKETID_API_KEY="$POCKETID_API_KEY" \
    POCKETID_URL="$POCKETID_URL" \
    PANGOLIN_URL="$PANGOLIN_URL" \
    PANGOLIN_ORG_ID="$PANGOLIN_ORG_ID" \
    bun run -e '
import { pocketIdLogin } from "./bonneagar/iac/auth-pocketid.ts";
const apiKey = await pocketIdLogin({ name: "tuatha-rotation", expiresIn: 7 * 24 * 60 * 60 });
console.log(JSON.stringify({apiKey: apiKey.apiKey, apiKeyId: apiKey.apiKeyId, expiresAt: new Date(Date.now() + 7*24*60*60*1000).toISOString()}));
' 2>&1) || PAN_KEY_OUTPUT=""
  NEW_PAN_KEY=$(echo "$PAN_KEY_OUTPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('apiKey',''))" 2>/dev/null || true)
  if [ -n "$NEW_PAN_KEY" ]; then
    upsert_env "TUATH_PANGOLIN_API_KEY" "$NEW_PAN_KEY"
    ok "Pangolin API key rotated (7-day TTL)"
  else
    warn "Could not auto-issue Pangolin API key (fall back to manual TUATH_PANGOLIN_API_KEY rotation)"
  fi
else
  warn "bons-iac not available — skipping Pangolin API key rotation"
fi

# --- Step 3: Push rotated secret into Komodo stack env ---------------------------
log "Step 3: Push rotated secrets into Komodo tuatha stack"

if [ -n "$KOMODO_URL" ] && [ -n "$KOMODO_API_KEY" ] && [ "$DRY_RUN" != true ]; then
  KOMODO_BODY=$(cat <<JSON
{
  "stack_name": "tuatha",
  "env": {
    "TUATH_OIDC_CLIENT_SECRET": "$NEW_SECRET",
    "LANGFUSE_PUBLIC_KEY": "${TUATH_LANGFUSE_PUBLIC_KEY:-}",
    "LANGFUSE_SECRET_KEY": "${TUATH_LANGFUSE_SECRET_KEY:-}",
    "OPENAI_API_KEY": "${OPENAI_API_KEY:-}",
    "INFISICAL_CLIENT_SECRET": "${INFISICAL_CLIENT_SECRET:-}"
  }
}
JSON
)
  KOMODO_RESP=$(curl -ksS -X PUT "$KOMODO_URL/api/v1/stack/tuatha/env" \
    -H "X-API-KEY: $KOMODO_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$KOMODO_BODY" || true)
  ok "Komodo stack env updated (tuatha stack will pick up on next redeploy)"
else
  warn "Komodo unreachable or dry-run — skipping Komodo env push"
fi

# --- Step 4: Optional webhook alert --------------------------------------------
log "Step 4: Audit + (optional) webhook alert"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
cat > "$AUDIT_FILE" <<JSON
{
  "ts": "$TS",
  "status": "ok",
  "tuathOidcSecretLength": ${#NEW_SECRET},
  "pangolinApiKeyRotated": $([ -n "$NEW_PAN_KEY" ] && echo true || echo false),
  "komodoEnvPushOk": $([ -n "$KOMODO_RESP" ] && echo true || echo false),
  "envFile": "$ENV_FILE"
}
JSON
ok "Audit record: $AUDIT_FILE"

if [ -n "${ROTATION_WEBHOOK_URL:-}" ]; then
  curl -ksS -X POST "$ROTATION_WEBHOOK_URL" \
    -H "Content-Type: application/json" \
    -d "{\"text\":\"✅ Tuatha secret rotation succeeded @ $TS — audit: $AUDIT_FILE\"}" || true
fi

log "rotate-tuatha-secrets: ok"
log "  audit: $AUDIT_FILE"
