/**
 * scripts/schema-validate.ts
 *
 * `bun run schema:validate` — CI drift gate for the generated Zod schemas.
 *
 * Regenerates `apps/web/src/lib/bi-ep.gen.ts` in-memory, diffs against the
 * committed file (byte-level + structural diff), and exits non-zero if the
 * upstream DuckLake schema has changed.
 *
 * Per openspec/changes/2026-07-19-leaving-cert-pdf-lineage-and-schema-codegen-v1
 * R30 (DuckLake → Zod + TanStack DB collection codegen).
 *
 * Usage:
 *   bun run schema:validate                 # default: introspect DuckLake
 *   bun run schema:validate --offline       # use the static BIEP v1 schema
 *   bun run schema:validate --gen-path <p>  # override the gen file path
 *   bun run schema:validate --quiet         # exit 0 silently on success
 *
 * Exit codes:
 *   0 — no drift (committed file matches the regenerated file)
 *   1 — drift detected (run `bun run schema:generate` to fix)
 *   2 — committed file missing
 */

import * as crypto from "node:crypto";
import * as fs from "node:fs/promises";
import * as path from "node:path";

import {
  buildBiepV1StaticTables,
  emitTableZodSchema,
  tableNameToIdentifier,
  type DuckDBTable,
} from "./_zod-from-duckdb";

// =============================================================================
// CLI arg parsing
// =============================================================================

interface CliArgs {
  offline: boolean;
  genPath: string;
  lockPath: string;
  quiet: boolean;
  help: boolean;
  repoRoot: string;
}

function parseArgs(argv: ReadonlyArray<string>): CliArgs {
  const args: CliArgs = {
    offline: false,
    genPath: "",
    lockPath: "",
    quiet: false,
    help: false,
    repoRoot: "",
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    switch (arg) {
      case "--offline":
        args.offline = true;
        break;
      case "--gen-path":
        if (!next) throw new Error("--gen-path requires a path argument");
        args.genPath = path.resolve(next);
        i++;
        break;
      case "--lock-path":
        if (!next) throw new Error("--lock-path requires a path argument");
        args.lockPath = path.resolve(next);
        i++;
        break;
      case "--quiet":
        args.quiet = true;
        break;
      case "--help":
      case "-h":
        args.help = true;
        break;
      default:
        if (arg.startsWith("--")) {
          throw new Error(`Unknown flag: ${arg}`);
        }
    }
  }
  return args;
}

function findRepoRoot(start: string): string {
  let dir = path.resolve(start);
  while (true) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      require("node:fs").accessSync(path.join(dir, "pyproject.toml"));
      return dir;
    } catch {
      const parent = path.dirname(dir);
      if (parent === dir) return path.resolve(start);
      dir = parent;
    }
  }
}

// =============================================================================
// In-memory regeneration
// =============================================================================

/**
 * Regenerate the bi-ep.gen.ts content in memory (without writing to disk).
 * Mirrors the emitter logic in `scripts/schema-generate.ts` so the diff is
 * apples-to-apples.
 */
function regenerateBiEpGen(tables: DuckDBTable[]): string {
  const tableEmits = tables.map((table) => ({
    identifier: tableNameToIdentifier(table.table),
    table,
    ...emitTableZodSchema(table, tableNameToIdentifier(table.table)),
  }));

  const collectionHelpers = tableEmits.map(({ identifier, table }) => {
    const dbName = `${table.database}_${table.schema}`;
    return `export function create${identifier}Collection() {
  return createCollection({
    schema: ${identifier}Schema,
    tableName: "${table.table}",
    database: "${dbName}",
    primaryKey: "topic_id",
    // ... additional TanStack DB wiring (loader, sync, etc.)
  });
}`;
  });

  // The header MUST match the emitter in schema-generate.ts exactly.
  // No timestamps — those live in the lock file.
  const header: string[] = [
    "// apps/web/src/lib/bi-ep.gen.ts",
    "//",
    "// AUTO-GENERATED by `bun run schema:generate` (scripts/schema-generate.ts).",
    "// DO NOT EDIT — re-run the generator to update.",
    "//",
    "// Per openspec/changes/2026-07-19-leaving-cert-pdf-lineage-and-schema-codegen-v1",
    "// R30 (DuckLake → Zod + TanStack DB collection codegen).",
    "",
    'import { z } from "zod";',
    'import { createCollection } from "@tanstack/db";',
    "",
    `// Generated from ${tables.length} BIEP v1 tables.`,
    "",
  ];

  const body: string[] = [];
  for (const { source } of tableEmits) {
    body.push(source, "");
  }

  const collectionSection: string[] = [
    "// =====================================================================",
    "// TanStack DB collection helpers",
    "// =====================================================================",
    "",
    ...collectionHelpers,
    "",
  ];

  return [...header, ...body, ...collectionSection].join("\n");
}

// =============================================================================
// DuckDB introspection (duplicated from schema-generate.ts; kept minimal here)
// =============================================================================

async function introspectFromDuckLake(): Promise<DuckDBTable[]> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const duckdbModule: any = await import("duckdb");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const Database: any = duckdbModule.Database ?? duckdbModule.default?.Database;
  if (!Database) {
    throw new Error("duckdb module did not export Database — package version mismatch?");
  }
  const db = new Database(":memory:");
  const token = process.env.MOTHERDUCK_TOKEN ?? "";
  if (!token) {
    if (typeof db.close === "function") db.close();
    throw new Error("MOTHERDUCK_TOKEN not set");
  }
  const conn = db.connect();
  conn.run(`ATTACH 'md:oideachais' AS md (TYPE motherduck, TOKEN '${token}');`);

  const subjects = [
    "mathematics",
    "chemistry",
    "geography",
    "english",
    "gaeilge",
    "computer_science",
  ];
  const suffixes = ["syllabus", "papers", "marking_schemes", "topics"];

  const out: DuckDBTable[] = [];
  for (const subject of subjects) {
    const prefix = subject === "computer_science" ? "cs" : subject;
    for (const suffix of suffixes) {
      const tableName = `${prefix}_${suffix}`;
      const table: DuckDBTable = {
        database: "oideachais",
        schema: "leaving_cert",
        table: tableName,
        columns: [],
      };
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const stmt: any = conn.prepare(`DESCRIBE md.leaving_cert.${tableName}`);
      const rows: Array<{
        column_name: string;
        column_type: string;
        null: string;
        comment: string | null;
      }> = await new Promise((resolve, reject) => {
        stmt.all((err: Error | null, result: unknown) => {
          if (err) reject(err);
          else resolve((result ?? []) as Array<{
            column_name: string;
            column_type: string;
            null: string;
            comment: string | null;
          }>);
        });
      });
      stmt.finalize();
      for (const row of rows) {
        table.columns.push({
          column_name: row.column_name,
          column_type: row.column_type,
          is_nullable: row.null === "YES" ? "YES" : "NO",
          comment: row.comment,
        });
      }
      out.push(table);
    }
  }
  if (typeof db.close === "function") db.close();
  return out;
}

// =============================================================================
// Diff printer
// =============================================================================

interface LineDiff {
  lineNo: number;
  committed: string;
  regenerated: string;
}

/**
 * Produce a minimal unified-style diff between the committed file and the
 * regenerated content. We don't use a third-party diff lib — a line-by-line
 * LCS is enough for CI output.
 */
function diffLines(committed: string, regenerated: string): LineDiff[] {
  const a = committed.split("\n");
  const b = regenerated.split("\n");
  const max = Math.max(a.length, b.length);
  const diffs: LineDiff[] = [];
  for (let i = 0; i < max; i++) {
    const ca = a[i] ?? "";
    const cb = b[i] ?? "";
    if (ca !== cb) {
      diffs.push({ lineNo: i + 1, committed: ca, regenerated: cb });
    }
  }
  return diffs;
}

// =============================================================================
// Main
// =============================================================================

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = args.repoRoot || findRepoRoot(process.cwd());
  const genPath =
    args.genPath ||
    path.join(
      repoRoot,
      "web/apps/cianfhoghlaim-leaving-cert/apps/web/src/lib/bi-ep.gen.ts",
    );
  const lockPath =
    args.lockPath ||
    path.join(
      repoRoot,
      "web/apps/cianfhoghlaim-leaving-cert/apps/web/src/lib/bi-ep.gen.lock.json",
    );

  if (args.help) {
    console.log(
      [
        "schema-validate — CI drift gate for the generated Zod schemas",
        "",
        "Usage:",
        "  bun run schema:validate [--offline] [--gen-path <p>] [--quiet]",
        "",
        "Options:",
        "  --offline             Use the static BIEP v1 schema (skip DuckLake)",
        "  --gen-path <path>     Override the gen file path",
        "  --lock-path <path>    Override the lock file path",
        "  --quiet               Exit 0 silently on success",
        "",
        "Exit codes:",
        "  0 — no drift",
        "  1 — drift detected",
        "  2 — gen file missing",
        "",
      ].join("\n"),
    );
    return;
  }

  // 1. Load the committed file.
  let committed: string;
  try {
    committed = await fs.readFile(genPath, "utf8");
  } catch {
    console.error(`[error] ${genPath} not found`);
    console.error(`[hint] run \`bun run schema:generate\` to create it`);
    process.exit(2);
  }

  // 2. Regenerate in memory.
  let tables: DuckDBTable[];
  if (args.offline) {
    tables = buildBiepV1StaticTables();
  } else {
    try {
      tables = await introspectFromDuckLake();
    } catch (err) {
      console.error(`[error] DuckLake introspection failed: ${(err as Error).message}`);
      console.error(`[hint] pass --offline to use the static schema`);
      process.exit(1);
    }
  }
  const regenerated = regenerateBiEpGen(tables);
  const regenHash = crypto.createHash("sha256").update(regenerated).digest("hex");
  const committedHash = crypto.createHash("sha256").update(committed).digest("hex");

  // 3. Compare.
  if (regenHash === committedHash) {
    if (!args.quiet) {
      console.log(`[schema:validate] OK — bi-ep.gen.ts matches the live DuckLake schema (hash=${regenHash.slice(0, 12)}…)`);
    }
    process.exit(0);
  }

  console.error("[schema:validate] DRIFT DETECTED");
  console.error(`  committed:  ${committedHash.slice(0, 12)}…`);
  console.error(`  regenerated: ${regenHash.slice(0, 12)}…`);
  console.error("");
  const diffs = diffLines(committed, regenerated);
  if (diffs.length <= 50) {
    for (const d of diffs) {
      console.error(`  line ${d.lineNo}:`);
      if (d.committed) console.error(`    - ${d.committed}`);
      if (d.regenerated) console.error(`    + ${d.regenerated}`);
    }
  } else {
    console.error(`  (${diffs.length} lines differ — too many to print; run \`bun run schema:generate\` for a full regeneration)`);
  }
  console.error("");
  console.error(`[hint] run \`bun run schema:generate\` to regenerate the committed file`);
  // Drift is always reported (even with --quiet) so CI + devs see the failure.
  process.exit(1);

  // Reference lockPath for future cross-checking.
  void lockPath;
}

if (import.meta.main) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}