// main.tsx — Cianfhoghlaim OS SPA entry point
// Uses @tanstack/react-router (file-based) without TanStack Start's
// virtual modules — for the initial dev deploy. TanStack Start migration
// deferred to Phase 2 (T1.7).

import * as React from "react";
import ReactDOM from "react-dom/client";
import { createRouter, createRoute, createRootRoute, RouterProvider, Outlet, Link } from "@tanstack/react-router";
import { TanStackRouterDevtools } from "@tanstack/react-router-devtools";

import "./app.css";

// Re-export the imported route components (the routeTree.gen.ts is auto-generated by @tanstack/router-plugin)
import * as IndexRoute from "./routes/index";
import * as MapRoute from "./routes/en/map";
import * as KeyCompetenciesRoute from "./routes/en/key-competencies";
import * as EnAboutRoute from "./routes/en/about";
import * as GaAboutRoute from "./routes/ga/about";

// Build the router manually (the routeTree.gen.ts may be stale in dev)
const rootRoute = createRootRoute({
  component: () => (
    <div className="h-screen w-screen flex flex-col bg-slate-900 text-slate-100 font-sans">
      <header className="h-14 bg-slate-950 border-b border-slate-800 flex items-center px-4 justify-between shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-full bg-amber-700 flex items-center justify-center font-cinzel font-bold text-amber-100">BA</div>
          <div>
            <h1 className="font-cinzel text-lg font-bold tracking-wider text-emerald-500">CIANFHOGHLAIM OS</h1>
            <span className="text-xs text-slate-500 italic">Aes Sedai — servants of all</span>
          </div>
        </div>
        <nav className="flex items-center gap-4">
          <Link to="/" className="text-slate-300 hover:text-emerald-400 text-sm">Curriculum</Link>
          <Link to="/en/map" className="text-slate-300 hover:text-emerald-400 text-sm">Map</Link>
          <Link to="/en/key-competencies" className="text-slate-300 hover:text-emerald-400 text-sm">Key Competencies</Link>
          <Link to="/en/about" className="text-slate-300 hover:text-emerald-400 text-sm">About</Link>
          <Link to="/ga/about" className="text-slate-300 hover:text-emerald-400 text-sm">Faoi</Link>
        </nav>
      </header>
      <main className="flex-1 overflow-y-auto">
        <Outlet />
      </main>
      {import.meta.env.DEV && <TanStackRouterDevtools position="bottom-right" />}
    </div>
  ),
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  component: (IndexRoute as any).default || (IndexRoute as any).Route?.component || (() => <div>Index</div>),
});

const mapRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/en/map",
  component: (MapRoute as any).default || (MapRoute as any).Route?.component || (() => <div>Map</div>),
});

const keyCompRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/en/key-competencies",
  component: (KeyCompetenciesRoute as any).default || (KeyCompetenciesRoute as any).Route?.component || (() => <div>Key Competencies</div>),
});

const enAboutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/en/about",
  component: (EnAboutRoute as any).default || (EnAboutRoute as any).Route?.component || (() => <div>About</div>),
});

const gaAboutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/ga/about",
  component: (GaAboutRoute as any).default || (GaAboutRoute as any).Route?.component || (() => <div>Faoi</div>),
});

const routeTree = rootRoute.addChildren([indexRoute, mapRoute, keyCompRoute, enAboutRoute, gaAboutRoute]);

const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const root = document.getElementById("root")!;
ReactDOM.createRoot(root).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
);