/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaEiraicTreasuresRouteImport } from './routes/ga/eiraic-treasures'
import { Route as GaAboutRouteImport } from './routes/ga/about'
import { Route as EnMapRouteImport } from './routes/en/map'
import { Route as EnKeyCompetenciesRouteImport } from './routes/en/key-competencies'
import { Route as EnEiraicTreasuresRouteImport } from './routes/en/eiraic-treasures'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as GaLeavingCertSubjectRouteImport } from './routes/ga/leaving-cert/$subject'
import { Route as EnLeavingCertSubjectRouteImport } from './routes/en/leaving-cert/$subject'
import { Route as EnKeyCompetenciesEmblemsRouteImport } from './routes/en/key-competencies.emblems'
import { Route as EnAssetsSubjectRouteImport } from './routes/en/assets/$subject'
import { Route as EnLeavingCertSubjectSectionRouteImport } from './routes/en/leaving-cert/$subject.$section'
import { Route as EnLeavingCertSubjectPracticeTopicRouteImport } from './routes/en/leaving-cert/$subject.practice.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaEiraicTreasuresRoute = GaEiraicTreasuresRouteImport.update({
  id: '/ga/eiraic-treasures',
  path: '/ga/eiraic-treasures',
  getParentRoute: () => rootRouteImport,
} as any)
const GaAboutRoute = GaAboutRouteImport.update({
  id: '/ga/about',
  path: '/ga/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMapRoute = EnMapRouteImport.update({
  id: '/en/map',
  path: '/en/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKeyCompetenciesRoute = EnKeyCompetenciesRouteImport.update({
  id: '/en/key-competencies',
  path: '/en/key-competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEiraicTreasuresRoute = EnEiraicTreasuresRouteImport.update({
  id: '/en/eiraic-treasures',
  path: '/en/eiraic-treasures',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertSubjectRoute = GaLeavingCertSubjectRouteImport.update({
  id: '/ga/leaving-cert/$subject',
  path: '/ga/leaving-cert/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertSubjectRoute = EnLeavingCertSubjectRouteImport.update({
  id: '/en/leaving-cert/$subject',
  path: '/en/leaving-cert/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKeyCompetenciesEmblemsRoute =
  EnKeyCompetenciesEmblemsRouteImport.update({
    id: '/emblems',
    path: '/emblems',
    getParentRoute: () => EnKeyCompetenciesRoute,
  } as any)
const EnAssetsSubjectRoute = EnAssetsSubjectRouteImport.update({
  id: '/en/assets/$subject',
  path: '/en/assets/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertSubjectSectionRoute =
  EnLeavingCertSubjectSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => EnLeavingCertSubjectRoute,
  } as any)
const EnLeavingCertSubjectPracticeTopicRoute =
  EnLeavingCertSubjectPracticeTopicRouteImport.update({
    id: '/practice/$topic',
    path: '/practice/$topic',
    getParentRoute: () => EnLeavingCertSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en/about': typeof EnAboutRoute
  '/en/eiraic-treasures': typeof EnEiraicTreasuresRoute
  '/en/key-competencies': typeof EnKeyCompetenciesRouteWithChildren
  '/en/map': typeof EnMapRoute
  '/ga/about': typeof GaAboutRoute
  '/ga/eiraic-treasures': typeof GaEiraicTreasuresRoute
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/key-competencies/emblems': typeof EnKeyCompetenciesEmblemsRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en/about': typeof EnAboutRoute
  '/en/eiraic-treasures': typeof EnEiraicTreasuresRoute
  '/en/key-competencies': typeof EnKeyCompetenciesRouteWithChildren
  '/en/map': typeof EnMapRoute
  '/ga/about': typeof GaAboutRoute
  '/ga/eiraic-treasures': typeof GaEiraicTreasuresRoute
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/key-competencies/emblems': typeof EnKeyCompetenciesEmblemsRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en/about': typeof EnAboutRoute
  '/en/eiraic-treasures': typeof EnEiraicTreasuresRoute
  '/en/key-competencies': typeof EnKeyCompetenciesRouteWithChildren
  '/en/map': typeof EnMapRoute
  '/ga/about': typeof GaAboutRoute
  '/ga/eiraic-treasures': typeof GaEiraicTreasuresRoute
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/key-competencies/emblems': typeof EnKeyCompetenciesEmblemsRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en/about'
    | '/en/eiraic-treasures'
    | '/en/key-competencies'
    | '/en/map'
    | '/ga/about'
    | '/ga/eiraic-treasures'
    | '/en/assets/$subject'
    | '/en/key-competencies/emblems'
    | '/en/leaving-cert/$subject'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en/about'
    | '/en/eiraic-treasures'
    | '/en/key-competencies'
    | '/en/map'
    | '/ga/about'
    | '/ga/eiraic-treasures'
    | '/en/assets/$subject'
    | '/en/key-competencies/emblems'
    | '/en/leaving-cert/$subject'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  id:
    | '__root__'
    | '/'
    | '/en/about'
    | '/en/eiraic-treasures'
    | '/en/key-competencies'
    | '/en/map'
    | '/ga/about'
    | '/ga/eiraic-treasures'
    | '/en/assets/$subject'
    | '/en/key-competencies/emblems'
    | '/en/leaving-cert/$subject'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnAboutRoute: typeof EnAboutRoute
  EnEiraicTreasuresRoute: typeof EnEiraicTreasuresRoute
  EnKeyCompetenciesRoute: typeof EnKeyCompetenciesRouteWithChildren
  EnMapRoute: typeof EnMapRoute
  GaAboutRoute: typeof GaAboutRoute
  GaEiraicTreasuresRoute: typeof GaEiraicTreasuresRoute
  EnAssetsSubjectRoute: typeof EnAssetsSubjectRoute
  EnLeavingCertSubjectRoute: typeof EnLeavingCertSubjectRouteWithChildren
  GaLeavingCertSubjectRoute: typeof GaLeavingCertSubjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/eiraic-treasures': {
      id: '/ga/eiraic-treasures'
      path: '/ga/eiraic-treasures'
      fullPath: '/ga/eiraic-treasures'
      preLoaderRoute: typeof GaEiraicTreasuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/about': {
      id: '/ga/about'
      path: '/ga/about'
      fullPath: '/ga/about'
      preLoaderRoute: typeof GaAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/map': {
      id: '/en/map'
      path: '/en/map'
      fullPath: '/en/map'
      preLoaderRoute: typeof EnMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/key-competencies': {
      id: '/en/key-competencies'
      path: '/en/key-competencies'
      fullPath: '/en/key-competencies'
      preLoaderRoute: typeof EnKeyCompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/eiraic-treasures': {
      id: '/en/eiraic-treasures'
      path: '/en/eiraic-treasures'
      fullPath: '/en/eiraic-treasures'
      preLoaderRoute: typeof EnEiraicTreasuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/$subject': {
      id: '/ga/leaving-cert/$subject'
      path: '/ga/leaving-cert/$subject'
      fullPath: '/ga/leaving-cert/$subject'
      preLoaderRoute: typeof GaLeavingCertSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/$subject': {
      id: '/en/leaving-cert/$subject'
      path: '/en/leaving-cert/$subject'
      fullPath: '/en/leaving-cert/$subject'
      preLoaderRoute: typeof EnLeavingCertSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/key-competencies/emblems': {
      id: '/en/key-competencies/emblems'
      path: '/emblems'
      fullPath: '/en/key-competencies/emblems'
      preLoaderRoute: typeof EnKeyCompetenciesEmblemsRouteImport
      parentRoute: typeof EnKeyCompetenciesRoute
    }
    '/en/assets/$subject': {
      id: '/en/assets/$subject'
      path: '/en/assets/$subject'
      fullPath: '/en/assets/$subject'
      preLoaderRoute: typeof EnAssetsSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/$subject/$section': {
      id: '/en/leaving-cert/$subject/$section'
      path: '/$section'
      fullPath: '/en/leaving-cert/$subject/$section'
      preLoaderRoute: typeof EnLeavingCertSubjectSectionRouteImport
      parentRoute: typeof EnLeavingCertSubjectRoute
    }
    '/en/leaving-cert/$subject/practice/$topic': {
      id: '/en/leaving-cert/$subject/practice/$topic'
      path: '/practice/$topic'
      fullPath: '/en/leaving-cert/$subject/practice/$topic'
      preLoaderRoute: typeof EnLeavingCertSubjectPracticeTopicRouteImport
      parentRoute: typeof EnLeavingCertSubjectRoute
    }
  }
}

interface EnKeyCompetenciesRouteChildren {
  EnKeyCompetenciesEmblemsRoute: typeof EnKeyCompetenciesEmblemsRoute
}

const EnKeyCompetenciesRouteChildren: EnKeyCompetenciesRouteChildren = {
  EnKeyCompetenciesEmblemsRoute: EnKeyCompetenciesEmblemsRoute,
}

const EnKeyCompetenciesRouteWithChildren =
  EnKeyCompetenciesRoute._addFileChildren(EnKeyCompetenciesRouteChildren)

interface EnLeavingCertSubjectRouteChildren {
  EnLeavingCertSubjectSectionRoute: typeof EnLeavingCertSubjectSectionRoute
  EnLeavingCertSubjectPracticeTopicRoute: typeof EnLeavingCertSubjectPracticeTopicRoute
}

const EnLeavingCertSubjectRouteChildren: EnLeavingCertSubjectRouteChildren = {
  EnLeavingCertSubjectSectionRoute: EnLeavingCertSubjectSectionRoute,
  EnLeavingCertSubjectPracticeTopicRoute:
    EnLeavingCertSubjectPracticeTopicRoute,
}

const EnLeavingCertSubjectRouteWithChildren =
  EnLeavingCertSubjectRoute._addFileChildren(EnLeavingCertSubjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnAboutRoute: EnAboutRoute,
  EnEiraicTreasuresRoute: EnEiraicTreasuresRoute,
  EnKeyCompetenciesRoute: EnKeyCompetenciesRouteWithChildren,
  EnMapRoute: EnMapRoute,
  GaAboutRoute: GaAboutRoute,
  GaEiraicTreasuresRoute: GaEiraicTreasuresRoute,
  EnAssetsSubjectRoute: EnAssetsSubjectRoute,
  EnLeavingCertSubjectRoute: EnLeavingCertSubjectRouteWithChildren,
  GaLeavingCertSubjectRoute: GaLeavingCertSubjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
