/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaEiraicTreasuresRouteImport } from './routes/ga/eiraic-treasures'
import { Route as GaAboutRouteImport } from './routes/ga/about'
import { Route as EnSubjectsRouteImport } from './routes/en/subjects'
import { Route as EnPracticeRouteImport } from './routes/en/practice'
import { Route as EnMapRouteImport } from './routes/en/map'
import { Route as EnKeyCompetenciesRouteImport } from './routes/en/key-competencies'
import { Route as EnEiraicTreasuresRouteImport } from './routes/en/eiraic-treasures'
import { Route as EnDiagramsRouteImport } from './routes/en/diagrams'
import { Route as EnBrownAjahRouteImport } from './routes/en/brown-ajah'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as GaLeavingCertSubjectRouteImport } from './routes/ga/leaving-cert/$subject'
import { Route as GaEiraicTreasuresTierRouteImport } from './routes/ga/eiraic-treasures.$tier'
import { Route as EnLeavingCertSubjectRouteImport } from './routes/en/leaving-cert/$subject'
import { Route as EnKeyCompetenciesEmblemsRouteImport } from './routes/en/key-competencies.emblems'
import { Route as EnKeyCompetenciesSlugRouteImport } from './routes/en/key-competencies.$slug'
import { Route as EnEiraicTreasuresTierRouteImport } from './routes/en/eiraic-treasures.$tier'
import { Route as EnBrownAjahMemberRouteImport } from './routes/en/brown-ajah.$member'
import { Route as EnAssetsSubjectRouteImport } from './routes/en/assets/$subject'
import { Route as EnLeavingCertSubjectSectionRouteImport } from './routes/en/leaving-cert/$subject.$section'
import { Route as EnLeavingCertSubjectPracticeTopicRouteImport } from './routes/en/leaving-cert/$subject.practice.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaEiraicTreasuresRoute = GaEiraicTreasuresRouteImport.update({
  id: '/ga/eiraic-treasures',
  path: '/ga/eiraic-treasures',
  getParentRoute: () => rootRouteImport,
} as any)
const GaAboutRoute = GaAboutRouteImport.update({
  id: '/ga/about',
  path: '/ga/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSubjectsRoute = EnSubjectsRouteImport.update({
  id: '/en/subjects',
  path: '/en/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPracticeRoute = EnPracticeRouteImport.update({
  id: '/en/practice',
  path: '/en/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMapRoute = EnMapRouteImport.update({
  id: '/en/map',
  path: '/en/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKeyCompetenciesRoute = EnKeyCompetenciesRouteImport.update({
  id: '/en/key-competencies',
  path: '/en/key-competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEiraicTreasuresRoute = EnEiraicTreasuresRouteImport.update({
  id: '/en/eiraic-treasures',
  path: '/en/eiraic-treasures',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDiagramsRoute = EnDiagramsRouteImport.update({
  id: '/en/diagrams',
  path: '/en/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBrownAjahRoute = EnBrownAjahRouteImport.update({
  id: '/en/brown-ajah',
  path: '/en/brown-ajah',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertSubjectRoute = GaLeavingCertSubjectRouteImport.update({
  id: '/ga/leaving-cert/$subject',
  path: '/ga/leaving-cert/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const GaEiraicTreasuresTierRoute = GaEiraicTreasuresTierRouteImport.update({
  id: '/$tier',
  path: '/$tier',
  getParentRoute: () => GaEiraicTreasuresRoute,
} as any)
const EnLeavingCertSubjectRoute = EnLeavingCertSubjectRouteImport.update({
  id: '/en/leaving-cert/$subject',
  path: '/en/leaving-cert/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKeyCompetenciesEmblemsRoute =
  EnKeyCompetenciesEmblemsRouteImport.update({
    id: '/emblems',
    path: '/emblems',
    getParentRoute: () => EnKeyCompetenciesRoute,
  } as any)
const EnKeyCompetenciesSlugRoute = EnKeyCompetenciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnKeyCompetenciesRoute,
} as any)
const EnEiraicTreasuresTierRoute = EnEiraicTreasuresTierRouteImport.update({
  id: '/$tier',
  path: '/$tier',
  getParentRoute: () => EnEiraicTreasuresRoute,
} as any)
const EnBrownAjahMemberRoute = EnBrownAjahMemberRouteImport.update({
  id: '/$member',
  path: '/$member',
  getParentRoute: () => EnBrownAjahRoute,
} as any)
const EnAssetsSubjectRoute = EnAssetsSubjectRouteImport.update({
  id: '/en/assets/$subject',
  path: '/en/assets/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertSubjectSectionRoute =
  EnLeavingCertSubjectSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => EnLeavingCertSubjectRoute,
  } as any)
const EnLeavingCertSubjectPracticeTopicRoute =
  EnLeavingCertSubjectPracticeTopicRouteImport.update({
    id: '/practice/$topic',
    path: '/practice/$topic',
    getParentRoute: () => EnLeavingCertSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en/about': typeof EnAboutRoute
  '/en/brown-ajah': typeof EnBrownAjahRouteWithChildren
  '/en/diagrams': typeof EnDiagramsRoute
  '/en/eiraic-treasures': typeof EnEiraicTreasuresRouteWithChildren
  '/en/key-competencies': typeof EnKeyCompetenciesRouteWithChildren
  '/en/map': typeof EnMapRoute
  '/en/practice': typeof EnPracticeRoute
  '/en/subjects': typeof EnSubjectsRoute
  '/ga/about': typeof GaAboutRoute
  '/ga/eiraic-treasures': typeof GaEiraicTreasuresRouteWithChildren
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/brown-ajah/$member': typeof EnBrownAjahMemberRoute
  '/en/eiraic-treasures/$tier': typeof EnEiraicTreasuresTierRoute
  '/en/key-competencies/$slug': typeof EnKeyCompetenciesSlugRoute
  '/en/key-competencies/emblems': typeof EnKeyCompetenciesEmblemsRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/eiraic-treasures/$tier': typeof GaEiraicTreasuresTierRoute
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en/about': typeof EnAboutRoute
  '/en/brown-ajah': typeof EnBrownAjahRouteWithChildren
  '/en/diagrams': typeof EnDiagramsRoute
  '/en/eiraic-treasures': typeof EnEiraicTreasuresRouteWithChildren
  '/en/key-competencies': typeof EnKeyCompetenciesRouteWithChildren
  '/en/map': typeof EnMapRoute
  '/en/practice': typeof EnPracticeRoute
  '/en/subjects': typeof EnSubjectsRoute
  '/ga/about': typeof GaAboutRoute
  '/ga/eiraic-treasures': typeof GaEiraicTreasuresRouteWithChildren
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/brown-ajah/$member': typeof EnBrownAjahMemberRoute
  '/en/eiraic-treasures/$tier': typeof EnEiraicTreasuresTierRoute
  '/en/key-competencies/$slug': typeof EnKeyCompetenciesSlugRoute
  '/en/key-competencies/emblems': typeof EnKeyCompetenciesEmblemsRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/eiraic-treasures/$tier': typeof GaEiraicTreasuresTierRoute
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en/about': typeof EnAboutRoute
  '/en/brown-ajah': typeof EnBrownAjahRouteWithChildren
  '/en/diagrams': typeof EnDiagramsRoute
  '/en/eiraic-treasures': typeof EnEiraicTreasuresRouteWithChildren
  '/en/key-competencies': typeof EnKeyCompetenciesRouteWithChildren
  '/en/map': typeof EnMapRoute
  '/en/practice': typeof EnPracticeRoute
  '/en/subjects': typeof EnSubjectsRoute
  '/ga/about': typeof GaAboutRoute
  '/ga/eiraic-treasures': typeof GaEiraicTreasuresRouteWithChildren
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/brown-ajah/$member': typeof EnBrownAjahMemberRoute
  '/en/eiraic-treasures/$tier': typeof EnEiraicTreasuresTierRoute
  '/en/key-competencies/$slug': typeof EnKeyCompetenciesSlugRoute
  '/en/key-competencies/emblems': typeof EnKeyCompetenciesEmblemsRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/eiraic-treasures/$tier': typeof GaEiraicTreasuresTierRoute
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en/about'
    | '/en/brown-ajah'
    | '/en/diagrams'
    | '/en/eiraic-treasures'
    | '/en/key-competencies'
    | '/en/map'
    | '/en/practice'
    | '/en/subjects'
    | '/ga/about'
    | '/ga/eiraic-treasures'
    | '/en/assets/$subject'
    | '/en/brown-ajah/$member'
    | '/en/eiraic-treasures/$tier'
    | '/en/key-competencies/$slug'
    | '/en/key-competencies/emblems'
    | '/en/leaving-cert/$subject'
    | '/ga/eiraic-treasures/$tier'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en/about'
    | '/en/brown-ajah'
    | '/en/diagrams'
    | '/en/eiraic-treasures'
    | '/en/key-competencies'
    | '/en/map'
    | '/en/practice'
    | '/en/subjects'
    | '/ga/about'
    | '/ga/eiraic-treasures'
    | '/en/assets/$subject'
    | '/en/brown-ajah/$member'
    | '/en/eiraic-treasures/$tier'
    | '/en/key-competencies/$slug'
    | '/en/key-competencies/emblems'
    | '/en/leaving-cert/$subject'
    | '/ga/eiraic-treasures/$tier'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  id:
    | '__root__'
    | '/'
    | '/en/about'
    | '/en/brown-ajah'
    | '/en/diagrams'
    | '/en/eiraic-treasures'
    | '/en/key-competencies'
    | '/en/map'
    | '/en/practice'
    | '/en/subjects'
    | '/ga/about'
    | '/ga/eiraic-treasures'
    | '/en/assets/$subject'
    | '/en/brown-ajah/$member'
    | '/en/eiraic-treasures/$tier'
    | '/en/key-competencies/$slug'
    | '/en/key-competencies/emblems'
    | '/en/leaving-cert/$subject'
    | '/ga/eiraic-treasures/$tier'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBrownAjahRoute: typeof EnBrownAjahRouteWithChildren
  EnDiagramsRoute: typeof EnDiagramsRoute
  EnEiraicTreasuresRoute: typeof EnEiraicTreasuresRouteWithChildren
  EnKeyCompetenciesRoute: typeof EnKeyCompetenciesRouteWithChildren
  EnMapRoute: typeof EnMapRoute
  EnPracticeRoute: typeof EnPracticeRoute
  EnSubjectsRoute: typeof EnSubjectsRoute
  GaAboutRoute: typeof GaAboutRoute
  GaEiraicTreasuresRoute: typeof GaEiraicTreasuresRouteWithChildren
  EnAssetsSubjectRoute: typeof EnAssetsSubjectRoute
  EnLeavingCertSubjectRoute: typeof EnLeavingCertSubjectRouteWithChildren
  GaLeavingCertSubjectRoute: typeof GaLeavingCertSubjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/eiraic-treasures': {
      id: '/ga/eiraic-treasures'
      path: '/ga/eiraic-treasures'
      fullPath: '/ga/eiraic-treasures'
      preLoaderRoute: typeof GaEiraicTreasuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/about': {
      id: '/ga/about'
      path: '/ga/about'
      fullPath: '/ga/about'
      preLoaderRoute: typeof GaAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/subjects': {
      id: '/en/subjects'
      path: '/en/subjects'
      fullPath: '/en/subjects'
      preLoaderRoute: typeof EnSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/practice': {
      id: '/en/practice'
      path: '/en/practice'
      fullPath: '/en/practice'
      preLoaderRoute: typeof EnPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/map': {
      id: '/en/map'
      path: '/en/map'
      fullPath: '/en/map'
      preLoaderRoute: typeof EnMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/key-competencies': {
      id: '/en/key-competencies'
      path: '/en/key-competencies'
      fullPath: '/en/key-competencies'
      preLoaderRoute: typeof EnKeyCompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/eiraic-treasures': {
      id: '/en/eiraic-treasures'
      path: '/en/eiraic-treasures'
      fullPath: '/en/eiraic-treasures'
      preLoaderRoute: typeof EnEiraicTreasuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/diagrams': {
      id: '/en/diagrams'
      path: '/en/diagrams'
      fullPath: '/en/diagrams'
      preLoaderRoute: typeof EnDiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/brown-ajah': {
      id: '/en/brown-ajah'
      path: '/en/brown-ajah'
      fullPath: '/en/brown-ajah'
      preLoaderRoute: typeof EnBrownAjahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/$subject': {
      id: '/ga/leaving-cert/$subject'
      path: '/ga/leaving-cert/$subject'
      fullPath: '/ga/leaving-cert/$subject'
      preLoaderRoute: typeof GaLeavingCertSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/eiraic-treasures/$tier': {
      id: '/ga/eiraic-treasures/$tier'
      path: '/$tier'
      fullPath: '/ga/eiraic-treasures/$tier'
      preLoaderRoute: typeof GaEiraicTreasuresTierRouteImport
      parentRoute: typeof GaEiraicTreasuresRoute
    }
    '/en/leaving-cert/$subject': {
      id: '/en/leaving-cert/$subject'
      path: '/en/leaving-cert/$subject'
      fullPath: '/en/leaving-cert/$subject'
      preLoaderRoute: typeof EnLeavingCertSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/key-competencies/emblems': {
      id: '/en/key-competencies/emblems'
      path: '/emblems'
      fullPath: '/en/key-competencies/emblems'
      preLoaderRoute: typeof EnKeyCompetenciesEmblemsRouteImport
      parentRoute: typeof EnKeyCompetenciesRoute
    }
    '/en/key-competencies/$slug': {
      id: '/en/key-competencies/$slug'
      path: '/$slug'
      fullPath: '/en/key-competencies/$slug'
      preLoaderRoute: typeof EnKeyCompetenciesSlugRouteImport
      parentRoute: typeof EnKeyCompetenciesRoute
    }
    '/en/eiraic-treasures/$tier': {
      id: '/en/eiraic-treasures/$tier'
      path: '/$tier'
      fullPath: '/en/eiraic-treasures/$tier'
      preLoaderRoute: typeof EnEiraicTreasuresTierRouteImport
      parentRoute: typeof EnEiraicTreasuresRoute
    }
    '/en/brown-ajah/$member': {
      id: '/en/brown-ajah/$member'
      path: '/$member'
      fullPath: '/en/brown-ajah/$member'
      preLoaderRoute: typeof EnBrownAjahMemberRouteImport
      parentRoute: typeof EnBrownAjahRoute
    }
    '/en/assets/$subject': {
      id: '/en/assets/$subject'
      path: '/en/assets/$subject'
      fullPath: '/en/assets/$subject'
      preLoaderRoute: typeof EnAssetsSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/$subject/$section': {
      id: '/en/leaving-cert/$subject/$section'
      path: '/$section'
      fullPath: '/en/leaving-cert/$subject/$section'
      preLoaderRoute: typeof EnLeavingCertSubjectSectionRouteImport
      parentRoute: typeof EnLeavingCertSubjectRoute
    }
    '/en/leaving-cert/$subject/practice/$topic': {
      id: '/en/leaving-cert/$subject/practice/$topic'
      path: '/practice/$topic'
      fullPath: '/en/leaving-cert/$subject/practice/$topic'
      preLoaderRoute: typeof EnLeavingCertSubjectPracticeTopicRouteImport
      parentRoute: typeof EnLeavingCertSubjectRoute
    }
  }
}

interface EnBrownAjahRouteChildren {
  EnBrownAjahMemberRoute: typeof EnBrownAjahMemberRoute
}

const EnBrownAjahRouteChildren: EnBrownAjahRouteChildren = {
  EnBrownAjahMemberRoute: EnBrownAjahMemberRoute,
}

const EnBrownAjahRouteWithChildren = EnBrownAjahRoute._addFileChildren(
  EnBrownAjahRouteChildren,
)

interface EnEiraicTreasuresRouteChildren {
  EnEiraicTreasuresTierRoute: typeof EnEiraicTreasuresTierRoute
}

const EnEiraicTreasuresRouteChildren: EnEiraicTreasuresRouteChildren = {
  EnEiraicTreasuresTierRoute: EnEiraicTreasuresTierRoute,
}

const EnEiraicTreasuresRouteWithChildren =
  EnEiraicTreasuresRoute._addFileChildren(EnEiraicTreasuresRouteChildren)

interface EnKeyCompetenciesRouteChildren {
  EnKeyCompetenciesSlugRoute: typeof EnKeyCompetenciesSlugRoute
  EnKeyCompetenciesEmblemsRoute: typeof EnKeyCompetenciesEmblemsRoute
}

const EnKeyCompetenciesRouteChildren: EnKeyCompetenciesRouteChildren = {
  EnKeyCompetenciesSlugRoute: EnKeyCompetenciesSlugRoute,
  EnKeyCompetenciesEmblemsRoute: EnKeyCompetenciesEmblemsRoute,
}

const EnKeyCompetenciesRouteWithChildren =
  EnKeyCompetenciesRoute._addFileChildren(EnKeyCompetenciesRouteChildren)

interface GaEiraicTreasuresRouteChildren {
  GaEiraicTreasuresTierRoute: typeof GaEiraicTreasuresTierRoute
}

const GaEiraicTreasuresRouteChildren: GaEiraicTreasuresRouteChildren = {
  GaEiraicTreasuresTierRoute: GaEiraicTreasuresTierRoute,
}

const GaEiraicTreasuresRouteWithChildren =
  GaEiraicTreasuresRoute._addFileChildren(GaEiraicTreasuresRouteChildren)

interface EnLeavingCertSubjectRouteChildren {
  EnLeavingCertSubjectSectionRoute: typeof EnLeavingCertSubjectSectionRoute
  EnLeavingCertSubjectPracticeTopicRoute: typeof EnLeavingCertSubjectPracticeTopicRoute
}

const EnLeavingCertSubjectRouteChildren: EnLeavingCertSubjectRouteChildren = {
  EnLeavingCertSubjectSectionRoute: EnLeavingCertSubjectSectionRoute,
  EnLeavingCertSubjectPracticeTopicRoute:
    EnLeavingCertSubjectPracticeTopicRoute,
}

const EnLeavingCertSubjectRouteWithChildren =
  EnLeavingCertSubjectRoute._addFileChildren(EnLeavingCertSubjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnAboutRoute: EnAboutRoute,
  EnBrownAjahRoute: EnBrownAjahRouteWithChildren,
  EnDiagramsRoute: EnDiagramsRoute,
  EnEiraicTreasuresRoute: EnEiraicTreasuresRouteWithChildren,
  EnKeyCompetenciesRoute: EnKeyCompetenciesRouteWithChildren,
  EnMapRoute: EnMapRoute,
  EnPracticeRoute: EnPracticeRoute,
  EnSubjectsRoute: EnSubjectsRoute,
  GaAboutRoute: GaAboutRoute,
  GaEiraicTreasuresRoute: GaEiraicTreasuresRouteWithChildren,
  EnAssetsSubjectRoute: EnAssetsSubjectRoute,
  EnLeavingCertSubjectRoute: EnLeavingCertSubjectRouteWithChildren,
  GaLeavingCertSubjectRoute: GaLeavingCertSubjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
