/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnMapRouteImport } from './routes/en/map'
import { Route as EnKeyCompetenciesRouteImport } from './routes/en/key-competencies'
import { Route as GaLeavingCertSubjectRouteImport } from './routes/ga/leaving-cert/$subject'
import { Route as EnLeavingCertSubjectRouteImport } from './routes/en/leaving-cert/$subject'
import { Route as EnAssetsSubjectRouteImport } from './routes/en/assets/$subject'
import { Route as EnLeavingCertSubjectSectionRouteImport } from './routes/en/leaving-cert/$subject.$section'
import { Route as EnLeavingCertSubjectPracticeTopicRouteImport } from './routes/en/leaving-cert/$subject.practice.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMapRoute = EnMapRouteImport.update({
  id: '/en/map',
  path: '/en/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKeyCompetenciesRoute = EnKeyCompetenciesRouteImport.update({
  id: '/en/key-competencies',
  path: '/en/key-competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const GaLeavingCertSubjectRoute = GaLeavingCertSubjectRouteImport.update({
  id: '/ga/leaving-cert/$subject',
  path: '/ga/leaving-cert/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertSubjectRoute = EnLeavingCertSubjectRouteImport.update({
  id: '/en/leaving-cert/$subject',
  path: '/en/leaving-cert/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAssetsSubjectRoute = EnAssetsSubjectRouteImport.update({
  id: '/en/assets/$subject',
  path: '/en/assets/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeavingCertSubjectSectionRoute =
  EnLeavingCertSubjectSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => EnLeavingCertSubjectRoute,
  } as any)
const EnLeavingCertSubjectPracticeTopicRoute =
  EnLeavingCertSubjectPracticeTopicRouteImport.update({
    id: '/practice/$topic',
    path: '/practice/$topic',
    getParentRoute: () => EnLeavingCertSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en/key-competencies': typeof EnKeyCompetenciesRoute
  '/en/map': typeof EnMapRoute
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en/key-competencies': typeof EnKeyCompetenciesRoute
  '/en/map': typeof EnMapRoute
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en/key-competencies': typeof EnKeyCompetenciesRoute
  '/en/map': typeof EnMapRoute
  '/en/assets/$subject': typeof EnAssetsSubjectRoute
  '/en/leaving-cert/$subject': typeof EnLeavingCertSubjectRouteWithChildren
  '/ga/leaving-cert/$subject': typeof GaLeavingCertSubjectRoute
  '/en/leaving-cert/$subject/$section': typeof EnLeavingCertSubjectSectionRoute
  '/en/leaving-cert/$subject/practice/$topic': typeof EnLeavingCertSubjectPracticeTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en/key-competencies'
    | '/en/map'
    | '/en/assets/$subject'
    | '/en/leaving-cert/$subject'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en/key-competencies'
    | '/en/map'
    | '/en/assets/$subject'
    | '/en/leaving-cert/$subject'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  id:
    | '__root__'
    | '/'
    | '/en/key-competencies'
    | '/en/map'
    | '/en/assets/$subject'
    | '/en/leaving-cert/$subject'
    | '/ga/leaving-cert/$subject'
    | '/en/leaving-cert/$subject/$section'
    | '/en/leaving-cert/$subject/practice/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnKeyCompetenciesRoute: typeof EnKeyCompetenciesRoute
  EnMapRoute: typeof EnMapRoute
  EnAssetsSubjectRoute: typeof EnAssetsSubjectRoute
  EnLeavingCertSubjectRoute: typeof EnLeavingCertSubjectRouteWithChildren
  GaLeavingCertSubjectRoute: typeof GaLeavingCertSubjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/map': {
      id: '/en/map'
      path: '/en/map'
      fullPath: '/en/map'
      preLoaderRoute: typeof EnMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/key-competencies': {
      id: '/en/key-competencies'
      path: '/en/key-competencies'
      fullPath: '/en/key-competencies'
      preLoaderRoute: typeof EnKeyCompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/leaving-cert/$subject': {
      id: '/ga/leaving-cert/$subject'
      path: '/ga/leaving-cert/$subject'
      fullPath: '/ga/leaving-cert/$subject'
      preLoaderRoute: typeof GaLeavingCertSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/$subject': {
      id: '/en/leaving-cert/$subject'
      path: '/en/leaving-cert/$subject'
      fullPath: '/en/leaving-cert/$subject'
      preLoaderRoute: typeof EnLeavingCertSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/assets/$subject': {
      id: '/en/assets/$subject'
      path: '/en/assets/$subject'
      fullPath: '/en/assets/$subject'
      preLoaderRoute: typeof EnAssetsSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leaving-cert/$subject/$section': {
      id: '/en/leaving-cert/$subject/$section'
      path: '/$section'
      fullPath: '/en/leaving-cert/$subject/$section'
      preLoaderRoute: typeof EnLeavingCertSubjectSectionRouteImport
      parentRoute: typeof EnLeavingCertSubjectRoute
    }
    '/en/leaving-cert/$subject/practice/$topic': {
      id: '/en/leaving-cert/$subject/practice/$topic'
      path: '/practice/$topic'
      fullPath: '/en/leaving-cert/$subject/practice/$topic'
      preLoaderRoute: typeof EnLeavingCertSubjectPracticeTopicRouteImport
      parentRoute: typeof EnLeavingCertSubjectRoute
    }
  }
}

interface EnLeavingCertSubjectRouteChildren {
  EnLeavingCertSubjectSectionRoute: typeof EnLeavingCertSubjectSectionRoute
  EnLeavingCertSubjectPracticeTopicRoute: typeof EnLeavingCertSubjectPracticeTopicRoute
}

const EnLeavingCertSubjectRouteChildren: EnLeavingCertSubjectRouteChildren = {
  EnLeavingCertSubjectSectionRoute: EnLeavingCertSubjectSectionRoute,
  EnLeavingCertSubjectPracticeTopicRoute:
    EnLeavingCertSubjectPracticeTopicRoute,
}

const EnLeavingCertSubjectRouteWithChildren =
  EnLeavingCertSubjectRoute._addFileChildren(EnLeavingCertSubjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnKeyCompetenciesRoute: EnKeyCompetenciesRoute,
  EnMapRoute: EnMapRoute,
  EnAssetsSubjectRoute: EnAssetsSubjectRoute,
  EnLeavingCertSubjectRoute: EnLeavingCertSubjectRouteWithChildren,
  GaLeavingCertSubjectRoute: GaLeavingCertSubjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
