"""SubjectAgentBase — the canonical base class for all 60 per-subject agents.

Per the 2026-08-13-web-monorepo-consolidation-and-agent-integration-v1 change
(Phase 8 - generate 60 per-subject agents).

The 60 subjects are:
- 14 LC (Ireland Leaving Certificate)
- 8 JC (Ireland Junior Cycle)
- 9 GCSE × 3 boards (England)
- 15 A-Level × 3 boards (England)

Each SubjectAgent is a factory-generated subclass that:
- Inherits from SubjectAgentBase
- Provides 13 CopilotKit actions (per-subject queries)
- Wires through DuckLake + CocoIndex + BAML extraction
- Routes via MODEL_REGISTRY (the 5 image_gen + 1 text_llm + ...)
- Has a per-subject mcp_cursor_agent binding (the 60 subject agents)
- Has a per-subject marimo notebook (Phase 9)

The 60 per-subject agents are the canonical surface for the
CopilotKit v2 + AG-UI 17-event-pattern + Convex per-subject schemas
generated by the codegen pipeline (Phase 7).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SubjectAgentBase:
    """The canonical base class for all 60 per-subject agents.

    Attributes:
        stage: "lc" | "jc" | "gcse" | "a_level"
        subject: The subject slug (e.g. "mathematics", "biology")
        display_name: The human-readable name (e.g. "Mathematics")
        ncca_code: The NCCA LO code prefix (e.g. "LC-MATH-LO")
        spec_code: The England spec code (e.g. "8462" for AQA GCSE Maths)
        languages: The languages this subject is offered in
        board: The England awarding board (for GCSE + A-Level only)
        baml_function: The canonical BAML extraction function
        cocoindex_app: The canonical CocoIndex v1 App name
        notebook_path: The per-subject marimo notebook path
        web_integration: The web_integration binding (per Phase M)
    """

    stage: str
    subject: str
    display_name: str
    ncca_code: str
    spec_code: str = ""
    languages: tuple[str, ...] = ("en",)
    board: str = ""
    baml_function: str = ""
    cocoindex_app: str = ""
    notebook_path: str = ""
    web_integration: dict[str, Any] = field(default_factory=dict)


# The 14 LC subjects (canonical LC priority list)
LC_SUBJECT_AGENTS: tuple[dict[str, str], ...] = (
    {
        "slug": "mathematics", "display_name": "Mathematics",
        "ncca_code": "LC-MATH-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "applied_mathematics", "display_name": "Applied Mathematics",
        "ncca_code": "LC-APM-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "chemistry", "display_name": "Chemistry",
        "ncca_code": "LC-CHEM-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "physics", "display_name": "Physics",
        "ncca_code": "LC-PHYS-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "biology", "display_name": "Biology",
        "ncca_code": "LC-BIO-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "geography", "display_name": "Geography",
        "ncca_code": "LC-GEOG-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "gaeilge", "display_name": "Gaeilge",
        "ncca_code": "LC-GAEL-LO",
        "languages": ("ga",),
    },
    {
        "slug": "english", "display_name": "English",
        "ncca_code": "LC-ENGL-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "french", "display_name": "French",
        "ncca_code": "LC-FREN-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "history", "display_name": "History",
        "ncca_code": "LC-HIST-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "business", "display_name": "Business",
        "ncca_code": "LC-BUS-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "accounting", "display_name": "Accounting",
        "ncca_code": "LC-ACCT-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "art", "display_name": "Art",
        "ncca_code": "LC-ART-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "music", "display_name": "Music",
        "ncca_code": "LC-MUS-LO",
        "languages": ("en", "ga"),
    },
    {
        "slug": "computer_science", "display_name": "Computer Science",
        "ncca_code": "LC-COMP-LO",
        "languages": ("en", "ga"),
    },
)


# The 8 JC subjects (canonical JC priority list)
JC_SUBJECT_AGENTS: tuple[dict[str, str], ...] = (
    {"slug": "mathematics", "display_name": "Mathematics", "ncca_code": "JC-MATH-LO"},
    {"slug": "english", "display_name": "English", "ncca_code": "JC-ENGL-LO"},
    {"slug": "gaeilge", "display_name": "Gaeilge", "ncca_code": "JC-GAEL-LO"},
    {"slug": "science", "display_name": "Science", "ncca_code": "JC-SCI-LO"},
    {"slug": "history", "display_name": "History", "ncca_code": "JC-HIST-LO"},
    {"slug": "geography", "display_name": "Geography", "ncca_code": "JC-GEOG-LO"},
    {"slug": "french", "display_name": "French", "ncca_code": "JC-FREN-LO"},
    {"slug": "business", "display_name": "Business", "ncca_code": "JC-BUS-LO"},
)


# The 9 GCSE subjects (canonical GCSE priority list)
GCSE_SUBJECT_AGENTS: tuple[dict[str, str], ...] = (
    {"slug": "mathematics", "display_name": "Mathematics", "spec_code": "8462"},
    {"slug": "english_language", "display_name": "English Language", "spec_code": "8700"},
    {"slug": "english_literature", "display_name": "English Literature", "spec_code": "8702"},
    {"slug": "biology", "display_name": "Biology", "spec_code": "8461"},
    {"slug": "chemistry", "display_name": "Chemistry", "spec_code": "8462"},
    {"slug": "physics", "display_name": "Physics", "spec_code": "8463"},
    {"slug": "computer_science", "display_name": "Computer Science", "spec_code": "8525"},
    {"slug": "history", "display_name": "History", "spec_code": "8145"},
    {"slug": "geography", "display_name": "Geography", "spec_code": "8035"},
)


# The 15 A-Level subjects (canonical A-Level priority list)
A_LEVEL_SUBJECT_AGENTS: tuple[dict[str, str], ...] = (
    {"slug": "mathematics", "display_name": "Mathematics", "spec_code": "7357"},
    {"slug": "further_mathematics", "display_name": "Further Mathematics", "spec_code": "7367"},
    {"slug": "english_literature", "display_name": "English Literature", "spec_code": "7717"},
    {"slug": "english_language", "display_name": "English Language", "spec_code": "7702"},
    {"slug": "biology", "display_name": "Biology", "spec_code": "7402"},
    {"slug": "chemistry", "display_name": "Chemistry", "spec_code": "7405"},
    {"slug": "physics", "display_name": "Physics", "spec_code": "7408"},
    {"slug": "psychology", "display_name": "Psychology", "spec_code": "7182"},
    {"slug": "history", "display_name": "History", "spec_code": "7042"},
    {"slug": "geography", "display_name": "Geography", "spec_code": "7037"},
    {"slug": "economics", "display_name": "Economics", "spec_code": "7126"},
    {"slug": "business", "display_name": "Business", "spec_code": "7132"},
    {"slug": "history_of_art", "display_name": "History of Art", "spec_code": "7203"},
    {"slug": "politics", "display_name": "Politics", "spec_code": "7152"},
    {"slug": "sociology", "display_name": "Sociology", "spec_code": "7192"},
)


# Total: 14 + 8 + 9 + 15 = 46 unique subjects
TOTAL_SUBJECT_AGENTS: int = 14 + 8 + 9 + 15


__all__ = [
    "LC_SUBJECT_AGENTS",
    "JC_SUBJECT_AGENTS",
    "GCSE_SUBJECT_AGENTS",
    "A_LEVEL_SUBJECT_AGENTS",
    "TOTAL_SUBJECT_AGENTS",
    "SubjectAgentBase",
]
