"""English schema — Cianfhoghlaim Oideachais.

DEPRECATED 2026-08-15 — the 12 hand-written Pydantic classes in this
module have been replaced with thin re-exports from the generated
BAML Python client. The BAML file
(``baml_src/british_isles/ireland/education/subjects/qpack_english.baml``)
is now the single source of truth. The hand-written schema was
explicitly documented as a BAML mirror.

Per the ``centralized-schema-registry`` capability (2026-08-15).
"""
from __future__ import annotations

# Re-export every Engl* class from the generated BAML Python client.
# Enums (str, Enum) and BaseModel subclasses are generated by
# `baml-cli generate` from `baml_src/.../qpack_english.baml`.
from baml_client.baml_client.types import (
    {prefix}BilingualText,
    {prefix}EvidenceLink,
    {prefix}NCCALevel,
    {prefix}TopicArea,
    {prefix}ItemType,
    {prefix}FeedbackChannel,
    {prefix}FormativeItem,
    {prefix}FormativeItemAttempt,
    {prefix}ScoreBreakdown,
    {prefix}QuestPack,
    {prefix}QuestPackValidation,
    {prefix}NCCALearningOutcome,
)

# Additional types that may exist per subject.
try:
    from baml_client.baml_client.types import (

    )
except ImportError:
    # Older BAML clients may not have these exact enum names; fall
    # back to the legacy strings.
    from enum import Enum

    class FormativeItemType(str, Enum):
        NUMERICAL = "numerical"
        SHORT_ANSWER = "short_answer"
        EXTENDED_RESPONSE = "extended_response"

    class FeedbackChannel(str, Enum):
        HINT = "hint"
        ELABORATION = "elaboration"
        MISCONCEPTION = "misconception"
        REINFORCEMENT = "reinforcement"


__all__ = [
    "BilingualText",
    "EvidenceLink",
    "EnglNCCALevel",
    "EnglTopicArea",
    "EnglNCCALearningOutcome",
    "FormativeItem",
    "FormativeItemAttempt",
    "ScoreBreakdown",
    "QuestPack",
    "QuestPackValidation",
    "FormativeItemType",
    "FeedbackChannel",
    "EnglBilingualText",
    "EnglEvidenceLink",
    "EnglFormativeItem",
    "EnglFormativeItemAttempt",
    "EnglScoreBreakdown",
    "EnglQuestPack",
    "EnglQuestPackValidation",
]
