/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCodeolasRouteImport } from './routes/api/codeolas'
import { Route as ApiBrowserRouteImport } from './routes/api/browser'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as LayoutWidgetsRouteImport } from './routes/_layout/widgets'
import { Route as LayoutToolsRouteImport } from './routes/_layout/tools'
import { Route as LayoutStacksIndexRouteImport } from './routes/_layout/stacks/index'
import { Route as LayoutAnalyticsIndexRouteImport } from './routes/_layout/analytics/index'
import { Route as LayoutAgentsIndexRouteImport } from './routes/_layout/agents/index'
import { Route as ApiMcpGatewayRouteImport } from './routes/api/mcp.gateway'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutMonitoringMetricsRouteImport } from './routes/_layout/monitoring/metrics'
import { Route as LayoutMonitoringLogsRouteImport } from './routes/_layout/monitoring/logs'
import { Route as LayoutDataPipelinesRouteImport } from './routes/_layout/data/pipelines'
import { Route as LayoutAgentsChatRouteImport } from './routes/_layout/agents/chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeolasRoute = ApiCodeolasRouteImport.update({
  id: '/api/codeolas',
  path: '/api/codeolas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserRoute = ApiBrowserRouteImport.update({
  id: '/api/browser',
  path: '/api/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWidgetsRoute = LayoutWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStacksIndexRoute = LayoutStacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsIndexRoute = LayoutAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsIndexRoute = LayoutAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiMcpGatewayRoute = ApiMcpGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => ApiMcpRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMonitoringMetricsRoute = LayoutMonitoringMetricsRouteImport.update({
  id: '/monitoring/metrics',
  path: '/monitoring/metrics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMonitoringLogsRoute = LayoutMonitoringLogsRouteImport.update({
  id: '/monitoring/logs',
  path: '/monitoring/logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDataPipelinesRoute = LayoutDataPipelinesRouteImport.update({
  id: '/data/pipelines',
  path: '/data/pipelines',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsChatRoute = LayoutAgentsChatRouteImport.update({
  id: '/agents/chat',
  path: '/agents/chat',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof LayoutToolsRoute
  '/widgets': typeof LayoutWidgetsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/browser': typeof ApiBrowserRoute
  '/api/codeolas': typeof ApiCodeolasRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/agents/chat': typeof LayoutAgentsChatRoute
  '/data/pipelines': typeof LayoutDataPipelinesRoute
  '/monitoring/logs': typeof LayoutMonitoringLogsRoute
  '/monitoring/metrics': typeof LayoutMonitoringMetricsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/gateway': typeof ApiMcpGatewayRoute
  '/agents/': typeof LayoutAgentsIndexRoute
  '/analytics/': typeof LayoutAnalyticsIndexRoute
  '/stacks/': typeof LayoutStacksIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/tools': typeof LayoutToolsRoute
  '/widgets': typeof LayoutWidgetsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/browser': typeof ApiBrowserRoute
  '/api/codeolas': typeof ApiCodeolasRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/agents/chat': typeof LayoutAgentsChatRoute
  '/data/pipelines': typeof LayoutDataPipelinesRoute
  '/monitoring/logs': typeof LayoutMonitoringLogsRoute
  '/monitoring/metrics': typeof LayoutMonitoringMetricsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/gateway': typeof ApiMcpGatewayRoute
  '/agents': typeof LayoutAgentsIndexRoute
  '/analytics': typeof LayoutAnalyticsIndexRoute
  '/stacks': typeof LayoutStacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/tools': typeof LayoutToolsRoute
  '/_layout/widgets': typeof LayoutWidgetsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/browser': typeof ApiBrowserRoute
  '/api/codeolas': typeof ApiCodeolasRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/agents/chat': typeof LayoutAgentsChatRoute
  '/_layout/data/pipelines': typeof LayoutDataPipelinesRoute
  '/_layout/monitoring/logs': typeof LayoutMonitoringLogsRoute
  '/_layout/monitoring/metrics': typeof LayoutMonitoringMetricsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/gateway': typeof ApiMcpGatewayRoute
  '/_layout/agents/': typeof LayoutAgentsIndexRoute
  '/_layout/analytics/': typeof LayoutAnalyticsIndexRoute
  '/_layout/stacks/': typeof LayoutStacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tools'
    | '/widgets'
    | '/api/agent'
    | '/api/browser'
    | '/api/codeolas'
    | '/api/health'
    | '/api/mcp'
    | '/agents/chat'
    | '/data/pipelines'
    | '/monitoring/logs'
    | '/monitoring/metrics'
    | '/api/auth/$'
    | '/api/mcp/gateway'
    | '/agents/'
    | '/analytics/'
    | '/stacks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/tools'
    | '/widgets'
    | '/api/agent'
    | '/api/browser'
    | '/api/codeolas'
    | '/api/health'
    | '/api/mcp'
    | '/'
    | '/agents/chat'
    | '/data/pipelines'
    | '/monitoring/logs'
    | '/monitoring/metrics'
    | '/api/auth/$'
    | '/api/mcp/gateway'
    | '/agents'
    | '/analytics'
    | '/stacks'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/tools'
    | '/_layout/widgets'
    | '/api/agent'
    | '/api/browser'
    | '/api/codeolas'
    | '/api/health'
    | '/api/mcp'
    | '/_layout/'
    | '/_layout/agents/chat'
    | '/_layout/data/pipelines'
    | '/_layout/monitoring/logs'
    | '/_layout/monitoring/metrics'
    | '/api/auth/$'
    | '/api/mcp/gateway'
    | '/_layout/agents/'
    | '/_layout/analytics/'
    | '/_layout/stacks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiBrowserRoute: typeof ApiBrowserRoute
  ApiCodeolasRoute: typeof ApiCodeolasRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codeolas': {
      id: '/api/codeolas'
      path: '/api/codeolas'
      fullPath: '/api/codeolas'
      preLoaderRoute: typeof ApiCodeolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser': {
      id: '/api/browser'
      path: '/api/browser'
      fullPath: '/api/browser'
      preLoaderRoute: typeof ApiBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/widgets': {
      id: '/_layout/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof LayoutWidgetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stacks/': {
      id: '/_layout/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof LayoutStacksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/': {
      id: '/_layout/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof LayoutAnalyticsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents/': {
      id: '/_layout/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof LayoutAgentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/mcp/gateway': {
      id: '/api/mcp/gateway'
      path: '/gateway'
      fullPath: '/api/mcp/gateway'
      preLoaderRoute: typeof ApiMcpGatewayRouteImport
      parentRoute: typeof ApiMcpRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/monitoring/metrics': {
      id: '/_layout/monitoring/metrics'
      path: '/monitoring/metrics'
      fullPath: '/monitoring/metrics'
      preLoaderRoute: typeof LayoutMonitoringMetricsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/monitoring/logs': {
      id: '/_layout/monitoring/logs'
      path: '/monitoring/logs'
      fullPath: '/monitoring/logs'
      preLoaderRoute: typeof LayoutMonitoringLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/data/pipelines': {
      id: '/_layout/data/pipelines'
      path: '/data/pipelines'
      fullPath: '/data/pipelines'
      preLoaderRoute: typeof LayoutDataPipelinesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents/chat': {
      id: '/_layout/agents/chat'
      path: '/agents/chat'
      fullPath: '/agents/chat'
      preLoaderRoute: typeof LayoutAgentsChatRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutToolsRoute: typeof LayoutToolsRoute
  LayoutWidgetsRoute: typeof LayoutWidgetsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAgentsChatRoute: typeof LayoutAgentsChatRoute
  LayoutDataPipelinesRoute: typeof LayoutDataPipelinesRoute
  LayoutMonitoringLogsRoute: typeof LayoutMonitoringLogsRoute
  LayoutMonitoringMetricsRoute: typeof LayoutMonitoringMetricsRoute
  LayoutAgentsIndexRoute: typeof LayoutAgentsIndexRoute
  LayoutAnalyticsIndexRoute: typeof LayoutAnalyticsIndexRoute
  LayoutStacksIndexRoute: typeof LayoutStacksIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutToolsRoute: LayoutToolsRoute,
  LayoutWidgetsRoute: LayoutWidgetsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAgentsChatRoute: LayoutAgentsChatRoute,
  LayoutDataPipelinesRoute: LayoutDataPipelinesRoute,
  LayoutMonitoringLogsRoute: LayoutMonitoringLogsRoute,
  LayoutMonitoringMetricsRoute: LayoutMonitoringMetricsRoute,
  LayoutAgentsIndexRoute: LayoutAgentsIndexRoute,
  LayoutAnalyticsIndexRoute: LayoutAnalyticsIndexRoute,
  LayoutStacksIndexRoute: LayoutStacksIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ApiMcpRouteChildren {
  ApiMcpGatewayRoute: typeof ApiMcpGatewayRoute
}

const ApiMcpRouteChildren: ApiMcpRouteChildren = {
  ApiMcpGatewayRoute: ApiMcpGatewayRoute,
}

const ApiMcpRouteWithChildren =
  ApiMcpRoute._addFileChildren(ApiMcpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiBrowserRoute: ApiBrowserRoute,
  ApiCodeolasRoute: ApiCodeolasRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
