"""Junior Cycle BAML extraction package (BIEP v2).

This package re-exports the 4 BAML extraction functions for the
Junior Cycle promotion from a single DLT source to a full BIEP-grade
pipeline (per the 2026-07-20-biep-v2-junior-cycle-extraction-v1 change).

The canonical BAML files are at:
    baml_src/british_isles/ireland/education/junior_cycle/{jc_curriculum_syllabus,jc_cba_descriptor,jc_short_course,jc_exam_paper_layout}.baml

The Python client generated by `baml-cli generate` re-exports the
generated Pydantic classes here.
"""
from __future__ import annotations

# Re-export the BAML-generated client (lazily imported to avoid forcing
# baml_client regeneration at import time).
try:
    from cianfhoghlaim.baml_client.types import (  # type: ignore[import-not-found]
        JCCurriculumSpec as _JCCurriculumSpec,
        JCStrandDescriptor as _JCStrandDescriptor,
        JCLearningOutcome as _JCLearningOutcome,
        JCExamPaper as _JCExamPaper,
        JCExamSection as _JCExamSection,
        JCQuestion as _JCQuestion,
        CBATask as _CBATask,
        JCShortCourse as _JCShortCourse,
        YearBand as _YearBand,
        JuniorCycleSubjectSlug as _JuniorCycleSubjectSlug,
        JuniorCycleLanguage as _JuniorCycleLanguage,
        JCStrand as _JCStrand,
        JCExamLevel as _JCExamLevel,
        JCQuestionType as _JCQuestionType,
    )
    __all__ = [
        "JCCurriculumSpec",
        "JCStrandDescriptor",
        "JCLearningOutcome",
        "JCExamPaper",
        "JCExamSection",
        "JCQuestion",
        "CBATask",
        "JCShortCourse",
        "YearBand",
        "JuniorCycleSubjectSlug",
        "JuniorCycleLanguage",
        "JCStrand",
        "JCExamLevel",
        "JCQuestionType",
    ]
except ImportError:
    # BAML client not yet generated — the canonical __all__ will be
    # populated by `baml-cli generate` + the runtime import.
    __all__: list[str] = []
