/**
 * Authentication Automation Module
 *
 * BetterAuth + PocketID configuration generation and client registration.
 */

import { dag, Container, Directory, Secret, object, func } from "@dagger.io/dagger";
import { APP_CONFIGS } from "./apps.js";

export interface AuthConfig {
  app: string;
  providerId: string;
  clientId: string;
  clientSecret: string;
  discoveryUrl: string;
  scopes: string[];
  trustedOrigins: string[];
}

/**
 * Default PocketID configuration
 */
const POCKETID_CONFIG = {
  issuer: "https://auth.cianfhoghlaim.ie",
  scopes: ["openid", "profile", "email", "groups"],
};

@object()
export class AuthAutomation {
  /**
   * Generate BetterAuth configuration for an app
   */
  @func()
  generateAuthConfig(
    appName: string,
    clientId: string,
    clientSecret: string,
    pocketIdIssuer: string = POCKETID_CONFIG.issuer,
    devPort?: number
  ): string {
    const app = APP_CONFIGS[appName];
    if (!app) {
      throw new Error("Unknown app: " + appName);
    }

    const port = devPort || app.defaultPort;
    const prodDomain = appName + ".cianfhoghlaim.ie";

    const config: AuthConfig = {
      app: appName,
      providerId: "pocketid",
      clientId,
      clientSecret,
      discoveryUrl: pocketIdIssuer + "/.well-known/openid-configuration",
      scopes: POCKETID_CONFIG.scopes,
      trustedOrigins: [
        "http://localhost:" + port,
        "https://" + prodDomain,
      ],
    };

    return JSON.stringify(config, null, 2);
  }

  /**
   * Generate auth.ts file content for BetterAuth
   */
  @func()
  generateAuthFile(appName: string, devPort?: number): string {
    const app = APP_CONFIGS[appName];
    if (!app) {
      throw new Error("Unknown app: " + appName);
    }

    const port = devPort || app.defaultPort;
    const prodDomain = appName.replace(/-/g, "") + ".cianfhoghlaim.ie";

    return `/**
 * BetterAuth Configuration for ${appName}
 *
 * Auto-generated by Dagger auth module.
 * Uses PocketID OAuth for authentication.
 */

import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { genericOAuth } from "better-auth/plugins";
import { db } from "../db/drizzle";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
  }),
  emailAndPassword: {
    enabled: true,
  },
  plugins: [
    genericOAuth({
      config: [
        {
          providerId: "pocketid",
          clientId: process.env.POCKETID_CLIENT_ID!,
          clientSecret: process.env.POCKETID_CLIENT_SECRET!,
          discoveryUrl: \`\${process.env.POCKETID_ISSUER || "https://auth.cianfhoghlaim.ie"}/.well-known/openid-configuration\`,
          scopes: ["openid", "profile", "email", "groups"],
        },
      ],
    }),
  ],
  trustedOrigins: [
    "http://localhost:${port}",
    "https://${prodDomain}",
  ],
});

export type Session = typeof auth.$Infer.Session;
export type User = typeof auth.$Infer.Session.user;
`;
  }

  /**
   * Generate auth-client.ts file content
   */
  @func()
  generateAuthClientFile(appName: string): string {
    return `/**
 * BetterAuth Client for ${appName}
 *
 * Auto-generated by Dagger auth module.
 */

import { createAuthClient } from "better-auth/react";
import { genericOAuthClient } from "better-auth/client/plugins";

const baseURL =
  typeof window !== "undefined"
    ? window.location.origin
    : process.env.AUTH_BASE_URL || "http://localhost:3000";

export const authClient = createAuthClient({
  baseURL,
  plugins: [genericOAuthClient()],
});

export const { signIn, signOut, signUp, useSession } = authClient;
`;
  }

  /**
   * Generate .env entries for auth
   */
  @func()
  generateEnvEntries(appName: string, devPort?: number): string {
    const app = APP_CONFIGS[appName];
    if (!app) {
      throw new Error("Unknown app: " + appName);
    }

    const port = devPort || app.defaultPort;

    return `# Authentication (BetterAuth + PocketID)
# Fill in with your PocketID client credentials
POCKETID_CLIENT_ID=your-client-id-here
POCKETID_CLIENT_SECRET=your-client-secret-here
POCKETID_ISSUER=https://auth.cianfhoghlaim.ie

# Auth URLs
AUTH_BASE_URL=http://localhost:${port}
AUTH_REDIRECT_URI=http://localhost:${port}/api/auth/callback/oidc

# Session secret (generate with: openssl rand -base64 32)
BETTER_AUTH_SECRET=change-this-to-a-random-secret
`;
  }

  /**
   * Generate login page component
   */
  @func()
  generateLoginPage(appName: string): string {
    return `/**
 * Login Page for ${appName}
 *
 * Auto-generated by Dagger auth module.
 */

import { useState } from "react";
import { signIn } from "../lib/auth-client";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleOIDCLogin = async () => {
    setLoading(true);
    try {
      await signIn.oauth2({
        providerId: "pocketid",
        callbackURL: "/",
      });
    } catch (e) {
      setError("Failed to initiate login");
    } finally {
      setLoading(false);
    }
  };

  const handleEmailLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      const result = await signIn.email({
        email,
        password,
        callbackURL: "/",
      });

      if (result.error) {
        setError(result.error.message || "Login failed");
      }
    } catch (e) {
      setError("An error occurred");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-background">
      <div className="w-full max-w-md space-y-8 p-8">
        <div className="text-center">
          <h1 className="text-2xl font-bold">${appName}</h1>
          <p className="text-muted-foreground">Sign in to continue</p>
        </div>

        <button
          onClick={handleOIDCLogin}
          disabled={loading}
          className="w-full py-2 px-4 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 disabled:opacity-50"
        >
          Sign in with PocketID
        </button>

        <div className="relative">
          <div className="absolute inset-0 flex items-center">
            <span className="w-full border-t" />
          </div>
          <div className="relative flex justify-center text-xs uppercase">
            <span className="bg-background px-2 text-muted-foreground">
              Or continue with email
            </span>
          </div>
        </div>

        <form onSubmit={handleEmailLogin} className="space-y-4">
          {error && (
            <div className="p-2 text-sm text-red-500 bg-red-50 rounded">
              {error}
            </div>
          )}

          <div>
            <label htmlFor="email" className="block text-sm font-medium">
              Email
            </label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="mt-1 block w-full px-3 py-2 border rounded-md"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium">
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="mt-1 block w-full px-3 py-2 border rounded-md"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-2 px-4 border border-input bg-background rounded-md hover:bg-accent disabled:opacity-50"
          >
            Sign in with Email
          </button>
        </form>
      </div>
    </div>
  );
}
`;
  }

  /**
   * Write auth files to an app directory
   */
  @func()
  async writeAuthFiles(
    source: Directory,
    appName: string,
    devPort?: number
  ): Promise<Directory> {
    const app = APP_CONFIGS[appName];
    if (!app) {
      throw new Error("Unknown app: " + appName);
    }

    const authFile = this.generateAuthFile(appName, devPort);
    const authClientFile = this.generateAuthClientFile(appName);
    const envEntries = this.generateEnvEntries(appName, devPort);

    // Write files
    let result = source
      .withNewFile(app.path + "/lib/auth.ts", authFile)
      .withNewFile(app.path + "/lib/auth-client.ts", authClientFile);

    // Append env entries to .env.example if it exists, otherwise create
    const envContent = envEntries;
    result = result.withNewFile(app.path + "/.env.auth.example", envContent);

    return result;
  }

  /**
   * List apps that need auth setup
   */
  @func()
  listAppsNeedingAuth(): string {
    const lines = ["Apps requiring authentication:", ""];

    for (const [name, config] of Object.entries(APP_CONFIGS)) {
      if (config.requiresAuth) {
        lines.push("  " + name + " (port " + config.defaultPort + ")");
      }
    }

    return lines.join("\n");
  }

  /**
   * Generate redirect URIs for PocketID client registration
   */
  @func()
  getRedirectUris(appName: string): string[] {
    const app = APP_CONFIGS[appName];
    if (!app) {
      throw new Error("Unknown app: " + appName);
    }

    const prodDomain = appName.replace(/-/g, "") + ".cianfhoghlaim.ie";

    return [
      "http://localhost:" + app.defaultPort + "/api/auth/callback/oidc",
      "https://" + prodDomain + "/api/auth/callback/oidc",
    ];
  }
}
