/**
 * Observability Module
 *
 * Provides integration with:
 * - Langfuse (LLM observability - traces, prompts, completions)
 * - MLflow (ML experiment tracking and model registry)
 * - Logfire (structured logging for FastAPI/Python)
 */

import { dag, Container, Directory, object, func } from "@dagger.io/dagger";

// =============================================================================
// Types
// =============================================================================

export interface LangfuseConfig {
  host: string;
  publicKey?: string;
  secretKey?: string;
  projectId?: string;
  enabled: boolean;
}

export interface MLflowConfig {
  trackingUri: string;
  artifactUri?: string;
  experimentName?: string;
  enabled: boolean;
}

export interface LogfireConfig {
  projectName: string;
  token?: string;
  serviceVersion?: string;
  environment: string;
}

export interface InstrumentationConfig {
  langfuse: LangfuseConfig;
  mlflow: MLflowConfig;
  logfire?: LogfireConfig;
}

// =============================================================================
// Default endpoints
// =============================================================================

// OLM proxy endpoints for private access (no SSO required)
const DEFAULT_LANGFUSE_HOST = "http://pangolin.cianfhoghlaim.ie:3000";
const DEFAULT_LANGFUSE_LOCAL = "http://localhost:3000";
// Public HTTPS endpoints (require SSO via TinyAuth)
const DEFAULT_LANGFUSE_PUBLIC = "https://langfuse.cianfhoghlaim.ie";

// OLM proxy endpoint for private access
const DEFAULT_MLFLOW_URI = "http://pangolin.cianfhoghlaim.ie:5000";
const DEFAULT_MLFLOW_LOCAL = "http://localhost:5000";
// Public HTTPS endpoint (requires SSO)
const DEFAULT_MLFLOW_PUBLIC = "https://mlflow.cianfhoghlaim.ie";

@object()
export class Observability {
  /**
   * Get Langfuse configuration for an app
   */
  @func()
  getLangfuseConfig(
    appName: string,
    host?: string,
    local: boolean = false
  ): LangfuseConfig {
    return {
      host: host || (local ? DEFAULT_LANGFUSE_LOCAL : DEFAULT_LANGFUSE_HOST),
      projectId: appName,
      enabled: true,
    };
  }

  /**
   * Get MLflow configuration
   */
  @func()
  getMLflowConfig(
    experimentName?: string,
    local: boolean = false
  ): MLflowConfig {
    return {
      trackingUri: local ? DEFAULT_MLFLOW_LOCAL : DEFAULT_MLFLOW_URI,
      experimentName,
      enabled: true,
    };
  }

  /**
   * Test connection to Langfuse
   */
  @func()
  async testLangfuseConnection(host?: string): Promise<boolean> {
    const url = host || DEFAULT_LANGFUSE_HOST;

    try {
      const result = await dag
        .container()
        .from("curlimages/curl:latest")
        .withExec(["curl", "-sf", `${url}/api/public/health`])
        .stdout();

      return result.includes("OK") || result.length > 0;
    } catch {
      return false;
    }
  }

  /**
   * Test connection to MLflow
   */
  @func()
  async testMLflowConnection(trackingUri?: string): Promise<boolean> {
    const url = trackingUri || DEFAULT_MLFLOW_URI;

    try {
      const result = await dag
        .container()
        .from("curlimages/curl:latest")
        .withExec(["curl", "-sf", `${url}/health`])
        .stdout();

      return result.length > 0;
    } catch {
      return false;
    }
  }

  /**
   * List MLflow experiments
   */
  @func()
  async listExperiments(trackingUri?: string): Promise<string[]> {
    const url = trackingUri || DEFAULT_MLFLOW_URI;

    try {
      const result = await dag
        .container()
        .from("curlimages/curl:latest")
        .withExec(["curl", "-sf", `${url}/api/2.0/mlflow/experiments/search`, "-d", '{"max_results": 100}'])
        .stdout();

      const parsed = JSON.parse(result);
      if (parsed.experiments && Array.isArray(parsed.experiments)) {
        return parsed.experiments.map((e: { name: string }) => e.name);
      }
      return [];
    } catch {
      return [];
    }
  }

  /**
   * Generate instrumentation code for TypeScript/Bun apps
   */
  @func()
  generateTypescriptInstrumentation(appName: string): string {
    return `// ${appName} - Langfuse Instrumentation
// Auto-generated by Dagger Observability module

import { Langfuse } from "langfuse";

// Initialize Langfuse client
export const langfuse = new Langfuse({
  publicKey: process.env.LANGFUSE_PUBLIC_KEY,
  secretKey: process.env.LANGFUSE_SECRET_KEY,
  baseUrl: process.env.LANGFUSE_HOST || "${DEFAULT_LANGFUSE_HOST}",
  flushAt: 15,
  flushInterval: 10000,
});

// Create a trace for a request
export function createTrace(name: string, metadata?: Record<string, unknown>) {
  return langfuse.trace({
    name,
    metadata: {
      app: "${appName}",
      ...metadata,
    },
  });
}

// Wrap an LLM call with tracing
export async function traceGeneration<T>(
  trace: ReturnType<typeof langfuse.trace>,
  params: {
    name: string;
    model: string;
    input: unknown;
    fn: () => Promise<T>;
  }
): Promise<T> {
  const generation = trace.generation({
    name: params.name,
    model: params.model,
    input: params.input,
  });

  try {
    const result = await params.fn();
    generation.end({
      output: result,
    });
    return result;
  } catch (error) {
    generation.end({
      statusMessage: error instanceof Error ? error.message : "Unknown error",
      level: "ERROR",
    });
    throw error;
  }
}

// Shutdown hook
export function shutdown() {
  return langfuse.shutdownAsync();
}

// Export convenience decorator
export function observed(name: string) {
  return function <T extends (...args: unknown[]) => Promise<unknown>>(
    target: T
  ): T {
    return (async function (...args: Parameters<T>) {
      const trace = createTrace(name);
      try {
        const result = await target.apply(this, args);
        trace.update({ output: result });
        return result;
      } catch (error) {
        trace.update({
          statusMessage: error instanceof Error ? error.message : "Unknown error",
          level: "ERROR",
        });
        throw error;
      }
    }) as T;
  };
}
`;
  }

  /**
   * Generate instrumentation code for Python/FastAPI apps
   */
  @func()
  generatePythonInstrumentation(appName: string): string {
    return `# ${appName} - Langfuse + Logfire Instrumentation
# Auto-generated by Dagger Observability module

import os
from functools import wraps
from typing import Any, Callable, TypeVar

from langfuse import Langfuse
from langfuse.decorators import observe, langfuse_context

# Optional: Logfire for structured logging
try:
    import logfire
    LOGFIRE_ENABLED = os.environ.get("LOGFIRE_TOKEN") is not None
except ImportError:
    LOGFIRE_ENABLED = False

# Initialize Langfuse client
langfuse = Langfuse(
    public_key=os.environ.get("LANGFUSE_PUBLIC_KEY"),
    secret_key=os.environ.get("LANGFUSE_SECRET_KEY"),
    host=os.environ.get("LANGFUSE_HOST", "${DEFAULT_LANGFUSE_HOST}"),
)

# Initialize Logfire if available
if LOGFIRE_ENABLED:
    logfire.configure(
        service_name="${appName}",
        service_version=os.environ.get("SERVICE_VERSION", "1.0.0"),
    )

T = TypeVar("T")


def create_trace(name: str, metadata: dict[str, Any] | None = None):
    """Create a Langfuse trace for a request."""
    return langfuse.trace(
        name=name,
        metadata={
            "app": "${appName}",
            **(metadata or {}),
        },
    )


def trace_llm_call(
    name: str,
    model: str,
    input_data: Any,
    output_data: Any,
    metadata: dict[str, Any] | None = None,
):
    """Log an LLM call to Langfuse."""
    trace = create_trace(name, metadata)
    trace.generation(
        name=name,
        model=model,
        input=input_data,
        output=output_data,
    )
    return trace


def shutdown():
    """Flush and shutdown Langfuse."""
    langfuse.flush()


# FastAPI integration
def instrument_fastapi(app):
    """Instrument a FastAPI app with Langfuse and Logfire."""
    from fastapi import Request
    from starlette.middleware.base import BaseHTTPMiddleware

    class LangfuseMiddleware(BaseHTTPMiddleware):
        async def dispatch(self, request: Request, call_next):
            trace = create_trace(
                name=f"{request.method} {request.url.path}",
                metadata={
                    "method": request.method,
                    "path": request.url.path,
                    "query": str(request.query_params),
                },
            )

            # Store trace in request state for use in handlers
            request.state.langfuse_trace = trace

            try:
                response = await call_next(request)
                trace.update(output={"status_code": response.status_code})
                return response
            except Exception as e:
                trace.update(
                    output={"error": str(e)},
                    level="ERROR",
                )
                raise

    app.add_middleware(LangfuseMiddleware)

    # Add Logfire instrumentation if available
    if LOGFIRE_ENABLED:
        logfire.instrument_fastapi(app)

    return app


# MLflow integration
def log_to_mlflow(
    experiment_name: str,
    run_name: str,
    params: dict[str, Any],
    metrics: dict[str, float],
    artifacts: dict[str, str] | None = None,
):
    """Log experiment results to MLflow."""
    import mlflow

    mlflow.set_tracking_uri(os.environ.get("MLFLOW_TRACKING_URI", "${DEFAULT_MLFLOW_URI}"))
    mlflow.set_experiment(experiment_name)

    with mlflow.start_run(run_name=run_name):
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)

        if artifacts:
            for name, path in artifacts.items():
                mlflow.log_artifact(path, name)
`;
  }

  /**
   * Generate environment variables for observability
   */
  @func()
  generateEnvVars(appName: string): string {
    return `# Observability Configuration for ${appName}
# Auto-generated by Dagger Observability module

# Langfuse - LLM Observability
LANGFUSE_HOST=${DEFAULT_LANGFUSE_HOST}
LANGFUSE_PUBLIC_KEY=  # Get from Langfuse dashboard
LANGFUSE_SECRET_KEY=  # Get from Langfuse dashboard

# MLflow - Experiment Tracking
MLFLOW_TRACKING_URI=${DEFAULT_MLFLOW_URI}
MLFLOW_EXPERIMENT_NAME=${appName}

# Logfire - Structured Logging (optional)
LOGFIRE_TOKEN=  # Get from Logfire dashboard
SERVICE_VERSION=1.0.0
`;
  }

  /**
   * Verify tracing is working for a project
   */
  @func()
  async verifyTracing(
    projectId: string,
    host?: string,
    publicKey?: string,
    secretKey?: string
  ): Promise<boolean> {
    const url = host || DEFAULT_LANGFUSE_HOST;

    // Create a test trace
    const container = dag
      .container()
      .from("python:3.12-slim")
      .withExec(["pip", "install", "--quiet", "langfuse"]);

    if (publicKey && secretKey) {
      container
        .withEnvVariable("LANGFUSE_PUBLIC_KEY", publicKey)
        .withEnvVariable("LANGFUSE_SECRET_KEY", secretKey)
        .withEnvVariable("LANGFUSE_HOST", url);
    }

    const script = `
from langfuse import Langfuse
import os

client = Langfuse()
trace = client.trace(
    name="dagger-test-trace",
    metadata={"test": True, "project": "${projectId}"}
)
trace.generation(
    name="test-generation",
    model="test-model",
    input="test input",
    output="test output"
)
client.flush()
print("SUCCESS")
`;

    try {
      const result = await container
        .withExec(["python", "-c", script])
        .stdout();

      return result.includes("SUCCESS");
    } catch {
      return false;
    }
  }

  /**
   * Apply observability to a container
   */
  @func()
  instrumentContainer(
    container: Container,
    appName: string,
    runtime: "bun" | "python"
  ): Container {
    // Add common environment variables
    let result = container
      .withEnvVariable("LANGFUSE_HOST", DEFAULT_LANGFUSE_HOST)
      .withEnvVariable("MLFLOW_TRACKING_URI", DEFAULT_MLFLOW_URI)
      .withEnvVariable("LANGFUSE_PROJECT", appName);

    // Runtime-specific dependencies
    if (runtime === "python") {
      result = result.withExec(["pip", "install", "--quiet", "langfuse", "mlflow"]);
    } else if (runtime === "bun") {
      result = result.withExec(["bun", "add", "langfuse"]);
    }

    return result;
  }

  /**
   * Generate Langfuse callback configuration for LiteLLM
   */
  @func()
  generateLiteLLMCallbackConfig(): string {
    return `# LiteLLM Langfuse Callback Configuration
# Add to litellm_config.yaml under litellm_settings

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

  # Langfuse-specific settings
  langfuse_host: "${DEFAULT_LANGFUSE_HOST}"
  langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
  langfuse_secret_key: os.environ/LANGFUSE_SECRET_KEY
`;
  }

  /**
   * Generate MLflow experiment configuration
   */
  @func()
  generateMLflowExperimentConfig(experimentName: string): string {
    return `# MLflow Experiment Configuration for ${experimentName}
# Auto-generated by Dagger Observability module

import mlflow
import os

# Set tracking URI
mlflow.set_tracking_uri(os.environ.get("MLFLOW_TRACKING_URI", "${DEFAULT_MLFLOW_URI}"))

# Set experiment
mlflow.set_experiment("${experimentName}")

# Enable autologging for common frameworks
mlflow.autolog()

# Example run
# with mlflow.start_run():
#     mlflow.log_param("model", "example")
#     mlflow.log_metric("accuracy", 0.95)
#     mlflow.log_artifact("model.pkl")
`;
  }

  /**
   * Get full instrumentation configuration
   */
  @func()
  getFullConfig(appName: string, local: boolean = false): InstrumentationConfig {
    return {
      langfuse: this.getLangfuseConfig(appName, undefined, local),
      mlflow: this.getMLflowConfig(appName, local),
    };
  }
}
