/**
 * AG-UI protocol event types for A-LEVEL Business.
 *
 * AUTO-GENERATED by scripts/schema-codegen/ag-ui-types.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * The 17 standard AG-UI event types (per https://docs.ag-ui.com/concepts/messages)
 * with the per-subject metadata baked in.
 *
 * Reference:
 *   openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 *   specs/tanstack-ai-agui-integration/spec.md
 */

import type {
  BaseEvent,
  RunAgentInput,
} from "@ag-ui/core";

// ─── The 17 standard AG-UI event types ─────────────────────────────────

export type AgUiEventType =
  | "RUN_STARTED"
  | "RUN_FINISHED"
  | "RUN_ERROR"
  | "STEP_STARTED"
  | "STEP_FINISHED"
  | "TEXT_MESSAGE_START"
  | "TEXT_MESSAGE_CONTENT"
  | "TEXT_MESSAGE_END"
  | "TOOL_CALL_START"
  | "TOOL_CALL_ARGS"
  | "TOOL_CALL_END"
  | "TOOL_CALL_RESULT"
  | "STATE_SNAPSHOT"
  | "STATE_DELTA"
  | "MESSAGES_SNAPSHOT"
  | "RAW"
  | "CUSTOM";

// ─── Per-subject typed event wrappers ────────────────────────────────────

export interface A-levelBusinessRunStarted extends BaseEvent {
  type: "RUN_STARTED";
  threadId: string;
  runId: string;
  subject: "business";
  stage: "a-level";
}

export interface A-levelBusinessRunFinished extends BaseEvent {
  type: "RUN_FINISHED";
  threadId: string;
  runId: string;
  subject: "business";
}

export interface A-levelBusinessRunError extends BaseEvent {
  type: "RUN_ERROR";
  threadId: string;
  runId: string;
  subject: "business";
  error: string;
}

export interface A-levelBusinessTextMessageStart extends BaseEvent {
  type: "TEXT_MESSAGE_START";
  messageId: string;
  subject: "business";
}

export interface A-levelBusinessTextMessageContent extends BaseEvent {
  type: "TEXT_MESSAGE_CONTENT";
  messageId: string;
  delta: string;
  subject: "business";
}

export interface A-levelBusinessToolCallStart extends BaseEvent {
  type: "TOOL_CALL_START";
  toolCallId: string;
  toolCallName: string;
  parentMessageId?: string;
  subject: "business";
}

export interface A-levelBusinessToolCallArgs extends BaseEvent {
  type: "TOOL_CALL_ARGS";
  toolCallId: string;
  delta: string;
  subject: "business";
}

export interface A-levelBusinessToolCallEnd extends BaseEvent {
  type: "TOOL_CALL_END";
  toolCallId: string;
  subject: "business";
}

export interface A-levelBusinessToolCallResult extends BaseEvent {
  type: "TOOL_CALL_RESULT";
  toolCallId: string;
  content: string;
  error?: string;
  subject: "business";
}

export interface A-levelBusinessStateDelta extends BaseEvent {
  type: "STATE_DELTA";
  delta: Record<string, unknown>;
  subject: "business";
}

export interface A-levelBusinessMessagesSnapshot extends BaseEvent {
  type: "MESSAGES_SNAPSHOT";
  messages: ReadonlyArray<unknown>;
  subject: "business";
}

// The canonical RunAgentInput for the per-subject agent
export interface A-levelBusinessRunAgentInput extends RunAgentInput {
  subject: "business";
  stage: "a-level";
  ncca_code: "AL-BUS";
  languages: ["en"];
}

// The canonical tools exposed by the per-subject agent
export interface A-levelBusinessTools {
  get_syllabus_topics: (params: {
    level?: "hl" | "ol" | "fl" | "a-level";
    language?: "en" | "ga";
  }) => Promise<unknown>;
  get_exam_papers: (params: {
    year: number;
    level?: "hl" | "ol" | "fl" | "a-level";
  }) => Promise<unknown>;
  get_marking_schemes: (params: {
    year: number;
    level?: "hl" | "ol" | "fl" | "a-level";
  }) => Promise<unknown>;
  get_topic_detail: (params: { topic_code: string }) => Promise<unknown>;
  get_cross_jurisdictional_equivalences: (params: {
    topic_code: string;
    jurisdiction?: "lc" | "gcse" | "a-level";
  }) => Promise<unknown>;
  semantic_search: (params: {
    query: string;
    top_k?: number;
  }) => Promise<unknown>;
  extract_syllabus_from_pdf: (params: { pdf_url: string }) => Promise<unknown>;
  save_annotation: (params: {
    topic_code: string;
    note: string;
  }) => Promise<unknown>;
  track_progress: (params: {
    topic_code: string;
    score: number;
  }) => Promise<unknown>;
  get_study_plan: (params: {
    subject: string;
    target_date?: string;
  }) => Promise<unknown>;
  compare_curricula: (params: {
    topic_code: string;
    stages: ReadonlyArray<string>;
  }) => Promise<unknown>;
  get_glossary_term: (params: {
    term: string;
    language?: "en" | "ga" | "both";
  }) => Promise<unknown>;
  extract_learning_outcome: (params: { text: string }) => Promise<unknown>;
}

// The canonical 17-event union type for the per-subject agent
export type A-levelBusinessEvent =
  | A-levelBusinessRunStarted
  | A-levelBusinessRunFinished
  | A-levelBusinessRunError
  | A-levelBusinessTextMessageStart
  | A-levelBusinessTextMessageContent
  | A-levelBusinessToolCallStart
  | A-levelBusinessToolCallArgs
  | A-levelBusinessToolCallEnd
  | A-levelBusinessToolCallResult
  | A-levelBusinessStateDelta
  | A-levelBusinessMessagesSnapshot;
