# =============================================================================
# NIMTABLE - Pangolin Blueprint
# =============================================================================

private-resources:
  nimtable:
    name: "Nimtable"
    full-domain: "nimtable.cianfhoghlaim.ie"
    mode: http
    destination: nimtable:3000
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
