/**
 * Per-subject Convex table for GCSE Chemistry.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Reference:
 *   openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 *   specs/schema-driven-codegen/spec.md

 * Subject metadata:
 *   stage:     gcse
 *   subject:   chemistry
 *   ncca_code: GCSE-CHEM
 *   languages: en
 */

import { defineTable, v, defineSchema } from "convex/schema";
import { chemistryType } from "./chemistry.types";

export const chemistry = defineTable({
  app: v.literal("oideachais"),
  stage: v.literal("gcse"),
  subject: v.literal("chemistry"),
  language: v.union(
    v.literal("en"),
  ),
  // Per-subject BAML-extracted fields:
  syllabus_topic_code: v.string(),
  syllabus_topic_title: v.string(),
  learning_outcome_code: v.string(),
  learning_outcome_text: v.string(),
  blooms_level: v.union(
    v.literal("remember"),
    v.literal("understand"),
    v.literal("apply"),
    v.literal("analyse"),
    v.literal("evaluate"),
    v.literal("create"),
  ),
  // BAML chemistryPayload fields (the structured extraction output):
  payload: v.object(chemistryType),
  // Metadata:
  ncca_code: v.string(),
  created_at: v.number(),  // epoch ms
  updated_at: v.number(),
})
  .index("by_app_stage_subject", ["app", "stage", "subject"])
  .index("by_topic", ["syllabus_topic_code"])
  .index("by_ncca_code", ["ncca_code"]);

// Re-export the type for the umbrella schema
export type chemistryDoc = typeof chemistryDocSchema;
declare const chemistryDocSchema: never;
