/**
 * Per-subject Convex table for GCSE Mathematics.
 *
 * AUTO-GENERATED by scripts/schema-codegen/convex-from-zod.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Reference:
 *   openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 *   specs/schema-driven-codegen/spec.md

 * Subject metadata:
 *   stage:     gcse
 *   subject:   mathematics
 *   ncca_code: GCSE-MATH
 *   languages: en
 */

import { defineTable, v, defineSchema } from "convex/schema";
import { mathematicsType } from "./mathematics.types";

export const mathematics = defineTable({
  app: v.literal("oideachais"),
  stage: v.literal("gcse"),
  subject: v.literal("mathematics"),
  language: v.union(
    v.literal("en"),
  ),
  // Per-subject BAML-extracted fields:
  syllabus_topic_code: v.string(),
  syllabus_topic_title: v.string(),
  learning_outcome_code: v.string(),
  learning_outcome_text: v.string(),
  blooms_level: v.union(
    v.literal("remember"),
    v.literal("understand"),
    v.literal("apply"),
    v.literal("analyse"),
    v.literal("evaluate"),
    v.literal("create"),
  ),
  // BAML mathematicsPayload fields (the structured extraction output):
  payload: v.object(mathematicsType),
  // Metadata:
  ncca_code: v.string(),
  created_at: v.number(),  // epoch ms
  updated_at: v.number(),
})
  .index("by_app_stage_subject", ["app", "stage", "subject"])
  .index("by_topic", ["syllabus_topic_code"])
  .index("by_ncca_code", ["ncca_code"]);

// Re-export the type for the umbrella schema
export type mathematicsDoc = typeof mathematicsDocSchema;
declare const mathematicsDocSchema: never;
