#!/usr/bin/env bash
#
# Americas (case-B) — domain-first rewrite of 9 files.
#
# Generated by `_generator.py` for Phase 0.2 follow-up of the openspec
# change `2026-08-24-dlt-sources-to-multi-repo-scaffold-v1` (sub-change `2026-08-24-legacy-import-fix-v1`).
# Companion to `migration_americas.sh` (case-A). Together they cover the
# 15 truly-broken `from dlt_sources.americas.*` imports documented in
# `stedding/sync-reports/legacy-import-audit-2026-08-24.md` §1.6:
#   - case-A (6 files): `dlt_sources/american_nations/<country>/{government,statistics}/__init__.py`
#   - case-B (9 files): `dlt_sources/{law,education,medicine}/<country>/american_nations/__init__.py`
#
# Usage:
#   bash migration_americas_case_b.sh           # APPLY (default)
#   bash migration_americas_case_b.sh --dry-run # print what would change; do NOT write
#
# Uses `perl -i -pe` for the in-place edit (BSD sed lacks `\b` support).
# No `git mv` is needed for case-B: the destination files already exist
# at the canonical `dlt_sources/<domain>/<country>/american_nations/` path;
# only their `from ... import ...` statement needs updating.
#
# What `apply_pair_b` does:
#   1. Print the BEFORE count via `git grep -l "<sed-from>" -- '*.py' | wc -l`.
#   2. `perl -i -pe "s|<sed-from>|<sed-to>|g"` against the SPECIFIC file
#      (not a directory-wide rewrite -- the target depends on the file's
#      containing directory).
#   3. Print the AFTER count (expect 0).

set -euo pipefail

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=1
    echo "[DRY RUN] No filesystem or git operations will be performed."
    echo "[DRY RUN] Every command below is prefixed with '[DRY RUN]'."
    echo
fi

# apply_pair_b <sed-from> <sed-to> <file-path>
#
# Per-file variant of `apply_pair` (no `git mv`). Use when the rewrite
# target depends on the file path. See Subagent E post-mortem
# `stedding/sync-reports/legacy-import-fix-2026-08-24.md` §3.3 + the audit
# §1.6 for why case-B cannot use the standard regex-with-`\b` strategy.
apply_pair_b() {
    local sed_from="$1"
    local sed_to="$2"
    local file_path="$3"
    echo "[PAIR-B] ${file_path}: ${sed_from} -> ${sed_to}"

    local before
    before=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
    echo "  Before: ${before} import sites"

    if [[ "${DRY_RUN}" == "1" ]]; then
        echo "  [DRY RUN] Would: perl -i -pe \"s|${sed_from}|${sed_to}|g\" ${file_path}"
        local after
        after=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
        echo "  After: ${after} import sites (expect 0)"
        return 0
    fi

    # --- APPLY path --------------------------------------------------------
    if [[ -f "${file_path}" ]]; then
        perl -i -pe "s|${sed_from}|${sed_to}|g" "${file_path}"
    else
        echo "  !! WARNING: file ${file_path} does not exist; skipping."
    fi

    local after
    after=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
    echo "  After: ${after} import sites (expect 0)"
    if [[ "${after}" != "0" ]]; then
        echo "  !! WARNING: ${after} import sites for ${file_path} survived."
        echo "     Manual review required."
    fi
}

# ----------------------------------------------------------------------------
# Pair list (9 per-file rewrites; deterministic, sourced from
# the Phase 0.2 audit §1.6 case-B + Subagent E post-mortem §3.3)
# ----------------------------------------------------------------------------

apply_pair_b 'from dlt_sources\.americas\.Brazil\.law[[:space:]]+import' 'from dlt_sources.law.brazil.american_nations import' 'dlt_sources/law/brazil/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Mexico\.law[[:space:]]+import' 'from dlt_sources.law.mexico.american_nations import' 'dlt_sources/law/mexico/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Venezuela\.law[[:space:]]+import' 'from dlt_sources.law.venezuela.american_nations import' 'dlt_sources/law/venezuela/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Brazil\.education[[:space:]]+import' 'from dlt_sources.education.brazil.american_nations import' 'dlt_sources/education/brazil/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Mexico\.education[[:space:]]+import' 'from dlt_sources.education.mexico.american_nations import' 'dlt_sources/education/mexico/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Venezuela\.education[[:space:]]+import' 'from dlt_sources.education.venezuela.american_nations import' 'dlt_sources/education/venezuela/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Brazil\.medicine[[:space:]]+import' 'from dlt_sources.medicine.brazil.american_nations import' 'dlt_sources/medicine/brazil/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Mexico\.medicine[[:space:]]+import' 'from dlt_sources.medicine.mexico.american_nations import' 'dlt_sources/medicine/mexico/american_nations/__init__.py'
apply_pair_b 'from dlt_sources\.americas\.Venezuela\.medicine[[:space:]]+import' 'from dlt_sources.medicine.venezuela.american_nations import' 'dlt_sources/medicine/venezuela/american_nations/__init__.py'

# Done.
