#!/usr/bin/env bash
#
# Canada — provinces under commonwealth/can/.
#
# Generated by `_generator.py` from `dlt_sources/LEGACY_ALIASES.md`
# (lines L109-L109) for Phase 0.2 of the openspec change
# `2026-08-24-dlt-sources-to-multi-repo-scaffold-v1`.
#
# Usage:
#   bash migration_commonwealth_canada_provinces.sh           # APPLY (default)
#   bash migration_commonwealth_canada_provinces.sh --dry-run # print what would change; do NOT write
#
# Per the v2 plan constraint: target is macOS. Implementation uses
# `perl -i -pe` (NOT BSD `sed`) for the in-place edit. BSD `sed` on
# macOS silently drops `\b` word boundaries (see Subagent E post-mortem
# in `stedding/sync-reports/legacy-import-fix-2026-08-24.md` §3.1),
# which made the prior regex-only-with-`\b` migration emit no-ops on
# every pair. Perl honors `\b` correctly. Both perl-5 and GNU `sed`
# are fine on macOS via Homebrew; the script does NOT require any
# non-vendor binaries.
#
# What each pair does (driven by the `apply_pair` function below):
#   1. Print the BEFORE count via `git grep -l "<sed-from>" -- '*.py' | wc -l`.
#   2. `git mv <old-fs> <new-fs>` -- preserving git history (no content
#      touched). Only when `<old-fs>` exists; the script is a no-op if the
#      directory has already been moved (idempotent on a partial run).
#   3. Apply the import-path rewrite via
#      `perl -i -pe "s|<sed-from>|<sed-to>|g"` to every matching file.
#      The `\b` in `<sed-from>` is honored by perl (BSD sed drops it)
#      and ensures only the top-level segment matches (e.g.
#      `british_isles.en\b` matches `.en` and `.en.foo` but NOT `.england`).
#   4. Print the AFTER count (expect 0; non-zero means an import survived
#      and the script surfaces a manual-review warning).
#
# Idempotent on the import-rewrite side (re-running `perl -i -pe` against
# an already-migrated import path is a no-op because `<sed-from>` no
# longer matches). The `git mv` is fail-safe -- it errors if the
# destination already exists with the same content, so a partial re-run
# halts cleanly.

set -euo pipefail

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=1
    echo "[DRY RUN] No filesystem or git operations will be performed."
    echo "[DRY RUN] Every command below is prefixed with '[DRY RUN]'."
    echo
fi

# apply_pair <sed-from> <sed-to> <old-fs> <new-fs>
#
# - <sed-from> -- the SEARCH pattern for sed and git grep, with `\.` already
#   escaped and a trailing `\b` for word-boundary matching. Example:
#     "from dlt_sources\.european_nations\.alb\b"
# - <sed-to>   -- the REPLACEMENT pattern. Example:
#     "from dlt_sources.european_nations.albania"
# - <old-fs>   -- the OLD filesystem path (used for `git mv` + directory
#   existence check). Example:
#     "dlt_sources/european_nations/alb"
# - <new-fs>   -- the NEW filesystem path. Example:
#     "dlt_sources/european_nations/albania"
apply_pair() {
    local sed_from="$1"
    local sed_to="$2"
    local old_fs="$3"
    local new_fs="$4"
    echo "[PAIR] ${old_fs} -> ${new_fs}"

    # `git grep -l` returns 1 when there are no matches. Combined with
    # `set -o pipefail` (enabled at the top of the script), the pipeline
    # would otherwise short-circuit the whole script on a pair that has
    # nothing to do (which is the common case on an already-migrated tree).
    # Use a `( ... || true )` subshell so the pipeline always succeeds; the
    # printed count is what matters. Restrict to `*.py` to skip the ~thousand
    # non-Python files that can never contain a Python `from ... import ...`.
    local before
    before=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
    echo "  Before: ${before} import sites"

    if [[ "${DRY_RUN}" == "1" ]]; then
        if [[ -d "${old_fs}" ]]; then
            echo "  [DRY RUN] Would: git mv \"${old_fs}\" \"${new_fs}\""
        fi
        echo "  [DRY RUN] Would: perl -i -pe \"s|${sed_from}|${sed_to}|g\" <every matching *.py file>"
        local after
        after=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
        echo "  After: ${after} import sites (expect 0)"
        return 0
    fi

    # --- APPLY path --------------------------------------------------------
    if [[ -d "${old_fs}" ]]; then
        git mv "${old_fs}" "${new_fs}"
    fi

    local matches
    matches=$(git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true)
    if [[ -n "${matches}" ]]; then
        while IFS= read -r f; do
            perl -i -pe "s|${sed_from}|${sed_to}|g" "${f}"
        done <<<"${matches}"
    fi

    local after
    after=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
    echo "  After: ${after} import sites (expect 0)"
    if [[ "${after}" != "0" ]]; then
        echo "  !! WARNING: ${after} import sites for ${old_fs} survived."
        echo "     Manual review required."
    fi
}

# ----------------------------------------------------------------------------
# Pair list (13 pairs; deterministic, sourced from
# LEGACY_ALIASES.md L109-L109)
# ----------------------------------------------------------------------------

apply_pair 'from dlt_sources\.commonwealth\.can\.ab\b' 'from dlt_sources.commonwealth.canada.provinces.alberta' 'dlt_sources/commonwealth/can/ab' 'dlt_sources/commonwealth/canada/provinces/alberta'
apply_pair 'from dlt_sources\.commonwealth\.can\.bc\b' 'from dlt_sources.commonwealth.canada.provinces.british_columbia' 'dlt_sources/commonwealth/can/bc' 'dlt_sources/commonwealth/canada/provinces/british_columbia'
apply_pair 'from dlt_sources\.commonwealth\.can\.mb\b' 'from dlt_sources.commonwealth.canada.provinces.manitoba' 'dlt_sources/commonwealth/can/mb' 'dlt_sources/commonwealth/canada/provinces/manitoba'
apply_pair 'from dlt_sources\.commonwealth\.can\.nb\b' 'from dlt_sources.commonwealth.canada.provinces.new_brunswick' 'dlt_sources/commonwealth/can/nb' 'dlt_sources/commonwealth/canada/provinces/new_brunswick'
apply_pair 'from dlt_sources\.commonwealth\.can\.nl\b' 'from dlt_sources.commonwealth.canada.provinces.newfoundland_and_labrador' 'dlt_sources/commonwealth/can/nl' 'dlt_sources/commonwealth/canada/provinces/newfoundland_and_labrador'
apply_pair 'from dlt_sources\.commonwealth\.can\.ns\b' 'from dlt_sources.commonwealth.canada.provinces.nova_scotia' 'dlt_sources/commonwealth/can/ns' 'dlt_sources/commonwealth/canada/provinces/nova_scotia'
apply_pair 'from dlt_sources\.commonwealth\.can\.nt\b' 'from dlt_sources.commonwealth.canada.provinces.northwest_territories' 'dlt_sources/commonwealth/can/nt' 'dlt_sources/commonwealth/canada/provinces/northwest_territories'
apply_pair 'from dlt_sources\.commonwealth\.can\.nu\b' 'from dlt_sources.commonwealth.canada.provinces.nunavut' 'dlt_sources/commonwealth/can/nu' 'dlt_sources/commonwealth/canada/provinces/nunavut'
apply_pair 'from dlt_sources\.commonwealth\.can\.on\b' 'from dlt_sources.commonwealth.canada.provinces.ontario' 'dlt_sources/commonwealth/can/on' 'dlt_sources/commonwealth/canada/provinces/ontario'
apply_pair 'from dlt_sources\.commonwealth\.can\.pe\b' 'from dlt_sources.commonwealth.canada.provinces.prince_edward_island' 'dlt_sources/commonwealth/can/pe' 'dlt_sources/commonwealth/canada/provinces/prince_edward_island'
apply_pair 'from dlt_sources\.commonwealth\.can\.qc\b' 'from dlt_sources.commonwealth.canada.provinces.quebec' 'dlt_sources/commonwealth/can/qc' 'dlt_sources/commonwealth/canada/provinces/quebec'
apply_pair 'from dlt_sources\.commonwealth\.can\.sk\b' 'from dlt_sources.commonwealth.canada.provinces.saskatchewan' 'dlt_sources/commonwealth/can/sk' 'dlt_sources/commonwealth/canada/provinces/saskatchewan'
apply_pair 'from dlt_sources\.commonwealth\.can\.yt\b' 'from dlt_sources.commonwealth.canada.provinces.yukon' 'dlt_sources/commonwealth/can/yt' 'dlt_sources/commonwealth/canada/provinces/yukon'

# Done.
