#!/usr/bin/env bash
#
# European nations — ISO 3-letter -> full snake_case.
#
# Generated by `_generator.py` from `dlt_sources/LEGACY_ALIASES.md`
# (lines L97-L97) for Phase 0.2 of the openspec change
# `2026-08-24-dlt-sources-to-multi-repo-scaffold-v1`.
#
# Usage:
#   bash migration_european_nations.sh           # APPLY (default)
#   bash migration_european_nations.sh --dry-run # print what would change; do NOT write
#
# Per the v2 plan constraint: target is macOS. Implementation uses
# `perl -i -pe` (NOT BSD `sed`) for the in-place edit. BSD `sed` on
# macOS silently drops `\b` word boundaries (see Subagent E post-mortem
# in `stedding/sync-reports/legacy-import-fix-2026-08-24.md` §3.1),
# which made the prior regex-only-with-`\b` migration emit no-ops on
# every pair. Perl honors `\b` correctly. Both perl-5 and GNU `sed`
# are fine on macOS via Homebrew; the script does NOT require any
# non-vendor binaries.
#
# What each pair does (driven by the `apply_pair` function below):
#   1. Print the BEFORE count via `git grep -l "<sed-from>" -- '*.py' | wc -l`.
#   2. `git mv <old-fs> <new-fs>` -- preserving git history (no content
#      touched). Only when `<old-fs>` exists; the script is a no-op if the
#      directory has already been moved (idempotent on a partial run).
#   3. Apply the import-path rewrite via
#      `perl -i -pe "s|<sed-from>|<sed-to>|g"` to every matching file.
#      The `\b` in `<sed-from>` is honored by perl (BSD sed drops it)
#      and ensures only the top-level segment matches (e.g.
#      `british_isles.en\b` matches `.en` and `.en.foo` but NOT `.england`).
#   4. Print the AFTER count (expect 0; non-zero means an import survived
#      and the script surfaces a manual-review warning).
#
# Idempotent on the import-rewrite side (re-running `perl -i -pe` against
# an already-migrated import path is a no-op because `<sed-from>` no
# longer matches). The `git mv` is fail-safe -- it errors if the
# destination already exists with the same content, so a partial re-run
# halts cleanly.

set -euo pipefail

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=1
    echo "[DRY RUN] No filesystem or git operations will be performed."
    echo "[DRY RUN] Every command below is prefixed with '[DRY RUN]'."
    echo
fi

# apply_pair <sed-from> <sed-to> <old-fs> <new-fs>
#
# - <sed-from> -- the SEARCH pattern for sed and git grep, with `\.` already
#   escaped and a trailing `\b` for word-boundary matching. Example:
#     "from dlt_sources\.european_nations\.alb\b"
# - <sed-to>   -- the REPLACEMENT pattern. Example:
#     "from dlt_sources.european_nations.albania"
# - <old-fs>   -- the OLD filesystem path (used for `git mv` + directory
#   existence check). Example:
#     "dlt_sources/european_nations/alb"
# - <new-fs>   -- the NEW filesystem path. Example:
#     "dlt_sources/european_nations/albania"
apply_pair() {
    local sed_from="$1"
    local sed_to="$2"
    local old_fs="$3"
    local new_fs="$4"
    echo "[PAIR] ${old_fs} -> ${new_fs}"

    # `git grep -l` returns 1 when there are no matches. Combined with
    # `set -o pipefail` (enabled at the top of the script), the pipeline
    # would otherwise short-circuit the whole script on a pair that has
    # nothing to do (which is the common case on an already-migrated tree).
    # Use a `( ... || true )` subshell so the pipeline always succeeds; the
    # printed count is what matters. Restrict to `*.py` to skip the ~thousand
    # non-Python files that can never contain a Python `from ... import ...`.
    local before
    before=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
    echo "  Before: ${before} import sites"

    if [[ "${DRY_RUN}" == "1" ]]; then
        if [[ -d "${old_fs}" ]]; then
            echo "  [DRY RUN] Would: git mv \"${old_fs}\" \"${new_fs}\""
        fi
        echo "  [DRY RUN] Would: perl -i -pe \"s|${sed_from}|${sed_to}|g\" <every matching *.py file>"
        local after
        after=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
        echo "  After: ${after} import sites (expect 0)"
        return 0
    fi

    # --- APPLY path --------------------------------------------------------
    if [[ -d "${old_fs}" ]]; then
        git mv "${old_fs}" "${new_fs}"
    fi

    local matches
    matches=$(git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true)
    if [[ -n "${matches}" ]]; then
        while IFS= read -r f; do
            perl -i -pe "s|${sed_from}|${sed_to}|g" "${f}"
        done <<<"${matches}"
    fi

    local after
    after=$( (git grep -l -- "${sed_from}" -- '*.py' 2>/dev/null || true) | wc -l | tr -d ' ')
    echo "  After: ${after} import sites (expect 0)"
    if [[ "${after}" != "0" ]]; then
        echo "  !! WARNING: ${after} import sites for ${old_fs} survived."
        echo "     Manual review required."
    fi
}

# ----------------------------------------------------------------------------
# Pair list (40 pairs; deterministic, sourced from
# LEGACY_ALIASES.md L97-L97)
# ----------------------------------------------------------------------------

apply_pair 'from dlt_sources\.european_nations\.alb\b' 'from dlt_sources.european_nations.albania' 'dlt_sources/european_nations/alb' 'dlt_sources/european_nations/albania'
apply_pair 'from dlt_sources\.european_nations\.aut\b' 'from dlt_sources.european_nations.austria' 'dlt_sources/european_nations/aut' 'dlt_sources/european_nations/austria'
apply_pair 'from dlt_sources\.european_nations\.bel\b' 'from dlt_sources.european_nations.belgium' 'dlt_sources/european_nations/bel' 'dlt_sources/european_nations/belgium'
apply_pair 'from dlt_sources\.european_nations\.bgr\b' 'from dlt_sources.european_nations.bulgaria' 'dlt_sources/european_nations/bgr' 'dlt_sources/european_nations/bulgaria'
apply_pair 'from dlt_sources\.european_nations\.bih\b' 'from dlt_sources.european_nations.bosnia_and_herzegovina' 'dlt_sources/european_nations/bih' 'dlt_sources/european_nations/bosnia_and_herzegovina'
apply_pair 'from dlt_sources\.european_nations\.che\b' 'from dlt_sources.european_nations.switzerland' 'dlt_sources/european_nations/che' 'dlt_sources/european_nations/switzerland'
apply_pair 'from dlt_sources\.european_nations\.cyp\b' 'from dlt_sources.european_nations.cyprus' 'dlt_sources/european_nations/cyp' 'dlt_sources/european_nations/cyprus'
apply_pair 'from dlt_sources\.european_nations\.cze\b' 'from dlt_sources.european_nations.czechia' 'dlt_sources/european_nations/cze' 'dlt_sources/european_nations/czechia'
apply_pair 'from dlt_sources\.european_nations\.deu\b' 'from dlt_sources.european_nations.germany' 'dlt_sources/european_nations/deu' 'dlt_sources/european_nations/germany'
apply_pair 'from dlt_sources\.european_nations\.dnk\b' 'from dlt_sources.european_nations.denmark' 'dlt_sources/european_nations/dnk' 'dlt_sources/european_nations/denmark'
apply_pair 'from dlt_sources\.european_nations\.esp\b' 'from dlt_sources.european_nations.spain' 'dlt_sources/european_nations/esp' 'dlt_sources/european_nations/spain'
apply_pair 'from dlt_sources\.european_nations\.est\b' 'from dlt_sources.european_nations.estonia' 'dlt_sources/european_nations/est' 'dlt_sources/european_nations/estonia'
apply_pair 'from dlt_sources\.european_nations\.fin\b' 'from dlt_sources.european_nations.finland' 'dlt_sources/european_nations/fin' 'dlt_sources/european_nations/finland'
apply_pair 'from dlt_sources\.european_nations\.fra\b' 'from dlt_sources.european_nations.france' 'dlt_sources/european_nations/fra' 'dlt_sources/european_nations/france'
apply_pair 'from dlt_sources\.european_nations\.geo\b' 'from dlt_sources.european_nations.georgia' 'dlt_sources/european_nations/geo' 'dlt_sources/european_nations/georgia'
apply_pair 'from dlt_sources\.european_nations\.grc\b' 'from dlt_sources.european_nations.greece' 'dlt_sources/european_nations/grc' 'dlt_sources/european_nations/greece'
apply_pair 'from dlt_sources\.european_nations\.hrv\b' 'from dlt_sources.european_nations.croatia' 'dlt_sources/european_nations/hrv' 'dlt_sources/european_nations/croatia'
apply_pair 'from dlt_sources\.european_nations\.hun\b' 'from dlt_sources.european_nations.hungary' 'dlt_sources/european_nations/hun' 'dlt_sources/european_nations/hungary'
apply_pair 'from dlt_sources\.european_nations\.isl\b' 'from dlt_sources.european_nations.iceland' 'dlt_sources/european_nations/isl' 'dlt_sources/european_nations/iceland'
apply_pair 'from dlt_sources\.european_nations\.ita\b' 'from dlt_sources.european_nations.italy' 'dlt_sources/european_nations/ita' 'dlt_sources/european_nations/italy'
apply_pair 'from dlt_sources\.european_nations\.lie\b' 'from dlt_sources.european_nations.liechtenstein' 'dlt_sources/european_nations/lie' 'dlt_sources/european_nations/liechtenstein'
apply_pair 'from dlt_sources\.european_nations\.ltu\b' 'from dlt_sources.european_nations.lithuania' 'dlt_sources/european_nations/ltu' 'dlt_sources/european_nations/lithuania'
apply_pair 'from dlt_sources\.european_nations\.lux\b' 'from dlt_sources.european_nations.luxembourg' 'dlt_sources/european_nations/lux' 'dlt_sources/european_nations/luxembourg'
apply_pair 'from dlt_sources\.european_nations\.lva\b' 'from dlt_sources.european_nations.latvia' 'dlt_sources/european_nations/lva' 'dlt_sources/european_nations/latvia'
apply_pair 'from dlt_sources\.european_nations\.mda\b' 'from dlt_sources.european_nations.moldova' 'dlt_sources/european_nations/mda' 'dlt_sources/european_nations/moldova'
apply_pair 'from dlt_sources\.european_nations\.mkd\b' 'from dlt_sources.european_nations.north_macedonia' 'dlt_sources/european_nations/mkd' 'dlt_sources/european_nations/north_macedonia'
apply_pair 'from dlt_sources\.european_nations\.mlt\b' 'from dlt_sources.european_nations.malta' 'dlt_sources/european_nations/mlt' 'dlt_sources/european_nations/malta'
apply_pair 'from dlt_sources\.european_nations\.mne\b' 'from dlt_sources.european_nations.montenegro' 'dlt_sources/european_nations/mne' 'dlt_sources/european_nations/montenegro'
apply_pair 'from dlt_sources\.european_nations\.nld\b' 'from dlt_sources.european_nations.netherlands' 'dlt_sources/european_nations/nld' 'dlt_sources/european_nations/netherlands'
apply_pair 'from dlt_sources\.european_nations\.nor\b' 'from dlt_sources.european_nations.norway' 'dlt_sources/european_nations/nor' 'dlt_sources/european_nations/norway'
apply_pair 'from dlt_sources\.european_nations\.pol\b' 'from dlt_sources.european_nations.poland' 'dlt_sources/european_nations/pol' 'dlt_sources/european_nations/poland'
apply_pair 'from dlt_sources\.european_nations\.prt\b' 'from dlt_sources.european_nations.portugal' 'dlt_sources/european_nations/prt' 'dlt_sources/european_nations/portugal'
apply_pair 'from dlt_sources\.european_nations\.rou\b' 'from dlt_sources.european_nations.romania' 'dlt_sources/european_nations/rou' 'dlt_sources/european_nations/romania'
apply_pair 'from dlt_sources\.european_nations\.srb\b' 'from dlt_sources.european_nations.serbia' 'dlt_sources/european_nations/srb' 'dlt_sources/european_nations/serbia'
apply_pair 'from dlt_sources\.european_nations\.svk\b' 'from dlt_sources.european_nations.slovakia' 'dlt_sources/european_nations/svk' 'dlt_sources/european_nations/slovakia'
apply_pair 'from dlt_sources\.european_nations\.svn\b' 'from dlt_sources.european_nations.slovenia' 'dlt_sources/european_nations/svn' 'dlt_sources/european_nations/slovenia'
apply_pair 'from dlt_sources\.european_nations\.swe\b' 'from dlt_sources.european_nations.sweden' 'dlt_sources/european_nations/swe' 'dlt_sources/european_nations/sweden'
apply_pair 'from dlt_sources\.european_nations\.tur\b' 'from dlt_sources.european_nations.turkey' 'dlt_sources/european_nations/tur' 'dlt_sources/european_nations/turkey'
apply_pair 'from dlt_sources\.european_nations\.ukr\b' 'from dlt_sources.european_nations.ukraine' 'dlt_sources/european_nations/ukr' 'dlt_sources/european_nations/ukraine'
apply_pair 'from dlt_sources\.european_nations\.xkx\b' 'from dlt_sources.european_nations.kosovo' 'dlt_sources/european_nations/xkx' 'dlt_sources/european_nations/kosovo'

# Done.
