private-resources:
  audiobookshelf:
    name: "Audiobookshelf"
    mode: http
    full-domain: "audiobookshelf.cianfhoghlaim.ie"
    destination: audiobookshelf:8080
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member