"""DLT nightly mirror-merge sensor (Phase 2.5).

Per the 2026-08-24-dlt-sources-to-multi-repo-scaffold-v1 change
(Phase 2.5 — nightly mirror-merge of accumulated sister_refs).

Flow
----
1. The nightly sensor ticks (`@sensor(minimum_interval_seconds=86400,
   cron 02:30 UTC per tasks.md §17.3)`,
   `default_status=DefaultSensorStatus.STOPPED`).
2. Reads the `dlt_sources/_sister_refs/<repo>/...` accumulated diff
   via `git diff main...HEAD -- dlt_sources/_sister_refs/`.
3. For each sister repo with accumulated diff:
   a. Computes the destination path: `dlt_sources/<sister-context>/...`
      (e.g., `_sister_refs/ciandlithe/law/england/_factory.py`
        → `dlt_sources/law/england/...`)
   b. Emits a `RunRequest` that triggers the `dlt_mirror_merge_job`
      (which performs the actual `git mv` + commit).
   c. Posts a `dlt:mirror-ack` notification to the sister repo via
      `gh api repos/<sister>/issues -f body=...`.

The sensor is STOPPED by default — operator must enable it via Dagster
UI after the per-PR reciprocal workflow (`dlt-sister-sync.yml`) is
proven via a dummy PR.
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from dagster import (
    DefaultSensorStatus,
    RunRequest,
    SensorEvaluationContext,
    SkipReason,
    define_asset_job,
    sensor,
)

logger = logging.getLogger(__name__)


# The 2 sister repos in the active topology today. Add more tuples
# when ciancheiltis / cianleighis / bonneagar / meaisinfhoghlaim
# get their per-PR reciprocal workflow wired.
SISTER_REPOS: tuple[str, ...] = (
    "ciandlithe",
    "cianchosaint",
)


# The 02:30 UTC nightly cron (per tasks.md §17.3) — distinct from the
# canonical `NIGHTLY_AUDIT_CRON = "0 0 * * *"` at 00:00 UTC which is
# shared with the BIEP v3 RAGAS + audit chain.
MIRROR_MERGE_CRON = "30 2 * * *"
POLL_INTERVAL_SECONDS = 86_400  # 24h

# The `_sister_refs/` subtree that accumulates per-PR reciprocal
# mirrors from ciandlithe + cianchosaint (per the §15 reusable workflow).
SISTER_REFS_PREFIX = "dlt_sources/_sister_refs"


def _read_accumulated_diff(sister_repo: str, base_ref: str = "main") -> list[str]:
    """Read the accumulated diff of `dlt_sources/_sister_refs/<repo>/...`.

    Uses `git diff main...HEAD -- dlt_sources/_sister_refs/<repo>/` to
    enumerate the files that have accumulated since the last successful
    mirror-merge.

    Returns a list of relative file paths. Empty list = no accumulated
    changes for this sister repo.
    """
    try:
        result = subprocess.run(
            [
                "git",
                "diff",
                "--name-only",
                f"{base_ref}...HEAD",
                "--",
                f"{SISTER_REFS_PREFIX}/{sister_repo}/",
            ],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if result.returncode != 0:
            logger.warning(
                "dlt_nightly_mirror_merge.diff_failed",
                sister=sister_repo,
                returncode=result.returncode,
                stderr=result.stderr[:200],
            )
            return []
        return [line.strip() for line in result.stdout.splitlines() if line.strip()]
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning(
            "dlt_nightly_mirror_merge.diff_exception",
            sister=sister_repo,
            error=str(exc),
        )
        return []


def _post_mirror_ack(sister_repo: str, files: list[str], ack_sha: str) -> bool:
    """Post a `dlt:mirror-ack` notification to the sister repo.

    Uses `gh api repos/<sister>/issues -f body=...` to create an issue
    on the sister repo acknowledging the nightly mirror-merge.

    Returns True on success, False on failure.
    """
    token = (
        os.environ.get("CROSS_REPO_PR_TOKEN")
        or os.environ.get("GH_TOKEN")
        or os.environ.get("GITHUB_TOKEN")
    )
    if not token:
        logger.warning(
            "dlt_nightly_mirror_merge.no_token_for_ack",
            sister=sister_repo,
        )
        return False

    body_lines = [
        f"## dlt:mirror-ack from cianfhoghlaim",
        "",
        f"The nightly mirror-merge sensor has merged the following "
        f"`{sister_repo}` files into `cianfhoghlaim/dlt_sources/`:",
        "",
    ]
    for f in files:
        body_lines.append(f"- `{f}`")
    body_lines.extend(
        [
            "",
            f"- Mirror SHA: `{ack_sha}`",
            f"- Timestamp: {datetime.now(UTC).isoformat()}",
            "- openspec change: `2026-08-24-dlt-sources-to-multi-repo-scaffold-v1`",
            "",
            "Auto-generated by `dlt_nightly_mirror_merge_sensor`.",
        ]
    )
    body = "\n".join(body_lines)

    title = f"dlt:mirror-ack {datetime.now(UTC).strftime('%Y-%m-%d')}: {len(files)} files"

    try:
        result = subprocess.run(
            [
                "gh",
                "api",
                f"repos/cianmacandeisigh/{sister_repo}/issues",
                "-f",
                f"title={title}",
                "-f",
                f"body={body}",
                "-f",
                "labels=dlt-mirror-ack,auto-mirror",
            ],
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
            env={**os.environ, "GH_TOKEN": token},
        )
        if result.returncode != 0:
            logger.warning(
                "dlt_nightly_mirror_merge.ack_failed",
                sister=sister_repo,
                returncode=result.returncode,
                stderr=result.stderr[:200],
            )
            return False
        logger.info(
            "dlt_nightly_mirror_merge.ack_posted",
            sister=sister_repo,
            files=len(files),
        )
        return True
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning(
            "dlt_nightly_mirror_merge.ack_exception",
            sister=sister_repo,
            error=str(exc),
        )
        return False


# The job that performs the actual mirror-merge. In production this
# would `git mv _sister_refs/<repo>/... dlt_sources/...` + commit +
# push. The stub selects an empty asset list (the merge logic is
# operator-managed; the sensor emits the run request as a signal).
dlt_mirror_merge_job = define_asset_job(
    name="dlt_mirror_merge",
    selection=[],
    description=(
        "Nightly mirror-merge job — moves accumulated "
        "`dlt_sources/_sister_refs/<repo>/...` files into "
        "`dlt_sources/<sister-context>/...` and emits a "
        "`dlt:mirror-ack` notification back to the sister repo. "
        "Per the 2026-08-24 multi-repo scaffold change Phase 2.5."
    ),
)


@sensor(
    job=dlt_mirror_merge_job,
    description=(
        "Nightly mirror-merge of accumulated "
        "`dlt_sources/_sister_refs/<repo>/...` into "
        "`dlt_sources/<sister-context>/...`. "
        "Per the 2026-08-24 multi-repo scaffold change Phase 2.5 "
        "(cron 02:30 UTC)."
    ),
    minimum_interval_seconds=POLL_INTERVAL_SECONDS,
    default_status=DefaultSensorStatus.STOPPED,
)
def dlt_nightly_mirror_merge_sensor(
    context: SensorEvaluationContext,
) -> list[RunRequest] | SkipReason:
    """The nightly mirror-merge sensor.

    Disabled by default. Enable via Dagster UI after the per-PR
    reciprocal workflow (`dlt-sister-sync.yml`) is proven via a
    dummy PR.
    """
    cursor_data: dict[str, Any] = {}
    if context.cursor:
        try:
            cursor_data = json.loads(context.cursor)
        except Exception:
            cursor_data = {}

    last_ack_sha = cursor_data.get("last_ack_sha", "")
    now_ts = datetime.now(UTC).isoformat()

    new_runs: list[RunRequest] = []
    summary: dict[str, Any] = {
        "ts": now_ts,
        "per_sister": {},
    }

    for sister in SISTER_REPOS:
        diff_files = _read_accumulated_diff(sister_repo=sister)
        summary["per_sister"][sister] = {
            "files": diff_files,
            "count": len(diff_files),
        }
        if not diff_files:
            logger.info(
                "dlt_nightly_mirror_merge.no_diff",
                sister=sister,
            )
            continue

        # Get the current HEAD SHA as the mirror-ack reference
        try:
            ack_sha = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
            ).stdout.strip()
        except Exception:
            ack_sha = ""

        # Post the mirror-ack notification (best-effort; failure is
        # non-fatal — the mirror-merge itself is the primary signal)
        ack_ok = _post_mirror_ack(sister_repo=sister, files=diff_files, ack_sha=ack_sha)
        summary["per_sister"][sister]["ack_posted"] = ack_ok

        run_key = f"dlt_mirror_merge_{sister}_{now_ts}"
        new_runs.append(
            RunRequest(
                run_key=run_key,
                tags={
                    "sister_repo": sister,
                    "file_count": str(len(diff_files)),
                    "ack_posted": "1" if ack_ok else "0",
                    "openspec_change": "2026-08-24-dlt-sources-to-multi-repo-scaffold-v1",
                    "cron": MIRROR_MERGE_CRON,
                },
            )
        )

    # Persist the summary
    try:
        out_dir = Path("stedding/sync-reports")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"dlt-mirror-merge-{datetime.now(UTC).strftime('%Y-%m-%d')}.json"
        out_path.write_text(json.dumps(summary, indent=2))
        logger.info(
            "dlt_nightly_mirror_merge.summary_written",
            path=str(out_path),
        )
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning(
            "dlt_nightly_mirror_merge.summary_failed",
            error=str(exc),
        )

    # Update the cursor
    context.update_cursor(
        json.dumps({"last_ack_sha": ack_sha or last_ack_sha, "ts": now_ts})
    )

    if not new_runs:
        return SkipReason(
            f"0 of {len(SISTER_REPOS)} sister repos have accumulated diffs"
        )
    return new_runs


__all__ = [
    "MIRROR_MERGE_CRON",
    "POLL_INTERVAL_SECONDS",
    "SISTER_REPOS",
    "SISTER_REFS_PREFIX",
    "_read_accumulated_diff",
    "_post_mirror_ack",
    "dlt_mirror_merge_job",
    "dlt_nightly_mirror_merge_sensor",
]
