"""Chemistry schema — Cianfhoghlaim Oideachais.

DEPRECATED 2026-08-15 — the 12 hand-written Pydantic classes in this
module have been replaced with thin re-exports from the generated
BAML Python client. The BAML file
(``baml_src/british_isles/ireland/education/subjects/qpack_chemistry.baml``)
is now the single source of truth. The hand-written schema was
explicitly documented as a BAML mirror.

Per the ``centralized-schema-registry`` capability (2026-08-15).

ADDITIONALLY DEPRECATED (2026-08-06) as part of the LC ingestion
consolidation — the canonical replacement for the whole
``subjects/chemistry`` package (this file + ``sources.py``) is
``dlt_sources/filesystem/leaving_cert_source.py`` (``lc5_documents``
resource), which covers chemistry across 6 subjects.

BROKEN — DO NOT IMPORT. The ``from ... import (...)`` block below
contains unfilled ``ChemName``-style template literals (e.g.
``ChemBilingualText``) left over from an unrendered code-generation
template. This is invalid Python and raises ``SyntaxError`` (or
``NameError``/``ImportError`` once the ``Chem`` tokens are lexed as
attribute access) at import time. Confirmed as of 2026-08-06 that
nothing else in the repo imports this module (grep for
``subjects.chemistry.schema`` / ``subjects/chemistry/schema`` found no
external callers — the package ``__init__.py`` only imports from
``.sources``, never from ``.schema``). Left in place, un-repaired, as
this module is being retired rather than fixed; see ``sources.py`` in
this same directory for the parallel deprecation note.
"""
from __future__ import annotations

# Re-export every Chem* class from the generated BAML Python client.
# Enums (str, Enum) and BaseModel subclasses are generated by
# `baml-cli generate` from `baml_src/.../qpack_chemistry.baml`.
from baml_client.baml_client.types import (
    ChemBilingualText,
    ChemEvidenceLink,
    ChemNCCALevel,
    ChemTopicArea,
    ChemItemType,
    ChemFeedbackChannel,
    ChemFormativeItem,
    ChemFormativeItemAttempt,
    ChemScoreBreakdown,
    ChemQuestPack,
    ChemQuestPackValidation,
    ChemNCCALearningOutcome,
)

# Additional types that may exist per subject.
try:
    from baml_client.baml_client.types import (
    ChemCommonMistake,
    ChemExperimentType,
    ChemQuestionType,
    )
except ImportError:
    # Older BAML clients may not have these exact enum names; fall
    # back to the legacy strings.
    from enum import Enum

    class FormativeItemType(str, Enum):
        NUMERICAL = "numerical"
        SHORT_ANSWER = "short_answer"
        EXTENDED_RESPONSE = "extended_response"

    class FeedbackChannel(str, Enum):
        HINT = "hint"
        ELABORATION = "elaboration"
        MISCONCEPTION = "misconception"
        REINFORCEMENT = "reinforcement"


__all__ = [
    "BilingualText",
    "EvidenceLink",
    "ChemNCCALevel",
    "ChemTopicArea",
    "ChemNCCALearningOutcome",
    "FormativeItem",
    "FormativeItemAttempt",
    "ScoreBreakdown",
    "QuestPack",
    "QuestPackValidation",
    "FormativeItemType",
    "FeedbackChannel",
    "ChemBilingualText",
    "ChemEvidenceLink",
    "ChemFormativeItem",
    "ChemFormativeItemAttempt",
    "ChemScoreBreakdown",
    "ChemQuestPack",
    "ChemQuestPackValidation",
]
