/**
 * AG-UI protocol event types for LC Accounting.
 *
 * AUTO-GENERATED by scripts/schema-codegen/ag-ui-types.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * The 17 standard AG-UI event types (per https://docs.ag-ui.com/concepts/messages)
 * with the per-subject metadata baked in.
 *
 * Reference:
 *   openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 *   specs/tanstack-ai-agui-integration/spec.md
 */

import type {
  BaseEvent,
  RunAgentInput,
} from "@ag-ui/core";

// ─── The 17 standard AG-UI event types ─────────────────────────────────

export type AgUiEventType =
  | "RUN_STARTED"
  | "RUN_FINISHED"
  | "RUN_ERROR"
  | "STEP_STARTED"
  | "STEP_FINISHED"
  | "TEXT_MESSAGE_START"
  | "TEXT_MESSAGE_CONTENT"
  | "TEXT_MESSAGE_END"
  | "TOOL_CALL_START"
  | "TOOL_CALL_ARGS"
  | "TOOL_CALL_END"
  | "TOOL_CALL_RESULT"
  | "STATE_SNAPSHOT"
  | "STATE_DELTA"
  | "MESSAGES_SNAPSHOT"
  | "RAW"
  | "CUSTOM";

// ─── Per-subject typed event wrappers ────────────────────────────────────

export interface LcAccountingRunStarted extends Omit<BaseEvent, "type"> {
  type: "RUN_STARTED";
  threadId: string;
  runId: string;
  subject: "accounting";
  stage: "lc";
}

export interface LcAccountingRunFinished extends Omit<BaseEvent, "type"> {
  type: "RUN_FINISHED";
  threadId: string;
  runId: string;
  subject: "accounting";
}

export interface LcAccountingRunError extends Omit<BaseEvent, "type"> {
  type: "RUN_ERROR";
  threadId: string;
  runId: string;
  subject: "accounting";
  error: string;
}

export interface LcAccountingTextMessageStart extends Omit<BaseEvent, "type"> {
  type: "TEXT_MESSAGE_START";
  messageId: string;
  subject: "accounting";
}

export interface LcAccountingTextMessageContent extends Omit<BaseEvent, "type"> {
  type: "TEXT_MESSAGE_CONTENT";
  messageId: string;
  delta: string;
  subject: "accounting";
}

export interface LcAccountingToolCallStart extends Omit<BaseEvent, "type"> {
  type: "TOOL_CALL_START";
  toolCallId: string;
  toolCallName: string;
  parentMessageId?: string;
  subject: "accounting";
}

export interface LcAccountingToolCallArgs extends Omit<BaseEvent, "type"> {
  type: "TOOL_CALL_ARGS";
  toolCallId: string;
  delta: string;
  subject: "accounting";
}

export interface LcAccountingToolCallEnd extends Omit<BaseEvent, "type"> {
  type: "TOOL_CALL_END";
  toolCallId: string;
  subject: "accounting";
}

export interface LcAccountingToolCallResult extends Omit<BaseEvent, "type"> {
  type: "TOOL_CALL_RESULT";
  toolCallId: string;
  content: string;
  error?: string;
  subject: "accounting";
}

export interface LcAccountingStateDelta extends Omit<BaseEvent, "type"> {
  type: "STATE_DELTA";
  delta: Record<string, unknown>;
  subject: "accounting";
}

export interface LcAccountingMessagesSnapshot extends Omit<BaseEvent, "type"> {
  type: "MESSAGES_SNAPSHOT";
  messages: ReadonlyArray<unknown>;
  subject: "accounting";
}

// The canonical RunAgentInput for the per-subject agent
export interface LcAccountingRunAgentInput extends RunAgentInput {
  subject: "accounting";
  stage: "lc";
  ncca_code: "LC-ACCT-LO";
  languages: ["en","ga"];
}

// The canonical tools exposed by the per-subject agent
export interface LcAccountingTools {
  get_syllabus_topics: (params: {
    level?: "hl" | "ol" | "fl" | "a-level";
    language?: "en" | "ga";
  }) => Promise<unknown>;
  get_exam_papers: (params: {
    year: number;
    level?: "hl" | "ol" | "fl" | "a-level";
  }) => Promise<unknown>;
  get_marking_schemes: (params: {
    year: number;
    level?: "hl" | "ol" | "fl" | "a-level";
  }) => Promise<unknown>;
  get_topic_detail: (params: { topic_code: string }) => Promise<unknown>;
  get_cross_jurisdictional_equivalences: (params: {
    topic_code: string;
    jurisdiction?: "lc" | "gcse" | "a-level";
  }) => Promise<unknown>;
  semantic_search: (params: {
    query: string;
    top_k?: number;
  }) => Promise<unknown>;
  extract_syllabus_from_pdf: (params: { pdf_url: string }) => Promise<unknown>;
  save_annotation: (params: {
    topic_code: string;
    note: string;
  }) => Promise<unknown>;
  track_progress: (params: {
    topic_code: string;
    score: number;
  }) => Promise<unknown>;
  get_study_plan: (params: {
    subject: string;
    target_date?: string;
  }) => Promise<unknown>;
  compare_curricula: (params: {
    topic_code: string;
    stages: ReadonlyArray<string>;
  }) => Promise<unknown>;
  get_glossary_term: (params: {
    term: string;
    language?: "en" | "ga" | "both";
  }) => Promise<unknown>;
  extract_learning_outcome: (params: { text: string }) => Promise<unknown>;
}

// The canonical 17-event union type for the per-subject agent
export type LcAccountingEvent =
  | LcAccountingRunStarted
  | LcAccountingRunFinished
  | LcAccountingRunError
  | LcAccountingTextMessageStart
  | LcAccountingTextMessageContent
  | LcAccountingToolCallStart
  | LcAccountingToolCallArgs
  | LcAccountingToolCallEnd
  | LcAccountingToolCallResult
  | LcAccountingStateDelta
  | LcAccountingMessagesSnapshot;
