private-resources:
  lmnr:
    name: "Lmnr"
    full-domain: "lmnr.cianfhoghlaim.ie"
    mode: http
    destination: lmnr:8080
    protocol: http
    sites:
      - arm1-oci
    roles:
      - Member
