/**
 * JC Mathematics — subject landing page.
 *
 * AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 *
 * Per openspec/changes/2026-08-13-web-monorepo-consolidation-and-agent-integration-v1/
 * specs/per-subject-coverage/spec.md.
 */

import { createFileRoute, Link } from "@tanstack/react-router";
import { CopilotKit } from "@copilotkit/react-core/v2";
import { useState } from "react";

import { useMathematicsActions } from "@/lib/copilotkit/jc/mathematics";
import { useMathematicsEvents } from "@/lib/ag-ui/jc/mathematics";

export const Route = createFileRoute("/jc/mathematics/")({
  component: MathematicsPage,
});

function MathematicsPage() {
  return (
    <CopilotKit runtimeUrl="/api/copilotkit/jc/mathematics">
      <div className="max-w-4xl mx-auto flex flex-col gap-8 h-full p-8">
        <div className="flex flex-col gap-2">
          <h1 className="text-4xl font-bold">
            Mathematics (JC)
          </h1>
          <p className="text-slate-600 text-lg">
            Mathematics — JC-MATH-LO — languages: en, ga
          </p>
        </div>

        <SubjectActionsSection subject="mathematics" stage="jc" />

        <Link
          to="/jc/mathematics/$topicId"
          params={{ topicId: "JC-MATH-LO-001" }}
          className="btn-tactile"
        >
          Open topic detail →
        </Link>
      </div>
    </CopilotKit>
  );
}

function SubjectActionsSection({
  subject,
  stage,
}: {
  subject: string;
  stage: string;
}) {
  useMathematicsActions();

  return (
    <div className="grid grid-cols-2 gap-4">
      <ActionCard
        title="Get syllabus topics"
        description="Fetch the Mathematics syllabus topics + learning outcomes"
        actionName="get_syllabus_topics"
      />
      <ActionCard
        title="Get exam papers"
        description="List exam papers by year + level"
        actionName="get_exam_papers"
      />
      <ActionCard
        title="Get marking schemes"
        description="Fetch marking schemes + rubrics"
        actionName="get_marking_schemes"
      />
      <ActionCard
        title="Semantic search"
        description="BGE-M3 vector search over the Mathematics embeddings"
        actionName="semantic_search"
      />
    </div>
  );
}

function ActionCard({
  title,
  description,
  actionName,
}: {
  title: string;
  description: string;
  actionName: string;
}) {
  return (
    <button
      className="rounded-lg border p-4 text-left hover:bg-slate-50"
      data-action={actionName}
    >
      <h3 className="font-semibold">{title}</h3>
      <p className="text-sm text-slate-600">{description}</p>
    </button>
  );
}
