/**
 * LC Accounting — per-topic detail page.
 *
 * AUTO-GENERATED by scripts/schema-codegen/per-subject-routes.ts (Phase O).
 * DO NOT EDIT — re-run `bun run scripts/schema-codegen/index.ts` to update.
 */

import { createFileRoute, useParams } from "@tanstack/react-router";
import { CopilotKit } from "@copilotkit/react-core/v2";

import { useAccountingActions } from "@/lib/copilotkit/lc/accounting";

export const Route = createFileRoute("/lc/accounting/$topicId")({
  component: AccountingTopicPage,
});

function AccountingTopicPage() {
  const { topicId } = useParams({ from: Route.id });

  return (
    <CopilotKit runtimeUrl="/api/copilotkit/lc/accounting">
      <div className="max-w-4xl mx-auto flex flex-col gap-8 h-full p-8">
        <h1 className="text-3xl font-bold">Topic: {topicId}</h1>
        <p className="text-slate-600">
          Accounting (LC) — topic detail.
        </p>

        <TopicDetailActions topicId={topicId} />
      </div>
    </CopilotKit>
  );
}

function TopicDetailActions({ topicId }: { topicId: string }) {
  useAccountingActions();

  return (
    <div className="grid grid-cols-2 gap-4">
      <button data-action="get_topic_detail" data-topic-id={topicId}>
        Get topic detail
      </button>
      <button data-action="get_cross_jurisdictional_equivalences" data-topic-id={topicId}>
        Get cross-jurisdictional equivalences
      </button>
      <button data-action="save_annotation" data-topic-id={topicId}>
        Save annotation
      </button>
      <button data-action="track_progress" data-topic-id={topicId}>
        Track progress
      </button>
    </div>
  );
}
